MercuryMessaging: MercuryMessaging.ResponderHandlerBuilder Class Reference
MercuryMessaging.ResponderHandlerBuilder Class Reference
Fluent builder for configuring message handlers on MmExtendableResponder.
Public Member Functions
ResponderHandlerBuilder (MmExtendableResponder responder)
Create a new handler builder for the given responder.
ResponderHandlerBuilder OnCustomMethod (int methodId, Action< MmMessage > handler)
Register a custom method handler (method ID >= 1000).
ResponderHandlerBuilder OnCustomMethod< T > (int methodId, Action< T > handler)
Register a custom method handler with typed message.
ResponderHandlerBuilder OnCustomMethod (MmMethod method, Action< MmMessage > handler)
Register a custom method handler using MmMethod enum.
ResponderHandlerBuilder OnInitialize (Action callback)
Set handler for Initialize messages.
ResponderHandlerBuilder OnRefresh (Action callback)
Set handler for Refresh messages.
ResponderHandlerBuilder OnRefresh (Action< List< MmTransform > > callback)
Set handler for Refresh messages with transforms.
ResponderHandlerBuilder OnSetActive (Action< bool > callback)
Set handler for SetActive messages.
ResponderHandlerBuilder OnSwitch (Action< string > callback)
Set handler for Switch messages.
ResponderHandlerBuilder OnComplete (Action< bool > callback)
Set handler for Complete messages.
ResponderHandlerBuilder OnComplete (Action callback)
Set handler for Complete messages (no parameter).
ResponderHandlerBuilder OnMessage (Action< MmMessage > callback)
Set handler for generic messages.
ResponderHandlerBuilder OnMessageBool (Action< bool > callback)
Set handler for bool messages.
ResponderHandlerBuilder OnMessageInt (Action< int > callback)
Set handler for int messages.
ResponderHandlerBuilder OnMessageFloat (Action< float > callback)
Set handler for float messages.
ResponderHandlerBuilder OnMessageString (Action< string > callback)
Set handler for string messages.
ResponderHandlerBuilder OnMessageVector3 (Action< Vector3 > callback)
Set handler for Vector3 messages.
ResponderHandlerWrapper Build ()
Apply all configured handlers to the responder.
Private Attributes
readonly MmExtendableResponder _responder
readonly List<(MmMethod method, Action< MmMessage > handler)> _customHandlers
Action _onInitialize
Action< List< MmTransform > > _onRefresh
Action< bool > _onSetActive
Action< string > _onSwitch
Action< bool > _onComplete
Action< MmMessage > _onMessage
Action< MmMessageBool > _onMessageBool
Action< MmMessageInt > _onMessageInt
Action< MmMessageFloat > _onMessageFloat
Action< MmMessageString > _onMessageString
Action< MmMessageVector3 > _onMessageVector3
Detailed Description
Fluent builder for configuring message handlers on MmExtendableResponder.
Provides a chainable API for registering both custom and standard method handlers.
Example Usage:
responder.ConfigureHandlers()
    .OnCustomMethod(1000, HandleCustomColor)
    .OnCustomMethod(1001, HandleCustomScale)
    .OnInitialize(() => Debug.Log("Initialized"))
    .OnRefresh(() => UpdateDisplay())
    .OnSetActive(active => ToggleEffects(active))
    .Build();
Definition at line 28 of file ResponderHandlerBuilder.cs.
Constructor & Destructor Documentation
ResponderHandlerBuilder()
MercuryMessaging.ResponderHandlerBuilder.ResponderHandlerBuilder (MmExtendableResponder responder)
Create a new handler builder for the given responder.
Definition at line 50 of file ResponderHandlerBuilder.cs.
References _responder.
Referenced by OnComplete(), OnComplete(), OnCustomMethod(), OnCustomMethod(), OnCustomMethod< T >(), OnInitialize(), OnMessage(), OnMessageBool(), OnMessageFloat(), OnMessageInt(), OnMessageString(), OnMessageVector3(), OnRefresh(), OnRefresh(), OnSetActive(), and OnSwitch().
Member Function Documentation
Build()
ResponderHandlerWrapper MercuryMessaging.ResponderHandlerBuilder.Build ()
Apply all configured handlers to the responder.
Returns a handler wrapper that can be used for standard method callbacks.
Definition at line 225 of file ResponderHandlerBuilder.cs.
References _customHandlers, _onComplete, _onInitialize, _onMessage, _onMessageBool, _onMessageFloat, _onMessageInt, _onMessageString, _onMessageVector3, _onRefresh, _onSetActive, _onSwitch, and _responder.
OnComplete() [1/2]
ResponderHandlerBuilder MercuryMessaging.ResponderHandlerBuilder.OnComplete (Action callback)
Set handler for Complete messages (no parameter).
Definition at line 153 of file ResponderHandlerBuilder.cs.
References ResponderHandlerBuilder(), and _onComplete.
OnComplete() [2/2]
ResponderHandlerBuilder MercuryMessaging.ResponderHandlerBuilder.OnComplete (Action< bool > callback)
Set handler for Complete messages.
Definition at line 144 of file ResponderHandlerBuilder.cs.
References ResponderHandlerBuilder(), and _onComplete.
OnCustomMethod() [1/2]
ResponderHandlerBuilder MercuryMessaging.ResponderHandlerBuilder.OnCustomMethod (int methodId, Action< MmMessage > handler)
Register a custom method handler (method ID >= 1000).
Parameters
methodId The custom method ID (must be >= 1000)
handler The handler to invoke for this method
Definition at line 62 of file ResponderHandlerBuilder.cs.
References ResponderHandlerBuilder(), and _customHandlers.
Referenced by OnCustomMethod(), and OnCustomMethod< T >().
OnCustomMethod() [2/2]
ResponderHandlerBuilder MercuryMessaging.ResponderHandlerBuilder.OnCustomMethod (MmMethod method, Action< MmMessage > handler)
Register a custom method handler using MmMethod enum.
Definition at line 87 of file ResponderHandlerBuilder.cs.
References ResponderHandlerBuilder(), and OnCustomMethod().
OnCustomMethod< T >()
ResponderHandlerBuilder MercuryMessaging.ResponderHandlerBuilder.OnCustomMethod< T > (int methodId, Action< T > handler)
Register a custom method handler with typed message.
Type Constraints
T : MmMessage
Definition at line 76 of file ResponderHandlerBuilder.cs.
References ResponderHandlerBuilder(), and OnCustomMethod().
OnInitialize()
ResponderHandlerBuilder MercuryMessaging.ResponderHandlerBuilder.OnInitialize (Action callback)
Set handler for Initialize messages.
Definition at line 99 of file ResponderHandlerBuilder.cs.
References ResponderHandlerBuilder(), and _onInitialize.
OnMessage()
ResponderHandlerBuilder MercuryMessaging.ResponderHandlerBuilder.OnMessage (Action< MmMessage > callback)
Set handler for generic messages.
Definition at line 166 of file ResponderHandlerBuilder.cs.
References ResponderHandlerBuilder(), and _onMessage.
OnMessageBool()
ResponderHandlerBuilder MercuryMessaging.ResponderHandlerBuilder.OnMessageBool (Action< bool > callback)
Set handler for bool messages.
Definition at line 175 of file ResponderHandlerBuilder.cs.
References ResponderHandlerBuilder(), and _onMessageBool.
OnMessageFloat()
ResponderHandlerBuilder MercuryMessaging.ResponderHandlerBuilder.OnMessageFloat (Action< float > callback)
Set handler for float messages.
Definition at line 193 of file ResponderHandlerBuilder.cs.
References ResponderHandlerBuilder(), and _onMessageFloat.
OnMessageInt()
ResponderHandlerBuilder MercuryMessaging.ResponderHandlerBuilder.OnMessageInt (Action< int > callback)
Set handler for int messages.
Definition at line 184 of file ResponderHandlerBuilder.cs.
References ResponderHandlerBuilder(), and _onMessageInt.
OnMessageString()
ResponderHandlerBuilder MercuryMessaging.ResponderHandlerBuilder.OnMessageString (Action< string > callback)
Set handler for string messages.
Definition at line 202 of file ResponderHandlerBuilder.cs.
References ResponderHandlerBuilder(), and _onMessageString.
OnMessageVector3()
ResponderHandlerBuilder MercuryMessaging.ResponderHandlerBuilder.OnMessageVector3 (Action< Vector3 > callback)
Set handler for Vector3 messages.
Definition at line 211 of file ResponderHandlerBuilder.cs.
References ResponderHandlerBuilder(), and _onMessageVector3.
OnRefresh() [1/2]
ResponderHandlerBuilder MercuryMessaging.ResponderHandlerBuilder.OnRefresh (Action callback)
Set handler for Refresh messages.
Definition at line 108 of file ResponderHandlerBuilder.cs.
References ResponderHandlerBuilder(), and _onRefresh.
OnRefresh() [2/2]
ResponderHandlerBuilder MercuryMessaging.ResponderHandlerBuilder.OnRefresh (Action< List< MmTransform > > callback)
Set handler for Refresh messages with transforms.
Definition at line 117 of file ResponderHandlerBuilder.cs.
References ResponderHandlerBuilder(), and _onRefresh.
OnSetActive()
ResponderHandlerBuilder MercuryMessaging.ResponderHandlerBuilder.OnSetActive (Action< bool > callback)
Set handler for SetActive messages.
Definition at line 126 of file ResponderHandlerBuilder.cs.
References ResponderHandlerBuilder(), and _onSetActive.
OnSwitch()
ResponderHandlerBuilder MercuryMessaging.ResponderHandlerBuilder.OnSwitch (Action< string > callback)
Set handler for Switch messages.
Definition at line 135 of file ResponderHandlerBuilder.cs.
References ResponderHandlerBuilder(), and _onSwitch.
Member Data Documentation
_customHandlers
readonly List<(MmMethod method, Action<MmMessage> handler)> MercuryMessaging.ResponderHandlerBuilder._customHandlers private
Initial value:
=
            new List<(MmMethod, Action<MmMessage>)>()
Definition at line 31 of file ResponderHandlerBuilder.cs.
Referenced by Build(), and OnCustomMethod().
_onComplete
Action<bool> MercuryMessaging.ResponderHandlerBuilder._onComplete private
Definition at line 39 of file ResponderHandlerBuilder.cs.
Referenced by Build(), OnComplete(), and OnComplete().
_onInitialize
Action MercuryMessaging.ResponderHandlerBuilder._onInitialize private
Definition at line 35 of file ResponderHandlerBuilder.cs.
Referenced by Build(), and OnInitialize().
_onMessage
Action<MmMessage> MercuryMessaging.ResponderHandlerBuilder._onMessage private
Definition at line 40 of file ResponderHandlerBuilder.cs.
Referenced by Build(), and OnMessage().
_onMessageBool
Action<MmMessageBool> MercuryMessaging.ResponderHandlerBuilder._onMessageBool private
Definition at line 41 of file ResponderHandlerBuilder.cs.
Referenced by Build(), and OnMessageBool().
_onMessageFloat
Action<MmMessageFloat> MercuryMessaging.ResponderHandlerBuilder._onMessageFloat private
Definition at line 43 of file ResponderHandlerBuilder.cs.
Referenced by Build(), and OnMessageFloat().
_onMessageInt
Action<MmMessageInt> MercuryMessaging.ResponderHandlerBuilder._onMessageInt private
Definition at line 42 of file ResponderHandlerBuilder.cs.
Referenced by Build(), and OnMessageInt().
_onMessageString
Action<MmMessageString> MercuryMessaging.ResponderHandlerBuilder._onMessageString private
Definition at line 44 of file ResponderHandlerBuilder.cs.
Referenced by Build(), and OnMessageString().
_onMessageVector3
Action<MmMessageVector3> MercuryMessaging.ResponderHandlerBuilder._onMessageVector3 private
Definition at line 45 of file ResponderHandlerBuilder.cs.
Referenced by Build(), and OnMessageVector3().
_onRefresh
Action<List<MmTransform> > MercuryMessaging.ResponderHandlerBuilder._onRefresh private
Definition at line 36 of file ResponderHandlerBuilder.cs.
Referenced by Build(), OnRefresh(), and OnRefresh().
_onSetActive
Action<bool> MercuryMessaging.ResponderHandlerBuilder._onSetActive private
Definition at line 37 of file ResponderHandlerBuilder.cs.
Referenced by Build(), and OnSetActive().
_onSwitch
Action<string> MercuryMessaging.ResponderHandlerBuilder._onSwitch private
Definition at line 38 of file ResponderHandlerBuilder.cs.
Referenced by Build(), and OnSwitch().
_responder
readonly MmExtendableResponder MercuryMessaging.ResponderHandlerBuilder._responder private
Definition at line 30 of file ResponderHandlerBuilder.cs.
Referenced by ResponderHandlerBuilder(), and Build().
The documentation for this class was generated from the following file:
Protocol/DSL/ResponderHandlerBuilder.cs