MercuryMessaging: MercuryMessaging.Data.MmDataCollectorExtensions Class Reference
MercuryMessaging.Data.MmDataCollectorExtensions Class Reference
Extension methods for MmDataCollector to enable fluent configuration.
Static Public Member Functions
static DataCollectionBuilder Configure (this MmDataCollector collector)
Start configuring the data collector with a fluent builder.
static void QuickCsv (this MmDataCollector collector, string fileName, string location=null)
Quick setup for CSV output.
static void QuickXml (this MmDataCollector collector, string fileName, string location=null)
Quick setup for XML output.
static void AddData (this MmDataCollector collector, string name, Func< string > dataProvider)
Add a data item using cleaner syntax.
static void StartRecording (this MmDataCollector collector)
Start recording data.
static void StopRecording (this MmDataCollector collector)
Stop recording and close the file.
static void PauseRecording (this MmDataCollector collector)
Pause recording (keeps file open but stops writing).
static void ResumeRecording (this MmDataCollector collector)
Resume recording.
static bool IsRecording (this MmDataCollector collector)
Check if currently recording.
static void WriteNow (this MmDataCollector collector)
Manually write a single data point (for Manual frequency mode).
static void SetEveryFrame (this MmDataCollector collector)
Set collection frequency to every frame.
static void SetManual (this MmDataCollector collector)
Set collection frequency to manual.
static void SetEndOfTask (this MmDataCollector collector)
Set collection frequency to end of task.
Detailed Description
Extension methods for MmDataCollector to enable fluent configuration.
Provides a clean, chainable API for setting up data collection.
Example Usage:
// Full fluent configuration
collector.Configure()
    .OutputAsCsv("experiment_data")
    .EveryFrame()
    .Collect("Position", () => transform.position.ToString())
    .CollectTimestamp()
    .Start();
// Quick setup helpers
collector.QuickCsv("results", Application.persistentDataPath);
collector.AddData("Score", () => score.ToString());
collector.StartRecording();
// Later...
collector.StopRecording();
Definition at line 34 of file MmDataCollectorExtensions.cs.
Member Function Documentation
AddData()
void MercuryMessaging.Data.MmDataCollectorExtensions.AddData (this MmDataCollector collector, string name, Func< string > dataProvider) static
Add a data item using cleaner syntax.
Definition at line 80 of file MmDataCollectorExtensions.cs.
References MercuryMessaging.Data.MmDataCollector.Add().
Configure()
DataCollectionBuilder MercuryMessaging.Data.MmDataCollectorExtensions.Configure (this MmDataCollector collector) static
Start configuring the data collector with a fluent builder.
Definition at line 41 of file MmDataCollectorExtensions.cs.
IsRecording()
bool MercuryMessaging.Data.MmDataCollectorExtensions.IsRecording (this MmDataCollector collector) static
Check if currently recording.
Definition at line 136 of file MmDataCollectorExtensions.cs.
References MercuryMessaging.Data.MmDataCollector.AllowWrite.
PauseRecording()
void MercuryMessaging.Data.MmDataCollectorExtensions.PauseRecording (this MmDataCollector collector) static
Pause recording (keeps file open but stops writing).
Definition at line 118 of file MmDataCollectorExtensions.cs.
QuickCsv()
void MercuryMessaging.Data.MmDataCollectorExtensions.QuickCsv (this MmDataCollector collector, string fileName, string location = null) static
Quick setup for CSV output.
Definition at line 56 of file MmDataCollectorExtensions.cs.
QuickXml()
void MercuryMessaging.Data.MmDataCollectorExtensions.QuickXml (this MmDataCollector collector, string fileName, string location = null) static
Quick setup for XML output.
Definition at line 68 of file MmDataCollectorExtensions.cs.
ResumeRecording()
void MercuryMessaging.Data.MmDataCollectorExtensions.ResumeRecording (this MmDataCollector collector) static
Resume recording.
Definition at line 127 of file MmDataCollectorExtensions.cs.
SetEndOfTask()
void MercuryMessaging.Data.MmDataCollectorExtensions.SetEndOfTask (this MmDataCollector collector) static
Set collection frequency to end of task.
Definition at line 175 of file MmDataCollectorExtensions.cs.
SetEveryFrame()
void MercuryMessaging.Data.MmDataCollectorExtensions.SetEveryFrame (this MmDataCollector collector) static
Set collection frequency to every frame.
Definition at line 157 of file MmDataCollectorExtensions.cs.
SetManual()
void MercuryMessaging.Data.MmDataCollectorExtensions.SetManual (this MmDataCollector collector) static
Set collection frequency to manual.
Definition at line 166 of file MmDataCollectorExtensions.cs.
StartRecording()
void MercuryMessaging.Data.MmDataCollectorExtensions.StartRecording (this MmDataCollector collector) static
Start recording data.
Definition at line 92 of file MmDataCollectorExtensions.cs.
References MercuryMessaging.Data.MmDataCollector.AllowWrite, MercuryMessaging.Data.MmDataCollector.CreateDataHandler(), MercuryMessaging.Data.MmDataCollector.FileLocation, MercuryMessaging.Data.MmDataCollector.FileName, and MercuryMessaging.Data.MmDataCollector.OpenTag().
StopRecording()
void MercuryMessaging.Data.MmDataCollectorExtensions.StopRecording (this MmDataCollector collector) static
Stop recording and close the file.
Definition at line 106 of file MmDataCollectorExtensions.cs.
References MercuryMessaging.Data.MmDataCollector.AllowWrite, MercuryMessaging.Data.MmDataCollector.CloseDataHandler(), and MercuryMessaging.Data.MmDataCollector.CloseTag().
WriteNow()
void MercuryMessaging.Data.MmDataCollectorExtensions.WriteNow (this MmDataCollector collector) static
Manually write a single data point (for Manual frequency mode).
Definition at line 144 of file MmDataCollectorExtensions.cs.
References MercuryMessaging.Data.MmDataCollector.AllowWrite, and MercuryMessaging.Data.MmDataCollector.Write().
The documentation for this class was generated from the following file:
Support/Data/MmDataCollectorExtensions.cs