MercuryMessaging: MercuryMessaging.FsmConfigBuilder< T > Class Template Reference
MercuryMessaging.FsmConfigBuilder< T > Class Template Reference
Fluent builder for configuring FiniteStateMachine event handlers.
Public Member Functions
FsmConfigBuilder (FiniteStateMachine< T > fsm, Func< string, T > stateResolver=null)
Create a new FSM configuration builder.
FsmConfigBuilder< T > OnGlobalEnter (Action callback)
Set the global enter callback (called when ANY state is entered).
FsmConfigBuilder< T > OnGlobalExit (Action callback)
Set the global exit callback (called when ANY state is exited).
FsmConfigBuilder< T > OnEnter (T state, Action callback)
Set the enter callback for a specific state.
FsmConfigBuilder< T > OnExit (T state, Action callback)
Set the exit callback for a specific state.
FsmConfigBuilder< T > On (T state, Action onEnter, Action onExit)
Set both enter and exit callbacks for a specific state.
FsmConfigBuilder< T > OnEnter (string stateName, Action callback)
Set the enter callback for a state by name.
FsmConfigBuilder< T > OnExit (string stateName, Action callback)
Set the exit callback for a state by name.
FsmConfigBuilder< T > On (string stateName, Action onEnter, Action onExit)
Set both enter and exit callbacks for a state by name.
FsmConfigBuilder< T > StartWith (T initialState)
Set the initial state and jump to it.
FsmConfigBuilder< T > StartWith (string stateName)
Set the initial state by name and jump to it.
void Build ()
Apply all configured settings to the FSM.
Private Attributes
readonly FiniteStateMachine< T > _fsm
readonly Func< string, T > _stateResolver
readonly List< Action > _deferredActions = new List<Action>()
FiniteStateMachine< T >.Transition _globalEnter
FiniteStateMachine< T >.Transition _globalExit
Detailed Description
Fluent builder for configuring FiniteStateMachine event handlers.
Provides a clean, chainable API for setting up state enter/exit callbacks.
Example Usage:
switchNode.ConfigureStates()
    .OnGlobalEnter(() => Debug.Log("Any state entered"))
    .OnGlobalExit(() => Debug.Log("Any state exited"))
    .OnEnter("MainMenu", () => RefreshMenuUI())
    .OnExit("MainMenu", () => CleanupMenu())
    .OnEnter("Gameplay", () => StartGame())
    .Build();
Template Parameters
T The state type (typically MmRoutingTableItem for MmRelaySwitchNode)
Definition at line 28 of file FsmConfigBuilder.cs.
Member Function Documentation
Build()
void MercuryMessaging.FsmConfigBuilder< T >.Build ()
Apply all configured settings to the FSM.
Definition at line 195 of file FsmConfigBuilder.cs.
References _deferredActions, _globalEnter, and _globalExit.
FsmConfigBuilder()
MercuryMessaging.FsmConfigBuilder< T >.FsmConfigBuilder (FiniteStateMachine< T > fsm, Func< string, T > stateResolver = null)
Create a new FSM configuration builder.
Parameters
fsm The FSM to configure.
stateResolver Function to resolve state name to state object.
Definition at line 42 of file FsmConfigBuilder.cs.
References _fsm, and _stateResolver.
Referenced by On(), On(), OnEnter(), OnEnter(), OnExit(), OnExit(), OnGlobalEnter(), OnGlobalExit(), StartWith(), and StartWith().
On() [1/2]
FsmConfigBuilder< T > MercuryMessaging.FsmConfigBuilder< T >.On (string stateName, Action onEnter, Action onExit)
Set both enter and exit callbacks for a state by name.
Definition at line 151 of file FsmConfigBuilder.cs.
References FsmConfigBuilder(), OnEnter(), and OnExit().
On() [2/2]
FsmConfigBuilder< T > MercuryMessaging.FsmConfigBuilder< T >.On (T state, Action onEnter, Action onExit)
Set both enter and exit callbacks for a specific state.
Definition at line 101 of file FsmConfigBuilder.cs.
References FsmConfigBuilder(), OnEnter(), and OnExit().
OnEnter() [1/2]
FsmConfigBuilder< T > MercuryMessaging.FsmConfigBuilder< T >.OnEnter (string stateName, Action callback)
Set the enter callback for a state by name.
Requires a state resolver to be set.
Definition at line 116 of file FsmConfigBuilder.cs.
References _deferredActions, _fsm, _stateResolver, FsmConfigBuilder(), and MercuryMessaging.Transition().
OnEnter() [2/2]
FsmConfigBuilder< T > MercuryMessaging.FsmConfigBuilder< T >.OnEnter (T state, Action callback)
Set the enter callback for a specific state.
Definition at line 75 of file FsmConfigBuilder.cs.
References _deferredActions, _fsm, FsmConfigBuilder(), and MercuryMessaging.Transition().
Referenced by On(), and On().
OnExit() [1/2]
FsmConfigBuilder< T > MercuryMessaging.FsmConfigBuilder< T >.OnExit (string stateName, Action callback)
Set the exit callback for a state by name.
Requires a state resolver to be set.
Definition at line 134 of file FsmConfigBuilder.cs.
References _deferredActions, _fsm, _stateResolver, FsmConfigBuilder(), and MercuryMessaging.Transition().
OnExit() [2/2]
FsmConfigBuilder< T > MercuryMessaging.FsmConfigBuilder< T >.OnExit (T state, Action callback)
Set the exit callback for a specific state.
Definition at line 88 of file FsmConfigBuilder.cs.
References _deferredActions, _fsm, FsmConfigBuilder(), and MercuryMessaging.Transition().
Referenced by On(), and On().
OnGlobalEnter()
FsmConfigBuilder< T > MercuryMessaging.FsmConfigBuilder< T >.OnGlobalEnter (Action callback)
Set the global enter callback (called when ANY state is entered).
Definition at line 53 of file FsmConfigBuilder.cs.
References _globalEnter, and FsmConfigBuilder().
OnGlobalExit()
FsmConfigBuilder< T > MercuryMessaging.FsmConfigBuilder< T >.OnGlobalExit (Action callback)
Set the global exit callback (called when ANY state is exited).
Definition at line 62 of file FsmConfigBuilder.cs.
References _globalExit, and FsmConfigBuilder().
StartWith() [1/2]
FsmConfigBuilder< T > MercuryMessaging.FsmConfigBuilder< T >.StartWith (string stateName)
Set the initial state by name and jump to it.
Definition at line 174 of file FsmConfigBuilder.cs.
References _deferredActions, _fsm, _stateResolver, and FsmConfigBuilder().
StartWith() [2/2]
FsmConfigBuilder< T > MercuryMessaging.FsmConfigBuilder< T >.StartWith (T initialState)
Set the initial state and jump to it.
Definition at line 165 of file FsmConfigBuilder.cs.
References _deferredActions, _fsm, and FsmConfigBuilder().
Member Data Documentation
_deferredActions
readonly List<Action> MercuryMessaging.FsmConfigBuilder< T >._deferredActions = new List<Action>() private
Definition at line 32 of file FsmConfigBuilder.cs.
Referenced by Build(), OnEnter(), OnEnter(), OnExit(), OnExit(), StartWith(), and StartWith().
_fsm
readonly FiniteStateMachine<T> MercuryMessaging.FsmConfigBuilder< T >._fsm private
Definition at line 30 of file FsmConfigBuilder.cs.
Referenced by FsmConfigBuilder(), OnEnter(), OnEnter(), OnExit(), OnExit(), StartWith(), and StartWith().
_globalEnter
FiniteStateMachine<T>.Transition MercuryMessaging.FsmConfigBuilder< T >._globalEnter private
Definition at line 34 of file FsmConfigBuilder.cs.
Referenced by Build(), and OnGlobalEnter().
_globalExit
FiniteStateMachine<T>.Transition MercuryMessaging.FsmConfigBuilder< T >._globalExit private
Definition at line 35 of file FsmConfigBuilder.cs.
Referenced by Build(), and OnGlobalExit().
_stateResolver
readonly Func<string, T> MercuryMessaging.FsmConfigBuilder< T >._stateResolver private
Definition at line 31 of file FsmConfigBuilder.cs.
Referenced by FsmConfigBuilder(), OnEnter(), OnExit(), and StartWith().
The documentation for this class was generated from the following file:
Protocol/FSM/FsmConfigBuilder.cs