MercuryMessaging: MercuryMessaging.MmPathSpecification Class Reference
MercuryMessaging.MmPathSpecification Class Reference
Path specification parser for hierarchical message routing.
Static Public Member Functions
static ParsedPath Parse (string path)
Parses a path string into a ParsedPath object.
static void ClearCache ()
Clears the path cache.
static int GetCacheSize ()
Gets the current cache size.
Static Private Member Functions
static ParsedPath ParseInternal (string path)
Internal parsing implementation.
static bool TryParseSegment (string segmentStr, out PathSegment segment)
Tries to parse a segment string into a PathSegment enum.
static void ValidatePath (List< PathSegment > segments, string originalPath)
Validates the overall path structure for logical consistency.
Static Private Attributes
static Dictionary< string, ParsedPath > pathCache = new Dictionary<string, ParsedPath>()
const int MaxCacheSize = 100
Detailed Description
Path specification parser for hierarchical message routing.
Parses paths like "parent/sibling/child" into navigation segments.
Definition at line 102 of file MmPathSpecification.cs.
Member Function Documentation
ClearCache()
void MercuryMessaging.MmPathSpecification.ClearCache () static
Clears the path cache.
Useful for testing or memory management.
Definition at line 284 of file MmPathSpecification.cs.
References pathCache.
GetCacheSize()
int MercuryMessaging.MmPathSpecification.GetCacheSize () static
Gets the current cache size.
Useful for diagnostics.
Definition at line 292 of file MmPathSpecification.cs.
References pathCache.
Parse()
ParsedPath MercuryMessaging.MmPathSpecification.Parse (string path) static
Parses a path string into a ParsedPath object.
Results are cached for performance.
Parameters
path Path string like "parent/sibling/child"
Returns
Parsed path object
Exceptions
MmInvalidPathException If path syntax is invalid
Definition at line 117 of file MmPathSpecification.cs.
References MaxCacheSize, ParseInternal(), and pathCache.
Referenced by MercuryMessaging.MmRelayNode.ResolvePathTargets().
ParseInternal()
ParsedPath MercuryMessaging.MmPathSpecification.ParseInternal (string path) static private
Internal parsing implementation.
Definition at line 152 of file MmPathSpecification.cs.
References TryParseSegment(), and ValidatePath().
Referenced by Parse().
TryParseSegment()
bool MercuryMessaging.MmPathSpecification.TryParseSegment (string segmentStr, out PathSegment segment) static private
Tries to parse a segment string into a PathSegment enum.
Definition at line 205 of file MmPathSpecification.cs.
Referenced by ParseInternal().
ValidatePath()
void MercuryMessaging.MmPathSpecification.ValidatePath (List< PathSegment > segments, string originalPath) static private
Validates the overall path structure for logical consistency.
Definition at line 239 of file MmPathSpecification.cs.
Referenced by ParseInternal().
Member Data Documentation
MaxCacheSize
const int MercuryMessaging.MmPathSpecification.MaxCacheSize = 100 static private
Definition at line 108 of file MmPathSpecification.cs.
Referenced by Parse().
pathCache
Dictionary<string, ParsedPath> MercuryMessaging.MmPathSpecification.pathCache = new Dictionary<string, ParsedPath>() static private
Definition at line 105 of file MmPathSpecification.cs.
Referenced by ClearCache(), GetCacheSize(), and Parse().
The documentation for this class was generated from the following file:
Protocol/Routing/MmPathSpecification.cs