MercuryMessaging: MercuryMessaging.Network.MmObjectPool< T > Class Template Reference
MercuryMessaging.Network.MmObjectPool< T > Class Template Reference
Generic object pool for reusable objects.
Public Member Functions
MmObjectPool (int maxSize=100, Action< T > resetAction=null)
Create a new object pool.
void Prewarm (int count)
Prewarm the pool with objects.
T Get ()
Get an object from the pool.
void Return (T obj)
Return an object to the pool.
void Clear ()
Clear the pool.
string GetStats ()
Get pool statistics.
Properties
int Count [get]
Number of objects currently in the pool.
int TotalCreated [get, private set]
Total objects created by this pool.
int TotalGets [get, private set]
Total get operations.
int TotalReturns [get, private set]
Total return operations.
float HitRate [get]
Hit rate (percentage of gets served from pool).
Private Attributes
readonly Stack< T > _pool = new Stack<T>()
readonly object _lock = new object()
readonly int _maxSize
readonly Action< T > _resetAction
Detailed Description
Generic object pool for reusable objects.
Thread-safe implementation.
Type Constraints
T : class
T : new()
Definition at line 17 of file MmMessagePool.cs.
Member Function Documentation
Clear()
void MercuryMessaging.Network.MmObjectPool< T >.Clear ()
Clear the pool.
Definition at line 138 of file MmMessagePool.cs.
References _lock, and _pool.
Referenced by MercuryMessaging.Network.MmMessagePoolManager.MmMessagePoolManager().
Get()
T MercuryMessaging.Network.MmObjectPool< T >.Get ()
Get an object from the pool.
Definition at line 87 of file MmMessagePool.cs.
References _lock, _pool, TotalCreated, and TotalGets.
GetStats()
string MercuryMessaging.Network.MmObjectPool< T >.GetStats ()
Get pool statistics.
Definition at line 149 of file MmMessagePool.cs.
MmObjectPool()
MercuryMessaging.Network.MmObjectPool< T >.MmObjectPool (int maxSize = 100, Action< T > resetAction = null)
Create a new object pool.
Parameters
maxSize Maximum pool size (excess returns are discarded)
resetAction Action to reset object state before reuse
Definition at line 63 of file MmMessagePool.cs.
References _maxSize, and _resetAction.
Prewarm()
void MercuryMessaging.Network.MmObjectPool< T >.Prewarm (int count)
Prewarm the pool with objects.
Definition at line 72 of file MmMessagePool.cs.
References _lock, _maxSize, _pool, and TotalCreated.
Return()
void MercuryMessaging.Network.MmObjectPool< T >.Return (T obj)
Return an object to the pool.
Definition at line 118 of file MmMessagePool.cs.
References _lock, _maxSize, _pool, _resetAction, and TotalReturns.
Member Data Documentation
_lock
readonly object MercuryMessaging.Network.MmObjectPool< T >._lock = new object() private
Definition at line 20 of file MmMessagePool.cs.
Referenced by Clear(), Get(), Prewarm(), and Return().
_maxSize
readonly int MercuryMessaging.Network.MmObjectPool< T >._maxSize private
Definition at line 21 of file MmMessagePool.cs.
Referenced by MmObjectPool(), Prewarm(), and Return().
_pool
readonly Stack<T> MercuryMessaging.Network.MmObjectPool< T >._pool = new Stack<T>() private
Definition at line 19 of file MmMessagePool.cs.
Referenced by Clear(), Get(), Prewarm(), and Return().
_resetAction
readonly Action<T> MercuryMessaging.Network.MmObjectPool< T >._resetAction private
Definition at line 22 of file MmMessagePool.cs.
Referenced by MmObjectPool(), and Return().
Property Documentation
Count
int MercuryMessaging.Network.MmObjectPool< T >.Count get
Number of objects currently in the pool.
Definition at line 27 of file MmMessagePool.cs.
HitRate
float MercuryMessaging.Network.MmObjectPool< T >.HitRate get
Hit rate (percentage of gets served from pool).
Definition at line 56 of file MmMessagePool.cs.
TotalCreated
int MercuryMessaging.Network.MmObjectPool< T >.TotalCreated get private set
Total objects created by this pool.
Definition at line 41 of file MmMessagePool.cs.
Referenced by Get(), and Prewarm().
TotalGets
int MercuryMessaging.Network.MmObjectPool< T >.TotalGets get private set
Total get operations.
Definition at line 46 of file MmMessagePool.cs.
Referenced by Get().
TotalReturns
int MercuryMessaging.Network.MmObjectPool< T >.TotalReturns get private set
Total return operations.
Definition at line 51 of file MmMessagePool.cs.
Referenced by Return().
The documentation for this class was generated from the following file:
Protocol/Network/MmMessagePool.cs