MercuryMessaging: MercuryMessaging.Data.MmMessageHistoryCache Class Reference
MercuryMessaging.Data.MmMessageHistoryCache Class Reference
Time-windowed LRU cache for tracking visited relay nodes in message routing.
Classes
class CacheEntry
Cache entry combining node ID with timestamp for time-based eviction.
struct CacheStatistics
Cache statistics snapshot for profiling/debugging.
Public Member Functions
MmMessageHistoryCache (int windowSizeMs=100)
Creates message history cache with specified time window.
void Add (int nodeId)
Adds a node ID to the visited set with current timestamp.
bool Contains (int nodeId)
Checks if a node ID has been visited (within time window).
void Clear ()
Clears all entries from the cache.
void EvictNow ()
Forces immediate eviction of old entries (normally done lazily during Add).
CacheStatistics GetStatistics ()
Gets cache statistics for profiling/debugging.
override string ToString ()
Properties
int Count [get]
Number of node IDs currently in cache.
int EvictionCount [get]
Total number of evictions performed (statistics).
int AddCount [get]
Total number of adds performed (statistics).
float HitRate = 0f [get, set]
Cache hit rate = (lookups that found node) / (total lookups).
Private Member Functions
void EvictOldEntries (float currentTime)
Evicts entries older than the time window.
int GetOldestEntryAge ()
Gets age of oldest entry in milliseconds (for statistics).
Private Attributes
readonly HashSet< int > _visitedNodes = new HashSet<int>()
Fast O(1) lookup for visited node IDs.
readonly LinkedList< CacheEntry > _evictionQueue = new LinkedList<CacheEntry>()
LRU ordering for time-based eviction (oldest entries first).
readonly Dictionary< int, LinkedListNode< CacheEntry > > _nodeMap
Map from node ID to LinkedListNode for O(1) removal during updates.
readonly float _windowSizeSeconds
Time window in seconds (converted from milliseconds).
int _evictionCount = 0
Counter for eviction operations (statistics).
int _addCount = 0
Counter for add operations (statistics).
float _lastEvictionCheck = 0f
Timestamp of last eviction check (optimize eviction frequency).
Static Private Attributes
const float EVICTION_CHECK_INTERVAL = 0.01f
Minimum time between eviction sweeps (seconds).
Detailed Description
Time-windowed LRU cache for tracking visited relay nodes in message routing.
Prevents circular routing more effectively than hop counting alone.
Design:
Hybrid approach: HashSet for O(1) lookups + LinkedList for LRU eviction
Time-based eviction: Entries older than window are automatically removed
Bounded memory: Evicts old entries to maintain constant memory footprint
Performance:
Add: O(1) amortized (eviction only when needed)
Contains: O(1) always
Memory: ~24 bytes per entry (node ID + timestamp + pointers)
Thread Safety: Not thread-safe (designed for Unity main thread usage)
Definition at line 29 of file MmMessageHistoryCache.cs.
Constructor & Destructor Documentation
MmMessageHistoryCache()
MercuryMessaging.Data.MmMessageHistoryCache.MmMessageHistoryCache (int windowSizeMs = 100)
Creates message history cache with specified time window.
Parameters
windowSizeMs Time window in milliseconds (default: 100ms)
Definition at line 127 of file MmMessageHistoryCache.cs.
References _lastEvictionCheck, and _windowSizeSeconds.
Member Function Documentation
Add()
void MercuryMessaging.Data.MmMessageHistoryCache.Add (int nodeId)
Adds a node ID to the visited set with current timestamp.
If node already exists, updates its timestamp (refreshes TTL).
Parameters
nodeId Relay node instance ID
Definition at line 145 of file MmMessageHistoryCache.cs.
References _addCount, _evictionQueue, _lastEvictionCheck, _nodeMap, _visitedNodes, EVICTION_CHECK_INTERVAL, and EvictOldEntries().
Clear()
void MercuryMessaging.Data.MmMessageHistoryCache.Clear ()
Clears all entries from the cache.
Definition at line 193 of file MmMessageHistoryCache.cs.
References _addCount, _evictionCount, _evictionQueue, _nodeMap, and _visitedNodes.
Contains()
bool MercuryMessaging.Data.MmMessageHistoryCache.Contains (int nodeId)
Checks if a node ID has been visited (within time window).
Parameters
nodeId Relay node instance ID
Returns
True if node was visited recently, false otherwise
Definition at line 185 of file MmMessageHistoryCache.cs.
References _visitedNodes.
EvictNow()
void MercuryMessaging.Data.MmMessageHistoryCache.EvictNow ()
Forces immediate eviction of old entries (normally done lazily during Add).
Useful for testing or manual cache management.
Definition at line 206 of file MmMessageHistoryCache.cs.
References EvictOldEntries().
EvictOldEntries()
void MercuryMessaging.Data.MmMessageHistoryCache.EvictOldEntries (float currentTime) private
Evicts entries older than the time window.
Iterates from oldest (front) until hitting entry within window.
Definition at line 235 of file MmMessageHistoryCache.cs.
References _evictionCount, _evictionQueue, _nodeMap, _visitedNodes, and _windowSizeSeconds.
Referenced by Add(), and EvictNow().
GetOldestEntryAge()
int MercuryMessaging.Data.MmMessageHistoryCache.GetOldestEntryAge () private
Gets age of oldest entry in milliseconds (for statistics).
Returns 0 if cache is empty.
Definition at line 262 of file MmMessageHistoryCache.cs.
References _evictionQueue.
Referenced by GetStatistics().
GetStatistics()
CacheStatistics MercuryMessaging.Data.MmMessageHistoryCache.GetStatistics ()
Gets cache statistics for profiling/debugging.
Definition at line 214 of file MmMessageHistoryCache.cs.
References _windowSizeSeconds, AddCount, Count, EvictionCount, GetOldestEntryAge(), and HitRate.
Referenced by ToString().
ToString()
override string MercuryMessaging.Data.MmMessageHistoryCache.ToString ()
Definition at line 301 of file MmMessageHistoryCache.cs.
References GetStatistics(), and MercuryMessaging.Data.MmMessageHistoryCache.CacheStatistics.ToString().
Member Data Documentation
_addCount
int MercuryMessaging.Data.MmMessageHistoryCache._addCount = 0 private
Counter for add operations (statistics).
Definition at line 81 of file MmMessageHistoryCache.cs.
Referenced by Add(), and Clear().
_evictionCount
int MercuryMessaging.Data.MmMessageHistoryCache._evictionCount = 0 private
Counter for eviction operations (statistics).
Definition at line 76 of file MmMessageHistoryCache.cs.
Referenced by Clear(), and EvictOldEntries().
_evictionQueue
readonly LinkedList<CacheEntry> MercuryMessaging.Data.MmMessageHistoryCache._evictionQueue = new LinkedList<CacheEntry>() private
LRU ordering for time-based eviction (oldest entries first).
Definition at line 60 of file MmMessageHistoryCache.cs.
Referenced by Add(), Clear(), EvictOldEntries(), and GetOldestEntryAge().
_lastEvictionCheck
float MercuryMessaging.Data.MmMessageHistoryCache._lastEvictionCheck = 0f private
Timestamp of last eviction check (optimize eviction frequency).
Definition at line 86 of file MmMessageHistoryCache.cs.
Referenced by MmMessageHistoryCache(), and Add().
_nodeMap
readonly Dictionary<int, LinkedListNode<CacheEntry> > MercuryMessaging.Data.MmMessageHistoryCache._nodeMap private
Initial value:
=
            new Dictionary<int, LinkedListNode<CacheEntry>>()
Map from node ID to LinkedListNode for O(1) removal during updates.
Definition at line 65 of file MmMessageHistoryCache.cs.
Referenced by Add(), Clear(), and EvictOldEntries().
_visitedNodes
readonly HashSet<int> MercuryMessaging.Data.MmMessageHistoryCache._visitedNodes = new HashSet<int>() private
Fast O(1) lookup for visited node IDs.
Definition at line 55 of file MmMessageHistoryCache.cs.
Referenced by Add(), Clear(), Contains(), and EvictOldEntries().
_windowSizeSeconds
readonly float MercuryMessaging.Data.MmMessageHistoryCache._windowSizeSeconds private
Time window in seconds (converted from milliseconds).
Definition at line 71 of file MmMessageHistoryCache.cs.
Referenced by MmMessageHistoryCache(), EvictOldEntries(), and GetStatistics().
EVICTION_CHECK_INTERVAL
const float MercuryMessaging.Data.MmMessageHistoryCache.EVICTION_CHECK_INTERVAL = 0.01f static private
Minimum time between eviction sweeps (seconds).
Prevents excessive eviction checks when adding many nodes rapidly.
Definition at line 92 of file MmMessageHistoryCache.cs.
Referenced by Add().
Property Documentation
AddCount
int MercuryMessaging.Data.MmMessageHistoryCache.AddCount get
Total number of adds performed (statistics).
Definition at line 111 of file MmMessageHistoryCache.cs.
Referenced by GetStatistics().
Count
int MercuryMessaging.Data.MmMessageHistoryCache.Count get
Number of node IDs currently in cache.
Definition at line 101 of file MmMessageHistoryCache.cs.
Referenced by GetStatistics().
EvictionCount
int MercuryMessaging.Data.MmMessageHistoryCache.EvictionCount get
Total number of evictions performed (statistics).
Definition at line 106 of file MmMessageHistoryCache.cs.
Referenced by GetStatistics().
HitRate
float MercuryMessaging.Data.MmMessageHistoryCache.HitRate = 0f get set
Cache hit rate = (lookups that found node) / (total lookups).
Updated externally by caller tracking Contains() results.
Definition at line 117 of file MmMessageHistoryCache.cs.
Referenced by GetStatistics().
The documentation for this class was generated from the following file:
Support/Data/MmMessageHistoryCache.cs