MercuryMessaging: MercuryMessaging.MmRoutingExtensions Class Reference
MercuryMessaging.MmRoutingExtensions Class Reference
Extension methods for simplified runtime hierarchy registration.
Static Public Member Functions
static MmRelayNode RegisterWith (this MmRelayNode child, MmRelayNode parent)
Registers this relay node as a child of the specified parent.
static MmRelayNode RegisterWith (this MmRelayNode child, MmRelayNode parent, MmLevelFilter level)
Registers this relay node as a child with a custom level filter.
static MmRelayNode RegisterWith (this MmRelayNode child, MmRelayNode parent, string name)
Registers this relay node as a child with a custom name.
static MmRelayNode RegisterChildren (this MmRelayNode parent, params MmRelayNode[] children)
Registers multiple children with this parent relay node.
static MmRelayNode RegisterResponders (this MmRelayNode parent, params MmResponder[] responders)
Registers multiple responders with this parent relay node.
static MmRelayNode UnregisterFrom (this MmRelayNode child, MmRelayNode parent)
Unregisters this relay node from its parent.
static MmRelayNode UnregisterChildren (this MmRelayNode parent, params MmRelayNode[] children)
Unregisters multiple children from this parent relay node.
static MmRelayNode RegisterWith (this MmBaseResponder responder, MmRelayNode parent)
Registers this responder's relay node as a child of the specified parent.
static MmRelayNode UnregisterFrom (this MmBaseResponder responder, MmRelayNode parent)
Unregisters this responder's relay node from the specified parent.
static bool HasParents (this MmRelayNode relay)
Checks if this relay node has any parents registered via AddParent.
static MmRelayNode GetFirstParent (this MmRelayNode relay)
Gets the first parent relay node from the routing table.
static bool IsRoot (this MmRelayNode relay)
Checks if this relay node is a root (has no parents).
Static Private Member Functions
static void RemoveFromRoutingTable (MmRelayNode parent, MmResponder responder)
Helper method to remove a responder from a relay node's routing table.
Detailed Description
Extension methods for simplified runtime hierarchy registration.
Part of DSL Phase 2.5: Runtime Registration.
These extensions simplify the common pattern of:
// Before (2 lines)
parentRelay.MmAddToRoutingTable(childRelay, MmLevelFilter.Child);
childRelay.AddParent(parentRelay);
// After (1 line)
childRelay.RegisterWith(parentRelay);
Definition at line 29 of file MmRoutingExtensions.cs.
Member Function Documentation
GetFirstParent()
MmRelayNode MercuryMessaging.MmRoutingExtensions.GetFirstParent (this MmRelayNode relay) static
Gets the first parent relay node from the routing table.
Parameters
relay The relay node to query.
Returns
The first parent relay node, or null if none.
Definition at line 313 of file MmRoutingExtensions.cs.
HasParents()
bool MercuryMessaging.MmRoutingExtensions.HasParents (this MmRelayNode relay) static
Checks if this relay node has any parents registered via AddParent.
Uses the routing table to find parent entries.
Parameters
relay The relay node to query.
Returns
True if the node has parent entries in its routing table.
Definition at line 295 of file MmRoutingExtensions.cs.
IsRoot()
bool MercuryMessaging.MmRoutingExtensions.IsRoot (this MmRelayNode relay) static
Checks if this relay node is a root (has no parents).
Parameters
relay The relay node to query.
Returns
True if the node has no parent entries.
Definition at line 331 of file MmRoutingExtensions.cs.
RegisterChildren()
MmRelayNode MercuryMessaging.MmRoutingExtensions.RegisterChildren (this MmRelayNode parent, params MmRelayNode[] children) static
Registers multiple children with this parent relay node.
Parameters
parent The parent relay node.
children The child relay nodes to register.
Returns
The parent relay node (for chaining).
parentRelay.RegisterChildren(child1, child2, child3);
Definition at line 132 of file MmRoutingExtensions.cs.
RegisterResponders()
MmRelayNode MercuryMessaging.MmRoutingExtensions.RegisterResponders (this MmRelayNode parent, params MmResponder[] responders) static
Registers multiple responders with this parent relay node.
Parameters
parent The parent relay node.
responders The responders to register.
Returns
The parent relay node (for chaining).
Definition at line 159 of file MmRoutingExtensions.cs.
RegisterWith() [1/4]
MmRelayNode MercuryMessaging.MmRoutingExtensions.RegisterWith (this MmBaseResponder responder, MmRelayNode parent) static
Registers this responder's relay node as a child of the specified parent.
Null-safe: no-op if responder has no relay node.
Parameters
responder The responder to register.
parent The parent relay node.
Returns
The relay node (for chaining), or null if not found.
Definition at line 264 of file MmRoutingExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
RegisterWith() [2/4]
MmRelayNode MercuryMessaging.MmRoutingExtensions.RegisterWith (this MmRelayNode child, MmRelayNode parent) static
Registers this relay node as a child of the specified parent.
Combines MmAddToRoutingTable + AddParent in a single call.
Parameters
child The child relay node to register.
parent The parent relay node.
Returns
The child relay node (for chaining).
// Single-line registration childRelay.RegisterWith(parentRelay);
// Chained with creation var relay = go.AddComponent<MmRelayNode>() .RegisterWith(parentRelay);
Definition at line 49 of file MmRoutingExtensions.cs.
References MercuryMessaging.MmRelayNode.AddParent(), and MercuryMessaging.MmRelayNode.MmAddToRoutingTable().
RegisterWith() [3/4]
MmRelayNode MercuryMessaging.MmRoutingExtensions.RegisterWith (this MmRelayNode child, MmRelayNode parent, MmLevelFilter level) static
Registers this relay node as a child with a custom level filter.
Parameters
child The child relay node to register.
parent The parent relay node.
level The level filter for routing (default: Child).
Returns
The child relay node (for chaining).
Definition at line 73 of file MmRoutingExtensions.cs.
References MercuryMessaging.MmRelayNode.AddParent(), and MercuryMessaging.MmRelayNode.MmAddToRoutingTable().
RegisterWith() [4/4]
MmRelayNode MercuryMessaging.MmRoutingExtensions.RegisterWith (this MmRelayNode child, MmRelayNode parent, string name) static
Registers this relay node as a child with a custom name.
Parameters
child The child relay node to register.
parent The parent relay node.
name The name for the routing table entry.
Returns
The child relay node (for chaining).
Definition at line 102 of file MmRoutingExtensions.cs.
References MercuryMessaging.MmRelayNode.AddParent(), and MercuryMessaging.MmRelayNode.MmAddToRoutingTable().
RemoveFromRoutingTable()
void MercuryMessaging.MmRoutingExtensions.RemoveFromRoutingTable (MmRelayNode parent, MmResponder responder) static private
Helper method to remove a responder from a relay node's routing table.
Definition at line 237 of file MmRoutingExtensions.cs.
References MercuryMessaging.ReorderableList< T >.Count, MercuryMessaging.MmRoutingTable.RemoveAt(), and MercuryMessaging.MmRelayNode.RoutingTable.
Referenced by UnregisterChildren(), and UnregisterFrom().
UnregisterChildren()
MmRelayNode MercuryMessaging.MmRoutingExtensions.UnregisterChildren (this MmRelayNode parent, params MmRelayNode[] children) static
Unregisters multiple children from this parent relay node.
Parameters
parent The parent relay node.
children The child relay nodes to unregister.
Returns
The parent relay node (for chaining).
Definition at line 215 of file MmRoutingExtensions.cs.
References RemoveFromRoutingTable().
UnregisterFrom() [1/2]
MmRelayNode MercuryMessaging.MmRoutingExtensions.UnregisterFrom (this MmBaseResponder responder, MmRelayNode parent) static
Unregisters this responder's relay node from the specified parent.
Null-safe: no-op if responder has no relay node.
Parameters
responder The responder to unregister.
parent The parent relay node.
Returns
The relay node (for chaining), or null if not found.
Definition at line 278 of file MmRoutingExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
UnregisterFrom() [2/2]
MmRelayNode MercuryMessaging.MmRoutingExtensions.UnregisterFrom (this MmRelayNode child, MmRelayNode parent) static
Unregisters this relay node from its parent.
Removes from routing table and clears parent reference.
Parameters
child The child relay node to unregister.
parent The parent relay node.
Returns
The child relay node (for chaining).
Definition at line 194 of file MmRoutingExtensions.cs.
References RemoveFromRoutingTable().
The documentation for this class was generated from the following file:
Protocol/DSL/MmRoutingExtensions.cs