MercuryMessaging: MercuryMessaging.Network.MmStateDeltaManager Class Reference
MercuryMessaging.Network.MmStateDeltaManager Class Reference
Manages state tracking for multiple networked objects.
Public Member Functions
MmStateTracker GetOrCreateTracker (uint netId)
Get or create a state tracker for a network ID.
MmStateTracker GetTracker (uint netId)
Get an existing tracker, or null if not found.
void RemoveTracker (uint netId)
Remove a tracker for a network ID.
List< MmStateDelta > ComputeAllDeltas ()
Compute deltas for all tracked objects.
void MarkAllAsSent ()
Mark all trackers as sent.
void ProcessAck (uint netId, uint sequence)
Process an acknowledgment from remote.
Properties
int TrackerCount [get]
Get count of tracked objects.
Private Attributes
readonly Dictionary< uint, MmStateTracker > _trackers = new Dictionary<uint, MmStateTracker>()
Detailed Description
Manages state tracking for multiple networked objects.
Definition at line 383 of file MmStateDelta.cs.
Member Function Documentation
ComputeAllDeltas()
List< MmStateDelta > MercuryMessaging.Network.MmStateDeltaManager.ComputeAllDeltas ()
Compute deltas for all tracked objects.
Returns
List of deltas for objects that have changed
Definition at line 421 of file MmStateDelta.cs.
References _trackers.
GetOrCreateTracker()
MmStateTracker MercuryMessaging.Network.MmStateDeltaManager.GetOrCreateTracker (uint netId)
Get or create a state tracker for a network ID.
Definition at line 390 of file MmStateDelta.cs.
References _trackers.
GetTracker()
MmStateTracker MercuryMessaging.Network.MmStateDeltaManager.GetTracker (uint netId)
Get an existing tracker, or null if not found.
Definition at line 403 of file MmStateDelta.cs.
References _trackers.
MarkAllAsSent()
void MercuryMessaging.Network.MmStateDeltaManager.MarkAllAsSent ()
Mark all trackers as sent.
Definition at line 440 of file MmStateDelta.cs.
References _trackers.
ProcessAck()
void MercuryMessaging.Network.MmStateDeltaManager.ProcessAck (uint netId, uint sequence)
Process an acknowledgment from remote.
Definition at line 451 of file MmStateDelta.cs.
References _trackers.
RemoveTracker()
void MercuryMessaging.Network.MmStateDeltaManager.RemoveTracker (uint netId)
Remove a tracker for a network ID.
Definition at line 412 of file MmStateDelta.cs.
References _trackers.
Member Data Documentation
_trackers
readonly Dictionary<uint, MmStateTracker> MercuryMessaging.Network.MmStateDeltaManager._trackers = new Dictionary<uint, MmStateTracker>() private
Definition at line 385 of file MmStateDelta.cs.
Referenced by ComputeAllDeltas(), GetOrCreateTracker(), GetTracker(), MarkAllAsSent(), ProcessAck(), and RemoveTracker().
Property Documentation
TrackerCount
int MercuryMessaging.Network.MmStateDeltaManager.TrackerCount get
Get count of tracked objects.
Definition at line 465 of file MmStateDelta.cs.
The documentation for this class was generated from the following file:
Protocol/Network/MmStateDelta.cs