MercuryMessaging: MercuryMessaging.Utilities Class Reference
MercuryMessaging.Utilities Class Reference
General utility functions Some have been found online.
Classes
struct EulerAnglesSimple
Static Public Member Functions
static Vector2 Project2D (Vector3 v, Vector3 axis)
static double PositiveAngleBetween (Vector2 v1, Vector2 v2)
http://www.mathworks.com/matlabcentral/newsreader/view_thread/151925
static double AngleBetween (Vector2 v1, Vector2 v2)
static Vector3 QuaternionToYawPitchRoll (Quaternion q)
static EulerAnglesSimple QuaternionToYawPitchRoll2 (Quaternion q)
static float GetMax (Vector3 v)
static float Max (float f1, float f2, float f3)
static string ConvertToOptimizedString (Matrix mat, char separator)
static Vector2 CsvToV2 (String s)
static IEnumerable< T > GetValues< T > ()
static T[] Shuffle< T > (T[] iArray)
Static Private Member Functions
static float Smooth (float currentValue, float previousValue, float weight)
Detailed Description
General utility functions Some have been found online.
Any taken from online sources should include a reference at the top of the function.
Definition at line 48 of file Utilities.cs.
Member Function Documentation
AngleBetween()
double MercuryMessaging.Utilities.AngleBetween (Vector2 v1, Vector2 v2) static
Definition at line 81 of file Utilities.cs.
Referenced by PositiveAngleBetween().
ConvertToOptimizedString()
string MercuryMessaging.Utilities.ConvertToOptimizedString (Matrix mat, char separator) static
Definition at line 171 of file Utilities.cs.
CsvToV2()
Vector2 MercuryMessaging.Utilities.CsvToV2 (String s) static
Definition at line 182 of file Utilities.cs.
GetMax()
float MercuryMessaging.Utilities.GetMax (Vector3 v) static
Definition at line 159 of file Utilities.cs.
GetValues< T >()
IEnumerable< T > MercuryMessaging.Utilities.GetValues< T > () static
Definition at line 193 of file Utilities.cs.
Max()
float MercuryMessaging.Utilities.Max (float f1, float f2, float f3) static
Definition at line 166 of file Utilities.cs.
PositiveAngleBetween()
double MercuryMessaging.Utilities.PositiveAngleBetween (Vector2 v1, Vector2 v2) static
http://www.mathworks.com/matlabcentral/newsreader/view_thread/151925
Parameters
v1
v2
Returns
Definition at line 72 of file Utilities.cs.
References AngleBetween().
Project2D()
Vector2 MercuryMessaging.Utilities.Project2D (Vector3 v, Vector3 axis) static
Definition at line 55 of file Utilities.cs.
Referenced by MercuryMessaging.StandardLibrary.Animation.InterpolatorOrbit.CalculateDistance().
QuaternionToYawPitchRoll()
Vector3 MercuryMessaging.Utilities.QuaternionToYawPitchRoll (Quaternion q) static
Definition at line 87 of file Utilities.cs.
QuaternionToYawPitchRoll2()
EulerAnglesSimple MercuryMessaging.Utilities.QuaternionToYawPitchRoll2 (Quaternion q) static
Definition at line 138 of file Utilities.cs.
Shuffle< T >()
T[] MercuryMessaging.Utilities.Shuffle< T > (T[] iArray) static
Definition at line 212 of file Utilities.cs.
Smooth()
float MercuryMessaging.Utilities.Smooth (float currentValue, float previousValue, float weight) static private
Definition at line 50 of file Utilities.cs.
The documentation for this class was generated from the following file:
Support/Utilities.cs