MercuryMessaging: MercuryMessaging.MmFluentExtensions Class Reference
MercuryMessaging.MmFluentExtensions Class Reference
Extension methods for MmRelayNode to enable fluent message sending.
Static Public Member Functions
static MmFluentMessage Send (this MmRelayNode relay, object payload)
Send a message using the fluent API.
static MmFluentMessage Send (this MmRelayNode relay, bool value)
Send a boolean message.
static MmFluentMessage Send (this MmRelayNode relay, int value)
Send an integer message.
static MmFluentMessage Send (this MmRelayNode relay, float value)
Send a float message.
static MmFluentMessage Send (this MmRelayNode relay, string value)
Send a string message.
static MmFluentMessage Send (this MmRelayNode relay, Vector3 value)
Send a Vector3 message.
static MmFluentMessage Send (this MmRelayNode relay, Vector4 value)
Send a Vector4 message.
static MmFluentMessage Send (this MmRelayNode relay, Quaternion value)
Send a Quaternion message.
static MmFluentMessage Send (this MmRelayNode relay, Transform value)
Send a Transform reference message.
static MmFluentMessage Send (this MmRelayNode relay, GameObject value)
Send a GameObject reference message.
static MmFluentMessage Send (this MmRelayNode relay, MmMessage message)
Send a custom MmMessage.
static MmFluentMessage Send (this MmRelayNode relay, MmMethod method)
Send a message with explicit method (no payload).
static MmFluentMessage Send (this MmRelayNode relay, MmMethod method, int value)
Send a message with explicit method and int value.
static MmFluentMessage Send (this MmRelayNode relay, MmMethod method, bool value)
Send a message with explicit method and bool value.
static MmFluentMessage Send (this MmRelayNode relay, MmMethod method, float value)
Send a message with explicit method and float value.
static MmFluentMessage Send (this MmRelayNode relay, MmMethod method, string value)
Send a message with explicit method and string value.
static MmFluentMessage Send (this MmRelayNode relay, MmMethod method, Vector3 value)
Send a message with explicit method and Vector3 value.
static MmFluentMessage Send (this MmRelayNode relay, MmMethod method, object payload)
Send a message with explicit method and object payload.
static MmFluentMessage Initialize (this MmRelayNode relay)
Send an Initialize command.
static MmFluentMessage Refresh (this MmRelayNode relay)
Send a Refresh command.
static MmFluentMessage Complete (this MmRelayNode relay)
Send a Complete command.
static MmFluentMessage SetActive (this MmRelayNode relay, bool active)
Send a SetActive command.
static MmFluentMessage Switch (this MmRelayNode relay, string stateName)
Send a Switch state command.
static MmFluentMessage Broadcast (this MmRelayNode relay, object payload)
Broadcast a message to all connected nodes.
static MmFluentMessage Broadcast (this MmRelayNode relay, string message)
Broadcast a string message to all connected nodes.
Static Private Member Functions
static MmMethod DetectMethodFromPayload (object payload)
Auto-detect the appropriate MmMethod based on payload type.
Detailed Description
Extension methods for MmRelayNode to enable fluent message sending.
These methods are the entry point for the fluent DSL API.
Definition at line 11 of file MmFluentExtensions.cs.
Member Function Documentation
Broadcast() [1/2]
MmFluentMessage MercuryMessaging.MmFluentExtensions.Broadcast (this MmRelayNode relay, object payload) static
Broadcast a message to all connected nodes.
Convenience method that automatically sets routing to SelfAndBidirectional.
Definition at line 248 of file MmFluentExtensions.cs.
References Send(), and MercuryMessaging.MmFluentMessage.ToAll().
Broadcast() [2/2]
MmFluentMessage MercuryMessaging.MmFluentExtensions.Broadcast (this MmRelayNode relay, string message) static
Broadcast a string message to all connected nodes.
Definition at line 257 of file MmFluentExtensions.cs.
References Send(), and MercuryMessaging.MmFluentMessage.ToAll().
Complete()
MmFluentMessage MercuryMessaging.MmFluentExtensions.Complete (this MmRelayNode relay) static
Send a Complete command.
Definition at line 216 of file MmFluentExtensions.cs.
DetectMethodFromPayload()
MmMethod MercuryMessaging.MmFluentExtensions.DetectMethodFromPayload (object payload) static private
Auto-detect the appropriate MmMethod based on payload type.
Definition at line 272 of file MmFluentExtensions.cs.
References MercuryMessaging.Message, and MercuryMessaging.MmMessage.MmMethod.
Referenced by Send().
Initialize()
MmFluentMessage MercuryMessaging.MmFluentExtensions.Initialize (this MmRelayNode relay) static
Send an Initialize command.
Definition at line 198 of file MmFluentExtensions.cs.
Refresh()
MmFluentMessage MercuryMessaging.MmFluentExtensions.Refresh (this MmRelayNode relay) static
Send a Refresh command.
Definition at line 207 of file MmFluentExtensions.cs.
Send() [1/18]
MmFluentMessage MercuryMessaging.MmFluentExtensions.Send (this MmRelayNode relay, bool value) static
Send a boolean message.
Definition at line 36 of file MmFluentExtensions.cs.
Send() [2/18]
MmFluentMessage MercuryMessaging.MmFluentExtensions.Send (this MmRelayNode relay, float value) static
Send a float message.
Definition at line 54 of file MmFluentExtensions.cs.
Send() [3/18]
MmFluentMessage MercuryMessaging.MmFluentExtensions.Send (this MmRelayNode relay, GameObject value) static
Send a GameObject reference message.
Definition at line 108 of file MmFluentExtensions.cs.
Send() [4/18]
MmFluentMessage MercuryMessaging.MmFluentExtensions.Send (this MmRelayNode relay, int value) static
Send an integer message.
Definition at line 45 of file MmFluentExtensions.cs.
Send() [5/18]
MmFluentMessage MercuryMessaging.MmFluentExtensions.Send (this MmRelayNode relay, MmMessage message) static
Send a custom MmMessage.
Definition at line 117 of file MmFluentExtensions.cs.
References MercuryMessaging.MmMessage.MmMethod.
Send() [6/18]
MmFluentMessage MercuryMessaging.MmFluentExtensions.Send (this MmRelayNode relay, MmMethod method) static
Send a message with explicit method (no payload).
Use for methods like Initialize, Refresh, Complete, NoOp that don't require a value.
Definition at line 130 of file MmFluentExtensions.cs.
Send() [7/18]
MmFluentMessage MercuryMessaging.MmFluentExtensions.Send (this MmRelayNode relay, MmMethod method, bool value) static
Send a message with explicit method and bool value.
Definition at line 149 of file MmFluentExtensions.cs.
Send() [8/18]
MmFluentMessage MercuryMessaging.MmFluentExtensions.Send (this MmRelayNode relay, MmMethod method, float value) static
Send a message with explicit method and float value.
Definition at line 158 of file MmFluentExtensions.cs.
Send() [9/18]
MmFluentMessage MercuryMessaging.MmFluentExtensions.Send (this MmRelayNode relay, MmMethod method, int value) static
Send a message with explicit method and int value.
Use this when you need to specify the method explicitly (e.g., for custom methods).
Definition at line 140 of file MmFluentExtensions.cs.
Send() [10/18]
MmFluentMessage MercuryMessaging.MmFluentExtensions.Send (this MmRelayNode relay, MmMethod method, object payload) static
Send a message with explicit method and object payload.
Definition at line 185 of file MmFluentExtensions.cs.
Send() [11/18]
MmFluentMessage MercuryMessaging.MmFluentExtensions.Send (this MmRelayNode relay, MmMethod method, string value) static
Send a message with explicit method and string value.
Definition at line 167 of file MmFluentExtensions.cs.
Send() [12/18]
MmFluentMessage MercuryMessaging.MmFluentExtensions.Send (this MmRelayNode relay, MmMethod method, Vector3 value) static
Send a message with explicit method and Vector3 value.
Definition at line 176 of file MmFluentExtensions.cs.
Send() [13/18]
MmFluentMessage MercuryMessaging.MmFluentExtensions.Send (this MmRelayNode relay, object payload) static
Send a message using the fluent API.
Parameters
relay The relay node to send from.
payload The message payload (will auto-detect type).
Returns
A fluent message builder for chaining.
Definition at line 22 of file MmFluentExtensions.cs.
References DetectMethodFromPayload().
Referenced by Broadcast(), Broadcast(), MercuryMessaging.MmNetworkExtensions.SendNetworked(), MercuryMessaging.MmNetworkExtensions.SendNetworked(), MercuryMessaging.MmNetworkExtensions.SendNetworked(), MercuryMessaging.MmNetworkExtensions.SendNetworked(), MercuryMessaging.MmNetworkExtensions.SendNetworked(), and MercuryMessaging.MmNetworkExtensions.SendNetworked().
Send() [14/18]
MmFluentMessage MercuryMessaging.MmFluentExtensions.Send (this MmRelayNode relay, Quaternion value) static
Send a Quaternion message.
Definition at line 90 of file MmFluentExtensions.cs.
Send() [15/18]
MmFluentMessage MercuryMessaging.MmFluentExtensions.Send (this MmRelayNode relay, string value) static
Send a string message.
Definition at line 63 of file MmFluentExtensions.cs.
Send() [16/18]
MmFluentMessage MercuryMessaging.MmFluentExtensions.Send (this MmRelayNode relay, Transform value) static
Send a Transform reference message.
Definition at line 99 of file MmFluentExtensions.cs.
Send() [17/18]
MmFluentMessage MercuryMessaging.MmFluentExtensions.Send (this MmRelayNode relay, Vector3 value) static
Send a Vector3 message.
Definition at line 72 of file MmFluentExtensions.cs.
Send() [18/18]
MmFluentMessage MercuryMessaging.MmFluentExtensions.Send (this MmRelayNode relay, Vector4 value) static
Send a Vector4 message.
Definition at line 81 of file MmFluentExtensions.cs.
SetActive()
MmFluentMessage MercuryMessaging.MmFluentExtensions.SetActive (this MmRelayNode relay, bool active) static
Send a SetActive command.
Definition at line 225 of file MmFluentExtensions.cs.
Switch()
MmFluentMessage MercuryMessaging.MmFluentExtensions.Switch (this MmRelayNode relay, string stateName) static
Send a Switch state command.
Definition at line 234 of file MmFluentExtensions.cs.
The documentation for this class was generated from the following file:
Protocol/DSL/MmFluentExtensions.cs