MercuryMessaging: MercuryMessaging.Network.MmLoopbackBackend Class Reference
MercuryMessaging.Network.MmLoopbackBackend Class Reference
Loopback backend for testing network code without an actual network.
Public Types
enum LoopbackMode { Echo , Server , Client }
Operating mode for the loopback backend.
Public Member Functions
void Initialize ()
Initialize the backend.Called once before use.
void Shutdown ()
Clean up resources.Called when backend is no longer needed.
void SendToServer (byte[] data, MmReliability reliability=MmReliability.Reliable)
Send a message to the server (client-side).
Parameters
data Binary message data
reliability Delivery guarantee
void SendToAllClients (byte[] data, MmReliability reliability=MmReliability.Reliable)
Send a message to all clients (server-side broadcast).
Parameters
data Binary message data
reliability Delivery guarantee
void SendToClient (int clientId, byte[] data, MmReliability reliability=MmReliability.Reliable)
Send a message to a specific client (server-side).
Parameters
clientId Target client's network ID
data Binary message data
reliability Delivery guarantee
void SendToOtherClients (int excludeClientId, byte[] data, MmReliability reliability=MmReliability.Reliable)
Send a message to all clients except one (server-side).Useful for forwarding messages from one client to others.
Parameters
excludeClientId Client ID to exclude
data Binary message data
reliability Delivery guarantee
void ProcessPendingMessages ()
Process any pending messages in the queue.
void FlushMessages ()
Force delivery of all pending messages immediately.
void ClearSentMessages ()
Clear the sent messages list.
void Reset ()
Reset the backend to initial state.
Properties
LoopbackMode Mode = LoopbackMode.Echo [get, set]
Current operating mode.
bool UseMessageQueue = false [get, set]
If true, messages are queued and delivered on ProcessPendingMessages().
int SimulatedLatencyMs = 0 [get, set]
Simulated latency in milliseconds (only applies when UseMessageQueue is true).
bool IsConnected [get]
Whether currently connected to the network.
bool IsServer [get]
Whether this instance is the server/host.
bool IsClient [get]
Whether this instance is a client (non-host).Note: On host machines, both IsServer and IsClient may be true.
int LocalClientId [get]
This client's network ID (-1 if not connected or if server-only).
string BackendName [get]
Human-readable name of this backend (e.g., "FishNet", "Fusion2").
int PendingMessageCount [get]
Get the number of pending messages in the queue.
List< byte[]> SentMessages = new List<byte[]>() [get]
List of all messages sent through this backend (for test verification).
bool RecordSentMessages = false [get, set]
If true, stores all sent messages in SentMessages list for verification.
Events
MmNetworkMessageReceived OnMessageReceived
MmNetworkConnectionChanged OnClientConnected
MmNetworkConnectionChanged OnClientDisconnected
Action OnConnectedToServer
Action OnDisconnectedFromServer
Private Member Functions
void DeliverMessage (byte[] data, int senderId)
Private Attributes
bool _isInitialized
readonly Queue<(byte[] data, int senderId, DateTime deliveryTime)> _messageQueue = new Queue<(byte[], int, DateTime)>()
Detailed Description
Loopback backend for testing network code without an actual network.
This backend immediately echoes sent messages back to OnMessageReceived, allowing unit tests and integration tests to verify serialization, deserialization, and message routing without network latency or complexity.
Modes:
Server mode: SendToAllClients echoes back, SendToServer is ignored
Client mode: SendToServer echoes back, SendToAllClients is ignored
Loopback mode (default): All sends echo back immediately
Definition at line 51 of file MmLoopbackBackend.cs.
Member Enumeration Documentation
LoopbackMode
enum MercuryMessaging.Network.MmLoopbackBackend.LoopbackMode
Operating mode for the loopback backend.
Enumerator
Echo
All sends immediately echo back (default).
Server
Simulate server behavior.
Client
Simulate client behavior.
Definition at line 58 of file MmLoopbackBackend.cs.
Member Function Documentation
ClearSentMessages()
void MercuryMessaging.Network.MmLoopbackBackend.ClearSentMessages ()
Clear the sent messages list.
References SentMessages.
DeliverMessage()
void MercuryMessaging.Network.MmLoopbackBackend.DeliverMessage (byte[] data, int senderId) private
Definition at line 220 of file MmLoopbackBackend.cs.
References _messageQueue, OnMessageReceived, SimulatedLatencyMs, and UseMessageQueue.
Referenced by SendToAllClients(), SendToClient(), SendToOtherClients(), and SendToServer().
FlushMessages()
void MercuryMessaging.Network.MmLoopbackBackend.FlushMessages ()
Force delivery of all pending messages immediately.
Definition at line 264 of file MmLoopbackBackend.cs.
References _messageQueue, and OnMessageReceived.
Initialize()
void MercuryMessaging.Network.MmLoopbackBackend.Initialize ()
Initialize the backend.Called once before use.
Implements MercuryMessaging.Network.IMmNetworkBackend.
Definition at line 135 of file MmLoopbackBackend.cs.
References _isInitialized, _messageQueue, Mode, OnClientConnected, and OnConnectedToServer.
ProcessPendingMessages()
void MercuryMessaging.Network.MmLoopbackBackend.ProcessPendingMessages ()
Process any pending messages in the queue.
Call this in Update() or a test loop when UseMessageQueue is true.
Definition at line 238 of file MmLoopbackBackend.cs.
References _messageQueue, and OnMessageReceived.
Reset()
void MercuryMessaging.Network.MmLoopbackBackend.Reset ()
Reset the backend to initial state.
Definition at line 295 of file MmLoopbackBackend.cs.
References _messageQueue, Mode, RecordSentMessages, SentMessages, Shutdown(), SimulatedLatencyMs, and UseMessageQueue.
SendToAllClients()
void MercuryMessaging.Network.MmLoopbackBackend.SendToAllClients (byte[] data, MmReliability reliability = MmReliability::Reliable)
Send a message to all clients (server-side broadcast).
Parameters
data Binary message data
reliability Delivery guarantee
Implements MercuryMessaging.Network.IMmNetworkBackend.
Definition at line 181 of file MmLoopbackBackend.cs.
References _isInitialized, DeliverMessage(), and Mode.
SendToClient()
void MercuryMessaging.Network.MmLoopbackBackend.SendToClient (int clientId, byte[] data, MmReliability reliability = MmReliability::Reliable)
Send a message to a specific client (server-side).
Parameters
clientId Target client's network ID
data Binary message data
reliability Delivery guarantee
Implements MercuryMessaging.Network.IMmNetworkBackend.
Definition at line 193 of file MmLoopbackBackend.cs.
References _isInitialized, DeliverMessage(), and Mode.
SendToOtherClients()
void MercuryMessaging.Network.MmLoopbackBackend.SendToOtherClients (int excludeClientId, byte[] data, MmReliability reliability = MmReliability::Reliable)
Send a message to all clients except one (server-side).Useful for forwarding messages from one client to others.
Parameters
excludeClientId Client ID to exclude
data Binary message data
reliability Delivery guarantee
Implements MercuryMessaging.Network.IMmNetworkBackend.
Definition at line 205 of file MmLoopbackBackend.cs.
References _isInitialized, DeliverMessage(), LocalClientId, and Mode.
SendToServer()
void MercuryMessaging.Network.MmLoopbackBackend.SendToServer (byte[] data, MmReliability reliability = MmReliability::Reliable)
Send a message to the server (client-side).
Parameters
data Binary message data
reliability Delivery guarantee
Implements MercuryMessaging.Network.IMmNetworkBackend.
Definition at line 169 of file MmLoopbackBackend.cs.
References _isInitialized, DeliverMessage(), LocalClientId, and Mode.
Shutdown()
void MercuryMessaging.Network.MmLoopbackBackend.Shutdown ()
Clean up resources.Called when backend is no longer needed.
Implements MercuryMessaging.Network.IMmNetworkBackend.
Definition at line 151 of file MmLoopbackBackend.cs.
References _isInitialized, _messageQueue, Mode, OnClientDisconnected, and OnDisconnectedFromServer.
Referenced by Reset().
Member Data Documentation
_isInitialized
bool MercuryMessaging.Network.MmLoopbackBackend._isInitialized private
Definition at line 96 of file MmLoopbackBackend.cs.
Referenced by Initialize(), SendToAllClients(), SendToClient(), SendToOtherClients(), SendToServer(), and Shutdown().
_messageQueue
readonly Queue<(byte[] data, int senderId, DateTime deliveryTime)> MercuryMessaging.Network.MmLoopbackBackend._messageQueue = new Queue<(byte[], int, DateTime)>() private
Definition at line 97 of file MmLoopbackBackend.cs.
Referenced by DeliverMessage(), FlushMessages(), Initialize(), ProcessPendingMessages(), Reset(), and Shutdown().
Property Documentation
BackendName
string MercuryMessaging.Network.MmLoopbackBackend.BackendName get
Human-readable name of this backend (e.g., "FishNet", "Fusion2").
Implements MercuryMessaging.Network.IMmNetworkBackend.
Definition at line 117 of file MmLoopbackBackend.cs.
IsClient
bool MercuryMessaging.Network.MmLoopbackBackend.IsClient get
Whether this instance is a client (non-host).Note: On host machines, both IsServer and IsClient may be true.
Implements MercuryMessaging.Network.IMmNetworkBackend.
Definition at line 111 of file MmLoopbackBackend.cs.
IsConnected
bool MercuryMessaging.Network.MmLoopbackBackend.IsConnected get
Whether currently connected to the network.
Implements MercuryMessaging.Network.IMmNetworkBackend.
Definition at line 105 of file MmLoopbackBackend.cs.
IsServer
bool MercuryMessaging.Network.MmLoopbackBackend.IsServer get
Whether this instance is the server/host.
Implements MercuryMessaging.Network.IMmNetworkBackend.
Definition at line 108 of file MmLoopbackBackend.cs.
LocalClientId
int MercuryMessaging.Network.MmLoopbackBackend.LocalClientId get
This client's network ID (-1 if not connected or if server-only).
Implements MercuryMessaging.Network.IMmNetworkBackend.
Definition at line 114 of file MmLoopbackBackend.cs.
Referenced by SendToOtherClients(), and SendToServer().
Mode
LoopbackMode MercuryMessaging.Network.MmLoopbackBackend.Mode = LoopbackMode.Echo get set
Current operating mode.
Definition at line 79 of file MmLoopbackBackend.cs.
Referenced by Initialize(), Reset(), SendToAllClients(), SendToClient(), SendToOtherClients(), SendToServer(), and Shutdown().
PendingMessageCount
int MercuryMessaging.Network.MmLoopbackBackend.PendingMessageCount get
Get the number of pending messages in the queue.
Definition at line 259 of file MmLoopbackBackend.cs.
RecordSentMessages
bool MercuryMessaging.Network.MmLoopbackBackend.RecordSentMessages = false get set
If true, stores all sent messages in SentMessages list for verification.
Definition at line 285 of file MmLoopbackBackend.cs.
Referenced by Reset().
SentMessages
List<byte[]> MercuryMessaging.Network.MmLoopbackBackend.SentMessages = new List<byte[]>() get
List of all messages sent through this backend (for test verification).
Definition at line 280 of file MmLoopbackBackend.cs.
Referenced by ClearSentMessages(), and Reset().
SimulatedLatencyMs
int MercuryMessaging.Network.MmLoopbackBackend.SimulatedLatencyMs = 0 get set
Simulated latency in milliseconds (only applies when UseMessageQueue is true).
Definition at line 90 of file MmLoopbackBackend.cs.
Referenced by DeliverMessage(), and Reset().
UseMessageQueue
bool MercuryMessaging.Network.MmLoopbackBackend.UseMessageQueue = false get set
If true, messages are queued and delivered on ProcessPendingMessages().
If false (default), messages are delivered immediately.
Definition at line 85 of file MmLoopbackBackend.cs.
Referenced by DeliverMessage(), and Reset().
Event Documentation
OnClientConnected
MmNetworkConnectionChanged MercuryMessaging.Network.MmLoopbackBackend.OnClientConnected
Definition at line 123 of file MmLoopbackBackend.cs.
Referenced by Initialize().
OnClientDisconnected
MmNetworkConnectionChanged MercuryMessaging.Network.MmLoopbackBackend.OnClientDisconnected
Definition at line 126 of file MmLoopbackBackend.cs.
Referenced by Shutdown().
OnConnectedToServer
Action MercuryMessaging.Network.MmLoopbackBackend.OnConnectedToServer
Definition at line 129 of file MmLoopbackBackend.cs.
Referenced by Initialize().
OnDisconnectedFromServer
Action MercuryMessaging.Network.MmLoopbackBackend.OnDisconnectedFromServer
Definition at line 132 of file MmLoopbackBackend.cs.
Referenced by Shutdown().
OnMessageReceived
MmNetworkMessageReceived MercuryMessaging.Network.MmLoopbackBackend.OnMessageReceived
Definition at line 120 of file MmLoopbackBackend.cs.
Referenced by DeliverMessage(), FlushMessages(), and ProcessPendingMessages().
The documentation for this class was generated from the following file:
Protocol/Network/MmLoopbackBackend.cs