MercuryMessaging: MercuryMessaging.MmHierarchyExtensions Class Reference
MercuryMessaging.MmHierarchyExtensions Class Reference
Extension methods for relay node hierarchy management.
Static Public Member Functions
static MmRelayNode AddChildNode (this MmRelayNode parent, string name)
Add a child relay node to this node.
static MmRelayNode AddChildNode< T > (this MmRelayNode parent, string name)
Add a child relay node with a responder component.
static MmRelaySwitchNode AddSwitchChild (this MmRelayNode parent, string name)
Add a switch node child.
static void DetachFromParent (this MmRelayNode node)
Detach this node from its parent hierarchy.
static void ReparentTo (this MmRelayNode node, MmRelayNode newParent)
Move this node to a new parent.
static void MmSetParent (this MmRelayNode node, MmRelayNode newParent, bool worldPositionStays=true)
Set the parent of this relay node, properly handling routing table registration.
static void MmSetParent (this MmRelayNode node, Transform newParentTransform, bool worldPositionStays=true)
Set the parent by Transform, looking up the MmRelayNode automatically.
static MmRelayNode CloneStructure (this MmRelayNode source, Transform newParent=null)
Clone this node's hierarchy structure under a new parent.
Detailed Description
Extension methods for relay node hierarchy management.
Definition at line 371 of file HierarchyBuilder.cs.
Member Function Documentation
AddChildNode()
MmRelayNode MercuryMessaging.MmHierarchyExtensions.AddChildNode (this MmRelayNode parent, string name) static
Add a child relay node to this node.
Creates the GameObject and registers in routing table.
Definition at line 377 of file HierarchyBuilder.cs.
References MercuryMessaging.MmRelayNode.MmAddToRoutingTable().
AddChildNode< T >()
MmRelayNode MercuryMessaging.MmHierarchyExtensions.AddChildNode< T > (this MmRelayNode parent, string name) static
Add a child relay node with a responder component.
Type Constraints
T : MmBaseResponder
Definition at line 392 of file HierarchyBuilder.cs.
AddSwitchChild()
MmRelaySwitchNode MercuryMessaging.MmHierarchyExtensions.AddSwitchChild (this MmRelayNode parent, string name) static
Add a switch node child.
Definition at line 403 of file HierarchyBuilder.cs.
References MercuryMessaging.MmRelayNode.MmAddToRoutingTable().
CloneStructure()
MmRelayNode MercuryMessaging.MmHierarchyExtensions.CloneStructure (this MmRelayNode source, Transform newParent = null) static
Clone this node's hierarchy structure under a new parent.
Does NOT clone responder state, only structure.
Definition at line 519 of file HierarchyBuilder.cs.
DetachFromParent()
void MercuryMessaging.MmHierarchyExtensions.DetachFromParent (this MmRelayNode node) static
Detach this node from its parent hierarchy.
Definition at line 418 of file HierarchyBuilder.cs.
References MercuryMessaging.MmRelayNode.RefreshParents().
MmSetParent() [1/2]
void MercuryMessaging.MmHierarchyExtensions.MmSetParent (this MmRelayNode node, MmRelayNode newParent, bool worldPositionStays = true) static
Set the parent of this relay node, properly handling routing table registration.
This is the recommended way to reparent relay nodes at runtime. Handles: unregister from old parent, Unity SetParent, register with new parent.
Parameters
node The node to reparent
newParent The new parent relay node (null to make this a root node)
worldPositionStays If true, the world position is maintained. Passed to Transform.SetParent.
Definition at line 452 of file HierarchyBuilder.cs.
References MercuryMessaging.MmRelayNode.AddParent(), MercuryMessaging.MmRelayNode.MmAddToRoutingTable(), and MercuryMessaging.MmRelayNode.RefreshParents().
MmSetParent() [2/2]
void MercuryMessaging.MmHierarchyExtensions.MmSetParent (this MmRelayNode node, Transform newParentTransform, bool worldPositionStays = true) static
Set the parent by Transform, looking up the MmRelayNode automatically.
Parameters
node The node to reparent
newParentTransform The new parent transform (must have MmRelayNode)
worldPositionStays If true, the world position is maintained.
Definition at line 495 of file HierarchyBuilder.cs.
ReparentTo()
void MercuryMessaging.MmHierarchyExtensions.ReparentTo (this MmRelayNode node, MmRelayNode newParent) static
Move this node to a new parent.
Note: Does NOT unregister from the old parent's routing table. For proper reparenting, use MmSetParent instead.
Definition at line 435 of file HierarchyBuilder.cs.
References MercuryMessaging.MmRelayNode.AddParent(), and MercuryMessaging.MmRelayNode.MmAddToRoutingTable().
The documentation for this class was generated from the following file:
Protocol/DSL/HierarchyBuilder.cs