MercuryMessaging: MercuryMessaging.Task.MmTaskManager< U > Class Template Reference
MercuryMessaging.Task.MmTaskManager< U > Class Template Reference
Class to manage a collection of tasks.
Public Member Functions
override void Awake ()
Get attached ItaskInfoCollectionLoader, which must be attached to the same game object.
override void Start ()
Prepare the tasks that were loaded.
MmTaskResponder< U > GetCurrentTaskResponder ()
Get current task responder.
MmTaskResponder< U > GetTaskResponder (MmRelayNode _mmRelayNode)
Extract a task responder from a given MmRelayNode.
virtual void ProceedToFirstTask ()
Set the current pointer to the first task in the list.
virtual void PrepareTasks ()
Prepare the tasks that were loaded by the TaskInfoCollectionLoader.
virtual void ProceedToNextTask ()
Move current task pointer to the next task info.
virtual bool ShouldTriggerSwitch ()
Base class implementation of ShouldTriggerSwitch always returns true.
LinkedListNode< U > GetNodeAt (int index)
Index accessor for LinkedList of task infos.
virtual void ApplySequenceID ()
Apply the user-based sequence ID to the associated MmTaskUserConfigurator.
override void MmInvoke (MmMessage msg)
Invoke an MmMethod.
virtual void SetActive (bool active)
Handle MmMethod: SetActive.
virtual void Initialize ()
Handle MmMethod: Initialize Initialize allows you to provide additional initialization logic in-between calls to Monobehavior provided Awake() and Start() calls.
virtual void Refresh (List< MmTransform > transformList)
Handle MmMethod: Refresh.
override MmRelayNode GetRelayNode ()
Implementation of IMmResponder's GetRelayNode.
virtual void Update ()
Base Update of MmResponder Derived classes should always override.
virtual void MmOnAwakeComplete ()
Post Awake callback used between objects implementing this interface.
virtual void MmOnStartComplete ()
Post Start callback used between objects implementing this interface This allows for initialization steps that must occur before one instance's Start and its first Update.
virtual void MmRegisterAwakeCompleteCallback (IMmCallback callback)
It is possible that certain handles are not going to be in-place when registration of the OnAwakeComplete callback is invoked.
virtual void MmRegisterStartCompleteCallback (IMmCallback callback)
It is possible that certain handles are not going to be in-place when registration of the OnStartComplete callback is invoked.
Public Attributes
MmRelaySwitchNode TasksNode
This switch node allows you to iterate through a set of tasks using the same mechanisms that allow you to iterate through an FSM of MmResponders.
LinkedList< U > TaskInfos
The loaded task infos.
MmTaskUserConfigurator MmTaskUserData
Contains information of where to load task data, and which tasks to load based on user ID.
bool SavePartialProgression = false
Allow task manager to save partial system progression info.
Protected Member Functions
virtual void Switch (string iName)
Handle MmMethod: Switch.
virtual void Complete (bool active)
Handle MmMethod: Switch.
virtual void ApplyTaskInfo (IMmSerializable serializableValue)
Handle MmMethod: TaskInfo Given a IMmSerializable, extract TaskInfo.
virtual void ReceivedMessage (MmMessage message)
Handle MmMethod: Base MmMessage.
virtual void ReceivedMessage (MmMessageBool message)
Handle MmMethod: MessageBool.
virtual void ReceivedMessage (MmMessageByteArray message)
Handle MmMethod: MessageByteArray.
virtual void ReceivedMessage (MmMessageFloat message)
Handle MmMethod: MessageFloat.
virtual void ReceivedMessage (MmMessageInt message)
Handle MmMethod: MessageInt.
virtual void ReceivedMessage (MmMessageSerializable message)
Handle MmMethod: MessageSerializable.
virtual void ReceivedMessage (MmMessageString message)
Handle MmMethod: MessageString Override this to handle Mercury's string messages.
virtual void ReceivedMessage (MmMessageTransform message)
Handle MmMethod: MessageTransform Override this to handle Mercury's transform messages.
virtual void ReceivedMessage (MmMessageTransformList message)
Handle MmMethod: MessageTransformList Override this to handle Mercury's transform list messages.
virtual void ReceivedMessage (MmMessageVector3 message)
Handle MmMethod: MessageVector3 Override this to handle Mercury's Vector3 messages.
virtual void ReceivedMessage (MmMessageVector4 message)
Handle MmMethod: MessageVector4 Override this to handle Mercury's Vector4 messages.
virtual void ReceivedMessage (MmMessageQuaternion message)
Handle MmMethod: MessageQuaternion Override this to handle Mercury's Quaternion messages.
Protected Attributes
LinkedListNode< U > currentTaskInfo
Node of currently selected task.
Properties
U CurrentTaskInfo [get, set]
Current task info.
U NextTaskInfo [get]
Next task info.
U PrevTaskInfo [get]
Previous task info.
int TotalTasksWithCurrentName [get]
Total number of task infos that have the same name.
IMmTaskInfoCollectionLoader< U > TaskInfoCollectionLoader [get]
Handle to the task info collection loader that is used to load the task collection.
GameObject MmGameObject [get]
Handle to an instance's GameObject.
MmTag Tag [get, set]
MmTags allow you to specify filters for execution in Mercury XM graphs.
bool TagCheckEnabled [get, set]
Determines whether tag checking is enabled for this IMmResponder.
bool ReceiveHandledMessages [get, set]
When true, this responder receives messages even if Handled=true.
Events
IMmCallback MmAwakeCompleteCallback
Event triggered in the MmResponder when this object is awoken.
IMmCallback MmStartCompleteCallback
Event triggered in the MmResponder when this object is started.
Private Attributes
IMmTaskInfoCollectionLoader< U > taskInfoCollectionLoader
This should be an item placed on the same GameObject as the MmTaskManager itself.
MmTag _mmTag = MmTagHelper.Everything
Determines whether tag checking is enabled for this IMmResponder.
bool tagCheckEnabled = true
By default IMmResponders have this set to true so that they receive all messages.
bool receiveHandledMessages = false
When true, this responder receives messages even if Handled=true.
Detailed Description
Class to manage a collection of tasks.
Template Parameters
U Must implement IMmTaskInfo
Type Constraints
U : class
U : IMmTaskInfo
U : new()
Definition at line 51 of file MmTaskManager.cs.
Member Function Documentation
ApplySequenceID()
virtual void MercuryMessaging.Task.MmTaskManager< U >.ApplySequenceID () virtual
Apply the user-based sequence ID to the associated MmTaskUserConfigurator.
Definition at line 253 of file MmTaskManager.cs.
References currentTaskInfo.
Referenced by PrepareTasks(), and ProceedToNextTask().
ApplyTaskInfo()
virtual void MercuryMessaging.MmBaseResponder.ApplyTaskInfo (IMmSerializable serializableValue) protected virtual inherited
Handle MmMethod: TaskInfo Given a IMmSerializable, extract TaskInfo.
Parameters
serializableValue Serializable class containing MmTask Info
Definition at line 202 of file MmBaseResponder.cs.
Referenced by MmInvoke().
Awake()
override void MercuryMessaging.Task.MmTaskManager< U >.Awake () virtual
Get attached ItaskInfoCollectionLoader, which must be attached to the same game object.
Reimplemented from MercuryMessaging.MmResponder.
Definition at line 128 of file MmTaskManager.cs.
References MercuryMessaging.MmLogger.LogApplication, MmTaskUserData, and taskInfoCollectionLoader.
Complete()
virtual void MercuryMessaging.MmBaseResponder.Complete (bool active) protected virtual inherited
Handle MmMethod: Switch.
Parameters
active Can be used to indicate active state of object that triggered complete message
Definition at line 193 of file MmBaseResponder.cs.
Referenced by MmInvoke().
GetCurrentTaskResponder()
MmTaskResponder< U > MercuryMessaging.Task.MmTaskManager< U >.GetCurrentTaskResponder ()
Get current task responder.
Returns
Current task responder
Definition at line 152 of file MmTaskManager.cs.
References TasksNode.
GetNodeAt()
LinkedListNode< U > MercuryMessaging.Task.MmTaskManager< U >.GetNodeAt (int index)
Index accessor for LinkedList of task infos.
Parameters
index Value index.
Returns
If in bounds, LinkedListNode at [index] from start.
Definition at line 232 of file MmTaskManager.cs.
References TaskInfos.
Referenced by PrepareTasks().
GetRelayNode()
override MmRelayNode MercuryMessaging.MmBaseResponder.GetRelayNode () inherited
Implementation of IMmResponder's GetRelayNode.
Returns
Returns MmRelayNode if one attached to GameObject, Otherwise returns NULL.
Implements MercuryMessaging.IMmResponder.
Definition at line 320 of file MmBaseResponder.cs.
Referenced by MercuryMessaging.MmMessagingExtensions.BroadcastInitialize(), MercuryMessaging.MmMessagingExtensions.BroadcastRefresh(), MercuryMessaging.MmMessagingExtensions.BroadcastSetActive(), MercuryMessaging.MmMessagingExtensions.BroadcastSwitch(), MercuryMessaging.MmMessagingExtensions.BroadcastValue(), MercuryMessaging.MmMessagingExtensions.BroadcastValue(), MercuryMessaging.MmMessagingExtensions.BroadcastValue(), MercuryMessaging.MmMessagingExtensions.BroadcastValue(), MercuryMessaging.MmResponderExtensions.Build(), MercuryMessaging.MmListenerExtensions.ClearAllListeners(), MercuryMessaging.MmQueryExtensions.FindByName(), MercuryMessaging.MmQueryExtensions.FindByPattern(), MercuryMessaging.MmListenerExtensions.GetListenerCount(), MercuryMessaging.MmQueryExtensions.HasSiblings(), MercuryMessaging.MmListenerExtensions.ListenFor(), MercuryMessaging.MmMessagingExtensions.NotifyComplete(), MercuryMessaging.MmMessagingExtensions.NotifyValue(), MercuryMessaging.MmMessagingExtensions.NotifyValue(), MercuryMessaging.MmMessagingExtensions.NotifyValue(), MercuryMessaging.MmMessagingExtensions.NotifyValue(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.On6DOF(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnAxis(), MercuryMessaging.MmListenerExtensions.OnBool(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnButton(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnClick(), MercuryMessaging.MmListenerExtensions.OnComplete(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnDrag(), MercuryMessaging.MmListenerExtensions.OnFloat(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnFocus(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnGaze(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnGesture(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnHover(), MercuryMessaging.MmListenerExtensions.OnInitialize(), MercuryMessaging.MmListenerExtensions.OnInt(), MercuryMessaging.MmListenerExtensions.OnRefresh(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnScroll(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnSelect(), MercuryMessaging.MmListenerExtensions.OnSetActive(), MercuryMessaging.MmListenerExtensions.OnString(), MercuryMessaging.MmListenerExtensions.OnSwitch(), MercuryMessaging.MmListenerExtensions.OnVector3(), MercuryMessaging.MmQueryExtensions.Query(), MercuryMessaging.MmRoutingExtensions.RegisterWith(), MercuryMessaging.MmMessagingExtensions.Send(), MercuryMessaging.MmMessagingExtensions.Send(), MercuryMessaging.MmMessagingExtensions.Send(), MercuryMessaging.MmQueryExtensions.SiblingCount(), MercuryMessaging.MmResponderExtensions.To(), MercuryMessaging.MmRoutingExtensions.UnregisterFrom(), and MercuryMessaging.MmTransformResponder.Update().
GetTaskResponder()
MmTaskResponder< U > MercuryMessaging.Task.MmTaskManager< U >.GetTaskResponder (MmRelayNode _mmRelayNode)
Extract a task responder from a given MmRelayNode.
Parameters
_mmRelayNode MmRelayNode - should share GameObject with a task responder.
Returns
MmTaskResponder, if present on GameObject.
Definition at line 163 of file MmTaskManager.cs.
Initialize()
virtual void MercuryMessaging.MmBaseResponder.Initialize () virtual inherited
Handle MmMethod: Initialize Initialize allows you to provide additional initialization logic in-between calls to Monobehavior provided Awake() and Start() calls.
Reimplemented in MercuryMessaging.Network.Backends.NetworkTestResponder.
Definition at line 166 of file MmBaseResponder.cs.
References MercuryMessaging.MmLogger.LogResponder.
Referenced by MmInvoke().
MmInvoke()
override void MercuryMessaging.MmBaseResponder.MmInvoke (MmMessage msg) virtual inherited
Invoke an MmMethod.
Implements a switch that handles the different MmMethods defined by default set in MmMethod MmMethod
Parameters
msgType Type of message. This specifies the type of the payload. This is important in networked scenarios, when proper deseriaization into the correct type requires knowing what was used to serialize the object originally. MmMessageType
msg The message to send.MmMessage
Reimplemented from MercuryMessaging.MmResponder.
Reimplemented in MercuryMessaging.MmExtendableResponder, MercuryMessaging.MmTransformResponder, MercuryMessaging.StandardLibrary.Input.MmInputResponder, and MercuryMessaging.StandardLibrary.UI.MmUIResponder.
Definition at line 67 of file MmBaseResponder.cs.
References ApplyTaskInfo(), Complete(), Initialize(), MercuryMessaging.MmMessage.MmMethod, ReceivedMessage(), Refresh(), SetActive(), and Switch().
MmOnAwakeComplete()
virtual void MercuryMessaging.MmResponder.MmOnAwakeComplete () virtual inherited
Post Awake callback used between objects implementing this interface.
This allows for initialization steps that must occur before one instance's Awake and its Start.
Implements MercuryMessaging.IMmResponder.
Definition at line 150 of file MmResponder.cs.
References MmAwakeCompleteCallback.
Referenced by Awake().
MmOnStartComplete()
virtual void MercuryMessaging.MmResponder.MmOnStartComplete () virtual inherited
Post Start callback used between objects implementing this interface This allows for initialization steps that must occur before one instance's Start and its first Update.
Implements MercuryMessaging.IMmResponder.
Definition at line 161 of file MmResponder.cs.
References MmStartCompleteCallback.
Referenced by Start().
MmRegisterAwakeCompleteCallback()
virtual void MercuryMessaging.MmResponder.MmRegisterAwakeCompleteCallback (IMmCallback callback) virtual inherited
It is possible that certain handles are not going to be in-place when registration of the OnAwakeComplete callback is invoked.
The is especially true in scenarios where MmRelayNodes are networked. This allows for a deferred registration, eliminating most instances where the Awake callback invocations fail.
Parameters
callback Callback to be registered.
Implements MercuryMessaging.IMmResponder.
Definition at line 175 of file MmResponder.cs.
References MercuryMessaging.IMmCallback(), and MmAwakeCompleteCallback.
MmRegisterStartCompleteCallback()
virtual void MercuryMessaging.MmResponder.MmRegisterStartCompleteCallback (IMmCallback callback) virtual inherited
It is possible that certain handles are not going to be in-place when registration of the OnStartComplete callback is invoked.
The is especially true in scenarios where MmRelayNodes are networked. This allows for a deferred registration, eliminating most instances where the Start callback invocations fail.
Parameters
callback Callback to be registered.
Implements MercuryMessaging.IMmResponder.
Definition at line 188 of file MmResponder.cs.
References MercuryMessaging.IMmCallback(), and MmStartCompleteCallback.
Referenced by MercuryMessaging.MmSwitchResponder.Awake().
PrepareTasks()
virtual void MercuryMessaging.Task.MmTaskManager< U >.PrepareTasks () virtual
Prepare the tasks that were loaded by the TaskInfoCollectionLoader.
Definition at line 180 of file MmTaskManager.cs.
References ApplySequenceID(), currentTaskInfo, GetNodeAt(), MercuryMessaging.MmLogger.LogError, MmTaskUserData, taskInfoCollectionLoader, and TaskInfos.
Referenced by Start().
ProceedToFirstTask()
virtual void MercuryMessaging.Task.MmTaskManager< U >.ProceedToFirstTask () virtual
Set the current pointer to the first task in the list.
Definition at line 171 of file MmTaskManager.cs.
References currentTaskInfo, and TaskInfos.
ProceedToNextTask()
virtual void MercuryMessaging.Task.MmTaskManager< U >.ProceedToNextTask () virtual
Move current task pointer to the next task info.
If the instance can, it will attempt to trigger a switch message to move the FSM to the next task state.
Definition at line 200 of file MmTaskManager.cs.
References ApplySequenceID(), CurrentTaskInfo, currentTaskInfo, SavePartialProgression, ShouldTriggerSwitch(), TaskInfoCollectionLoader, TaskInfos, and TasksNode.
ReceivedMessage() [1/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessage message) protected virtual inherited
Handle MmMethod: Base MmMessage.
Override this to handle base Mercury Messages.
Parameters
message MmMessage
Definition at line 211 of file MmBaseResponder.cs.
Referenced by MmInvoke().
ReceivedMessage() [2/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageBool message) protected virtual inherited
Handle MmMethod: MessageBool.
Override this to handle Mercury's bool messages.
Parameters
message MmMessageBool
Reimplemented in MercuryMessaging.Network.Backends.NetworkTestResponder.
Definition at line 220 of file MmBaseResponder.cs.
ReceivedMessage() [3/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageByteArray message) protected virtual inherited
Handle MmMethod: MessageByteArray.
Override this to handle Mercury's byte array messages.
Parameters
message MmMessageByteArray
Definition at line 229 of file MmBaseResponder.cs.
ReceivedMessage() [4/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageFloat message) protected virtual inherited
Handle MmMethod: MessageFloat.
Override this to handle Mercury's float messages.
Parameters
message MmMessageFloat
Reimplemented in MercuryMessaging.Network.Backends.NetworkTestResponder.
Definition at line 238 of file MmBaseResponder.cs.
ReceivedMessage() [5/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageInt message) protected virtual inherited
Handle MmMethod: MessageInt.
Override this to handle Mercury's int messages.
Parameters
message MmMessageInt
Reimplemented in MercuryMessaging.Network.Backends.NetworkTestResponder.
Definition at line 247 of file MmBaseResponder.cs.
ReceivedMessage() [6/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageQuaternion message) protected virtual inherited
Handle MmMethod: MessageQuaternion Override this to handle Mercury's Quaternion messages.
Parameters
message MmMessageQuaternion
Definition at line 310 of file MmBaseResponder.cs.
ReceivedMessage() [7/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageSerializable message) protected virtual inherited
Handle MmMethod: MessageSerializable.
Override this to handle Mercury's serializable messages.
Parameters
message MmMessageSerializable
Definition at line 256 of file MmBaseResponder.cs.
ReceivedMessage() [8/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageString message) protected virtual inherited
Handle MmMethod: MessageString Override this to handle Mercury's string messages.
Parameters
message MmMessageString
Reimplemented in MercuryMessaging.MmGuiResponder, and MercuryMessaging.Network.Backends.NetworkTestResponder.
Definition at line 265 of file MmBaseResponder.cs.
ReceivedMessage() [9/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageTransform message) protected virtual inherited
Handle MmMethod: MessageTransform Override this to handle Mercury's transform messages.
Parameters
message MmMessageTransform
Definition at line 274 of file MmBaseResponder.cs.
ReceivedMessage() [10/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageTransformList message) protected virtual inherited
Handle MmMethod: MessageTransformList Override this to handle Mercury's transform list messages.
Parameters
message MmMessageTransformList
Definition at line 283 of file MmBaseResponder.cs.
ReceivedMessage() [11/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageVector3 message) protected virtual inherited
Handle MmMethod: MessageVector3 Override this to handle Mercury's Vector3 messages.
Parameters
message MmMessageVector3
Reimplemented in MercuryMessaging.Network.Backends.NetworkTestResponder.
Definition at line 292 of file MmBaseResponder.cs.
ReceivedMessage() [12/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageVector4 message) protected virtual inherited
Handle MmMethod: MessageVector4 Override this to handle Mercury's Vector4 messages.
Parameters
message MmMessageVector4
Definition at line 301 of file MmBaseResponder.cs.
Refresh()
virtual void MercuryMessaging.MmBaseResponder.Refresh (List< MmTransform > transformList) virtual inherited
Handle MmMethod: Refresh.
Parameters
transformList List of transforms needed in refreshing an MmResponder.
Reimplemented in MercuryMessaging.Network.Backends.NetworkTestResponder.
Definition at line 175 of file MmBaseResponder.cs.
References MercuryMessaging.MmLogger.LogResponder.
Referenced by MmInvoke().
SetActive()
virtual void MercuryMessaging.MmBaseResponder.SetActive (bool active) virtual inherited
Handle MmMethod: SetActive.
Parameters
active Value of active state.
Reimplemented in MercuryMessaging.MmGuiResponder, and MercuryMessaging.Network.Backends.NetworkTestResponder.
Definition at line 154 of file MmBaseResponder.cs.
References MercuryMessaging.MmLogger.LogResponder.
Referenced by MmInvoke().
ShouldTriggerSwitch()
virtual bool MercuryMessaging.Task.MmTaskManager< U >.ShouldTriggerSwitch () virtual
Base class implementation of ShouldTriggerSwitch always returns true.
Returns
Whether to trigger a switch in the FSM
Definition at line 222 of file MmTaskManager.cs.
Referenced by ProceedToNextTask().
Start()
override void MercuryMessaging.Task.MmTaskManager< U >.Start () virtual
Prepare the tasks that were loaded.
Reimplemented from MercuryMessaging.MmResponder.
Definition at line 139 of file MmTaskManager.cs.
References MercuryMessaging.MmLogger.LogApplication, and PrepareTasks().
Switch()
virtual void MercuryMessaging.MmBaseResponder.Switch (string iName) protected virtual inherited
Handle MmMethod: Switch.
Parameters
iName Name of value in which to active.
Reimplemented in MercuryMessaging.MmSwitchResponder.
Definition at line 184 of file MmBaseResponder.cs.
Referenced by MmInvoke().
Update()
virtual void MercuryMessaging.MmResponder.Update () virtual inherited
Base Update of MmResponder Derived classes should always override.
Reimplemented in MercuryMessaging.MmTransformResponder, and MercuryMessaging.Task.MmTaskResponder< T >.
Definition at line 140 of file MmResponder.cs.
Member Data Documentation
_mmTag
MmTag MercuryMessaging.MmResponder._mmTag = MmTagHelper.Everything private inherited
Determines whether tag checking is enabled for this IMmResponder.
Definition at line 62 of file MmResponder.cs.
currentTaskInfo
LinkedListNode<U> MercuryMessaging.Task.MmTaskManager< U >.currentTaskInfo protected
Node of currently selected task.
Definition at line 75 of file MmTaskManager.cs.
Referenced by ApplySequenceID(), PrepareTasks(), ProceedToFirstTask(), and ProceedToNextTask().
MmTaskUserData
MmTaskUserConfigurator MercuryMessaging.Task.MmTaskManager< U >.MmTaskUserData
Contains information of where to load task data, and which tasks to load based on user ID.
Definition at line 70 of file MmTaskManager.cs.
Referenced by Awake(), and PrepareTasks().
receiveHandledMessages
bool MercuryMessaging.MmResponder.receiveHandledMessages = false private inherited
When true, this responder receives messages even if Handled=true.
Useful for logging, analytics, or handlers that need to see all messages. Default: false (responder skipped after message is handled). Similar to WPF's handledEventsToo parameter.
Definition at line 76 of file MmResponder.cs.
SavePartialProgression
bool MercuryMessaging.Task.MmTaskManager< U >.SavePartialProgression = false
Allow task manager to save partial system progression info.
Definition at line 93 of file MmTaskManager.cs.
Referenced by ProceedToNextTask().
tagCheckEnabled
bool MercuryMessaging.MmResponder.tagCheckEnabled = true private inherited
By default IMmResponders have this set to true so that they receive all messages.
Definition at line 68 of file MmResponder.cs.
Referenced by MercuryMessaging.MmRelayNode.MmAddToRoutingTable().
taskInfoCollectionLoader
IMmTaskInfoCollectionLoader<U> MercuryMessaging.Task.MmTaskManager< U >.taskInfoCollectionLoader private
This should be an item placed on the same GameObject as the MmTaskManager itself.
Definition at line 98 of file MmTaskManager.cs.
Referenced by Awake(), and PrepareTasks().
TaskInfos
LinkedList<U> MercuryMessaging.Task.MmTaskManager< U >.TaskInfos
The loaded task infos.
Definition at line 64 of file MmTaskManager.cs.
Referenced by GetNodeAt(), PrepareTasks(), ProceedToFirstTask(), and ProceedToNextTask().
TasksNode
MmRelaySwitchNode MercuryMessaging.Task.MmTaskManager< U >.TasksNode
This switch node allows you to iterate through a set of tasks using the same mechanisms that allow you to iterate through an FSM of MmResponders.
Definition at line 59 of file MmTaskManager.cs.
Referenced by GetCurrentTaskResponder(), and ProceedToNextTask().
Property Documentation
CurrentTaskInfo
U MercuryMessaging.Task.MmTaskManager< U >.CurrentTaskInfo get set
Current task info.
Definition at line 80 of file MmTaskManager.cs.
Referenced by ProceedToNextTask().
MmGameObject
GameObject MercuryMessaging.MmResponder.MmGameObject get inherited
Handle to an instance's GameObject.
Implements MercuryMessaging.IMmResponder.
Definition at line 81 of file MmResponder.cs.
NextTaskInfo
U MercuryMessaging.Task.MmTaskManager< U >.NextTaskInfo get
Next task info.
Definition at line 84 of file MmTaskManager.cs.
PrevTaskInfo
U MercuryMessaging.Task.MmTaskManager< U >.PrevTaskInfo get
Previous task info.
Definition at line 88 of file MmTaskManager.cs.
ReceiveHandledMessages
bool MercuryMessaging.MmResponder.ReceiveHandledMessages get set inherited
When true, this responder receives messages even if Handled=true.
Useful for logging, analytics, or handlers that need to see all messages.
Definition at line 110 of file MmResponder.cs.
Tag
MmTag MercuryMessaging.MmResponder.Tag get set inherited
MmTags allow you to specify filters for execution in Mercury XM graphs.
Implements MercuryMessaging.IMmResponder.
Definition at line 90 of file MmResponder.cs.
Referenced by MercuryMessaging.MmTagExtensions.HasTag(), and MercuryMessaging.MmRelayNode.MmAddToRoutingTable().
TagCheckEnabled
bool MercuryMessaging.MmResponder.TagCheckEnabled get set inherited
Determines whether tag checking is enabled for this IMmResponder.
Implements MercuryMessaging.IMmResponder.
Definition at line 100 of file MmResponder.cs.
Referenced by MercuryMessaging.MmRelayNode.MmAddToRoutingTable(), and MercuryMessaging.MmRelayNode.TagCheck().
TaskInfoCollectionLoader
IMmTaskInfoCollectionLoader<U> MercuryMessaging.Task.MmTaskManager< U >.TaskInfoCollectionLoader get
Handle to the task info collection loader that is used to load the task collection.
Definition at line 117 of file MmTaskManager.cs.
Referenced by ProceedToNextTask().
TotalTasksWithCurrentName
int MercuryMessaging.Task.MmTaskManager< U >.TotalTasksWithCurrentName get
Total number of task infos that have the same name.
Definition at line 103 of file MmTaskManager.cs.
Event Documentation
MmAwakeCompleteCallback
IMmCallback MercuryMessaging.MmResponder.MmAwakeCompleteCallback private inherited
Event triggered in the MmResponder when this object is awoken.
Definition at line 50 of file MmResponder.cs.
Referenced by MmOnAwakeComplete(), and MmRegisterAwakeCompleteCallback().
MmStartCompleteCallback
IMmCallback MercuryMessaging.MmResponder.MmStartCompleteCallback private inherited
Event triggered in the MmResponder when this object is started.
Definition at line 56 of file MmResponder.cs.
Referenced by MmOnStartComplete(), and MmRegisterStartCompleteCallback().
The documentation for this class was generated from the following file:
Task/MmTaskManager.cs