MercuryMessaging: MercuryMessaging.MmNetworkResponder Class Reference
MercuryMessaging.MmNetworkResponder Class Reference abstract
Public Member Functions
virtual void MmOnAwakeComplete ()
Post Awake callback used between objects implementing this interface.
virtual void MmOnStartComplete ()
Post Start callback used between objects implementing this interface This allows for initialization steps that must occur before one instance's Start and its first Update.
void MmRegisterAwakeCompleteCallback (IMmCallback callback)
It is possible that certain handles are not going to be in-place when registration of the OnAwakeComplete callback is invoked.
void MmRegisterStartCompleteCallback (IMmCallback callback)
It is possible that certain handles are not going to be in-place when registration of the OnStartComplete callback is invoked.
void MmInvoke (MmMessage msg, int connectionId=-1)
This is the network equivalent of IMmResponder's MmInvoke.
virtual void Awake ()
Awake gets the MmRelayNode, if one is present.
virtual void Start ()
Attempts to register the this responder with the MmNetworkManager.
void MmSendMessageToServer (MmMessage msg)
Method serializes message and sends it to server.
void MmSendMessageToClient (int channelId, MmMessage msg)
Send a message to a specific client.
void MmSendMessageToClient (MmMessage msg)
Send a message to all clients.
Properties
MmRelayNode MmRelayNode [get, private set]
Get a handle to an MmRelayNode that shares the same GameObject.
bool AllowClientToSend [get]
Allows us to stop messages on client from sending.
bool IsActiveAndEnabled [get]
Set when Network Obj is active & enabled.
bool OnServer [get]
Indicates whether the network responder is executing on a server.
bool OnClient [get]
Indicates whether the network responder is executing on a client.
Events
IMmCallback MmAwakeCompleteCallback
Event triggered in the MmNetworkResponder when this object is awoken.
IMmCallback MmStartCompleteCallback
Event triggered in the MmNetworkResponder when this object is started.
IMmCallback MmAwake
Event triggered in the MmNetworkResponder when this object is awoken.
IMmCallback MmStart
Event triggered in the MmNetworkResponder when this object is started.
Private Attributes
bool allowClientToSend = true
Allows us to stop messages on client from sending.
Detailed Description
Definition at line 38 of file MmNetworkResponder.cs.
Member Function Documentation
Awake()
virtual void MercuryMessaging.MmNetworkResponder.Awake () virtual
Awake gets the MmRelayNode, if one is present.
Also calls the post-awake callback.
Definition at line 172 of file MmNetworkResponder.cs.
References MercuryMessaging.MmLogger.LogFramework, MmAwake, and MmRelayNode.
MmInvoke()
void MercuryMessaging.MmNetworkResponder.MmInvoke (MmMessage msg, int connectionId = -1) abstract
This is the network equivalent of IMmResponder's MmInvoke.
The difference is this class allows specification of connectionIDs which can be used to ensure messages are routed to the correct objects on network clients.
Parameters
msgType Type of message. This specifies the type of the payload. This is important in networked scenarios, when proper deseriaization into the correct type requires knowing what was used to serialize the object originally.
msg The message to send.
connectionId Connection ID - use to identify clients.
Implements MercuryMessaging.IMmNetworkResponder.
Referenced by MercuryMessaging.MmQuickNode.MmInvoke(), and MercuryMessaging.MmRelayNode.MmInvoke().
MmOnAwakeComplete()
virtual void MercuryMessaging.MmNetworkResponder.MmOnAwakeComplete () virtual
Post Awake callback used between objects implementing this interface.
This allows for initialization steps that must occur before one instance's Awake and its Start.
Implements MercuryMessaging.IMmNetworkResponder.
Definition at line 78 of file MmNetworkResponder.cs.
References MmAwakeCompleteCallback.
MmOnStartComplete()
virtual void MercuryMessaging.MmNetworkResponder.MmOnStartComplete () virtual
Post Start callback used between objects implementing this interface This allows for initialization steps that must occur before one instance's Start and its first Update.
Implements MercuryMessaging.IMmNetworkResponder.
Definition at line 89 of file MmNetworkResponder.cs.
References MmStartCompleteCallback.
MmRegisterAwakeCompleteCallback()
void MercuryMessaging.MmNetworkResponder.MmRegisterAwakeCompleteCallback (IMmCallback callback)
It is possible that certain handles are not going to be in-place when registration of the OnAwakeComplete callback is invoked.
The is especially true in scenarios where MmRelayNodes are networked. This allows for a deferred registration, eliminating most instances where the Awake callback invocations fail.
Parameters
callback Callback to be registered.
Implements MercuryMessaging.IMmNetworkResponder.
Definition at line 103 of file MmNetworkResponder.cs.
References MercuryMessaging.IMmCallback(), and MmAwakeCompleteCallback.
MmRegisterStartCompleteCallback()
void MercuryMessaging.MmNetworkResponder.MmRegisterStartCompleteCallback (IMmCallback callback)
It is possible that certain handles are not going to be in-place when registration of the OnStartComplete callback is invoked.
The is especially true in scenarios where MmRelayNodes are networked. This allows for a deferred registration, eliminating most instances where the Start callback invocations fail.
Parameters
callback Callback to be registered.
Implements MercuryMessaging.IMmNetworkResponder.
Definition at line 116 of file MmNetworkResponder.cs.
References MercuryMessaging.IMmCallback(), and MmStartCompleteCallback.
MmSendMessageToClient() [1/2]
void MercuryMessaging.MmNetworkResponder.MmSendMessageToClient (int channelId, MmMessage msg) abstract
Send a message to a specific client.
Parameters
channelId Client connection ID
msgType Type of message. This specifies the type of the payload. This is important in networked scenarios, when proper deseriaization into the correct type requires knowing what was used to serialize the object originally.
msg The message to send.
MmSendMessageToClient() [2/2]
void MercuryMessaging.MmNetworkResponder.MmSendMessageToClient (MmMessage msg) abstract
Send a message to all clients.
Parameters
msgType Type of message. This specifies the type of the payload. This is important in networked scenarios, when proper deseriaization into the correct type requires knowing what was used to serialize the object originally.
msg The message to send.
MmSendMessageToServer()
void MercuryMessaging.MmNetworkResponder.MmSendMessageToServer (MmMessage msg) abstract
Method serializes message and sends it to server.
Parameters
msgType Type of message. This specifies the type of the payload. This is important in networked scenarios, when proper deseriaization into the correct type requires knowing what was used to serialize the object originally.
msg The message to send.
Start()
virtual void MercuryMessaging.MmNetworkResponder.Start () virtual
Attempts to register the this responder with the MmNetworkManager.
Also calls the post-start callback.
Definition at line 187 of file MmNetworkResponder.cs.
References MercuryMessaging.MmLogger.LogFramework, and MmStart.
Member Data Documentation
allowClientToSend
bool MercuryMessaging.MmNetworkResponder.allowClientToSend = true private
Allows us to stop messages on client from sending.
Definition at line 124 of file MmNetworkResponder.cs.
Property Documentation
AllowClientToSend
bool MercuryMessaging.MmNetworkResponder.AllowClientToSend get
Allows us to stop messages on client from sending.
Implements MercuryMessaging.IMmNetworkResponder.
Definition at line 129 of file MmNetworkResponder.cs.
IsActiveAndEnabled
bool MercuryMessaging.MmNetworkResponder.IsActiveAndEnabled get abstract
Set when Network Obj is active & enabled.
This is important since Objects in network scenarios may not be awake/active at the same times.
Implements MercuryMessaging.IMmNetworkResponder.
Definition at line 136 of file MmNetworkResponder.cs.
MmRelayNode
MmRelayNode MercuryMessaging.MmNetworkResponder.MmRelayNode get private set
Get a handle to an MmRelayNode that shares the same GameObject.
Definition at line 43 of file MmNetworkResponder.cs.
Referenced by Awake().
OnClient
bool MercuryMessaging.MmNetworkResponder.OnClient get abstract
Indicates whether the network responder is executing on a client.
Implements MercuryMessaging.IMmNetworkResponder.
Definition at line 146 of file MmNetworkResponder.cs.
OnServer
bool MercuryMessaging.MmNetworkResponder.OnServer get abstract
Indicates whether the network responder is executing on a server.
Implements MercuryMessaging.IMmNetworkResponder.
Definition at line 141 of file MmNetworkResponder.cs.
Event Documentation
MmAwake
IMmCallback MercuryMessaging.MmNetworkResponder.MmAwake
Event triggered in the MmNetworkResponder when this object is awoken.
Todo: Needs to be swapped for MmAwakeCompleteCallback
Definition at line 64 of file MmNetworkResponder.cs.
Referenced by Awake().
MmAwakeCompleteCallback
IMmCallback MercuryMessaging.MmNetworkResponder.MmAwakeCompleteCallback private
Event triggered in the MmNetworkResponder when this object is awoken.
Definition at line 51 of file MmNetworkResponder.cs.
Referenced by MmOnAwakeComplete(), and MmRegisterAwakeCompleteCallback().
MmStart
IMmCallback MercuryMessaging.MmNetworkResponder.MmStart
Event triggered in the MmNetworkResponder when this object is started.
Todo: Needs to be swapped for MmStartCompleteCallback
Definition at line 71 of file MmNetworkResponder.cs.
Referenced by Start().
MmStartCompleteCallback
IMmCallback MercuryMessaging.MmNetworkResponder.MmStartCompleteCallback private
Event triggered in the MmNetworkResponder when this object is started.
Definition at line 57 of file MmNetworkResponder.cs.
Referenced by MmOnStartComplete(), and MmRegisterStartCompleteCallback().
The documentation for this class was generated from the following file:
Protocol/Network/MmNetworkResponder.cs