MercuryMessaging: MercuryMessaging.Network.MmNetworkBridge Class Reference
MercuryMessaging.Network.MmNetworkBridge Class Reference
Central orchestrator for MercuryMessaging network communication.
Public Member Functions
void Configure (IMmNetworkBackend backend, IMmGameObjectResolver resolver)
Configure the network bridge with a backend and resolver.
void Initialize ()
Initialize the network bridge and start listening for messages.
void Shutdown ()
Shutdown the network bridge and clean up resources.
void RegisterRelayNode (uint networkId, MmRelayNode relayNode)
Register an MmRelayNode with its network ID for message routing.
void UnregisterRelayNode (uint networkId)
Unregister an MmRelayNode.
bool TryGetRelayNode (uint networkId, out MmRelayNode relayNode)
Try to get a registered relay node by network ID.
void SendToAllClients (MmMessage message, MmReliability reliability=MmReliability.Reliable)
Send a message to all connected clients (server-side).
void SendToServer (MmMessage message, MmReliability reliability=MmReliability.Reliable)
Send a message to the server (client-side).
void SendToClient (int clientId, MmMessage message, MmReliability reliability=MmReliability.Reliable)
Send a message to a specific client (server-side).
void Send (MmMessage message, MmReliability reliability=MmReliability.Reliable)
Send a message using the appropriate method based on server/client status.
Properties
static MmNetworkBridge Instance [get]
Singleton instance of the network bridge.
IMmNetworkBackend Backend [get, private set]
The active network backend.
IMmGameObjectResolver Resolver [get, private set]
The active GameObject resolver.
bool IsInitialized [get, private set]
Whether the bridge has been initialized.
bool IsConnected [get]
Whether connected to the network.
bool IsServer [get]
Whether this instance is the server/host.
bool IsClient [get]
Whether this instance is a client.
string BackendName [get]
Name of the active backend.
Events
Action< MmMessage > OnMessageReceived
Fired when a message is received and deserialized (before routing).
Action< MmMessage > OnMessageSent
Fired when a message is sent.
Private Member Functions
void Awake ()
void OnDestroy ()
bool ValidateSend (MmMessage message)
void PrepareMessageForSend (MmMessage message)
void HandleReceivedMessage (byte[] data, int senderId)
void ResolveGameObjectReferences (MmMessage message)
void RouteMessage (MmMessage message)
Private Attributes
readonly Dictionary< uint, MmRelayNode > _relayNodeRegistry = new Dictionary<uint, MmRelayNode>()
Registry of MmRelayNodes by their network IDs.
Static Private Attributes
static MmNetworkBridge _instance
Detailed Description
Central orchestrator for MercuryMessaging network communication.
MmNetworkBridge:
Manages the active network backend (FishNet, Fusion 2)
Handles message serialization/deserialization via MmBinarySerializer
Resolves network IDs to GameObjects via IMmGameObjectResolver
Routes incoming network messages to the correct MmRelayNode
Usage:
Set Backend and Resolver before connecting
Call Initialize() to start
Use Send() methods to transmit messages
Received messages are automatically routed to MmRelayNodes
Definition at line 56 of file MmNetworkBridge.cs.
Member Function Documentation
Awake()
void MercuryMessaging.Network.MmNetworkBridge.Awake () private
Definition at line 126 of file MmNetworkBridge.cs.
References _instance.
Configure()
void MercuryMessaging.Network.MmNetworkBridge.Configure (IMmNetworkBackend backend, IMmGameObjectResolver resolver)
Configure the network bridge with a backend and resolver.
Parameters
backend Network transport backend
resolver GameObject ID resolver
Definition at line 142 of file MmNetworkBridge.cs.
References Backend, IsInitialized, Resolver, and Shutdown().
HandleReceivedMessage()
void MercuryMessaging.Network.MmNetworkBridge.HandleReceivedMessage (byte[] data, int senderId) private
Definition at line 353 of file MmNetworkBridge.cs.
References MercuryMessaging.Network.MmBinarySerializer.Deserialize(), OnMessageReceived, ResolveGameObjectReferences(), and RouteMessage().
Referenced by Initialize(), and Shutdown().
Initialize()
void MercuryMessaging.Network.MmNetworkBridge.Initialize ()
Initialize the network bridge and start listening for messages.
Definition at line 159 of file MmNetworkBridge.cs.
References Backend, HandleReceivedMessage(), IsInitialized, and Resolver.
OnDestroy()
void MercuryMessaging.Network.MmNetworkBridge.OnDestroy () private
Definition at line 192 of file MmNetworkBridge.cs.
References Shutdown().
PrepareMessageForSend()
void MercuryMessaging.Network.MmNetworkBridge.PrepareMessageForSend (MmMessage message) private
Definition at line 333 of file MmNetworkBridge.cs.
References Resolver, and MercuryMessaging.MmMessageGameObject.Value.
Referenced by SendToAllClients(), SendToClient(), and SendToServer().
RegisterRelayNode()
void MercuryMessaging.Network.MmNetworkBridge.RegisterRelayNode (uint networkId, MmRelayNode relayNode)
Register an MmRelayNode with its network ID for message routing.
Parameters
networkId The network ID of the relay node
relayNode The relay node to register
Definition at line 206 of file MmNetworkBridge.cs.
References _relayNodeRegistry.
Referenced by RouteMessage().
ResolveGameObjectReferences()
void MercuryMessaging.Network.MmNetworkBridge.ResolveGameObjectReferences (MmMessage message) private
Definition at line 377 of file MmNetworkBridge.cs.
References MercuryMessaging.MmMessageGameObject.GameObjectNetId, and Resolver.
Referenced by HandleReceivedMessage().
RouteMessage()
void MercuryMessaging.Network.MmNetworkBridge.RouteMessage (MmMessage message) private
Definition at line 386 of file MmNetworkBridge.cs.
References MercuryMessaging.MmMessage.NetId, RegisterRelayNode(), Resolver, and TryGetRelayNode().
Referenced by HandleReceivedMessage().
Send()
void MercuryMessaging.Network.MmNetworkBridge.Send (MmMessage message, MmReliability reliability = MmReliability::Reliable)
Send a message using the appropriate method based on server/client status.
Clients send to server, server broadcasts to all clients.
Parameters
message The message to send
reliability Delivery guarantee
Definition at line 301 of file MmNetworkBridge.cs.
References Backend, SendToAllClients(), and SendToServer().
SendToAllClients()
void MercuryMessaging.Network.MmNetworkBridge.SendToAllClients (MmMessage message, MmReliability reliability = MmReliability::Reliable)
Send a message to all connected clients (server-side).
Parameters
message The message to send
reliability Delivery guarantee
Definition at line 248 of file MmNetworkBridge.cs.
References Backend, OnMessageSent, PrepareMessageForSend(), MercuryMessaging.Network.MmBinarySerializer.Serialize(), and ValidateSend().
Referenced by Send().
SendToClient()
void MercuryMessaging.Network.MmNetworkBridge.SendToClient (int clientId, MmMessage message, MmReliability reliability = MmReliability::Reliable)
Send a message to a specific client (server-side).
Parameters
clientId Target client ID
message The message to send
reliability Delivery guarantee
Definition at line 283 of file MmNetworkBridge.cs.
References Backend, OnMessageSent, PrepareMessageForSend(), MercuryMessaging.Network.MmBinarySerializer.Serialize(), and ValidateSend().
SendToServer()
void MercuryMessaging.Network.MmNetworkBridge.SendToServer (MmMessage message, MmReliability reliability = MmReliability::Reliable)
Send a message to the server (client-side).
Parameters
message The message to send
reliability Delivery guarantee
Definition at line 265 of file MmNetworkBridge.cs.
References Backend, OnMessageSent, PrepareMessageForSend(), MercuryMessaging.Network.MmBinarySerializer.Serialize(), and ValidateSend().
Referenced by Send().
Shutdown()
void MercuryMessaging.Network.MmNetworkBridge.Shutdown ()
Shutdown the network bridge and clean up resources.
Definition at line 177 of file MmNetworkBridge.cs.
References _relayNodeRegistry, Backend, HandleReceivedMessage(), and IsInitialized.
Referenced by Configure(), and OnDestroy().
TryGetRelayNode()
bool MercuryMessaging.Network.MmNetworkBridge.TryGetRelayNode (uint networkId, out MmRelayNode relayNode)
Try to get a registered relay node by network ID.
Definition at line 234 of file MmNetworkBridge.cs.
References _relayNodeRegistry.
Referenced by RouteMessage().
UnregisterRelayNode()
void MercuryMessaging.Network.MmNetworkBridge.UnregisterRelayNode (uint networkId)
Unregister an MmRelayNode.
Parameters
networkId The network ID to unregister
Definition at line 223 of file MmNetworkBridge.cs.
References _relayNodeRegistry.
ValidateSend()
bool MercuryMessaging.Network.MmNetworkBridge.ValidateSend (MmMessage message) private
Definition at line 313 of file MmNetworkBridge.cs.
References Backend, and IsInitialized.
Referenced by SendToAllClients(), SendToClient(), and SendToServer().
Member Data Documentation
_instance
MmNetworkBridge MercuryMessaging.Network.MmNetworkBridge._instance static private
Definition at line 60 of file MmNetworkBridge.cs.
Referenced by Awake().
_relayNodeRegistry
readonly Dictionary<uint, MmRelayNode> MercuryMessaging.Network.MmNetworkBridge._relayNodeRegistry = new Dictionary<uint, MmRelayNode>() private
Registry of MmRelayNodes by their network IDs.
Definition at line 105 of file MmNetworkBridge.cs.
Referenced by RegisterRelayNode(), Shutdown(), TryGetRelayNode(), and UnregisterRelayNode().
Property Documentation
Backend
IMmNetworkBackend MercuryMessaging.Network.MmNetworkBridge.Backend get private set
The active network backend.
Definition at line 90 of file MmNetworkBridge.cs.
Referenced by Configure(), Initialize(), Send(), SendToAllClients(), SendToClient(), SendToServer(), Shutdown(), and ValidateSend().
BackendName
string MercuryMessaging.Network.MmNetworkBridge.BackendName get
Name of the active backend.
Definition at line 436 of file MmNetworkBridge.cs.
Instance
MmNetworkBridge MercuryMessaging.Network.MmNetworkBridge.Instance static get
Singleton instance of the network bridge.
Definition at line 65 of file MmNetworkBridge.cs.
Referenced by MercuryMessaging.Network.Backends.Fusion2TestManager.BuildTestHierarchy(), MercuryMessaging.Network.Backends.Fusion2TestManager.Initialize(), MercuryMessaging.Network.Backends.Fusion2TestManager.ResolveTargetNetId(), MercuryMessaging.Network.Backends.Fusion2TestManager.SendTestInt(), MercuryMessaging.Network.Backends.Fusion2TestManager.SendTestString(), MercuryMessaging.Network.Backends.Fusion2TestManager.SendTestVector3(), MercuryMessaging.Network.Backends.Fusion2TestManager.Shutdown(), MercuryMessaging.Network.Backends.Fusion2TestManager.TestHierarchicalRouting(), and MercuryMessaging.Network.Backends.Fusion2TestManager.UpdateStatus().
IsClient
bool MercuryMessaging.Network.MmNetworkBridge.IsClient get
Whether this instance is a client.
Definition at line 431 of file MmNetworkBridge.cs.
IsConnected
bool MercuryMessaging.Network.MmNetworkBridge.IsConnected get
Whether connected to the network.
Definition at line 421 of file MmNetworkBridge.cs.
IsInitialized
bool MercuryMessaging.Network.MmNetworkBridge.IsInitialized get private set
Whether the bridge has been initialized.
Definition at line 100 of file MmNetworkBridge.cs.
Referenced by Configure(), Initialize(), Shutdown(), and ValidateSend().
IsServer
bool MercuryMessaging.Network.MmNetworkBridge.IsServer get
Whether this instance is the server/host.
Definition at line 426 of file MmNetworkBridge.cs.
Resolver
IMmGameObjectResolver MercuryMessaging.Network.MmNetworkBridge.Resolver get private set
The active GameObject resolver.
Definition at line 95 of file MmNetworkBridge.cs.
Referenced by Configure(), Initialize(), PrepareMessageForSend(), ResolveGameObjectReferences(), and RouteMessage().
Event Documentation
OnMessageReceived
Action<MmMessage> MercuryMessaging.Network.MmNetworkBridge.OnMessageReceived
Fired when a message is received and deserialized (before routing).
Useful for logging and debugging.
Definition at line 115 of file MmNetworkBridge.cs.
Referenced by HandleReceivedMessage().
OnMessageSent
Action<MmMessage> MercuryMessaging.Network.MmNetworkBridge.OnMessageSent
Fired when a message is sent.
Definition at line 120 of file MmNetworkBridge.cs.
Referenced by SendToAllClients(), SendToClient(), and SendToServer().
The documentation for this class was generated from the following file:
Protocol/Network/MmNetworkBridge.cs