MercuryMessaging: MercuryMessaging.MmRoutingTable Class Reference
MercuryMessaging.MmRoutingTable Class Reference
A form of Reorderable List ReorderableList<T> specifically for all derivations of MmResponder.
Public Types
enum ListFilter { All = 0 , RelayNodeOnly , ResponderOnly }
Useful for extracting certain types of MmResponders from the list.
Public Member Functions
List< string > GetMmNames (ListFilter filter=default(ListFilter), MmLevelFilter levelFilter=MmLevelFilterHelper.Default)
Get a list of the names all MmRoutingTableItems that match the provided filters.
List< MmRoutingTableItem > GetMmRoutingTableItems (ListFilter filter=default(ListFilter), MmLevelFilter levelFilter=MmLevelFilterHelper.Default)
Get a list of all MmRoutingTableItems that match the provided filters.
List< MmRelayNode > GetOnlyMmRelayNodes ()
Get a list of all MmRoutingTableItems that reference MmRelayNodes.
bool ContainsKey (string key)
Checks whether the MmRoutingTable contains an item with the provided name.
bool Contains (MmResponder responder)
Checks whether the MmRoutingTable contains an item with the provided MmResponder reference.
bool CheckFilter (MmRoutingTableItem item, ListFilter listFilter, MmLevelFilter levelFilter)
Checks the provided MmRoutingTableItem to see whether it passes the list filter requirements.
new void Add (MmRoutingTableItem item)
Override Add to maintain cache and indices.
new bool Remove (MmRoutingTableItem item)
Override Remove to maintain cache and indices.
new void RemoveAt (int index)
Override RemoveAt to maintain cache and indices.
new void Insert (int index, MmRoutingTableItem item)
Override Insert to maintain cache and indices.
new void Clear ()
Override Clear to maintain cache and indices.
ReorderableList ()
IEnumerator< T > GetEnumerator ()
void Add (T item)
bool Contains (T item)
void CopyTo (T[] array, int arrayIndex)
bool Remove (T item)
int IndexOf (T item)
void Insert (int index, T item)
Public Attributes
List< T > _list
Properties
float CacheHitRate [get]
Get cache hit rate (0.0 to 1.0).
MmRoutingTableItem this[string name] [get, set]
Accessor for MmRoutingTableItems by name.
MmRoutingTableItem this[MmResponder responder] [get]
Accessor for MmRoutingTableItems by MmResponder reference.
new MmRoutingTableItem this[int index] [get, set]
Override indexer setter to maintain cache and indices.
int Count [get]
bool IsReadOnly [get]
Private Member Functions
void EnsureIndicesInitialized ()
Initialize index structures if needed.
void RebuildIndices ()
Rebuild indices from current list contents.
void AddToIndices (MmRoutingTableItem item)
Add item to indices.
void RemoveFromIndices (MmRoutingTableItem item)
Remove item from indices.
void InvalidateIndices ()
Invalidate indices (set to null, will rebuild on next access).
void EnsureCacheInitialized ()
Initialize cache structures if needed.
void InvalidateCache ()
Clear all cached filter results.
void TouchCacheKey (MmFilterCacheKey key)
Update LRU tracking for cache key.
void EvictLRUIfNeeded ()
Evict least recently used cache entry if cache is full.
IEnumerator IEnumerable. GetEnumerator ()
Private Attributes
Dictionary< MmFilterCacheKey, List< MmRoutingTableItem > > _filterCache
Cache for filtered responder lists.
LinkedList< MmFilterCacheKey > _lruOrder
LRU tracking for cache eviction.
int _cacheHits = 0
Cache statistics for profiling (optional).
int _cacheMisses = 0
Dictionary< string, MmRoutingTableItem > _nameIndex
Dictionary index for O(1) lookup by name.
Dictionary< MmResponder, MmRoutingTableItem > _responderIndex
Dictionary index for O(1) lookup by responder reference.
Static Private Attributes
const int MAX_CACHE_SIZE = 100
Maximum number of cached filter results.
Detailed Description
A form of Reorderable List ReorderableList<T> specifically for all derivations of MmResponder.
Includes LRU cache for filtered responder lists (QW-3 optimization).
Definition at line 86 of file MmRoutingTable.cs.
Member Enumeration Documentation
ListFilter
enum MercuryMessaging.MmRoutingTable.ListFilter
Useful for extracting certain types of MmResponders from the list.
Enumerator
All
RelayNodeOnly
ResponderOnly
Definition at line 91 of file MmRoutingTable.cs.
Member Function Documentation
Add() [1/2]
new void MercuryMessaging.MmRoutingTable.Add (MmRoutingTableItem item)
Override Add to maintain cache and indices.
Definition at line 499 of file MmRoutingTable.cs.
References AddToIndices(), and InvalidateCache().
Add() [2/2]
void MercuryMessaging.ReorderableList< T >.Add (T item) inherited
Definition at line 68 of file ReorderableList.cs.
References _list.
AddToIndices()
void MercuryMessaging.MmRoutingTable.AddToIndices (MmRoutingTableItem item) private
Add item to indices.
Definition at line 185 of file MmRoutingTable.cs.
References _nameIndex, _responderIndex, EnsureIndicesInitialized(), MercuryMessaging.MmRoutingTableItem.Name, and MercuryMessaging.MmRoutingTableItem.Responder.
Referenced by Add(), and Insert().
CheckFilter()
bool MercuryMessaging.MmRoutingTable.CheckFilter (MmRoutingTableItem item, ListFilter listFilter, MmLevelFilter levelFilter)
Checks the provided MmRoutingTableItem to see whether it passes the list filter requirements.
Parameters
item Observed MmRoutingTableItem.
listFilter ListFilter ListFilter
levelFilter LevelFilter MmLevelFilter
Returns
Whether MmRoutingTableItem passes filter check.
Definition at line 477 of file MmRoutingTable.cs.
References MercuryMessaging.MmRoutingTableItem.Level, and MercuryMessaging.MmRoutingTableItem.Responder.
Referenced by GetMmRoutingTableItems().
Clear()
new void MercuryMessaging.MmRoutingTable.Clear ()
Override Clear to maintain cache and indices.
Definition at line 547 of file MmRoutingTable.cs.
References InvalidateCache(), and InvalidateIndices().
Contains() [1/2]
bool MercuryMessaging.MmRoutingTable.Contains (MmResponder responder)
Checks whether the MmRoutingTable contains an item with the provided MmResponder reference.
Parameters
responder MmResponder for which to search.
Returns
Whether the MmRoutingTable contains an item with the provided MmResponder reference.
Definition at line 464 of file MmRoutingTable.cs.
Contains() [2/2]
bool MercuryMessaging.ReorderableList< T >.Contains (T item) inherited
Definition at line 78 of file ReorderableList.cs.
References _list.
ContainsKey()
bool MercuryMessaging.MmRoutingTable.ContainsKey (string key)
Checks whether the MmRoutingTable contains an item with the provided name.
Parameters
key Name for which to search.
Returns
Whether the MmRoutingTable contains an item with the provided name.
Definition at line 452 of file MmRoutingTable.cs.
CopyTo()
void MercuryMessaging.ReorderableList< T >.CopyTo (T[] array, int arrayIndex) inherited
Definition at line 83 of file ReorderableList.cs.
References _list.
EnsureCacheInitialized()
void MercuryMessaging.MmRoutingTable.EnsureCacheInitialized () private
Initialize cache structures if needed.
Definition at line 260 of file MmRoutingTable.cs.
References _filterCache, _lruOrder, and MAX_CACHE_SIZE.
Referenced by GetMmRoutingTableItems().
EnsureIndicesInitialized()
void MercuryMessaging.MmRoutingTable.EnsureIndicesInitialized () private
Initialize index structures if needed.
Definition at line 145 of file MmRoutingTable.cs.
References _nameIndex, _responderIndex, and RebuildIndices().
Referenced by AddToIndices().
EvictLRUIfNeeded()
void MercuryMessaging.MmRoutingTable.EvictLRUIfNeeded () private
Evict least recently used cache entry if cache is full.
Definition at line 298 of file MmRoutingTable.cs.
References _filterCache, _lruOrder, and MAX_CACHE_SIZE.
Referenced by GetMmRoutingTableItems().
GetEnumerator() [1/2]
IEnumerator IEnumerable. MercuryMessaging.ReorderableList< T >.GetEnumerator () private inherited
Definition at line 59 of file ReorderableList.cs.
References GetEnumerator().
GetEnumerator() [2/2]
IEnumerator< T > MercuryMessaging.ReorderableList< T >.GetEnumerator () inherited
Definition at line 54 of file ReorderableList.cs.
References _list.
Referenced by GetEnumerator().
GetMmNames()
List< string > MercuryMessaging.MmRoutingTable.GetMmNames (ListFilter filter = default(ListFilter), MmLevelFilter levelFilter = MmLevelFilterHelper::Default)
Get a list of the names all MmRoutingTableItems that match the provided filters.
Parameters
filter ListFilter ListFilter
levelFilter LevelFilter MmLevelFilter
Returns
List of names of MmRoutingTableItems that pass filter checks.
Definition at line 369 of file MmRoutingTable.cs.
References GetMmRoutingTableItems().
GetMmRoutingTableItems()
List< MmRoutingTableItem > MercuryMessaging.MmRoutingTable.GetMmRoutingTableItems (ListFilter filter = default(ListFilter), MmLevelFilter levelFilter = MmLevelFilterHelper::Default)
Get a list of all MmRoutingTableItems that match the provided filters.
Uses LRU cache for performance (QW-3 optimization).
Parameters
filter ListFilter ListFilter
levelFilter LevelFilter MmLevelFilter
Returns
List of MmRoutingTableItems that pass filter checks.
Definition at line 390 of file MmRoutingTable.cs.
References _cacheHits, _cacheMisses, _filterCache, CheckFilter(), EnsureCacheInitialized(), EvictLRUIfNeeded(), and TouchCacheKey().
Referenced by GetMmNames().
GetOnlyMmRelayNodes()
List< MmRelayNode > MercuryMessaging.MmRoutingTable.GetOnlyMmRelayNodes ()
Get a list of all MmRoutingTableItems that reference MmRelayNodes.
Returns
List of all MmRoutingTableItems that reference MmRelayNodes.
Definition at line 432 of file MmRoutingTable.cs.
IndexOf()
int MercuryMessaging.ReorderableList< T >.IndexOf (T item) inherited
Definition at line 107 of file ReorderableList.cs.
References _list.
Insert() [1/2]
new void MercuryMessaging.MmRoutingTable.Insert (int index, MmRoutingTableItem item)
Override Insert to maintain cache and indices.
Definition at line 537 of file MmRoutingTable.cs.
References AddToIndices(), and InvalidateCache().
Insert() [2/2]
void MercuryMessaging.ReorderableList< T >.Insert (int index, T item) inherited
Definition at line 112 of file ReorderableList.cs.
References _list.
InvalidateCache()
void MercuryMessaging.MmRoutingTable.InvalidateCache () private
Clear all cached filter results.
Called when routing table is modified (add/remove responder).
Definition at line 273 of file MmRoutingTable.cs.
References _filterCache, and _lruOrder.
Referenced by Add(), Clear(), Insert(), Remove(), and RemoveAt().
InvalidateIndices()
void MercuryMessaging.MmRoutingTable.InvalidateIndices () private
Invalidate indices (set to null, will rebuild on next access).
Definition at line 238 of file MmRoutingTable.cs.
References _nameIndex, and _responderIndex.
Referenced by Clear().
RebuildIndices()
void MercuryMessaging.MmRoutingTable.RebuildIndices () private
Rebuild indices from current list contents.
Called after deserialization or when indices are null.
Definition at line 159 of file MmRoutingTable.cs.
References MercuryMessaging.ReorderableList< T >._list, _nameIndex, and _responderIndex.
Referenced by EnsureIndicesInitialized().
Remove() [1/2]
new bool MercuryMessaging.MmRoutingTable.Remove (MmRoutingTableItem item)
Override Remove to maintain cache and indices.
Definition at line 509 of file MmRoutingTable.cs.
References InvalidateCache(), and RemoveFromIndices().
Remove() [2/2]
bool MercuryMessaging.ReorderableList< T >.Remove (T item) inherited
Definition at line 88 of file ReorderableList.cs.
References _list.
RemoveAt()
new void MercuryMessaging.MmRoutingTable.RemoveAt (int index)
Override RemoveAt to maintain cache and indices.
Definition at line 523 of file MmRoutingTable.cs.
References MercuryMessaging.ReorderableList< T >._list, InvalidateCache(), and RemoveFromIndices().
Referenced by MercuryMessaging.MmRoutingExtensions.RemoveFromRoutingTable().
RemoveFromIndices()
void MercuryMessaging.MmRoutingTable.RemoveFromIndices (MmRoutingTableItem item) private
Remove item from indices.
Definition at line 207 of file MmRoutingTable.cs.
References MercuryMessaging.ReorderableList< T >._list, _nameIndex, _responderIndex, MercuryMessaging.MmRoutingTableItem.Name, and MercuryMessaging.MmRoutingTableItem.Responder.
Referenced by Remove(), and RemoveAt().
ReorderableList()
MercuryMessaging.ReorderableList< T >.ReorderableList () inherited
Definition at line 49 of file ReorderableList.cs.
References _list.
TouchCacheKey()
void MercuryMessaging.MmRoutingTable.TouchCacheKey (MmFilterCacheKey key) private
Update LRU tracking for cache key.
Moves key to end of LRU list (most recently used position).
Parameters
key Cache key that was accessed
Definition at line 287 of file MmRoutingTable.cs.
References _lruOrder.
Referenced by GetMmRoutingTableItems().
Member Data Documentation
_cacheHits
int MercuryMessaging.MmRoutingTable._cacheHits = 0 private
Cache statistics for profiling (optional).
Definition at line 120 of file MmRoutingTable.cs.
Referenced by GetMmRoutingTableItems().
_cacheMisses
int MercuryMessaging.MmRoutingTable._cacheMisses = 0 private
Definition at line 122 of file MmRoutingTable.cs.
Referenced by GetMmRoutingTableItems().
_filterCache
Dictionary<MmFilterCacheKey, List<MmRoutingTableItem> > MercuryMessaging.MmRoutingTable._filterCache private
Cache for filtered responder lists.
Key: combination of ListFilter and MmLevelFilter Value: pre-filtered list of routing table items
Definition at line 107 of file MmRoutingTable.cs.
Referenced by EnsureCacheInitialized(), EvictLRUIfNeeded(), GetMmRoutingTableItems(), and InvalidateCache().
_list
List<T> MercuryMessaging.ReorderableList< T >._list inherited
Definition at line 45 of file ReorderableList.cs.
Referenced by Add(), Clear(), Contains(), CopyTo(), GetEnumerator(), IndexOf(), Insert(), MercuryMessaging.MmRoutingTable.RebuildIndices(), Remove(), MercuryMessaging.MmRoutingTable.RemoveAt(), RemoveAt(), MercuryMessaging.MmRoutingTable.RemoveFromIndices(), and ReorderableList().
_lruOrder
LinkedList<MmFilterCacheKey> MercuryMessaging.MmRoutingTable._lruOrder private
LRU tracking for cache eviction.
Most recently used keys are at the end of the list.
Definition at line 114 of file MmRoutingTable.cs.
Referenced by EnsureCacheInitialized(), EvictLRUIfNeeded(), InvalidateCache(), and TouchCacheKey().
_nameIndex
Dictionary<string, MmRoutingTableItem> MercuryMessaging.MmRoutingTable._nameIndex private
Dictionary index for O(1) lookup by name.
Note: Names are not guaranteed unique - stores first occurrence.
Definition at line 133 of file MmRoutingTable.cs.
Referenced by AddToIndices(), EnsureIndicesInitialized(), InvalidateIndices(), RebuildIndices(), and RemoveFromIndices().
_responderIndex
Dictionary<MmResponder, MmRoutingTableItem> MercuryMessaging.MmRoutingTable._responderIndex private
Dictionary index for O(1) lookup by responder reference.
Responder references ARE unique in the routing table.
Definition at line 140 of file MmRoutingTable.cs.
Referenced by AddToIndices(), EnsureIndicesInitialized(), InvalidateIndices(), RebuildIndices(), and RemoveFromIndices().
MAX_CACHE_SIZE
const int MercuryMessaging.MmRoutingTable.MAX_CACHE_SIZE = 100 static private
Maximum number of cached filter results.
Prevents unbounded memory growth while maintaining high hit rate.
Definition at line 99 of file MmRoutingTable.cs.
Referenced by EnsureCacheInitialized(), and EvictLRUIfNeeded().
Property Documentation
CacheHitRate
float MercuryMessaging.MmRoutingTable.CacheHitRate get
Get cache hit rate (0.0 to 1.0).
Returns 0 if no cache operations yet.
Definition at line 248 of file MmRoutingTable.cs.
Count
int MercuryMessaging.ReorderableList< T >.Count get inherited
Definition at line 93 of file ReorderableList.cs.
Referenced by MercuryMessaging.MmRoutingExtensions.RemoveFromRoutingTable().
IsReadOnly
bool MercuryMessaging.ReorderableList< T >.IsReadOnly get inherited
Definition at line 98 of file ReorderableList.cs.
this[int index]
new MmRoutingTableItem MercuryMessaging.MmRoutingTable.this[int index] get set
Override indexer setter to maintain cache and indices.
Definition at line 557 of file MmRoutingTable.cs.
this[MmResponder responder]
MmRoutingTableItem MercuryMessaging.MmRoutingTable.this[MmResponder responder] get
Accessor for MmRoutingTableItems by MmResponder reference.
Uses O(1) dictionary lookup (Phase 2 optimization).
Parameters
responder MmResponder for which to search.
Returns
MmRoutingTableItem with reference or NULL.
Definition at line 351 of file MmRoutingTable.cs.
this[string name]
MmRoutingTableItem MercuryMessaging.MmRoutingTable.this[string name] get set
Accessor for MmRoutingTableItems by name.
Uses O(1) dictionary lookup (Phase 2 optimization). Will throw KeyNotFoundException if not found.
Parameters
name Name of MmRoutingTableItem.
Returns
First item with the name, or null if not found.
Definition at line 318 of file MmRoutingTable.cs.
The documentation for this class was generated from the following file:
Protocol/Routing/MmRoutingTable.cs