MercuryMessaging: MercuryMessaging.Network.MmReliabilityManager Class Reference
MercuryMessaging.Network.MmReliabilityManager Class Reference
Manages reliable message delivery with acknowledgments.
Public Member Functions
byte[] WrapPacket (byte[] data, MmReliability reliability, int targetClient)
Wrap data with reliability header and track for ACK.
byte[] UnwrapPacket (byte[] packet, out MmPacketHeader header)
Process received packet and extract data.
byte[] CreateAckPacket ()
Create an ACK-only packet.
byte[] CreatePingPacket (double sendTime)
Create a ping packet for RTT measurement.
byte[] CreatePongPacket (double originalSendTime)
Create a pong response packet.
void ProcessPong (byte[] packet)
Process a pong packet and update RTT.
void UpdateRTT (float measuredRTT)
Update RTT estimate using EWMA.
void Update (double currentTime)
Check for packets that need retransmission.
void Reset ()
Reset state (e.g., on disconnect).
Public Attributes
int MaxRetries = 5
Maximum retries before giving up on a packet.
float InitialRTO = 0.2f
Initial retransmit timeout in seconds.
float MaxRTO = 5.0f
Maximum retransmit timeout in seconds.
float RTTAlpha = 0.125f
RTT smoothing factor (EWMA).
Properties
float SmoothedRTT = 0.1f [get, private set]
Current smoothed RTT estimate.
float RTTVariance = 0.05f [get, private set]
RTT variance for timeout calculation.
float CurrentRTO [get]
Current retransmit timeout.
int PendingCount [get]
Number of packets awaiting acknowledgment.
Events
Action< uint > OnPacketAcked
Action< uint > OnPacketLost
Action< byte[], int > OnRetransmit
Private Member Functions
uint GetNextSequence ()
Get next sequence number.
void TrackReceived (uint seq)
Track a received sequence number.
void ProcessAcks (uint ackSeq, uint ackBits)
Process acknowledgments from received packet.
Private Attributes
uint _nextSequence = 1
uint _lastReceivedSequence = 0
uint _receivedBitfield = 0
readonly Dictionary< uint, MmPendingPacket > _pendingPackets = new Dictionary<uint, MmPendingPacket>()
readonly object _lock = new object()
Detailed Description
Manages reliable message delivery with acknowledgments.
Definition at line 96 of file MmReliabilityManager.cs.
Member Function Documentation
CreateAckPacket()
byte[] MercuryMessaging.Network.MmReliabilityManager.CreateAckPacket ()
Create an ACK-only packet.
Definition at line 233 of file MmReliabilityManager.cs.
References _lastReceivedSequence, _receivedBitfield, and MercuryMessaging.Network.Unreliable.
CreatePingPacket()
byte[] MercuryMessaging.Network.MmReliabilityManager.CreatePingPacket (double sendTime)
Create a ping packet for RTT measurement.
Definition at line 255 of file MmReliabilityManager.cs.
References MercuryMessaging.Network.Unreliable.
CreatePongPacket()
byte[] MercuryMessaging.Network.MmReliabilityManager.CreatePongPacket (double originalSendTime)
Create a pong response packet.
Definition at line 278 of file MmReliabilityManager.cs.
References MercuryMessaging.Network.Unreliable.
GetNextSequence()
uint MercuryMessaging.Network.MmReliabilityManager.GetNextSequence () private
Get next sequence number.
Definition at line 399 of file MmReliabilityManager.cs.
References _nextSequence.
Referenced by WrapPacket().
ProcessAcks()
void MercuryMessaging.Network.MmReliabilityManager.ProcessAcks (uint ackSeq, uint ackBits) private
Process acknowledgments from received packet.
Definition at line 434 of file MmReliabilityManager.cs.
References _lock, _pendingPackets, and OnPacketAcked.
Referenced by UnwrapPacket().
ProcessPong()
void MercuryMessaging.Network.MmReliabilityManager.ProcessPong (byte[] packet)
Process a pong packet and update RTT.
Definition at line 301 of file MmReliabilityManager.cs.
References MercuryMessaging.Network.MmPacketHeader.Read(), and UpdateRTT().
Reset()
void MercuryMessaging.Network.MmReliabilityManager.Reset ()
Reset state (e.g., on disconnect).
Definition at line 477 of file MmReliabilityManager.cs.
References _lastReceivedSequence, _lock, _nextSequence, _pendingPackets, _receivedBitfield, RTTVariance, and SmoothedRTT.
TrackReceived()
void MercuryMessaging.Network.MmReliabilityManager.TrackReceived (uint seq) private
Track a received sequence number.
Definition at line 407 of file MmReliabilityManager.cs.
References _lastReceivedSequence, and _receivedBitfield.
Referenced by UnwrapPacket().
UnwrapPacket()
byte[] MercuryMessaging.Network.MmReliabilityManager.UnwrapPacket (byte[] packet, out MmPacketHeader header)
Process received packet and extract data.
Definition at line 208 of file MmReliabilityManager.cs.
References ProcessAcks(), MercuryMessaging.Network.MmPacketHeader.Read(), and TrackReceived().
Update()
void MercuryMessaging.Network.MmReliabilityManager.Update (double currentTime)
Check for packets that need retransmission.
Call this periodically (e.g., every frame).
Definition at line 337 of file MmReliabilityManager.cs.
References _lock, _pendingPackets, CurrentRTO, MaxRetries, OnPacketLost, and OnRetransmit.
UpdateRTT()
void MercuryMessaging.Network.MmReliabilityManager.UpdateRTT (float measuredRTT)
Update RTT estimate using EWMA.
Definition at line 318 of file MmReliabilityManager.cs.
References RTTAlpha, RTTVariance, and SmoothedRTT.
Referenced by ProcessPong().
WrapPacket()
byte[] MercuryMessaging.Network.MmReliabilityManager.WrapPacket (byte[] data, MmReliability reliability, int targetClient)
Wrap data with reliability header and track for ACK.
Definition at line 164 of file MmReliabilityManager.cs.
References _lastReceivedSequence, _lock, _pendingPackets, _receivedBitfield, and GetNextSequence().
Member Data Documentation
_lastReceivedSequence
uint MercuryMessaging.Network.MmReliabilityManager._lastReceivedSequence = 0 private
Definition at line 135 of file MmReliabilityManager.cs.
Referenced by CreateAckPacket(), Reset(), TrackReceived(), and WrapPacket().
_lock
readonly object MercuryMessaging.Network.MmReliabilityManager._lock = new object() private
Definition at line 140 of file MmReliabilityManager.cs.
Referenced by ProcessAcks(), Reset(), Update(), and WrapPacket().
_nextSequence
uint MercuryMessaging.Network.MmReliabilityManager._nextSequence = 1 private
Definition at line 134 of file MmReliabilityManager.cs.
Referenced by GetNextSequence(), and Reset().
_pendingPackets
readonly Dictionary<uint, MmPendingPacket> MercuryMessaging.Network.MmReliabilityManager._pendingPackets = new Dictionary<uint, MmPendingPacket>() private
Definition at line 139 of file MmReliabilityManager.cs.
Referenced by ProcessAcks(), Reset(), Update(), and WrapPacket().
_receivedBitfield
uint MercuryMessaging.Network.MmReliabilityManager._receivedBitfield = 0 private
Definition at line 136 of file MmReliabilityManager.cs.
Referenced by CreateAckPacket(), Reset(), TrackReceived(), and WrapPacket().
InitialRTO
float MercuryMessaging.Network.MmReliabilityManager.InitialRTO = 0.2f
Initial retransmit timeout in seconds.
Definition at line 106 of file MmReliabilityManager.cs.
MaxRetries
int MercuryMessaging.Network.MmReliabilityManager.MaxRetries = 5
Maximum retries before giving up on a packet.
Definition at line 101 of file MmReliabilityManager.cs.
Referenced by Update().
MaxRTO
float MercuryMessaging.Network.MmReliabilityManager.MaxRTO = 5.0f
Maximum retransmit timeout in seconds.
Definition at line 111 of file MmReliabilityManager.cs.
RTTAlpha
float MercuryMessaging.Network.MmReliabilityManager.RTTAlpha = 0.125f
RTT smoothing factor (EWMA).
Definition at line 116 of file MmReliabilityManager.cs.
Referenced by UpdateRTT().
Property Documentation
CurrentRTO
float MercuryMessaging.Network.MmReliabilityManager.CurrentRTO get
Current retransmit timeout.
Definition at line 131 of file MmReliabilityManager.cs.
Referenced by Update().
PendingCount
int MercuryMessaging.Network.MmReliabilityManager.PendingCount get
Number of packets awaiting acknowledgment.
Definition at line 150 of file MmReliabilityManager.cs.
RTTVariance
float MercuryMessaging.Network.MmReliabilityManager.RTTVariance = 0.05f get private set
RTT variance for timeout calculation.
Definition at line 126 of file MmReliabilityManager.cs.
Referenced by Reset(), and UpdateRTT().
SmoothedRTT
float MercuryMessaging.Network.MmReliabilityManager.SmoothedRTT = 0.1f get private set
Current smoothed RTT estimate.
Definition at line 121 of file MmReliabilityManager.cs.
Referenced by Reset(), and UpdateRTT().
Event Documentation
OnPacketAcked
Action<uint> MercuryMessaging.Network.MmReliabilityManager.OnPacketAcked
Definition at line 143 of file MmReliabilityManager.cs.
Referenced by ProcessAcks().
OnPacketLost
Action<uint> MercuryMessaging.Network.MmReliabilityManager.OnPacketLost
Definition at line 144 of file MmReliabilityManager.cs.
Referenced by Update().
OnRetransmit
Action<byte[], int> MercuryMessaging.Network.MmReliabilityManager.OnRetransmit
Definition at line 145 of file MmReliabilityManager.cs.
Referenced by Update().
The documentation for this class was generated from the following file:
Protocol/Network/MmReliabilityManager.cs