MercuryMessaging: MercuryMessaging.Task.MmTaskCollectionDesigner Class Reference
MercuryMessaging.Task.MmTaskCollectionDesigner Class Reference
Public Member Functions
void Shuffle< T > (ref T[] array)
void Shuffle< T > (ref T[][] array)
void OnValidate ()
virtual void Generate ()
Generate the MmTaskInfo collection.
virtual void Save ()
Save the MmTaskInfo collection to file.
Public Attributes
int NUM_OF_TASKS = 13
int MAX_USER_COUNT = 100
string FileName
The name of the file.
int NumberOfUnrecordedTasks
Static Public Attributes
static int SEED = 19790610
Protected Attributes
System.Random Rnd = new System.Random(SEED)
List< MmTaskInfo > taskSequence
Private Member Functions
bool Within (int h1, int h2, int range)
Detailed Description
Definition at line 43 of file MmTaskCollectionDesigner.cs.
Member Function Documentation
Generate()
virtual void MercuryMessaging.Task.MmTaskCollectionDesigner.Generate () virtual
Generate the MmTaskInfo collection.
Implements MercuryMessaging.Task.IMmTaskCollectionDesigner.
Definition at line 89 of file MmTaskCollectionDesigner.cs.
OnValidate()
void MercuryMessaging.Task.MmTaskCollectionDesigner.OnValidate ()
Definition at line 84 of file MmTaskCollectionDesigner.cs.
References Rnd, and SEED.
Save()
virtual void MercuryMessaging.Task.MmTaskCollectionDesigner.Save () virtual
Save the MmTaskInfo collection to file.
Implements MercuryMessaging.Task.IMmTaskCollectionDesigner.
Definition at line 92 of file MmTaskCollectionDesigner.cs.
References FileName, and taskSequence.
Shuffle< T >() [1/2]
void MercuryMessaging.Task.MmTaskCollectionDesigner.Shuffle< T > (ref T[] array)
Definition at line 60 of file MmTaskCollectionDesigner.cs.
References Rnd.
Shuffle< T >() [2/2]
void MercuryMessaging.Task.MmTaskCollectionDesigner.Shuffle< T > (ref T array[][])
Definition at line 72 of file MmTaskCollectionDesigner.cs.
References Rnd.
Within()
bool MercuryMessaging.Task.MmTaskCollectionDesigner.Within (int h1, int h2, int range) private
Definition at line 118 of file MmTaskCollectionDesigner.cs.
Member Data Documentation
FileName
string MercuryMessaging.Task.MmTaskCollectionDesigner.FileName
The name of the file.
Definition at line 57 of file MmTaskCollectionDesigner.cs.
Referenced by Save().
MAX_USER_COUNT
int MercuryMessaging.Task.MmTaskCollectionDesigner.MAX_USER_COUNT = 100
Definition at line 48 of file MmTaskCollectionDesigner.cs.
NUM_OF_TASKS
int MercuryMessaging.Task.MmTaskCollectionDesigner.NUM_OF_TASKS = 13
Definition at line 47 of file MmTaskCollectionDesigner.cs.
NumberOfUnrecordedTasks
int MercuryMessaging.Task.MmTaskCollectionDesigner.NumberOfUnrecordedTasks
Definition at line 58 of file MmTaskCollectionDesigner.cs.
Rnd
System.Random MercuryMessaging.Task.MmTaskCollectionDesigner.Rnd = new System.Random(SEED) protected
Definition at line 50 of file MmTaskCollectionDesigner.cs.
Referenced by OnValidate(), Shuffle< T >(), and Shuffle< T >().
SEED
int MercuryMessaging.Task.MmTaskCollectionDesigner.SEED = 19790610 static
Definition at line 45 of file MmTaskCollectionDesigner.cs.
Referenced by OnValidate().
taskSequence
List<MmTaskInfo> MercuryMessaging.Task.MmTaskCollectionDesigner.taskSequence protected
Definition at line 52 of file MmTaskCollectionDesigner.cs.
Referenced by Save().
The documentation for this class was generated from the following file:
Task/MmTaskCollectionDesigner.cs