MercuryMessaging: MercuryMessaging.StandardLibrary.Input.KeyboardHandler Class Reference
MercuryMessaging.StandardLibrary.Input.KeyboardHandler Class Reference
Sample Keyboard Handler, useful for creating simple input handling using MercuryMessaging.
Classes
class Entry
Public Types
enum Modifier { None = 0 , Alt = 1 , Ctrl = 2 , Shift = 4 }
enum RespondWhen { Pressed , Clutched , Released }
Public Member Functions
void Update ()
void Start ()
Static Public Member Functions
static void HandleKeyPress (KeyCode key)
static void HandleKeyRelease (KeyCode key)
static void HandleKeyPress (KeyCode key, Modifier modifier)
static void HandleKeyRelease (KeyCode key, Modifier modifier)
static string Descriptions ()
static void AddEntry (KeyCode key, string description, UnityAction response, RespondWhen respondWhen=RespondWhen.Pressed, Modifier modifier=Modifier.None, UnityAction clutchAbortResponse=null, UnityAction clutchReleaseResponse=null)
static void ProcessDelayedEntries ()
static void Call (UnityAction a)
static void Log (string msg)
Static Public Attributes
static int Delay = 120
static readonly Dictionary< KeyCode, Entry > Entries = new Dictionary<KeyCode, Entry>()
static readonly Dictionary< KeyCode, KeyCode > EquivalentKeyCode = new Dictionary<KeyCode, KeyCode>()
static MmLogger.LogFunc LogMessage
Private Attributes
Modifier mods
Static Private Attributes
static readonly List< Entry > DelayedEntries = new List<Entry>()
Detailed Description
Sample Keyboard Handler, useful for creating simple input handling using MercuryMessaging.
Definition at line 46 of file KeyboardHandler.cs.
Member Enumeration Documentation
Modifier
enum MercuryMessaging.StandardLibrary.Input.KeyboardHandler.Modifier
Enumerator
None
Alt
Ctrl
Shift
Definition at line 53 of file KeyboardHandler.cs.
RespondWhen
enum MercuryMessaging.StandardLibrary.Input.KeyboardHandler.RespondWhen
Enumerator
Pressed
Clutched
Released
Definition at line 61 of file KeyboardHandler.cs.
Member Function Documentation
AddEntry()
void MercuryMessaging.StandardLibrary.Input.KeyboardHandler.AddEntry (KeyCode key, string description, UnityAction response, RespondWhen respondWhen = RespondWhen::Pressed, Modifier modifier = Modifier::None, UnityAction clutchAbortResponse = null, UnityAction clutchReleaseResponse = null) static
Definition at line 199 of file KeyboardHandler.cs.
References DelayedEntries, and Entries.
Referenced by MercuryMessaging.StandardLibrary.Animation.MaterialChanger< T, TI >.Awake(), and Start().
Call()
void MercuryMessaging.StandardLibrary.Input.KeyboardHandler.Call (UnityAction a) static
Definition at line 235 of file KeyboardHandler.cs.
Referenced by HandleKeyPress(), HandleKeyRelease(), and ProcessDelayedEntries().
Descriptions()
string MercuryMessaging.StandardLibrary.Input.KeyboardHandler.Descriptions () static
Definition at line 192 of file KeyboardHandler.cs.
References Entries.
HandleKeyPress() [1/2]
void MercuryMessaging.StandardLibrary.Input.KeyboardHandler.HandleKeyPress (KeyCode key) static
Definition at line 98 of file KeyboardHandler.cs.
References HandleKeyPress().
Referenced by HandleKeyPress(), HandleKeyPress(), and Update().
HandleKeyPress() [2/2]
void MercuryMessaging.StandardLibrary.Input.KeyboardHandler.HandleKeyPress (KeyCode key, Modifier modifier) static
Definition at line 108 of file KeyboardHandler.cs.
References Call(), Delay, MercuryMessaging.StandardLibrary.Input.KeyboardHandler.Entry.Description, Entries, EquivalentKeyCode, HandleKeyPress(), MercuryMessaging.StandardLibrary.Input.KeyboardHandler.Entry.IsAllowed, Log(), MercuryMessaging.StandardLibrary.Input.KeyboardHandler.Entry.Modifier, MercuryMessaging.StandardLibrary.Input.KeyboardHandler.Entry.Response, and MercuryMessaging.StandardLibrary.Input.KeyboardHandler.Entry.ResponseTiming.
HandleKeyRelease() [1/2]
void MercuryMessaging.StandardLibrary.Input.KeyboardHandler.HandleKeyRelease (KeyCode key) static
Definition at line 103 of file KeyboardHandler.cs.
References HandleKeyRelease().
Referenced by HandleKeyRelease(), HandleKeyRelease(), and Update().
HandleKeyRelease() [2/2]
void MercuryMessaging.StandardLibrary.Input.KeyboardHandler.HandleKeyRelease (KeyCode key, Modifier modifier) static
Definition at line 144 of file KeyboardHandler.cs.
References Call(), MercuryMessaging.StandardLibrary.Input.KeyboardHandler.Entry.ClutchAbortResponse, MercuryMessaging.StandardLibrary.Input.KeyboardHandler.Entry.ClutchReleaseResponse, MercuryMessaging.StandardLibrary.Input.KeyboardHandler.Entry.CountDown, MercuryMessaging.StandardLibrary.Input.KeyboardHandler.Entry.Description, Entries, EquivalentKeyCode, HandleKeyRelease(), MercuryMessaging.StandardLibrary.Input.KeyboardHandler.Entry.IsAllowed, Log(), MercuryMessaging.StandardLibrary.Input.KeyboardHandler.Entry.Modifier, MercuryMessaging.StandardLibrary.Input.KeyboardHandler.Entry.Response, and MercuryMessaging.StandardLibrary.Input.KeyboardHandler.Entry.ResponseTiming.
Log()
void MercuryMessaging.StandardLibrary.Input.KeyboardHandler.Log (string msg) static
Definition at line 240 of file KeyboardHandler.cs.
References LogMessage.
Referenced by HandleKeyPress(), HandleKeyRelease(), and ProcessDelayedEntries().
ProcessDelayedEntries()
void MercuryMessaging.StandardLibrary.Input.KeyboardHandler.ProcessDelayedEntries () static
Definition at line 220 of file KeyboardHandler.cs.
References Call(), DelayedEntries, and Log().
Referenced by Update().
Start()
void MercuryMessaging.StandardLibrary.Input.KeyboardHandler.Start ()
Definition at line 278 of file KeyboardHandler.cs.
References AddEntry(), MercuryMessaging.MmGuiHandler.Instance, MercuryMessaging.MmLogger.LogApplication, LogMessage, and MercuryMessaging.MmGuiHandler.ShowMessage().
Update()
void MercuryMessaging.StandardLibrary.Input.KeyboardHandler.Update ()
Definition at line 244 of file KeyboardHandler.cs.
References Entries, EquivalentKeyCode, HandleKeyPress(), HandleKeyRelease(), mods, and ProcessDelayedEntries().
Member Data Documentation
Delay
int MercuryMessaging.StandardLibrary.Input.KeyboardHandler.Delay = 120 static
Definition at line 48 of file KeyboardHandler.cs.
Referenced by HandleKeyPress().
DelayedEntries
readonly List<Entry> MercuryMessaging.StandardLibrary.Input.KeyboardHandler.DelayedEntries = new List<Entry>() static private
Definition at line 95 of file KeyboardHandler.cs.
Referenced by AddEntry(), and ProcessDelayedEntries().
Entries
readonly Dictionary<KeyCode, Entry> MercuryMessaging.StandardLibrary.Input.KeyboardHandler.Entries = new Dictionary<KeyCode, Entry>() static
Definition at line 93 of file KeyboardHandler.cs.
Referenced by AddEntry(), Descriptions(), HandleKeyPress(), HandleKeyRelease(), and Update().
EquivalentKeyCode
readonly Dictionary<KeyCode, KeyCode> MercuryMessaging.StandardLibrary.Input.KeyboardHandler.EquivalentKeyCode = new Dictionary<KeyCode, KeyCode>() static
Definition at line 94 of file KeyboardHandler.cs.
Referenced by HandleKeyPress(), HandleKeyRelease(), and Update().
LogMessage
MmLogger.LogFunc MercuryMessaging.StandardLibrary.Input.KeyboardHandler.LogMessage static
Definition at line 96 of file KeyboardHandler.cs.
Referenced by Log(), and Start().
mods
Modifier MercuryMessaging.StandardLibrary.Input.KeyboardHandler.mods private
Definition at line 50 of file KeyboardHandler.cs.
Referenced by Update().
The documentation for this class was generated from the following file:
StandardLibrary/Input/KeyboardHandler.cs