MercuryMessaging: MercuryMessaging.MmAppStateSwitchResponder Class Reference
MercuryMessaging.MmAppStateSwitchResponder Class Reference
MmSwitchResponder for controlling MmAppStates.
Public Member Functions
override void Start ()
Invokes method to Setup App States.
virtual void SetupAppStates ()
Setup app states in derivations.
override void Awake ()
Auto-grabs the MmRelaySwitchNode.
virtual void OnMmSwitchNodeAwakeCompleteCallback ()
Callback called after associated MmRelaySwitchNode awoken.
virtual void OnMmNodeSwitchStartCompleteCallback ()
Callback called after associated MmRelaySwitchNode started.
virtual void MmSwitchSetup ()
This is called when the MmNetworkResponder is started Important Note: this will only trigger locally.
override void MmInvoke (MmMessage msg)
Invoke an MmMethod.
virtual void SetActive (bool active)
Handle MmMethod: SetActive.
virtual void Initialize ()
Handle MmMethod: Initialize Initialize allows you to provide additional initialization logic in-between calls to Monobehavior provided Awake() and Start() calls.
virtual void Refresh (List< MmTransform > transformList)
Handle MmMethod: Refresh.
override MmRelayNode GetRelayNode ()
Implementation of IMmResponder's GetRelayNode.
virtual void Update ()
Base Update of MmResponder Derived classes should always override.
virtual void MmOnAwakeComplete ()
Post Awake callback used between objects implementing this interface.
virtual void MmOnStartComplete ()
Post Start callback used between objects implementing this interface This allows for initialization steps that must occur before one instance's Start and its first Update.
virtual void MmRegisterAwakeCompleteCallback (IMmCallback callback)
It is possible that certain handles are not going to be in-place when registration of the OnAwakeComplete callback is invoked.
virtual void MmRegisterStartCompleteCallback (IMmCallback callback)
It is possible that certain handles are not going to be in-place when registration of the OnStartComplete callback is invoked.
Public Attributes
MmGuiHandler MmGuiHandler
Handle to associated MmGuiHandler.
string InitialState
Initial state for MmRelaySwitchNode FSM.
Protected Member Functions
override void Switch (string iName)
This responder will receive the switch message triggered by an MmInvoke.
virtual void Complete (bool active)
Handle MmMethod: Switch.
virtual void ApplyTaskInfo (IMmSerializable serializableValue)
Handle MmMethod: TaskInfo Given a IMmSerializable, extract TaskInfo.
virtual void ReceivedMessage (MmMessage message)
Handle MmMethod: Base MmMessage.
virtual void ReceivedMessage (MmMessageBool message)
Handle MmMethod: MessageBool.
virtual void ReceivedMessage (MmMessageByteArray message)
Handle MmMethod: MessageByteArray.
virtual void ReceivedMessage (MmMessageFloat message)
Handle MmMethod: MessageFloat.
virtual void ReceivedMessage (MmMessageInt message)
Handle MmMethod: MessageInt.
virtual void ReceivedMessage (MmMessageSerializable message)
Handle MmMethod: MessageSerializable.
virtual void ReceivedMessage (MmMessageString message)
Handle MmMethod: MessageString Override this to handle Mercury's string messages.
virtual void ReceivedMessage (MmMessageTransform message)
Handle MmMethod: MessageTransform Override this to handle Mercury's transform messages.
virtual void ReceivedMessage (MmMessageTransformList message)
Handle MmMethod: MessageTransformList Override this to handle Mercury's transform list messages.
virtual void ReceivedMessage (MmMessageVector3 message)
Handle MmMethod: MessageVector3 Override this to handle Mercury's Vector3 messages.
virtual void ReceivedMessage (MmMessageVector4 message)
Handle MmMethod: MessageVector4 Override this to handle Mercury's Vector4 messages.
virtual void ReceivedMessage (MmMessageQuaternion message)
Handle MmMethod: MessageQuaternion Override this to handle Mercury's Quaternion messages.
Properties
MmRelayNode Current [get]
Current AppState.
MmRelaySwitchNode MmRelaySwitchNode [get, private set]
Handle to MmRelaySwitchNode.
GameObject MmGameObject [get]
Handle to an instance's GameObject.
MmTag Tag [get, set]
MmTags allow you to specify filters for execution in Mercury XM graphs.
bool TagCheckEnabled [get, set]
Determines whether tag checking is enabled for this IMmResponder.
bool ReceiveHandledMessages [get, set]
When true, this responder receives messages even if Handled=true.
Events
IMmCallback MmAwakeCompleteCallback
Event triggered in the MmResponder when this object is awoken.
IMmCallback MmStartCompleteCallback
Event triggered in the MmResponder when this object is started.
Private Attributes
Dictionary< string, MmAppStateResponder > mmAppStateResponders
Collection of MmAppStateResponder.
MmTag _mmTag = MmTagHelper.Everything
Determines whether tag checking is enabled for this IMmResponder.
bool tagCheckEnabled = true
By default IMmResponders have this set to true so that they receive all messages.
bool receiveHandledMessages = false
When true, this responder receives messages even if Handled=true.
Detailed Description
MmSwitchResponder for controlling MmAppStates.
Definition at line 41 of file MmAppStateSwitchResponder.cs.
Member Function Documentation
ApplyTaskInfo()
virtual void MercuryMessaging.MmBaseResponder.ApplyTaskInfo (IMmSerializable serializableValue) protected virtual inherited
Handle MmMethod: TaskInfo Given a IMmSerializable, extract TaskInfo.
Parameters
serializableValue Serializable class containing MmTask Info
Definition at line 202 of file MmBaseResponder.cs.
Referenced by MmInvoke().
Awake()
override void MercuryMessaging.MmSwitchResponder.Awake () virtual inherited
Auto-grabs the MmRelaySwitchNode.
Also assigns/invokes Awake callbacks.
Reimplemented from MercuryMessaging.MmResponder.
Definition at line 60 of file MmSwitchResponder.cs.
References MercuryMessaging.MmLogger.LogResponder, MercuryMessaging.MmResponder.MmRegisterStartCompleteCallback(), MmRelaySwitchNode, MmSwitchSetup(), OnMmNodeSwitchStartCompleteCallback(), and OnMmSwitchNodeAwakeCompleteCallback().
Complete()
virtual void MercuryMessaging.MmBaseResponder.Complete (bool active) protected virtual inherited
Handle MmMethod: Switch.
Parameters
active Can be used to indicate active state of object that triggered complete message
Definition at line 193 of file MmBaseResponder.cs.
Referenced by MmInvoke().
GetRelayNode()
override MmRelayNode MercuryMessaging.MmBaseResponder.GetRelayNode () inherited
Implementation of IMmResponder's GetRelayNode.
Returns
Returns MmRelayNode if one attached to GameObject, Otherwise returns NULL.
Implements MercuryMessaging.IMmResponder.
Definition at line 320 of file MmBaseResponder.cs.
Referenced by MercuryMessaging.MmMessagingExtensions.BroadcastInitialize(), MercuryMessaging.MmMessagingExtensions.BroadcastRefresh(), MercuryMessaging.MmMessagingExtensions.BroadcastSetActive(), MercuryMessaging.MmMessagingExtensions.BroadcastSwitch(), MercuryMessaging.MmMessagingExtensions.BroadcastValue(), MercuryMessaging.MmMessagingExtensions.BroadcastValue(), MercuryMessaging.MmMessagingExtensions.BroadcastValue(), MercuryMessaging.MmMessagingExtensions.BroadcastValue(), MercuryMessaging.MmResponderExtensions.Build(), MercuryMessaging.MmListenerExtensions.ClearAllListeners(), MercuryMessaging.MmQueryExtensions.FindByName(), MercuryMessaging.MmQueryExtensions.FindByPattern(), MercuryMessaging.MmListenerExtensions.GetListenerCount(), MercuryMessaging.MmQueryExtensions.HasSiblings(), MercuryMessaging.MmListenerExtensions.ListenFor(), MercuryMessaging.MmMessagingExtensions.NotifyComplete(), MercuryMessaging.MmMessagingExtensions.NotifyValue(), MercuryMessaging.MmMessagingExtensions.NotifyValue(), MercuryMessaging.MmMessagingExtensions.NotifyValue(), MercuryMessaging.MmMessagingExtensions.NotifyValue(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.On6DOF(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnAxis(), MercuryMessaging.MmListenerExtensions.OnBool(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnButton(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnClick(), MercuryMessaging.MmListenerExtensions.OnComplete(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnDrag(), MercuryMessaging.MmListenerExtensions.OnFloat(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnFocus(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnGaze(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnGesture(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnHover(), MercuryMessaging.MmListenerExtensions.OnInitialize(), MercuryMessaging.MmListenerExtensions.OnInt(), MercuryMessaging.MmListenerExtensions.OnRefresh(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnScroll(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnSelect(), MercuryMessaging.MmListenerExtensions.OnSetActive(), MercuryMessaging.MmListenerExtensions.OnString(), MercuryMessaging.MmListenerExtensions.OnSwitch(), MercuryMessaging.MmListenerExtensions.OnVector3(), MercuryMessaging.MmQueryExtensions.Query(), MercuryMessaging.MmRoutingExtensions.RegisterWith(), MercuryMessaging.MmMessagingExtensions.Send(), MercuryMessaging.MmMessagingExtensions.Send(), MercuryMessaging.MmMessagingExtensions.Send(), MercuryMessaging.MmQueryExtensions.SiblingCount(), MercuryMessaging.MmResponderExtensions.To(), MercuryMessaging.MmRoutingExtensions.UnregisterFrom(), and MercuryMessaging.MmTransformResponder.Update().
Initialize()
virtual void MercuryMessaging.MmBaseResponder.Initialize () virtual inherited
Handle MmMethod: Initialize Initialize allows you to provide additional initialization logic in-between calls to Monobehavior provided Awake() and Start() calls.
Reimplemented in MercuryMessaging.Network.Backends.NetworkTestResponder.
Definition at line 166 of file MmBaseResponder.cs.
References MercuryMessaging.MmLogger.LogResponder.
Referenced by MmInvoke().
MmInvoke()
override void MercuryMessaging.MmBaseResponder.MmInvoke (MmMessage msg) virtual inherited
Invoke an MmMethod.
Implements a switch that handles the different MmMethods defined by default set in MmMethod MmMethod
Parameters
msgType Type of message. This specifies the type of the payload. This is important in networked scenarios, when proper deseriaization into the correct type requires knowing what was used to serialize the object originally. MmMessageType
msg The message to send.MmMessage
Reimplemented from MercuryMessaging.MmResponder.
Reimplemented in MercuryMessaging.MmExtendableResponder, MercuryMessaging.MmTransformResponder, MercuryMessaging.StandardLibrary.Input.MmInputResponder, and MercuryMessaging.StandardLibrary.UI.MmUIResponder.
Definition at line 67 of file MmBaseResponder.cs.
References ApplyTaskInfo(), Complete(), Initialize(), MercuryMessaging.MmMessage.MmMethod, ReceivedMessage(), Refresh(), SetActive(), and Switch().
MmOnAwakeComplete()
virtual void MercuryMessaging.MmResponder.MmOnAwakeComplete () virtual inherited
Post Awake callback used between objects implementing this interface.
This allows for initialization steps that must occur before one instance's Awake and its Start.
Implements MercuryMessaging.IMmResponder.
Definition at line 150 of file MmResponder.cs.
References MmAwakeCompleteCallback.
Referenced by Awake().
MmOnStartComplete()
virtual void MercuryMessaging.MmResponder.MmOnStartComplete () virtual inherited
Post Start callback used between objects implementing this interface This allows for initialization steps that must occur before one instance's Start and its first Update.
Implements MercuryMessaging.IMmResponder.
Definition at line 161 of file MmResponder.cs.
References MmStartCompleteCallback.
Referenced by Start().
MmRegisterAwakeCompleteCallback()
virtual void MercuryMessaging.MmResponder.MmRegisterAwakeCompleteCallback (IMmCallback callback) virtual inherited
It is possible that certain handles are not going to be in-place when registration of the OnAwakeComplete callback is invoked.
The is especially true in scenarios where MmRelayNodes are networked. This allows for a deferred registration, eliminating most instances where the Awake callback invocations fail.
Parameters
callback Callback to be registered.
Implements MercuryMessaging.IMmResponder.
Definition at line 175 of file MmResponder.cs.
References MercuryMessaging.IMmCallback(), and MmAwakeCompleteCallback.
MmRegisterStartCompleteCallback()
virtual void MercuryMessaging.MmResponder.MmRegisterStartCompleteCallback (IMmCallback callback) virtual inherited
It is possible that certain handles are not going to be in-place when registration of the OnStartComplete callback is invoked.
The is especially true in scenarios where MmRelayNodes are networked. This allows for a deferred registration, eliminating most instances where the Start callback invocations fail.
Parameters
callback Callback to be registered.
Implements MercuryMessaging.IMmResponder.
Definition at line 188 of file MmResponder.cs.
References MercuryMessaging.IMmCallback(), and MmStartCompleteCallback.
Referenced by MercuryMessaging.MmSwitchResponder.Awake().
MmSwitchSetup()
virtual void MercuryMessaging.MmSwitchResponder.MmSwitchSetup () virtual inherited
This is called when the MmNetworkResponder is started Important Note: this will only trigger locally.
The reason for this is that the following code needs to execute on every instance of the MmRelayNode across the network Thus, in order to avoid triggering the message each time a client connects, we just trigger the message locally.
Definition at line 148 of file MmSwitchResponder.cs.
References InitialState, MercuryMessaging.MmLogger.LogResponder, and MmRelaySwitchNode.
Referenced by Awake().
OnMmNodeSwitchStartCompleteCallback()
virtual void MercuryMessaging.MmSwitchResponder.OnMmNodeSwitchStartCompleteCallback () virtual inherited
Callback called after associated MmRelaySwitchNode started.
Definition at line 133 of file MmSwitchResponder.cs.
References MercuryMessaging.MmLogger.LogResponder, and MmRelaySwitchNode.
Referenced by Awake().
OnMmSwitchNodeAwakeCompleteCallback()
virtual void MercuryMessaging.MmSwitchResponder.OnMmSwitchNodeAwakeCompleteCallback () virtual inherited
Callback called after associated MmRelaySwitchNode awoken.
Definition at line 124 of file MmSwitchResponder.cs.
References MercuryMessaging.MmLogger.LogResponder.
Referenced by Awake().
ReceivedMessage() [1/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessage message) protected virtual inherited
Handle MmMethod: Base MmMessage.
Override this to handle base Mercury Messages.
Parameters
message MmMessage
Definition at line 211 of file MmBaseResponder.cs.
Referenced by MmInvoke().
ReceivedMessage() [2/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageBool message) protected virtual inherited
Handle MmMethod: MessageBool.
Override this to handle Mercury's bool messages.
Parameters
message MmMessageBool
Reimplemented in MercuryMessaging.Network.Backends.NetworkTestResponder.
Definition at line 220 of file MmBaseResponder.cs.
ReceivedMessage() [3/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageByteArray message) protected virtual inherited
Handle MmMethod: MessageByteArray.
Override this to handle Mercury's byte array messages.
Parameters
message MmMessageByteArray
Definition at line 229 of file MmBaseResponder.cs.
ReceivedMessage() [4/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageFloat message) protected virtual inherited
Handle MmMethod: MessageFloat.
Override this to handle Mercury's float messages.
Parameters
message MmMessageFloat
Reimplemented in MercuryMessaging.Network.Backends.NetworkTestResponder.
Definition at line 238 of file MmBaseResponder.cs.
ReceivedMessage() [5/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageInt message) protected virtual inherited
Handle MmMethod: MessageInt.
Override this to handle Mercury's int messages.
Parameters
message MmMessageInt
Reimplemented in MercuryMessaging.Network.Backends.NetworkTestResponder.
Definition at line 247 of file MmBaseResponder.cs.
ReceivedMessage() [6/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageQuaternion message) protected virtual inherited
Handle MmMethod: MessageQuaternion Override this to handle Mercury's Quaternion messages.
Parameters
message MmMessageQuaternion
Definition at line 310 of file MmBaseResponder.cs.
ReceivedMessage() [7/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageSerializable message) protected virtual inherited
Handle MmMethod: MessageSerializable.
Override this to handle Mercury's serializable messages.
Parameters
message MmMessageSerializable
Definition at line 256 of file MmBaseResponder.cs.
ReceivedMessage() [8/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageString message) protected virtual inherited
Handle MmMethod: MessageString Override this to handle Mercury's string messages.
Parameters
message MmMessageString
Reimplemented in MercuryMessaging.MmGuiResponder, and MercuryMessaging.Network.Backends.NetworkTestResponder.
Definition at line 265 of file MmBaseResponder.cs.
ReceivedMessage() [9/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageTransform message) protected virtual inherited
Handle MmMethod: MessageTransform Override this to handle Mercury's transform messages.
Parameters
message MmMessageTransform
Definition at line 274 of file MmBaseResponder.cs.
ReceivedMessage() [10/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageTransformList message) protected virtual inherited
Handle MmMethod: MessageTransformList Override this to handle Mercury's transform list messages.
Parameters
message MmMessageTransformList
Definition at line 283 of file MmBaseResponder.cs.
ReceivedMessage() [11/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageVector3 message) protected virtual inherited
Handle MmMethod: MessageVector3 Override this to handle Mercury's Vector3 messages.
Parameters
message MmMessageVector3
Reimplemented in MercuryMessaging.Network.Backends.NetworkTestResponder.
Definition at line 292 of file MmBaseResponder.cs.
ReceivedMessage() [12/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageVector4 message) protected virtual inherited
Handle MmMethod: MessageVector4 Override this to handle Mercury's Vector4 messages.
Parameters
message MmMessageVector4
Definition at line 301 of file MmBaseResponder.cs.
Refresh()
virtual void MercuryMessaging.MmBaseResponder.Refresh (List< MmTransform > transformList) virtual inherited
Handle MmMethod: Refresh.
Parameters
transformList List of transforms needed in refreshing an MmResponder.
Reimplemented in MercuryMessaging.Network.Backends.NetworkTestResponder.
Definition at line 175 of file MmBaseResponder.cs.
References MercuryMessaging.MmLogger.LogResponder.
Referenced by MmInvoke().
SetActive()
virtual void MercuryMessaging.MmBaseResponder.SetActive (bool active) virtual inherited
Handle MmMethod: SetActive.
Parameters
active Value of active state.
Reimplemented in MercuryMessaging.MmGuiResponder, and MercuryMessaging.Network.Backends.NetworkTestResponder.
Definition at line 154 of file MmBaseResponder.cs.
References MercuryMessaging.MmLogger.LogResponder.
Referenced by MmInvoke().
SetupAppStates()
virtual void MercuryMessaging.MmAppStateSwitchResponder.SetupAppStates () virtual
Setup app states in derivations.
Get handle to singleton instance MmGuiHandler, is present.
Definition at line 75 of file MmAppStateSwitchResponder.cs.
References MercuryMessaging.MmLogger.LogApplication, and MmGuiHandler.
Referenced by Start().
Start()
override void MercuryMessaging.MmAppStateSwitchResponder.Start () virtual
Invokes method to Setup App States.
Reimplemented from MercuryMessaging.MmResponder.
Definition at line 64 of file MmAppStateSwitchResponder.cs.
References SetupAppStates().
Switch()
override void MercuryMessaging.MmSwitchResponder.Switch (string iName) protected virtual inherited
This responder will receive the switch message triggered by an MmInvoke.
It will then trigger the jump state in the FSM of the associated MmRelaySwitchNode.
Parameters
iName Name of state to jump to.
Reimplemented from MercuryMessaging.MmBaseResponder.
Definition at line 176 of file MmSwitchResponder.cs.
References MmRelaySwitchNode.
Update()
virtual void MercuryMessaging.MmResponder.Update () virtual inherited
Base Update of MmResponder Derived classes should always override.
Reimplemented in MercuryMessaging.MmTransformResponder, and MercuryMessaging.Task.MmTaskResponder< T >.
Definition at line 140 of file MmResponder.cs.
Member Data Documentation
_mmTag
MmTag MercuryMessaging.MmResponder._mmTag = MmTagHelper.Everything private inherited
Determines whether tag checking is enabled for this IMmResponder.
Definition at line 62 of file MmResponder.cs.
InitialState
string MercuryMessaging.MmSwitchResponder.InitialState inherited
Initial state for MmRelaySwitchNode FSM.
Definition at line 54 of file MmSwitchResponder.cs.
Referenced by MmSwitchSetup().
mmAppStateResponders
Dictionary<string, MmAppStateResponder> MercuryMessaging.MmAppStateSwitchResponder.mmAppStateResponders private
Collection of MmAppStateResponder.
Definition at line 46 of file MmAppStateSwitchResponder.cs.
MmGuiHandler
MmGuiHandler MercuryMessaging.MmAppStateSwitchResponder.MmGuiHandler
Handle to associated MmGuiHandler.
Definition at line 51 of file MmAppStateSwitchResponder.cs.
Referenced by SetupAppStates().
receiveHandledMessages
bool MercuryMessaging.MmResponder.receiveHandledMessages = false private inherited
When true, this responder receives messages even if Handled=true.
Useful for logging, analytics, or handlers that need to see all messages. Default: false (responder skipped after message is handled). Similar to WPF's handledEventsToo parameter.
Definition at line 76 of file MmResponder.cs.
tagCheckEnabled
bool MercuryMessaging.MmResponder.tagCheckEnabled = true private inherited
By default IMmResponders have this set to true so that they receive all messages.
Definition at line 68 of file MmResponder.cs.
Referenced by MercuryMessaging.MmRelayNode.MmAddToRoutingTable().
Property Documentation
Current
MmRelayNode MercuryMessaging.MmAppStateSwitchResponder.Current get
Current AppState.
Definition at line 56 of file MmAppStateSwitchResponder.cs.
MmGameObject
GameObject MercuryMessaging.MmResponder.MmGameObject get inherited
Handle to an instance's GameObject.
Implements MercuryMessaging.IMmResponder.
Definition at line 81 of file MmResponder.cs.
MmRelaySwitchNode
MmRelaySwitchNode MercuryMessaging.MmSwitchResponder.MmRelaySwitchNode get private set inherited
Handle to MmRelaySwitchNode.
Definition at line 49 of file MmSwitchResponder.cs.
Referenced by Awake(), MmSwitchSetup(), OnMmNodeSwitchStartCompleteCallback(), Start(), and Switch().
ReceiveHandledMessages
bool MercuryMessaging.MmResponder.ReceiveHandledMessages get set inherited
When true, this responder receives messages even if Handled=true.
Useful for logging, analytics, or handlers that need to see all messages.
Definition at line 110 of file MmResponder.cs.
Tag
MmTag MercuryMessaging.MmResponder.Tag get set inherited
MmTags allow you to specify filters for execution in Mercury XM graphs.
Implements MercuryMessaging.IMmResponder.
Definition at line 90 of file MmResponder.cs.
Referenced by MercuryMessaging.MmTagExtensions.HasTag(), and MercuryMessaging.MmRelayNode.MmAddToRoutingTable().
TagCheckEnabled
bool MercuryMessaging.MmResponder.TagCheckEnabled get set inherited
Determines whether tag checking is enabled for this IMmResponder.
Implements MercuryMessaging.IMmResponder.
Definition at line 100 of file MmResponder.cs.
Referenced by MercuryMessaging.MmRelayNode.MmAddToRoutingTable(), and MercuryMessaging.MmRelayNode.TagCheck().
Event Documentation
MmAwakeCompleteCallback
IMmCallback MercuryMessaging.MmResponder.MmAwakeCompleteCallback private inherited
Event triggered in the MmResponder when this object is awoken.
Definition at line 50 of file MmResponder.cs.
Referenced by MmOnAwakeComplete(), and MmRegisterAwakeCompleteCallback().
MmStartCompleteCallback
IMmCallback MercuryMessaging.MmResponder.MmStartCompleteCallback private inherited
Event triggered in the MmResponder when this object is started.
Definition at line 56 of file MmResponder.cs.
Referenced by MmOnStartComplete(), and MmRegisterStartCompleteCallback().
The documentation for this class was generated from the following file:
Protocol/AppState/MmAppStateSwitchResponder.cs