MercuryMessaging: MercuryMessaging.MmHashSetPool Class Reference
MercuryMessaging.MmHashSetPool Class Reference
Pool for HashSet<int> used by VisitedNodes in message routing.
Static Public Member Functions
static HashSet< int > Get ()
Get a cleared HashSet from the pool.
static void Return (HashSet< int > set)
Return a HashSet to the pool for reuse.
static HashSet< int > GetCopy (HashSet< int > source)
Get a HashSet from the pool and populate it with existing values.
static string GetStatistics ()
Get pool statistics for debugging.
Static Public Attributes
const int DEFAULT_CAPACITY = 100
Default pool capacity.
const int MAX_SIZE = 1000
Maximum pool size.
Properties
static int ActiveCount [get]
Current number of HashSets in use.
static int InactiveCount [get]
Current number of HashSets available in pool.
Static Private Attributes
const int HASHSET_INITIAL_CAPACITY = 16
Initial capacity for each HashSet (typical hierarchy depth).
const bool COLLECTION_CHECK = true
Enable collection checks in editor for debugging pool misuse.
static readonly ObjectPool< HashSet< int > > _pool
Detailed Description
Pool for HashSet<int> used by VisitedNodes in message routing.
Eliminates per-message HashSet allocations in cycle detection.
Usage: var visitedNodes = MmHashSetPool.Get(); // ... use for cycle detection ... MmHashSetPool.Return(visitedNodes);
Definition at line 47 of file MmHashSetPool.cs.
Member Function Documentation
Get()
HashSet< int > MercuryMessaging.MmHashSetPool.Get () static
Get a cleared HashSet from the pool.
The returned set is guaranteed to be empty.
Returns
An empty HashSet<int> for tracking visited nodes.
Definition at line 98 of file MmHashSetPool.cs.
References _pool.
Referenced by MercuryMessaging.MmRelayNode.MmInvoke(), and MercuryMessaging.MmRelayNode.MmInvokeWithPath().
GetCopy()
HashSet< int > MercuryMessaging.MmHashSetPool.GetCopy (HashSet< int > source) static
Get a HashSet from the pool and populate it with existing values.
Used when copying VisitedNodes from one message to another.
Parameters
source Source HashSet to copy from (can be null).
Returns
A new HashSet containing copied values.
Definition at line 121 of file MmHashSetPool.cs.
References _pool.
GetStatistics()
string MercuryMessaging.MmHashSetPool.GetStatistics () static
Get pool statistics for debugging.
Definition at line 142 of file MmHashSetPool.cs.
Return()
void MercuryMessaging.MmHashSetPool.Return (HashSet< int > set) static
Return a HashSet to the pool for reuse.
Parameters
set The HashSet to return.
Definition at line 107 of file MmHashSetPool.cs.
References _pool.
Referenced by MercuryMessaging.MmMessagePool.ResetMessage().
Member Data Documentation
_pool
readonly ObjectPool<HashSet<int> > MercuryMessaging.MmHashSetPool._pool static private
Initial value:
= new ObjectPool<HashSet<int>>(
            createFunc: () => new HashSet<int>(HASHSET_INITIAL_CAPACITY),
            actionOnGet: set => set.Clear(),
            actionOnRelease: null,
            actionOnDestroy: null,
            collectionCheck: COLLECTION_CHECK,
            defaultCapacity: DEFAULT_CAPACITY,
            maxSize: MAX_SIZE
        )
Definition at line 79 of file MmHashSetPool.cs.
Referenced by Get(), GetCopy(), and Return().
COLLECTION_CHECK
const bool MercuryMessaging.MmHashSetPool.COLLECTION_CHECK = true static private
Enable collection checks in editor for debugging pool misuse.
Definition at line 70 of file MmHashSetPool.cs.
DEFAULT_CAPACITY
const int MercuryMessaging.MmHashSetPool.DEFAULT_CAPACITY = 100 static
Default pool capacity.
Definition at line 54 of file MmHashSetPool.cs.
HASHSET_INITIAL_CAPACITY
const int MercuryMessaging.MmHashSetPool.HASHSET_INITIAL_CAPACITY = 16 static private
Initial capacity for each HashSet (typical hierarchy depth).
Definition at line 64 of file MmHashSetPool.cs.
MAX_SIZE
const int MercuryMessaging.MmHashSetPool.MAX_SIZE = 1000 static
Maximum pool size.
Definition at line 59 of file MmHashSetPool.cs.
Property Documentation
ActiveCount
int MercuryMessaging.MmHashSetPool.ActiveCount static get
Current number of HashSets in use.
Definition at line 150 of file MmHashSetPool.cs.
InactiveCount
int MercuryMessaging.MmHashSetPool.InactiveCount static get
Current number of HashSets available in pool.
Definition at line 155 of file MmHashSetPool.cs.
The documentation for this class was generated from the following file:
Protocol/Core/MmHashSetPool.cs