MercuryMessaging: MercuryMessaging.MmPredicateList Class Reference
MercuryMessaging.MmPredicateList Class Reference
Container for multiple predicates.
Public Member Functions
void Add (MmPredicate predicate)
Add a predicate to the list.
bool EvaluateAll (MmRelayNode source, GameObject target)
Evaluate all predicates against a target.
void Clear ()
Clear all predicates.
Properties
int Count [get]
Number of predicates in this list.
Private Attributes
readonly List< MmPredicate > _predicates = new List<MmPredicate>(4)
Detailed Description
Container for multiple predicates.
Used by MmFluentMessage to store predicate chains without allocating on each method call.
Definition at line 173 of file MmFluentPredicates.cs.
Member Function Documentation
Add()
void MercuryMessaging.MmPredicateList.Add (MmPredicate predicate)
Add a predicate to the list.
Definition at line 185 of file MmFluentPredicates.cs.
References _predicates.
Clear()
void MercuryMessaging.MmPredicateList.Clear ()
Clear all predicates.
Definition at line 208 of file MmFluentPredicates.cs.
References _predicates.
Referenced by MercuryMessaging.MmPredicateListPool.Return().
EvaluateAll()
bool MercuryMessaging.MmPredicateList.EvaluateAll (MmRelayNode source, GameObject target)
Evaluate all predicates against a target.
Returns true only if ALL predicates pass.
Definition at line 195 of file MmFluentPredicates.cs.
References _predicates.
Member Data Documentation
_predicates
readonly List<MmPredicate> MercuryMessaging.MmPredicateList._predicates = new List<MmPredicate>(4) private
Definition at line 175 of file MmFluentPredicates.cs.
Referenced by Add(), Clear(), and EvaluateAll().
Property Documentation
Count
int MercuryMessaging.MmPredicateList.Count get
Number of predicates in this list.
Definition at line 180 of file MmFluentPredicates.cs.
The documentation for this class was generated from the following file:
Protocol/DSL/MmFluentPredicates.cs