MercuryMessaging: MercuryMessaging.Network.MmStateInterpolator Class Reference
MercuryMessaging.Network.MmStateInterpolator Class Reference
State interpolation for smooth remote entity display.
Public Member Functions
void AddState (MmStateSnapshot state)
Add a received state to the buffer.
MmStateSnapshot GetInterpolatedState (double currentTime)
Get interpolated state for the given render time.
void Clear ()
Clear the state buffer.
Public Attributes
float InterpolationDelay = 0.1f
Interpolation delay (seconds).
float MaxExtrapolation = 0.2f
Extrapolation limit (seconds).
Private Member Functions
MmStateSnapshot Interpolate (MmStateSnapshot a, MmStateSnapshot b, float t)
MmStateSnapshot Extrapolate (MmStateSnapshot state, float deltaTime)
Private Attributes
readonly List< MmStateSnapshot > _stateBuffer = new List<MmStateSnapshot>()
Detailed Description
State interpolation for smooth remote entity display.
Definition at line 430 of file MmNetworkPrediction.cs.
Member Function Documentation
AddState()
void MercuryMessaging.Network.MmStateInterpolator.AddState (MmStateSnapshot state)
Add a received state to the buffer.
Definition at line 448 of file MmNetworkPrediction.cs.
References _stateBuffer, and MercuryMessaging.Network.MmStateSnapshot.ServerTime.
Clear()
void MercuryMessaging.Network.MmStateInterpolator.Clear ()
Clear the state buffer.
Definition at line 546 of file MmNetworkPrediction.cs.
References _stateBuffer.
Extrapolate()
MmStateSnapshot MercuryMessaging.Network.MmStateInterpolator.Extrapolate (MmStateSnapshot state, float deltaTime) private
Definition at line 530 of file MmNetworkPrediction.cs.
References MercuryMessaging.Network.MmStateSnapshot.AngularVelocity, MercuryMessaging.Network.Quaternion, MercuryMessaging.Network.MmStateSnapshot.SequenceNumber, and MercuryMessaging.Network.MmStateSnapshot.Velocity.
Referenced by GetInterpolatedState().
GetInterpolatedState()
MmStateSnapshot MercuryMessaging.Network.MmStateInterpolator.GetInterpolatedState (double currentTime)
Get interpolated state for the given render time.
Definition at line 472 of file MmNetworkPrediction.cs.
References _stateBuffer, Extrapolate(), Interpolate(), InterpolationDelay, MaxExtrapolation, and MercuryMessaging.Network.MmStateSnapshot.ServerTime.
Interpolate()
MmStateSnapshot MercuryMessaging.Network.MmStateInterpolator.Interpolate (MmStateSnapshot a, MmStateSnapshot b, float t) private
Definition at line 517 of file MmNetworkPrediction.cs.
References MercuryMessaging.Network.MmStateSnapshot.AngularVelocity, MercuryMessaging.Network.MmStateSnapshot.Position, MercuryMessaging.Network.Quaternion, MercuryMessaging.Network.MmStateSnapshot.Rotation, MercuryMessaging.Network.MmStateSnapshot.SequenceNumber, MercuryMessaging.Network.MmStateSnapshot.ServerTime, MercuryMessaging.Network.Vector3, and MercuryMessaging.Network.MmStateSnapshot.Velocity.
Referenced by GetInterpolatedState().
Member Data Documentation
_stateBuffer
readonly List<MmStateSnapshot> MercuryMessaging.Network.MmStateInterpolator._stateBuffer = new List<MmStateSnapshot>() private
Definition at line 443 of file MmNetworkPrediction.cs.
Referenced by AddState(), Clear(), and GetInterpolatedState().
InterpolationDelay
float MercuryMessaging.Network.MmStateInterpolator.InterpolationDelay = 0.1f
Interpolation delay (seconds).
Definition at line 435 of file MmNetworkPrediction.cs.
Referenced by GetInterpolatedState().
MaxExtrapolation
float MercuryMessaging.Network.MmStateInterpolator.MaxExtrapolation = 0.2f
Extrapolation limit (seconds).
Definition at line 440 of file MmNetworkPrediction.cs.
Referenced by GetInterpolatedState().
The documentation for this class was generated from the following file:
Protocol/Network/MmNetworkPrediction.cs