MercuryMessaging: MercuryMessaging.MmQueryExtensions Class Reference
MercuryMessaging.MmQueryExtensions Class Reference
Extension methods for querying MercuryMessaging hierarchies.
Static Public Member Functions
static MmQueryBuilder Query (this MmRelayNode relay)
Creates a query builder for traversing this relay node's hierarchy.
static MmQuery< T > Query< T > (this MmRelayNode relay)
Starts a typed query directly for the specified responder type.
static T FindDescendant< T > (this MmRelayNode relay)
Finds the first responder of type T in descendants.
static T FindAncestor< T > (this MmRelayNode relay)
Finds the first responder of type T in ancestors.
static System.Collections.Generic.List< T > FindAllDescendants< T > (this MmRelayNode relay)
Finds all responders of type T in descendants.
static MmResponder FindByName (this MmRelayNode relay, string name)
Finds a responder by name in the hierarchy.
static System.Collections.Generic.List< MmResponder > FindByPattern (this MmRelayNode relay, string pattern)
Finds responders matching a name pattern in the hierarchy.
static int ChildCount (this MmRelayNode relay)
Gets the count of direct children.
static int DescendantCount (this MmRelayNode relay)
Gets the count of all descendants.
static bool HasChildren (this MmRelayNode relay)
Checks if any children exist.
static bool HasDescendant< T > (this MmRelayNode relay)
Checks if any responders of type T exist in descendants.
static MmQueryBuilder Query (this MmBaseResponder responder)
Creates a query builder for traversing this responder's hierarchy.
static MmQuery< T > Query< T > (this MmBaseResponder responder)
Starts a typed query directly for the specified responder type (from responder).
static T FindDescendant< T > (this MmBaseResponder responder)
Finds the first responder of type T in descendants (from responder).
static T FindAncestor< T > (this MmBaseResponder responder)
Finds the first responder of type T in ancestors (from responder).
static System.Collections.Generic.List< T > FindAllDescendants< T > (this MmBaseResponder responder)
Finds all responders of type T in descendants (from responder).
static MmResponder FindByName (this MmBaseResponder responder, string name)
Finds a responder by name in the hierarchy (from responder).
static System.Collections.Generic.List< MmResponder > FindByPattern (this MmBaseResponder responder, string pattern)
Finds responders matching a name pattern (from responder).
static int SiblingCount (this MmBaseResponder responder)
Gets the count of siblings (from responder).
static bool HasSiblings (this MmBaseResponder responder)
Checks if this responder has siblings.
Detailed Description
Extension methods for querying MercuryMessaging hierarchies.
Part of DSL Phase 2.2: Hierarchy Query DSL.
Provides LINQ-like querying capabilities for traversing and filtering responder hierarchies. Supports both MmRelayNode and MmBaseResponder.
Example usage:
// Query from relay node
var enemies = relay.Query()
    .Descendants()
    .OfType<EnemyResponder>()
    .Active()
    .ToList();
// Execute action on all matching responders
relay.Query()
    .Children()
    .WithTag(MmTag.Tag0)
    .Execute(r => r.DoSomething());
// Query from responder (same API!)
myResponder.Query()
    .Siblings()
    .OfType<UIResponder>()
    .FirstOrDefault();
Definition at line 42 of file MmQueryExtensions.cs.
Member Function Documentation
ChildCount()
int MercuryMessaging.MmQueryExtensions.ChildCount (this MmRelayNode relay) static
Gets the count of direct children.
Parameters
relay The relay node to count from.
Returns
The number of direct children.
Definition at line 158 of file MmQueryExtensions.cs.
DescendantCount()
int MercuryMessaging.MmQueryExtensions.DescendantCount (this MmRelayNode relay) static
Gets the count of all descendants.
Parameters
relay The relay node to count from.
Returns
The number of descendants.
Definition at line 169 of file MmQueryExtensions.cs.
References MercuryMessaging.Descendants.
FindAllDescendants< T >() [1/2]
System.Collections.Generic.List< T > MercuryMessaging.MmQueryExtensions.FindAllDescendants< T > (this MmBaseResponder responder) static
Finds all responders of type T in descendants (from responder).
Type Constraints
T : class
Definition at line 262 of file MmQueryExtensions.cs.
FindAllDescendants< T >() [2/2]
System.Collections.Generic.List< T > MercuryMessaging.MmQueryExtensions.FindAllDescendants< T > (this MmRelayNode relay) static
Finds all responders of type T in descendants.
Shorthand for Query<T>().Descendants().ToList().
Template Parameters
T The responder type to find.
Parameters
relay The relay node to search from.
Returns
A list of all matching responders.
Type Constraints
T : class
Definition at line 121 of file MmQueryExtensions.cs.
References MercuryMessaging.Descendants.
FindAncestor< T >() [1/2]
T MercuryMessaging.MmQueryExtensions.FindAncestor< T > (this MmBaseResponder responder) static
Finds the first responder of type T in ancestors (from responder).
Type Constraints
T : class
Definition at line 252 of file MmQueryExtensions.cs.
FindAncestor< T >() [2/2]
T MercuryMessaging.MmQueryExtensions.FindAncestor< T > (this MmRelayNode relay) static
Finds the first responder of type T in ancestors.
Shorthand for Query<T>().Ancestors().FirstOrDefault().
Template Parameters
T The responder type to find.
Parameters
relay The relay node to search from.
Returns
The first matching responder, or null if not found.
Type Constraints
T : class
Definition at line 108 of file MmQueryExtensions.cs.
References MercuryMessaging.Ancestors.
FindByName() [1/2]
MmResponder MercuryMessaging.MmQueryExtensions.FindByName (this MmBaseResponder responder, string name) static
Finds a responder by name in the hierarchy (from responder).
Definition at line 272 of file MmQueryExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
FindByName() [2/2]
MmResponder MercuryMessaging.MmQueryExtensions.FindByName (this MmRelayNode relay, string name) static
Finds a responder by name in the hierarchy.
Searches descendants by default.
Parameters
relay The relay node to search from.
name The exact name to match.
Returns
The first matching responder, or null if not found.
Definition at line 134 of file MmQueryExtensions.cs.
References MercuryMessaging.Descendants.
FindByPattern() [1/2]
System.Collections.Generic.List< MmResponder > MercuryMessaging.MmQueryExtensions.FindByPattern (this MmBaseResponder responder, string pattern) static
Finds responders matching a name pattern (from responder).
Definition at line 282 of file MmQueryExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
FindByPattern() [2/2]
System.Collections.Generic.List< MmResponder > MercuryMessaging.MmQueryExtensions.FindByPattern (this MmRelayNode relay, string pattern) static
Finds responders matching a name pattern in the hierarchy.
Supports wildcards (* matches any characters).
Parameters
relay The relay node to search from.
pattern The name pattern (e.g., "Enemy*").
Returns
A list of all matching responders.
Definition at line 147 of file MmQueryExtensions.cs.
References MercuryMessaging.Descendants.
FindDescendant< T >() [1/2]
T MercuryMessaging.MmQueryExtensions.FindDescendant< T > (this MmBaseResponder responder) static
Finds the first responder of type T in descendants (from responder).
Type Constraints
T : class
Definition at line 242 of file MmQueryExtensions.cs.
FindDescendant< T >() [2/2]
T MercuryMessaging.MmQueryExtensions.FindDescendant< T > (this MmRelayNode relay) static
Finds the first responder of type T in descendants.
Shorthand for Query<T>().Descendants().FirstOrDefault().
Template Parameters
T The responder type to find.
Parameters
relay The relay node to search from.
Returns
The first matching responder, or null if not found.
Type Constraints
T : class
Definition at line 95 of file MmQueryExtensions.cs.
References MercuryMessaging.Descendants.
HasChildren()
bool MercuryMessaging.MmQueryExtensions.HasChildren (this MmRelayNode relay) static
Checks if any children exist.
Parameters
relay The relay node to check.
Returns
True if at least one child exists.
Definition at line 180 of file MmQueryExtensions.cs.
HasDescendant< T >()
bool MercuryMessaging.MmQueryExtensions.HasDescendant< T > (this MmRelayNode relay) static
Checks if any responders of type T exist in descendants.
Template Parameters
T The responder type to check for.
Parameters
relay The relay node to check.
Returns
True if at least one matching responder exists.
Type Constraints
T : class
Definition at line 192 of file MmQueryExtensions.cs.
References MercuryMessaging.Descendants.
HasSiblings()
bool MercuryMessaging.MmQueryExtensions.HasSiblings (this MmBaseResponder responder) static
Checks if this responder has siblings.
Definition at line 302 of file MmQueryExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode(), and MercuryMessaging.Siblings.
Query() [1/2]
MmQueryBuilder MercuryMessaging.MmQueryExtensions.Query (this MmBaseResponder responder) static
Creates a query builder for traversing this responder's hierarchy.
Null-safe: returns default builder if responder has no relay node.
Parameters
responder The responder to query from.
Returns
A query builder for configuring the query.
myResponder.Query() .Siblings() .OfType<UIResponder>() .Execute(r => r.Hide());
Definition at line 214 of file MmQueryExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
Query() [2/2]
MmQueryBuilder MercuryMessaging.MmQueryExtensions.Query (this MmRelayNode relay) static
Creates a query builder for traversing this relay node's hierarchy.
Use fluent methods to filter and execute queries.
Parameters
relay The relay node to query from.
Returns
A query builder for configuring the query.
relay.Query() .Descendants() .OfType<MyResponder>() .ToList();
Definition at line 59 of file MmQueryExtensions.cs.
Query< T >() [1/2]
MmQuery< T > MercuryMessaging.MmQueryExtensions.Query< T > (this MmBaseResponder responder) static
Starts a typed query directly for the specified responder type (from responder).
Null-safe: returns default query if responder has no relay node.
Template Parameters
T The responder type to query for.
Parameters
responder The responder to query from.
Returns
A typed query for the specified type.
Type Constraints
T : class
Definition at line 228 of file MmQueryExtensions.cs.
Query< T >() [2/2]
MmQuery< T > MercuryMessaging.MmQueryExtensions.Query< T > (this MmRelayNode relay) static
Starts a typed query directly for the specified responder type.
Shorthand for Query().OfType<T>().
Template Parameters
T The responder type to query for.
Parameters
relay The relay node to query from.
Returns
A typed query for the specified type.
var enemies = relay.Query<EnemyResponder>() .Descendants() .Active() .ToList();
Type Constraints
T : class
Definition at line 78 of file MmQueryExtensions.cs.
SiblingCount()
int MercuryMessaging.MmQueryExtensions.SiblingCount (this MmBaseResponder responder) static
Gets the count of siblings (from responder).
Definition at line 292 of file MmQueryExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode(), and MercuryMessaging.Siblings.
The documentation for this class was generated from the following file:
Protocol/DSL/MmQueryExtensions.cs