MercuryMessaging: MercuryMessaging.MmMessageFactory Class Reference
MercuryMessaging.MmMessageFactory Class Reference
Factory class for creating MmMessage instances from various types.
Static Public Member Functions
static MmMessage Create< T > (T value)
Create a message from a value, automatically detecting the message type.
static MmMessage Create (object value)
Create a message from an object, with runtime type detection.
static MmMessageBool Bool (bool value)
Create a boolean message.
static MmMessageInt Int (int value)
Create an integer message.
static MmMessageFloat Float (float value)
Create a float message.
static MmMessageString String (string value)
Create a string message.
static MmMessageVector3 Vector3 (Vector3 value)
Create a Vector3 message.
static MmMessageVector4 Vector4 (Vector4 value)
Create a Vector4 message.
static MmMessageQuaternion Quaternion (Quaternion value)
Create a Quaternion message.
static MmMessageTransform Transform (Transform value, bool useGlobal=true)
Create a Transform message from a Unity Transform.
static MmMessageTransform Transform (MmTransform value)
Create a Transform message from an MmTransform.
static MmMessageGameObject GameObject (GameObject value)
Create a GameObject message.
static MmMessageByteArray ByteArray (byte[] value)
Create a byte array message.
static MmMessageTransformList TransformList (List< MmTransform > value)
Create a Transform list message.
static MmMessage Initialize ()
Create an Initialize command message.
static MmMessage Refresh ()
Create a Refresh command message.
static MmMessage Complete ()
Create a Complete command message.
static MmMessageBool SetActive (bool active)
Create a SetActive command message.
static MmMessageString Switch (string stateName)
Create a Switch command message.
static MmMessageInt Switch (int stateIndex)
Create a Switch command message by state index.
static MmMessage Custom (int methodId)
Create a custom method message.
static MmMessage Custom< T > (int methodId, T payload)
Create a custom method message with a payload.
static T WithMetadata< T > (this T message, MmMetadataBlock metadata)
Configure metadata on a message.
static T ToChildren< T > (this T message)
Configure a message to target children.
static T ToParents< T > (this T message)
Configure a message to target parents.
static T ToDescendants< T > (this T message)
Configure a message to target descendants.
static T ToAll< T > (this T message)
Configure a message to target all directions.
static T WithTag< T > (this T message, MmTag tag)
Configure a message with a specific tag.
Detailed Description
Factory class for creating MmMessage instances from various types.
Provides type-safe message creation with automatic method detection.
Phase 3 - Task 3.1: Message Factory
Definition at line 14 of file MmMessageFactory.cs.
Member Function Documentation
Bool()
MmMessageBool MercuryMessaging.MmMessageFactory.Bool (bool value) static
Create a boolean message.
Definition at line 85 of file MmMessageFactory.cs.
Referenced by Create(), and Create< T >().
ByteArray()
MmMessageByteArray MercuryMessaging.MmMessageFactory.ByteArray (byte[] value) static
Create a byte array message.
Definition at line 219 of file MmMessageFactory.cs.
Referenced by Create(), and Create< T >().
Complete()
MmMessage MercuryMessaging.MmMessageFactory.Complete () static
Create a Complete command message.
Definition at line 269 of file MmMessageFactory.cs.
References MercuryMessaging.Complete.
Create()
MmMessage MercuryMessaging.MmMessageFactory.Create (object value) static
Create a message from an object, with runtime type detection.
Parameters
value The value to wrap
Returns
An MmMessage containing the value
Definition at line 55 of file MmMessageFactory.cs.
References Bool(), ByteArray(), Float(), GameObject(), Int(), MercuryMessaging.NoOp, Quaternion(), String(), Transform(), Vector3(), and Vector4().
Referenced by Custom< T >().
Create< T >()
MmMessage MercuryMessaging.MmMessageFactory.Create< T > (T value) static
Create a message from a value, automatically detecting the message type.
Template Parameters
T The value type
Parameters
value The value to wrap in a message
Returns
An MmMessage containing the value
var msg = MmMessageFactory.Create(42); // Creates MmMessageInt var msg = MmMessageFactory.Create("Hello"); // Creates MmMessageString var msg = MmMessageFactory.Create(true); // Creates MmMessageBool
Definition at line 30 of file MmMessageFactory.cs.
References Bool(), ByteArray(), Float(), GameObject(), Int(), Quaternion(), String(), Transform(), Vector3(), and Vector4().
Custom()
MmMessage MercuryMessaging.MmMessageFactory.Custom (int methodId) static
Create a custom method message.
Parameters
methodId Custom method ID (should be >= 1000)
Returns
A message with the custom method ID
var msg = MmMessageFactory.Custom(1001); relay.MmInvoke(msg);
Definition at line 327 of file MmMessageFactory.cs.
Custom< T >()
MmMessage MercuryMessaging.MmMessageFactory.Custom< T > (int methodId, T payload) static
Create a custom method message with a payload.
Template Parameters
T The payload type
Parameters
methodId Custom method ID
payload The payload value
Returns
A message with the custom method and payload
Definition at line 344 of file MmMessageFactory.cs.
References Create().
Float()
MmMessageFloat MercuryMessaging.MmMessageFactory.Float (float value) static
Create a float message.
Definition at line 111 of file MmMessageFactory.cs.
Referenced by Create(), and Create< T >().
GameObject()
MmMessageGameObject MercuryMessaging.MmMessageFactory.GameObject (GameObject value) static
Create a GameObject message.
Definition at line 206 of file MmMessageFactory.cs.
References GameObject().
Referenced by Create(), Create< T >(), and GameObject().
Initialize()
MmMessage MercuryMessaging.MmMessageFactory.Initialize () static
Create an Initialize command message.
Definition at line 251 of file MmMessageFactory.cs.
References MercuryMessaging.Initialize.
Int()
MmMessageInt MercuryMessaging.MmMessageFactory.Int (int value) static
Create an integer message.
Definition at line 98 of file MmMessageFactory.cs.
Referenced by Create(), and Create< T >().
Quaternion()
MmMessageQuaternion MercuryMessaging.MmMessageFactory.Quaternion (Quaternion value) static
Create a Quaternion message.
Definition at line 163 of file MmMessageFactory.cs.
References Quaternion().
Referenced by Create(), Create< T >(), and Quaternion().
Refresh()
MmMessage MercuryMessaging.MmMessageFactory.Refresh () static
Create a Refresh command message.
Definition at line 260 of file MmMessageFactory.cs.
References MercuryMessaging.Refresh.
SetActive()
MmMessageBool MercuryMessaging.MmMessageFactory.SetActive (bool active) static
Create a SetActive command message.
Definition at line 278 of file MmMessageFactory.cs.
String()
MmMessageString MercuryMessaging.MmMessageFactory.String (string value) static
Create a string message.
Definition at line 124 of file MmMessageFactory.cs.
Referenced by Create(), and Create< T >().
Switch() [1/2]
MmMessageInt MercuryMessaging.MmMessageFactory.Switch (int stateIndex) static
Create a Switch command message by state index.
Definition at line 304 of file MmMessageFactory.cs.
Switch() [2/2]
MmMessageString MercuryMessaging.MmMessageFactory.Switch (string stateName) static
Create a Switch command message.
Definition at line 291 of file MmMessageFactory.cs.
ToAll< T >()
T MercuryMessaging.MmMessageFactory.ToAll< T > (this T message) static
Configure a message to target all directions.
Type Constraints
T : MmMessage
Definition at line 402 of file MmMessageFactory.cs.
References MercuryMessaging.MmLevelFilterHelper.SelfAndBidirectional.
ToChildren< T >()
T MercuryMessaging.MmMessageFactory.ToChildren< T > (this T message) static
Configure a message to target children.
Type Constraints
T : MmMessage
Definition at line 372 of file MmMessageFactory.cs.
ToDescendants< T >()
T MercuryMessaging.MmMessageFactory.ToDescendants< T > (this T message) static
Configure a message to target descendants.
Type Constraints
T : MmMessage
Definition at line 392 of file MmMessageFactory.cs.
ToParents< T >()
T MercuryMessaging.MmMessageFactory.ToParents< T > (this T message) static
Configure a message to target parents.
Type Constraints
T : MmMessage
Definition at line 382 of file MmMessageFactory.cs.
Transform() [1/2]
MmMessageTransform MercuryMessaging.MmMessageFactory.Transform (MmTransform value) static
Create a Transform message from an MmTransform.
Definition at line 193 of file MmMessageFactory.cs.
Transform() [2/2]
MmMessageTransform MercuryMessaging.MmMessageFactory.Transform (Transform value, bool useGlobal = true) static
Create a Transform message from a Unity Transform.
Note: Converts Transform to MmTransform internally using global coordinates.
Parameters
value The Unity Transform to convert.
useGlobal Use global (world) coordinates if true, local if false. Default: true.
Definition at line 179 of file MmMessageFactory.cs.
References MercuryMessaging.MmTransform, and Transform().
Referenced by Create(), Create< T >(), and Transform().
TransformList()
MmMessageTransformList MercuryMessaging.MmMessageFactory.TransformList (List< MmTransform > value) static
Create a Transform list message.
Definition at line 234 of file MmMessageFactory.cs.
Vector3()
MmMessageVector3 MercuryMessaging.MmMessageFactory.Vector3 (Vector3 value) static
Create a Vector3 message.
Definition at line 137 of file MmMessageFactory.cs.
References Vector3().
Referenced by Create(), Create< T >(), and Vector3().
Vector4()
MmMessageVector4 MercuryMessaging.MmMessageFactory.Vector4 (Vector4 value) static
Create a Vector4 message.
Definition at line 150 of file MmMessageFactory.cs.
References Vector4().
Referenced by Create(), Create< T >(), and Vector4().
WithMetadata< T >()
T MercuryMessaging.MmMessageFactory.WithMetadata< T > (this T message, MmMetadataBlock metadata) static
Configure metadata on a message.
Parameters
message The message to configure
metadata The metadata block to apply
Returns
The configured message
Type Constraints
T : MmMessage
Definition at line 362 of file MmMessageFactory.cs.
WithTag< T >()
T MercuryMessaging.MmMessageFactory.WithTag< T > (this T message, MmTag tag) static
Configure a message with a specific tag.
Type Constraints
T : MmMessage
Definition at line 412 of file MmMessageFactory.cs.
The documentation for this class was generated from the following file:
Protocol/DSL/MmMessageFactory.cs