MercuryMessaging: MercuryMessaging.MmMessagingExtensions Class Reference
MercuryMessaging.MmMessagingExtensions Class Reference
Unified messaging extensions for both MmRelayNode and MmBaseResponder.
Static Public Member Functions
static void BroadcastInitialize (this MmRelayNode relay)
Broadcast Initialize to self and all children.
static void BroadcastRefresh (this MmRelayNode relay)
Broadcast Refresh to self and all children.
static void BroadcastSetActive (this MmRelayNode relay, bool active)
Broadcast SetActive to self and all children.
static void BroadcastSwitch (this MmRelayNode relay, string state)
Broadcast Switch to self and all children.
static void BroadcastValue (this MmRelayNode relay, bool value)
Broadcast bool value to self and all children.
static void BroadcastValue (this MmRelayNode relay, int value)
Broadcast int value to self and all children.
static void BroadcastValue (this MmRelayNode relay, float value)
Broadcast float value to self and all children.
static void BroadcastValue (this MmRelayNode relay, string value)
Broadcast string value to self and all children.
static void NotifyComplete (this MmRelayNode relay)
Notify Complete to all parents/ancestors.
static void NotifyValue (this MmRelayNode relay, bool value)
Notify bool value to all parents.
static void NotifyValue (this MmRelayNode relay, int value)
Notify int value to all parents.
static void NotifyValue (this MmRelayNode relay, float value)
Notify float value to all parents.
static void NotifyValue (this MmRelayNode relay, string value)
Notify string value to all parents.
static void BroadcastInitialize (this MmBaseResponder responder)
Broadcast Initialize to self and all children (from responder).
static void BroadcastRefresh (this MmBaseResponder responder)
Broadcast Refresh to self and all children (from responder).
static void BroadcastSetActive (this MmBaseResponder responder, bool active)
Broadcast SetActive to self and all children (from responder).
static void BroadcastSwitch (this MmBaseResponder responder, string state)
Broadcast Switch to self and all children (from responder).
static void BroadcastValue (this MmBaseResponder responder, bool value)
Broadcast bool value to self and all children (from responder).
static void BroadcastValue (this MmBaseResponder responder, int value)
Broadcast int value to self and all children (from responder).
static void BroadcastValue (this MmBaseResponder responder, float value)
Broadcast float value to self and all children (from responder).
static void BroadcastValue (this MmBaseResponder responder, string value)
Broadcast string value to self and all children (from responder).
static void NotifyComplete (this MmBaseResponder responder)
Notify Complete to all parents/ancestors (from responder).
static void NotifyValue (this MmBaseResponder responder, bool value)
Notify bool value to all parents (from responder).
static void NotifyValue (this MmBaseResponder responder, int value)
Notify int value to all parents (from responder).
static void NotifyValue (this MmBaseResponder responder, float value)
Notify float value to all parents (from responder).
static void NotifyValue (this MmBaseResponder responder, string value)
Notify string value to all parents (from responder).
static MmFluentMessage Send (this MmBaseResponder responder, object payload)
Start a fluent message chain from a responder with a payload.
static MmFluentMessage Send (this MmBaseResponder responder, MmMethod method)
Start a fluent message chain from a responder with a method.
static MmFluentMessage Send (this MmBaseResponder responder, MmMethod method, object payload)
Start a fluent message chain from a responder with method and payload.
Detailed Description
Unified messaging extensions for both MmRelayNode and MmBaseResponder.
Provides a consistent API across both types for common messaging operations.
Naming Convention:
Broadcast* = Send DOWN to descendants (matches MmMethod enum names)
Notify* = Send UP to parents (matches MmMethod enum names)
Example Usage:
// On relay nodes
relay.BroadcastInitialize();
relay.BroadcastValue("hello");
relay.NotifyComplete();
// Same API on responders!
responder.BroadcastInitialize();
responder.NotifyValue(42);
// Fluent chain (Tier 2)
responder.Send("hello").ToDescendants().WithTag(MmTag.Tag0).Execute();
Definition at line 40 of file MmMessagingExtensions.cs.
Member Function Documentation
BroadcastInitialize() [1/2]
void MercuryMessaging.MmMessagingExtensions.BroadcastInitialize (this MmBaseResponder responder) static
Broadcast Initialize to self and all children (from responder).
Null-safe: does nothing if responder has no relay node.
Definition at line 139 of file MmMessagingExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
BroadcastInitialize() [2/2]
void MercuryMessaging.MmMessagingExtensions.BroadcastInitialize (this MmRelayNode relay) static
Broadcast Initialize to self and all children.
Uses default SelfAndChildren routing (includes self).
BroadcastRefresh() [1/2]
void MercuryMessaging.MmMessagingExtensions.BroadcastRefresh (this MmBaseResponder responder) static
Broadcast Refresh to self and all children (from responder).
Null-safe: does nothing if responder has no relay node.
Definition at line 150 of file MmMessagingExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
BroadcastRefresh() [2/2]
void MercuryMessaging.MmMessagingExtensions.BroadcastRefresh (this MmRelayNode relay) static
Broadcast Refresh to self and all children.
Uses default SelfAndChildren routing (includes self).
BroadcastSetActive() [1/2]
void MercuryMessaging.MmMessagingExtensions.BroadcastSetActive (this MmBaseResponder responder, bool active) static
Broadcast SetActive to self and all children (from responder).
Definition at line 158 of file MmMessagingExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
BroadcastSetActive() [2/2]
void MercuryMessaging.MmMessagingExtensions.BroadcastSetActive (this MmRelayNode relay, bool active) static
Broadcast SetActive to self and all children.
Parameters
relay The relay node to broadcast from.
active The active state to set.
BroadcastSwitch() [1/2]
void MercuryMessaging.MmMessagingExtensions.BroadcastSwitch (this MmBaseResponder responder, string state) static
Broadcast Switch to self and all children (from responder).
Definition at line 166 of file MmMessagingExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
BroadcastSwitch() [2/2]
void MercuryMessaging.MmMessagingExtensions.BroadcastSwitch (this MmRelayNode relay, string state) static
Broadcast Switch to self and all children.
Parameters
relay The relay node to broadcast from.
state The state name to switch to.
BroadcastValue() [1/8]
void MercuryMessaging.MmMessagingExtensions.BroadcastValue (this MmBaseResponder responder, bool value) static
Broadcast bool value to self and all children (from responder).
Definition at line 174 of file MmMessagingExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
BroadcastValue() [2/8]
void MercuryMessaging.MmMessagingExtensions.BroadcastValue (this MmBaseResponder responder, float value) static
Broadcast float value to self and all children (from responder).
Definition at line 190 of file MmMessagingExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
BroadcastValue() [3/8]
void MercuryMessaging.MmMessagingExtensions.BroadcastValue (this MmBaseResponder responder, int value) static
Broadcast int value to self and all children (from responder).
Definition at line 182 of file MmMessagingExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
BroadcastValue() [4/8]
void MercuryMessaging.MmMessagingExtensions.BroadcastValue (this MmBaseResponder responder, string value) static
Broadcast string value to self and all children (from responder).
Definition at line 198 of file MmMessagingExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
BroadcastValue() [5/8]
void MercuryMessaging.MmMessagingExtensions.BroadcastValue (this MmRelayNode relay, bool value) static
Broadcast bool value to self and all children.
BroadcastValue() [6/8]
void MercuryMessaging.MmMessagingExtensions.BroadcastValue (this MmRelayNode relay, float value) static
Broadcast float value to self and all children.
BroadcastValue() [7/8]
void MercuryMessaging.MmMessagingExtensions.BroadcastValue (this MmRelayNode relay, int value) static
Broadcast int value to self and all children.
BroadcastValue() [8/8]
void MercuryMessaging.MmMessagingExtensions.BroadcastValue (this MmRelayNode relay, string value) static
Broadcast string value to self and all children.
NotifyComplete() [1/2]
void MercuryMessaging.MmMessagingExtensions.NotifyComplete (this MmBaseResponder responder) static
Notify Complete to all parents/ancestors (from responder).
Null-safe: does nothing if responder has no relay node.
Definition at line 213 of file MmMessagingExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
NotifyComplete() [2/2]
void MercuryMessaging.MmMessagingExtensions.NotifyComplete (this MmRelayNode relay) static
Notify Complete to all parents/ancestors.
Equivalent to: relay.Send(MmMethod.Complete).ToParents().Execute()
NotifyValue() [1/8]
void MercuryMessaging.MmMessagingExtensions.NotifyValue (this MmBaseResponder responder, bool value) static
Notify bool value to all parents (from responder).
Definition at line 221 of file MmMessagingExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
NotifyValue() [2/8]
void MercuryMessaging.MmMessagingExtensions.NotifyValue (this MmBaseResponder responder, float value) static
Notify float value to all parents (from responder).
Definition at line 237 of file MmMessagingExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
NotifyValue() [3/8]
void MercuryMessaging.MmMessagingExtensions.NotifyValue (this MmBaseResponder responder, int value) static
Notify int value to all parents (from responder).
Definition at line 229 of file MmMessagingExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
NotifyValue() [4/8]
void MercuryMessaging.MmMessagingExtensions.NotifyValue (this MmBaseResponder responder, string value) static
Notify string value to all parents (from responder).
Definition at line 245 of file MmMessagingExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
NotifyValue() [5/8]
void MercuryMessaging.MmMessagingExtensions.NotifyValue (this MmRelayNode relay, bool value) static
Notify bool value to all parents.
NotifyValue() [6/8]
void MercuryMessaging.MmMessagingExtensions.NotifyValue (this MmRelayNode relay, float value) static
Notify float value to all parents.
NotifyValue() [7/8]
void MercuryMessaging.MmMessagingExtensions.NotifyValue (this MmRelayNode relay, int value) static
Notify int value to all parents.
NotifyValue() [8/8]
void MercuryMessaging.MmMessagingExtensions.NotifyValue (this MmRelayNode relay, string value) static
Notify string value to all parents.
Send() [1/3]
MmFluentMessage MercuryMessaging.MmMessagingExtensions.Send (this MmBaseResponder responder, MmMethod method) static
Start a fluent message chain from a responder with a method.
Returns a default MmFluentMessage if responder has no relay node.
Example: responder.Send(MmMethod.Initialize).ToDescendants().Execute();
Parameters
responder The responder to send from.
method The MmMethod to invoke.
Returns
A fluent message builder for chaining.
Definition at line 286 of file MmMessagingExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
Send() [2/3]
MmFluentMessage MercuryMessaging.MmMessagingExtensions.Send (this MmBaseResponder responder, MmMethod method, object payload) static
Start a fluent message chain from a responder with method and payload.
Returns a default MmFluentMessage if responder has no relay node.
Example: responder.Send(MmMethod.MessageString, "hello").ToDescendants().Execute();
Parameters
responder The responder to send from.
method The MmMethod to invoke.
payload The value to send.
Returns
A fluent message builder for chaining.
Definition at line 308 of file MmMessagingExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
Send() [3/3]
MmFluentMessage MercuryMessaging.MmMessagingExtensions.Send (this MmBaseResponder responder, object payload) static
Start a fluent message chain from a responder with a payload.
Returns a default MmFluentMessage if responder has no relay node.
Example: responder.Send("hello").ToDescendants().Execute();
Parameters
responder The responder to send from.
payload The value to send (bool, int, float, string, etc.).
Returns
A fluent message builder for chaining.
Definition at line 265 of file MmMessagingExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
The documentation for this class was generated from the following file:
Protocol/DSL/MmMessagingExtensions.cs