MercuryMessaging: MercuryMessaging.Data.DataCollectionBuilder Class Reference
MercuryMessaging.Data.DataCollectionBuilder Class Reference
Fluent builder for configuring MmDataCollector instances.
Public Member Functions
DataCollectionBuilder (MmDataCollector collector)
Create a new data collection builder.
DataCollectionBuilder OutputAsCsv (string fileName)
Set output format to CSV with specified filename.
DataCollectionBuilder OutputAsXml (string fileName)
Set output format to XML with specified filename.
DataCollectionBuilder AtLocation (string path)
Set the output file location.
DataCollectionBuilder InPersistentData ()
Use persistent data path for output.
DataCollectionBuilder InStreamingAssets ()
Use streaming assets path for output.
DataCollectionBuilder EveryFrame ()
Collect data every frame (in LateUpdate).
DataCollectionBuilder Manually ()
Collect data only when manually triggered.
DataCollectionBuilder AtEndOfTask ()
Collect data at end of task.
DataCollectionBuilder Collect (string name, Func< string > dataProvider)
Add a data item to collect with a string provider function.
DataCollectionBuilder Collect (string name, Func< Vector3 > dataProvider)
Add a Vector3 data item (auto-converted to string).
DataCollectionBuilder Collect (string name, Func< Quaternion > dataProvider)
Add a Quaternion data item (auto-converted to euler angles string).
DataCollectionBuilder Collect (string name, Func< float > dataProvider, string format="F4")
Add a float data item.
DataCollectionBuilder Collect (string name, Func< int > dataProvider)
Add an int data item.
DataCollectionBuilder Collect (string name, Func< bool > dataProvider)
Add a bool data item.
DataCollectionBuilder CollectPosition (string name, Transform transform)
Add a Transform position data item.
DataCollectionBuilder CollectRotation (string name, Transform transform)
Add a Transform rotation data item.
DataCollectionBuilder CollectTimestamp (string name="Timestamp")
Add timestamp data item.
DataCollectionBuilder CollectGameTime (string name="GameTime")
Add Unity time data item.
DataCollectionBuilder CollectFrameCount (string name="Frame")
Add frame count data item.
MmDataCollector Build ()
Apply configuration and prepare for collection (does not start).
MmDataCollector Start ()
Apply configuration and start data collection.
Private Attributes
readonly MmDataCollector _collector
readonly List<(string name, Func< string > printData)> _dataItems
string _fileName = "data"
string _fileLocation
MmDataCollectionOutputType _outputType = MmDataCollectionOutputType.CSV
MmDataCollectionFreq _frequency = MmDataCollectionFreq.Manual
Detailed Description
Fluent builder for configuring MmDataCollector instances.
Provides a clean, chainable API for setting up data collection.
Example Usage:
collector.Configure()
    .OutputAsCsv("experiment_results")
    .AtLocation(Application.persistentDataPath)
    .EveryFrame()
    .Collect("Position", () => transform.position.ToString())
    .Collect("Rotation", () => transform.rotation.eulerAngles.ToString())
    .Collect("Time", () => Time.time.ToString("F3"))
    .Start();
Definition at line 29 of file DataCollectionBuilder.cs.
Constructor & Destructor Documentation
DataCollectionBuilder()
MercuryMessaging.Data.DataCollectionBuilder.DataCollectionBuilder (MmDataCollector collector)
Create a new data collection builder.
Definition at line 43 of file DataCollectionBuilder.cs.
References _collector, and _fileLocation.
Referenced by AtEndOfTask(), AtLocation(), Collect(), Collect(), Collect(), Collect(), Collect(), Collect(), CollectFrameCount(), CollectGameTime(), CollectPosition(), CollectRotation(), CollectTimestamp(), EveryFrame(), InPersistentData(), InStreamingAssets(), Manually(), OutputAsCsv(), and OutputAsXml().
Member Function Documentation
AtEndOfTask()
DataCollectionBuilder MercuryMessaging.Data.DataCollectionBuilder.AtEndOfTask ()
Collect data at end of task.
Definition at line 123 of file DataCollectionBuilder.cs.
References DataCollectionBuilder(), and _frequency.
AtLocation()
DataCollectionBuilder MercuryMessaging.Data.DataCollectionBuilder.AtLocation (string path)
Set the output file location.
Definition at line 74 of file DataCollectionBuilder.cs.
References DataCollectionBuilder(), and _fileLocation.
Build()
MmDataCollector MercuryMessaging.Data.DataCollectionBuilder.Build ()
Apply configuration and prepare for collection (does not start).
Definition at line 242 of file DataCollectionBuilder.cs.
References _collector, _dataItems, _frequency, and _outputType.
Referenced by Start().
Collect() [1/6]
DataCollectionBuilder MercuryMessaging.Data.DataCollectionBuilder.Collect (string name, Func< bool > dataProvider)
Add a bool data item.
Definition at line 190 of file DataCollectionBuilder.cs.
References DataCollectionBuilder(), and Collect().
Collect() [2/6]
DataCollectionBuilder MercuryMessaging.Data.DataCollectionBuilder.Collect (string name, Func< float > dataProvider, string format = "F4")
Add a float data item.
Definition at line 174 of file DataCollectionBuilder.cs.
References DataCollectionBuilder(), and Collect().
Collect() [3/6]
DataCollectionBuilder MercuryMessaging.Data.DataCollectionBuilder.Collect (string name, Func< int > dataProvider)
Add an int data item.
Definition at line 182 of file DataCollectionBuilder.cs.
References DataCollectionBuilder(), and Collect().
Collect() [4/6]
DataCollectionBuilder MercuryMessaging.Data.DataCollectionBuilder.Collect (string name, Func< Quaternion > dataProvider)
Add a Quaternion data item (auto-converted to euler angles string).
Definition at line 162 of file DataCollectionBuilder.cs.
References DataCollectionBuilder(), and Collect().
Collect() [5/6]
DataCollectionBuilder MercuryMessaging.Data.DataCollectionBuilder.Collect (string name, Func< string > dataProvider)
Add a data item to collect with a string provider function.
Definition at line 136 of file DataCollectionBuilder.cs.
References DataCollectionBuilder(), and _dataItems.
Referenced by Collect(), Collect(), Collect(), Collect(), Collect(), CollectFrameCount(), CollectGameTime(), CollectPosition(), CollectRotation(), and CollectTimestamp().
Collect() [6/6]
DataCollectionBuilder MercuryMessaging.Data.DataCollectionBuilder.Collect (string name, Func< Vector3 > dataProvider)
Add a Vector3 data item (auto-converted to string).
Definition at line 150 of file DataCollectionBuilder.cs.
References DataCollectionBuilder(), and Collect().
CollectFrameCount()
DataCollectionBuilder MercuryMessaging.Data.DataCollectionBuilder.CollectFrameCount (string name = "Frame")
Add frame count data item.
Definition at line 230 of file DataCollectionBuilder.cs.
References DataCollectionBuilder(), and Collect().
CollectGameTime()
DataCollectionBuilder MercuryMessaging.Data.DataCollectionBuilder.CollectGameTime (string name = "GameTime")
Add Unity time data item.
Definition at line 222 of file DataCollectionBuilder.cs.
References DataCollectionBuilder(), and Collect().
CollectPosition()
DataCollectionBuilder MercuryMessaging.Data.DataCollectionBuilder.CollectPosition (string name, Transform transform)
Add a Transform position data item.
Definition at line 198 of file DataCollectionBuilder.cs.
References DataCollectionBuilder(), and Collect().
CollectRotation()
DataCollectionBuilder MercuryMessaging.Data.DataCollectionBuilder.CollectRotation (string name, Transform transform)
Add a Transform rotation data item.
Definition at line 206 of file DataCollectionBuilder.cs.
References DataCollectionBuilder(), and Collect().
CollectTimestamp()
DataCollectionBuilder MercuryMessaging.Data.DataCollectionBuilder.CollectTimestamp (string name = "Timestamp")
Add timestamp data item.
Definition at line 214 of file DataCollectionBuilder.cs.
References DataCollectionBuilder(), and Collect().
EveryFrame()
DataCollectionBuilder MercuryMessaging.Data.DataCollectionBuilder.EveryFrame ()
Collect data every frame (in LateUpdate).
Definition at line 105 of file DataCollectionBuilder.cs.
References DataCollectionBuilder(), and _frequency.
InPersistentData()
DataCollectionBuilder MercuryMessaging.Data.DataCollectionBuilder.InPersistentData ()
Use persistent data path for output.
Definition at line 83 of file DataCollectionBuilder.cs.
References DataCollectionBuilder(), and _fileLocation.
InStreamingAssets()
DataCollectionBuilder MercuryMessaging.Data.DataCollectionBuilder.InStreamingAssets ()
Use streaming assets path for output.
Definition at line 92 of file DataCollectionBuilder.cs.
References DataCollectionBuilder(), and _fileLocation.
Manually()
DataCollectionBuilder MercuryMessaging.Data.DataCollectionBuilder.Manually ()
Collect data only when manually triggered.
Definition at line 114 of file DataCollectionBuilder.cs.
References DataCollectionBuilder(), and _frequency.
OutputAsCsv()
DataCollectionBuilder MercuryMessaging.Data.DataCollectionBuilder.OutputAsCsv (string fileName)
Set output format to CSV with specified filename.
Definition at line 54 of file DataCollectionBuilder.cs.
References DataCollectionBuilder(), _fileName, and _outputType.
OutputAsXml()
DataCollectionBuilder MercuryMessaging.Data.DataCollectionBuilder.OutputAsXml (string fileName)
Set output format to XML with specified filename.
Definition at line 64 of file DataCollectionBuilder.cs.
References DataCollectionBuilder(), _fileName, and _outputType.
Start()
MmDataCollector MercuryMessaging.Data.DataCollectionBuilder.Start ()
Apply configuration and start data collection.
Definition at line 261 of file DataCollectionBuilder.cs.
References _collector, _fileLocation, _fileName, and Build().
Member Data Documentation
_collector
readonly MmDataCollector MercuryMessaging.Data.DataCollectionBuilder._collector private
Definition at line 31 of file DataCollectionBuilder.cs.
Referenced by DataCollectionBuilder(), Build(), and Start().
_dataItems
readonly List<(string name, Func<string> printData)> MercuryMessaging.Data.DataCollectionBuilder._dataItems private
Initial value:
=
            new List<(string, Func<string>)>()
Definition at line 32 of file DataCollectionBuilder.cs.
Referenced by Build(), and Collect().
_fileLocation
string MercuryMessaging.Data.DataCollectionBuilder._fileLocation private
Definition at line 36 of file DataCollectionBuilder.cs.
Referenced by DataCollectionBuilder(), AtLocation(), InPersistentData(), InStreamingAssets(), and Start().
_fileName
string MercuryMessaging.Data.DataCollectionBuilder._fileName = "data" private
Definition at line 35 of file DataCollectionBuilder.cs.
Referenced by OutputAsCsv(), OutputAsXml(), and Start().
_frequency
MmDataCollectionFreq MercuryMessaging.Data.DataCollectionBuilder._frequency = MmDataCollectionFreq.Manual private
Definition at line 38 of file DataCollectionBuilder.cs.
Referenced by AtEndOfTask(), Build(), EveryFrame(), and Manually().
_outputType
MmDataCollectionOutputType MercuryMessaging.Data.DataCollectionBuilder._outputType = MmDataCollectionOutputType.CSV private
Definition at line 37 of file DataCollectionBuilder.cs.
Referenced by Build(), OutputAsCsv(), and OutputAsXml().
The documentation for this class was generated from the following file:
Support/Data/DataCollectionBuilder.cs