MercuryMessaging: MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions Class Reference
MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions Class Reference
Extension methods for subscribing to Standard Library messages.
Static Public Member Functions
static MmListenerSubscription< MmUIClickMessage > OnClick (this MmRelayNode relay, Action< MmUIClickMessage > handler)
Subscribes to UI click messages.
static MmListenerSubscription< MmUIClickMessage > OnClick (this MmRelayNode relay, Action< UnityEngine.Vector2 > handler)
Subscribes to UI click messages with position-only handler.
static MmListenerSubscription< MmUIHoverMessage > OnHover (this MmRelayNode relay, Action< MmUIHoverMessage > handler)
Subscribes to UI hover messages.
static MmListenerSubscription< MmUIHoverMessage > OnHover (this MmRelayNode relay, Action< bool > handler)
Subscribes to UI hover enter/exit with bool handler.
static MmListenerSubscription< MmUIDragMessage > OnDrag (this MmRelayNode relay, Action< MmUIDragMessage > handler)
Subscribes to UI drag messages.
static MmListenerSubscription< MmUIDragMessage > OnDrag (this MmRelayNode relay, Action< UnityEngine.Vector2 > handler)
Subscribes to UI drag with delta-only handler.
static MmListenerSubscription< MmUIScrollMessage > OnScroll (this MmRelayNode relay, Action< MmUIScrollMessage > handler)
Subscribes to UI scroll messages.
static MmListenerSubscription< MmUIScrollMessage > OnScroll (this MmRelayNode relay, Action< UnityEngine.Vector2 > handler)
Subscribes to UI scroll with delta-only handler.
static MmListenerSubscription< MmUIFocusMessage > OnFocus (this MmRelayNode relay, Action< MmUIFocusMessage > handler)
Subscribes to UI focus messages.
static MmListenerSubscription< MmUIFocusMessage > OnFocus (this MmRelayNode relay, Action< bool > handler)
Subscribes to UI focus with bool handler (focused/unfocused).
static MmListenerSubscription< MmUISelectMessage > OnSelect (this MmRelayNode relay, Action< MmUISelectMessage > handler)
Subscribes to UI selection messages.
static MmListenerSubscription< MmUISelectMessage > OnSelect (this MmRelayNode relay, Action< int > handler)
Subscribes to UI selection with index handler.
static MmListenerSubscription< MmUISelectMessage > OnSelect (this MmRelayNode relay, Action< string > handler)
Subscribes to UI selection with value handler.
static MmListenerSubscription< MmUISubmitMessage > OnUISubmit (this MmRelayNode relay, Action< MmUISubmitMessage > handler)
Subscribes to UI submit messages.
static MmListenerSubscription< MmUISubmitMessage > OnUISubmit (this MmRelayNode relay, Action< string > handler)
Subscribes to UI submit with data handler.
static MmListenerSubscription< MmUICancelMessage > OnUICancel (this MmRelayNode relay, Action< MmUICancelMessage > handler)
Subscribes to UI cancel messages.
static MmListenerSubscription< MmUICancelMessage > OnUICancel (this MmRelayNode relay, Action handler)
Subscribes to UI cancel with simple handler.
static MmListenerSubscription< MmInput6DOFMessage > On6DOF (this MmRelayNode relay, Action< MmInput6DOFMessage > handler)
Subscribes to 6DOF controller input messages.
static MmListenerSubscription< MmInput6DOFMessage > On6DOF (this MmRelayNode relay, MmHandedness hand, Action< MmInput6DOFMessage > handler)
Subscribes to 6DOF input for a specific hand.
static MmListenerSubscription< MmInputGestureMessage > OnGesture (this MmRelayNode relay, Action< MmInputGestureMessage > handler)
Subscribes to gesture recognition messages.
static MmListenerSubscription< MmInputGestureMessage > OnGesture (this MmRelayNode relay, MmGestureType gestureType, Action< MmInputGestureMessage > handler)
Subscribes to a specific gesture type.
static MmListenerSubscription< MmInputGestureMessage > OnGesture (this MmRelayNode relay, MmGestureType gestureType, float minConfidence, Action< MmInputGestureMessage > handler)
Subscribes to gestures with minimum confidence.
static MmListenerSubscription< MmInputHapticMessage > OnHaptic (this MmRelayNode relay, Action< MmInputHapticMessage > handler)
Subscribes to haptic feedback messages.
static MmListenerSubscription< MmInputButtonMessage > OnButton (this MmRelayNode relay, Action< MmInputButtonMessage > handler)
Subscribes to button input messages.
static MmListenerSubscription< MmInputButtonMessage > OnButton (this MmRelayNode relay, string buttonName, Action< MmInputButtonMessage > handler)
Subscribes to a specific button by name.
static MmListenerSubscription< MmInputButtonMessage > OnButtonPressed (this MmRelayNode relay, Action< MmInputButtonMessage > handler)
Subscribes to button press events only.
static MmListenerSubscription< MmInputButtonMessage > OnButtonReleased (this MmRelayNode relay, Action< MmInputButtonMessage > handler)
Subscribes to button release events only.
static MmListenerSubscription< MmInputAxisMessage > OnAxis (this MmRelayNode relay, Action< MmInputAxisMessage > handler)
Subscribes to axis input messages.
static MmListenerSubscription< MmInputAxisMessage > OnAxis (this MmRelayNode relay, string axisName, Action< MmInputAxisMessage > handler)
Subscribes to a specific axis by name.
static MmListenerSubscription< MmInputTouchMessage > OnTouch (this MmRelayNode relay, Action< MmInputTouchMessage > handler)
Subscribes to touch input messages.
static MmListenerSubscription< MmInputControllerStateMessage > OnControllerState (this MmRelayNode relay, Action< MmInputControllerStateMessage > handler)
Subscribes to controller state messages.
static MmListenerSubscription< MmInputControllerStateMessage > OnControllerConnected (this MmRelayNode relay, Action< MmInputControllerStateMessage > handler)
Subscribes to controller connect events.
static MmListenerSubscription< MmInputControllerStateMessage > OnControllerDisconnected (this MmRelayNode relay, Action< MmInputControllerStateMessage > handler)
Subscribes to controller disconnect events.
static MmListenerSubscription< MmInputGazeMessage > OnGaze (this MmRelayNode relay, Action< MmInputGazeMessage > handler)
Subscribes to gaze tracking messages.
static MmListenerSubscription< MmInputGazeMessage > OnGazeHit (this MmRelayNode relay, Action< MmInputGazeMessage > handler)
Subscribes to gaze hits only (when looking at something).
static MmListenerSubscription< MmUIClickMessage > OnClick (this MmBaseResponder responder, Action< MmUIClickMessage > handler)
Subscribes to UI click messages (from responder).
static MmListenerSubscription< MmUIHoverMessage > OnHover (this MmBaseResponder responder, Action< MmUIHoverMessage > handler)
Subscribes to UI hover messages (from responder).
static MmListenerSubscription< MmUIDragMessage > OnDrag (this MmBaseResponder responder, Action< MmUIDragMessage > handler)
Subscribes to UI drag messages (from responder).
static MmListenerSubscription< MmUIScrollMessage > OnScroll (this MmBaseResponder responder, Action< MmUIScrollMessage > handler)
Subscribes to UI scroll messages (from responder).
static MmListenerSubscription< MmUIFocusMessage > OnFocus (this MmBaseResponder responder, Action< MmUIFocusMessage > handler)
Subscribes to UI focus messages (from responder).
static MmListenerSubscription< MmUISelectMessage > OnSelect (this MmBaseResponder responder, Action< MmUISelectMessage > handler)
Subscribes to UI select messages (from responder).
static MmListenerSubscription< MmInput6DOFMessage > On6DOF (this MmBaseResponder responder, Action< MmInput6DOFMessage > handler)
Subscribes to 6DOF messages (from responder).
static MmListenerSubscription< MmInputGestureMessage > OnGesture (this MmBaseResponder responder, Action< MmInputGestureMessage > handler)
Subscribes to gesture messages (from responder).
static MmListenerSubscription< MmInputButtonMessage > OnButton (this MmBaseResponder responder, Action< MmInputButtonMessage > handler)
Subscribes to button messages (from responder).
static MmListenerSubscription< MmInputAxisMessage > OnAxis (this MmBaseResponder responder, Action< MmInputAxisMessage > handler)
Subscribes to axis messages (from responder).
static MmListenerSubscription< MmInputGazeMessage > OnGaze (this MmBaseResponder responder, Action< MmInputGazeMessage > handler)
Subscribes to gaze messages (from responder).
Detailed Description
Extension methods for subscribing to Standard Library messages.
Part of DSL Phase 2.4: Standard Library Handler Shortcuts.
Provides convenience methods for listening to UI (100-199) and Input (200-299) messages without needing the full builder pattern.
Example usage:
// UI message shortcuts
relay.OnClick(msg => HandleClick(msg.Position));
relay.OnHover(msg => ShowTooltip(msg.IsEnter));
relay.OnDrag(msg => MoveObject(msg.Delta));
// Input message shortcuts
relay.On6DOF(msg => UpdateHand(msg.Position, msg.Rotation));
relay.OnGesture(msg => RecognizeGesture(msg.GestureType));
relay.OnButton(msg => HandleButton(msg.ButtonName, msg.State));
Definition at line 35 of file MmStandardLibraryListenerExtensions.cs.
Member Function Documentation
On6DOF() [1/3]
MmListenerSubscription< MmInput6DOFMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.On6DOF (this MmBaseResponder responder, Action< MmInput6DOFMessage > handler) static
Subscribes to 6DOF messages (from responder).
Definition at line 685 of file MmStandardLibraryListenerExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
On6DOF() [2/3]
MmListenerSubscription< MmInput6DOFMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.On6DOF (this MmRelayNode relay, Action< MmInput6DOFMessage > handler) static
Subscribes to 6DOF controller input messages.
Parameters
relay The relay node to listen on.
handler Handler called with 6DOF message.
Returns
A subscription handle.
relay.On6DOF(msg => { if (msg.Hand == MmHandedness.Right && msg.IsTracked) rightHand.SetPositionAndRotation(msg.Position, msg.Rotation); });
Definition at line 336 of file MmStandardLibraryListenerExtensions.cs.
On6DOF() [3/3]
MmListenerSubscription< MmInput6DOFMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.On6DOF (this MmRelayNode relay, MmHandedness hand, Action< MmInput6DOFMessage > handler) static
Subscribes to 6DOF input for a specific hand.
Definition at line 349 of file MmStandardLibraryListenerExtensions.cs.
OnAxis() [1/3]
MmListenerSubscription< MmInputAxisMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnAxis (this MmBaseResponder responder, Action< MmInputAxisMessage > handler) static
Subscribes to axis messages (from responder).
Definition at line 715 of file MmStandardLibraryListenerExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
OnAxis() [2/3]
MmListenerSubscription< MmInputAxisMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnAxis (this MmRelayNode relay, Action< MmInputAxisMessage > handler) static
Subscribes to axis input messages.
Definition at line 493 of file MmStandardLibraryListenerExtensions.cs.
OnAxis() [3/3]
MmListenerSubscription< MmInputAxisMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnAxis (this MmRelayNode relay, string axisName, Action< MmInputAxisMessage > handler) static
Subscribes to a specific axis by name.
Definition at line 506 of file MmStandardLibraryListenerExtensions.cs.
OnButton() [1/3]
MmListenerSubscription< MmInputButtonMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnButton (this MmBaseResponder responder, Action< MmInputButtonMessage > handler) static
Subscribes to button messages (from responder).
Definition at line 705 of file MmStandardLibraryListenerExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
OnButton() [2/3]
MmListenerSubscription< MmInputButtonMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnButton (this MmRelayNode relay, Action< MmInputButtonMessage > handler) static
Subscribes to button input messages.
Definition at line 433 of file MmStandardLibraryListenerExtensions.cs.
OnButton() [3/3]
MmListenerSubscription< MmInputButtonMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnButton (this MmRelayNode relay, string buttonName, Action< MmInputButtonMessage > handler) static
Subscribes to a specific button by name.
Definition at line 446 of file MmStandardLibraryListenerExtensions.cs.
OnButtonPressed()
MmListenerSubscription< MmInputButtonMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnButtonPressed (this MmRelayNode relay, Action< MmInputButtonMessage > handler) static
Subscribes to button press events only.
Definition at line 461 of file MmStandardLibraryListenerExtensions.cs.
OnButtonReleased()
MmListenerSubscription< MmInputButtonMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnButtonReleased (this MmRelayNode relay, Action< MmInputButtonMessage > handler) static
Subscribes to button release events only.
Definition at line 475 of file MmStandardLibraryListenerExtensions.cs.
OnClick() [1/3]
MmListenerSubscription< MmUIClickMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnClick (this MmBaseResponder responder, Action< MmUIClickMessage > handler) static
Subscribes to UI click messages (from responder).
Definition at line 621 of file MmStandardLibraryListenerExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
OnClick() [2/3]
MmListenerSubscription< MmUIClickMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnClick (this MmRelayNode relay, Action< MmUIClickMessage > handler) static
Subscribes to UI click messages.
Parameters
relay The relay node to listen on.
handler Handler called with click message.
Returns
A subscription handle.
relay.OnClick(msg => { if (msg.IsDoubleClick) OpenItem(); if (msg.IsRightClick) ShowContextMenu(); });
Definition at line 56 of file MmStandardLibraryListenerExtensions.cs.
OnClick() [3/3]
MmListenerSubscription< MmUIClickMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnClick (this MmRelayNode relay, Action< UnityEngine.Vector2 > handler) static
Subscribes to UI click messages with position-only handler.
Definition at line 69 of file MmStandardLibraryListenerExtensions.cs.
OnControllerConnected()
MmListenerSubscription< MmInputControllerStateMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnControllerConnected (this MmRelayNode relay, Action< MmInputControllerStateMessage > handler) static
Subscribes to controller connect events.
Definition at line 555 of file MmStandardLibraryListenerExtensions.cs.
OnControllerDisconnected()
MmListenerSubscription< MmInputControllerStateMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnControllerDisconnected (this MmRelayNode relay, Action< MmInputControllerStateMessage > handler) static
Subscribes to controller disconnect events.
Definition at line 569 of file MmStandardLibraryListenerExtensions.cs.
OnControllerState()
MmListenerSubscription< MmInputControllerStateMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnControllerState (this MmRelayNode relay, Action< MmInputControllerStateMessage > handler) static
Subscribes to controller state messages.
Definition at line 542 of file MmStandardLibraryListenerExtensions.cs.
OnDrag() [1/3]
MmListenerSubscription< MmUIDragMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnDrag (this MmBaseResponder responder, Action< MmUIDragMessage > handler) static
Subscribes to UI drag messages (from responder).
Definition at line 641 of file MmStandardLibraryListenerExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
OnDrag() [2/3]
MmListenerSubscription< MmUIDragMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnDrag (this MmRelayNode relay, Action< MmUIDragMessage > handler) static
Subscribes to UI drag messages.
Parameters
relay The relay node to listen on.
handler Handler called with drag message.
Returns
A subscription handle.
relay.OnDrag(msg => { if (msg.Phase == MmDragPhase.Move) transform.position += (Vector3)msg.Delta; });
Definition at line 134 of file MmStandardLibraryListenerExtensions.cs.
OnDrag() [3/3]
MmListenerSubscription< MmUIDragMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnDrag (this MmRelayNode relay, Action< UnityEngine.Vector2 > handler) static
Subscribes to UI drag with delta-only handler.
Definition at line 147 of file MmStandardLibraryListenerExtensions.cs.
OnFocus() [1/3]
MmListenerSubscription< MmUIFocusMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnFocus (this MmBaseResponder responder, Action< MmUIFocusMessage > handler) static
Subscribes to UI focus messages (from responder).
Definition at line 661 of file MmStandardLibraryListenerExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
OnFocus() [2/3]
MmListenerSubscription< MmUIFocusMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnFocus (this MmRelayNode relay, Action< bool > handler) static
Subscribes to UI focus with bool handler (focused/unfocused).
Definition at line 207 of file MmStandardLibraryListenerExtensions.cs.
OnFocus() [3/3]
MmListenerSubscription< MmUIFocusMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnFocus (this MmRelayNode relay, Action< MmUIFocusMessage > handler) static
Subscribes to UI focus messages.
Definition at line 194 of file MmStandardLibraryListenerExtensions.cs.
OnGaze() [1/2]
MmListenerSubscription< MmInputGazeMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnGaze (this MmBaseResponder responder, Action< MmInputGazeMessage > handler) static
Subscribes to gaze messages (from responder).
Definition at line 725 of file MmStandardLibraryListenerExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
OnGaze() [2/2]
MmListenerSubscription< MmInputGazeMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnGaze (this MmRelayNode relay, Action< MmInputGazeMessage > handler) static
Subscribes to gaze tracking messages.
Definition at line 587 of file MmStandardLibraryListenerExtensions.cs.
OnGazeHit()
MmListenerSubscription< MmInputGazeMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnGazeHit (this MmRelayNode relay, Action< MmInputGazeMessage > handler) static
Subscribes to gaze hits only (when looking at something).
Definition at line 600 of file MmStandardLibraryListenerExtensions.cs.
OnGesture() [1/4]
MmListenerSubscription< MmInputGestureMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnGesture (this MmBaseResponder responder, Action< MmInputGestureMessage > handler) static
Subscribes to gesture messages (from responder).
Definition at line 695 of file MmStandardLibraryListenerExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
OnGesture() [2/4]
MmListenerSubscription< MmInputGestureMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnGesture (this MmRelayNode relay, Action< MmInputGestureMessage > handler) static
Subscribes to gesture recognition messages.
Definition at line 368 of file MmStandardLibraryListenerExtensions.cs.
OnGesture() [3/4]
MmListenerSubscription< MmInputGestureMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnGesture (this MmRelayNode relay, MmGestureType gestureType, Action< MmInputGestureMessage > handler) static
Subscribes to a specific gesture type.
Definition at line 381 of file MmStandardLibraryListenerExtensions.cs.
OnGesture() [4/4]
MmListenerSubscription< MmInputGestureMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnGesture (this MmRelayNode relay, MmGestureType gestureType, float minConfidence, Action< MmInputGestureMessage > handler) static
Subscribes to gestures with minimum confidence.
Definition at line 396 of file MmStandardLibraryListenerExtensions.cs.
OnHaptic()
MmListenerSubscription< MmInputHapticMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnHaptic (this MmRelayNode relay, Action< MmInputHapticMessage > handler) static
Subscribes to haptic feedback messages.
Definition at line 416 of file MmStandardLibraryListenerExtensions.cs.
OnHover() [1/3]
MmListenerSubscription< MmUIHoverMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnHover (this MmBaseResponder responder, Action< MmUIHoverMessage > handler) static
Subscribes to UI hover messages (from responder).
Definition at line 631 of file MmStandardLibraryListenerExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
OnHover() [2/3]
MmListenerSubscription< MmUIHoverMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnHover (this MmRelayNode relay, Action< bool > handler) static
Subscribes to UI hover enter/exit with bool handler.
Definition at line 108 of file MmStandardLibraryListenerExtensions.cs.
OnHover() [3/3]
MmListenerSubscription< MmUIHoverMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnHover (this MmRelayNode relay, Action< MmUIHoverMessage > handler) static
Subscribes to UI hover messages.
Parameters
relay The relay node to listen on.
handler Handler called with hover message.
Returns
A subscription handle.
relay.OnHover(msg => { if (msg.IsEnter) ShowTooltip(); else HideTooltip(); });
Definition at line 95 of file MmStandardLibraryListenerExtensions.cs.
OnScroll() [1/3]
MmListenerSubscription< MmUIScrollMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnScroll (this MmBaseResponder responder, Action< MmUIScrollMessage > handler) static
Subscribes to UI scroll messages (from responder).
Definition at line 651 of file MmStandardLibraryListenerExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
OnScroll() [2/3]
MmListenerSubscription< MmUIScrollMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnScroll (this MmRelayNode relay, Action< MmUIScrollMessage > handler) static
Subscribes to UI scroll messages.
Definition at line 164 of file MmStandardLibraryListenerExtensions.cs.
OnScroll() [3/3]
MmListenerSubscription< MmUIScrollMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnScroll (this MmRelayNode relay, Action< UnityEngine.Vector2 > handler) static
Subscribes to UI scroll with delta-only handler.
Definition at line 177 of file MmStandardLibraryListenerExtensions.cs.
OnSelect() [1/4]
MmListenerSubscription< MmUISelectMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnSelect (this MmBaseResponder responder, Action< MmUISelectMessage > handler) static
Subscribes to UI select messages (from responder).
Definition at line 671 of file MmStandardLibraryListenerExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
OnSelect() [2/4]
MmListenerSubscription< MmUISelectMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnSelect (this MmRelayNode relay, Action< int > handler) static
Subscribes to UI selection with index handler.
Definition at line 237 of file MmStandardLibraryListenerExtensions.cs.
OnSelect() [3/4]
MmListenerSubscription< MmUISelectMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnSelect (this MmRelayNode relay, Action< MmUISelectMessage > handler) static
Subscribes to UI selection messages.
Definition at line 224 of file MmStandardLibraryListenerExtensions.cs.
OnSelect() [4/4]
MmListenerSubscription< MmUISelectMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnSelect (this MmRelayNode relay, Action< string > handler) static
Subscribes to UI selection with value handler.
Definition at line 250 of file MmStandardLibraryListenerExtensions.cs.
OnTouch()
MmListenerSubscription< MmInputTouchMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnTouch (this MmRelayNode relay, Action< MmInputTouchMessage > handler) static
Subscribes to touch input messages.
Definition at line 525 of file MmStandardLibraryListenerExtensions.cs.
OnUICancel() [1/2]
MmListenerSubscription< MmUICancelMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnUICancel (this MmRelayNode relay, Action handler) static
Subscribes to UI cancel with simple handler.
Definition at line 306 of file MmStandardLibraryListenerExtensions.cs.
OnUICancel() [2/2]
MmListenerSubscription< MmUICancelMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnUICancel (this MmRelayNode relay, Action< MmUICancelMessage > handler) static
Subscribes to UI cancel messages.
Definition at line 293 of file MmStandardLibraryListenerExtensions.cs.
OnUISubmit() [1/2]
MmListenerSubscription< MmUISubmitMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnUISubmit (this MmRelayNode relay, Action< MmUISubmitMessage > handler) static
Subscribes to UI submit messages.
Definition at line 267 of file MmStandardLibraryListenerExtensions.cs.
OnUISubmit() [2/2]
MmListenerSubscription< MmUISubmitMessage > MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnUISubmit (this MmRelayNode relay, Action< string > handler) static
Subscribes to UI submit with data handler.
Definition at line 280 of file MmStandardLibraryListenerExtensions.cs.
The documentation for this class was generated from the following file:
StandardLibrary/MmStandardLibraryListenerExtensions.cs