MercuryMessaging: MercuryMessaging.MmResponder Class Reference
MercuryMessaging.MmResponder Class Reference abstract
Base implmentation of IMmResponder.
Public Member Functions
virtual void Awake ()
Awake: Invokes MmOnAwakeComplete.
virtual void Start ()
Start: Invokes MmOnStartComplete.
virtual void Update ()
Base Update of MmResponder Derived classes should always override.
virtual void MmOnAwakeComplete ()
Post Awake callback used between objects implementing this interface.
virtual void MmOnStartComplete ()
Post Start callback used between objects implementing this interface This allows for initialization steps that must occur before one instance's Start and its first Update.
virtual void MmRegisterAwakeCompleteCallback (IMmCallback callback)
It is possible that certain handles are not going to be in-place when registration of the OnAwakeComplete callback is invoked.
virtual void MmRegisterStartCompleteCallback (IMmCallback callback)
It is possible that certain handles are not going to be in-place when registration of the OnStartComplete callback is invoked.
MmRelayNode GetRelayNode ()
Get a handle to a IMmResponder's MmRelayNode, if one is present.
virtual void MmInvoke (MmMessage message)
Invoke an MmMethod.
Properties
GameObject MmGameObject [get]
Handle to an instance's GameObject.
MmTag Tag [get, set]
MmTags allow you to specify filters for execution in Mercury XM graphs.
bool TagCheckEnabled [get, set]
Determines whether tag checking is enabled for this IMmResponder.
bool ReceiveHandledMessages [get, set]
When true, this responder receives messages even if Handled=true.
Events
IMmCallback MmAwakeCompleteCallback
Event triggered in the MmResponder when this object is awoken.
IMmCallback MmStartCompleteCallback
Event triggered in the MmResponder when this object is started.
Private Attributes
MmTag _mmTag = MmTagHelper.Everything
Determines whether tag checking is enabled for this IMmResponder.
bool tagCheckEnabled = true
By default IMmResponders have this set to true so that they receive all messages.
bool receiveHandledMessages = false
When true, this responder receives messages even if Handled=true.
Detailed Description
Base implmentation of IMmResponder.
Definition at line 44 of file MmResponder.cs.
Member Function Documentation
Awake()
virtual void MercuryMessaging.MmResponder.Awake () virtual
Awake: Invokes MmOnAwakeComplete.
Reimplemented in MercuryMessaging.MmGuiResponder, MercuryMessaging.MmRelayAppStateNode, MercuryMessaging.MmRelayNode, MercuryMessaging.MmRelaySwitchNode, MercuryMessaging.MmSwitchResponder, MercuryMessaging.Task.MmTaskManager< U >, and MercuryMessaging.Task.MmTaskResponder< T >.
Definition at line 119 of file MmResponder.cs.
References MercuryMessaging.MmLogger.LogResponder, and MmOnAwakeComplete().
GetRelayNode()
MmRelayNode MercuryMessaging.MmResponder.GetRelayNode () abstract
Get a handle to a IMmResponder's MmRelayNode, if one is present.
Returns
an MmRelayNode sharing the GameObject with the instance.
Implements MercuryMessaging.IMmResponder.
MmInvoke()
virtual void MercuryMessaging.MmResponder.MmInvoke (MmMessage message) virtual
Invoke an MmMethod.
Parameters
msgType Type of message. This specifies the type of the payload. This is important in networked scenarios, when proper deseriaization into the correct type requires knowing what was used to serialize the object originally.
message The message to send. This class builds on UNET's MessageBase so it is Auto [de]serialized by UNET.
Implements MercuryMessaging.IMmResponder.
Reimplemented in MercuryMessaging.MmBaseResponder, MercuryMessaging.MmExtendableResponder, MercuryMessaging.MmQuickNode, MercuryMessaging.MmRelayNode, MercuryMessaging.MmTransformResponder, MercuryMessaging.StandardLibrary.Input.MmInputResponder, and MercuryMessaging.StandardLibrary.UI.MmUIResponder.
Definition at line 213 of file MmResponder.cs.
MmOnAwakeComplete()
virtual void MercuryMessaging.MmResponder.MmOnAwakeComplete () virtual
Post Awake callback used between objects implementing this interface.
This allows for initialization steps that must occur before one instance's Awake and its Start.
Implements MercuryMessaging.IMmResponder.
Definition at line 150 of file MmResponder.cs.
References MmAwakeCompleteCallback.
Referenced by Awake().
MmOnStartComplete()
virtual void MercuryMessaging.MmResponder.MmOnStartComplete () virtual
Post Start callback used between objects implementing this interface This allows for initialization steps that must occur before one instance's Start and its first Update.
Implements MercuryMessaging.IMmResponder.
Definition at line 161 of file MmResponder.cs.
References MmStartCompleteCallback.
Referenced by Start().
MmRegisterAwakeCompleteCallback()
virtual void MercuryMessaging.MmResponder.MmRegisterAwakeCompleteCallback (IMmCallback callback) virtual
It is possible that certain handles are not going to be in-place when registration of the OnAwakeComplete callback is invoked.
The is especially true in scenarios where MmRelayNodes are networked. This allows for a deferred registration, eliminating most instances where the Awake callback invocations fail.
Parameters
callback Callback to be registered.
Implements MercuryMessaging.IMmResponder.
Definition at line 175 of file MmResponder.cs.
References MercuryMessaging.IMmCallback(), and MmAwakeCompleteCallback.
MmRegisterStartCompleteCallback()
virtual void MercuryMessaging.MmResponder.MmRegisterStartCompleteCallback (IMmCallback callback) virtual
It is possible that certain handles are not going to be in-place when registration of the OnStartComplete callback is invoked.
The is especially true in scenarios where MmRelayNodes are networked. This allows for a deferred registration, eliminating most instances where the Start callback invocations fail.
Parameters
callback Callback to be registered.
Implements MercuryMessaging.IMmResponder.
Definition at line 188 of file MmResponder.cs.
References MercuryMessaging.IMmCallback(), and MmStartCompleteCallback.
Referenced by MercuryMessaging.MmSwitchResponder.Awake().
Start()
virtual void MercuryMessaging.MmResponder.Start () virtual
Start: Invokes MmOnStartComplete.
Reimplemented in MercuryMessaging.MmAppStateSwitchResponder, MercuryMessaging.MmRelayNode, MercuryMessaging.MmRelaySwitchNode, MercuryMessaging.MmSwitchResponder, and MercuryMessaging.Task.MmTaskManager< U >.
Definition at line 129 of file MmResponder.cs.
References MercuryMessaging.MmLogger.LogResponder, and MmOnStartComplete().
Update()
virtual void MercuryMessaging.MmResponder.Update () virtual
Base Update of MmResponder Derived classes should always override.
Reimplemented in MercuryMessaging.MmTransformResponder, and MercuryMessaging.Task.MmTaskResponder< T >.
Definition at line 140 of file MmResponder.cs.
Member Data Documentation
_mmTag
MmTag MercuryMessaging.MmResponder._mmTag = MmTagHelper.Everything private
Determines whether tag checking is enabled for this IMmResponder.
Definition at line 62 of file MmResponder.cs.
receiveHandledMessages
bool MercuryMessaging.MmResponder.receiveHandledMessages = false private
When true, this responder receives messages even if Handled=true.
Useful for logging, analytics, or handlers that need to see all messages. Default: false (responder skipped after message is handled). Similar to WPF's handledEventsToo parameter.
Definition at line 76 of file MmResponder.cs.
tagCheckEnabled
bool MercuryMessaging.MmResponder.tagCheckEnabled = true private
By default IMmResponders have this set to true so that they receive all messages.
Definition at line 68 of file MmResponder.cs.
Referenced by MercuryMessaging.MmRelayNode.MmAddToRoutingTable().
Property Documentation
MmGameObject
GameObject MercuryMessaging.MmResponder.MmGameObject get
Handle to an instance's GameObject.
Implements MercuryMessaging.IMmResponder.
Definition at line 81 of file MmResponder.cs.
ReceiveHandledMessages
bool MercuryMessaging.MmResponder.ReceiveHandledMessages get set
When true, this responder receives messages even if Handled=true.
Useful for logging, analytics, or handlers that need to see all messages.
Definition at line 110 of file MmResponder.cs.
Tag
MmTag MercuryMessaging.MmResponder.Tag get set
MmTags allow you to specify filters for execution in Mercury XM graphs.
Implements MercuryMessaging.IMmResponder.
Definition at line 90 of file MmResponder.cs.
Referenced by MercuryMessaging.MmTagExtensions.HasTag(), and MercuryMessaging.MmRelayNode.MmAddToRoutingTable().
TagCheckEnabled
bool MercuryMessaging.MmResponder.TagCheckEnabled get set
Determines whether tag checking is enabled for this IMmResponder.
Implements MercuryMessaging.IMmResponder.
Definition at line 100 of file MmResponder.cs.
Referenced by MercuryMessaging.MmRelayNode.MmAddToRoutingTable(), and MercuryMessaging.MmRelayNode.TagCheck().
Event Documentation
MmAwakeCompleteCallback
IMmCallback MercuryMessaging.MmResponder.MmAwakeCompleteCallback private
Event triggered in the MmResponder when this object is awoken.
Definition at line 50 of file MmResponder.cs.
Referenced by MmOnAwakeComplete(), and MmRegisterAwakeCompleteCallback().
MmStartCompleteCallback
IMmCallback MercuryMessaging.MmResponder.MmStartCompleteCallback private
Event triggered in the MmResponder when this object is started.
Definition at line 56 of file MmResponder.cs.
Referenced by MmOnStartComplete(), and MmRegisterStartCompleteCallback().
The documentation for this class was generated from the following file:
Protocol/Responders/MmResponder.cs