MercuryMessaging: MercuryMessaging.Network.MmWriter Class Reference
MercuryMessaging.Network.MmWriter Class Reference sealed
High-performance binary writer that uses ArrayPool for zero-allocation serialization.
Public Member Functions
void WriteByte (byte value)
void WriteSByte (sbyte value)
void WriteBool (bool value)
void WriteShort (short value)
void WriteUShort (ushort value)
void WriteInt (int value)
void WriteUInt (uint value)
void WriteLong (long value)
void WriteULong (ulong value)
void WriteFloat (float value)
void WriteDouble (double value)
void WriteString (string value)
Write a string with length prefix (ushort).
void WriteBytes (byte[] value)
Write a byte array with length prefix (int).
void WriteRawBytes (byte[] value, int offset, int count)
Write raw bytes without length prefix.
void WriteVector2 (Vector2 value)
void WriteVector3 (Vector3 value)
void WriteVector4 (Vector4 value)
void WriteQuaternion (Quaternion value)
void WriteColor (Color value)
void WriteColor32 (Color32 value)
byte[] ToArray ()
Get the written data as a new byte array.
ArraySegment< byte > AsSegment ()
Get access to the internal buffer segment.
void CopyTo (byte[] destination, int destinationOffset)
Copy written data to a destination array.
void Dispose ()
Static Public Member Functions
static MmWriter Get ()
Get a writer from the pool.
static MmWriter Get (int capacityHint)
Get a writer from the pool with initial capacity hint.
Properties
int Position [get]
Current write position (number of bytes written).
int Capacity [get]
Current buffer capacity.
Private Member Functions
MmWriter ()
void Reset ()
void EnsureCapacity (int additionalBytes)
Private Attributes
byte[] _buffer
int _position
bool _disposed
Static Private Attributes
const int DefaultCapacity = 256
const int MaxCapacity = 1024 * 1024
static readonly Encoding Utf8 = Encoding.UTF8
static readonly ObjectPool< MmWriter > Pool
Detailed Description
High-performance binary writer that uses ArrayPool for zero-allocation serialization.
Implements IDisposable to return the buffer to the pool.
Usage:
using (var writer = MmWriter.Get())
{
    writer.WriteInt(42);
    writer.WriteString("Hello");
    byte[] data = writer.ToArray(); // Only allocation is the final array
}
Definition at line 29 of file MmWriter.cs.
Constructor & Destructor Documentation
MmWriter()
MercuryMessaging.Network.MmWriter.MmWriter () private
Definition at line 68 of file MmWriter.cs.
References _buffer, _disposed, _position, and DefaultCapacity.
Referenced by Get(), and Get().
Member Function Documentation
AsSegment()
ArraySegment< byte > MercuryMessaging.Network.MmWriter.AsSegment ()
Get access to the internal buffer segment.
Valid only until writer is disposed.
Definition at line 332 of file MmWriter.cs.
References _buffer, and _position.
CopyTo()
void MercuryMessaging.Network.MmWriter.CopyTo (byte[] destination, int destinationOffset)
Copy written data to a destination array.
Definition at line 340 of file MmWriter.cs.
References _buffer, and _position.
Dispose()
void MercuryMessaging.Network.MmWriter.Dispose ()
Definition at line 384 of file MmWriter.cs.
References _buffer, _disposed, and Pool.
EnsureCapacity()
void MercuryMessaging.Network.MmWriter.EnsureCapacity (int additionalBytes) private
Definition at line 349 of file MmWriter.cs.
References _buffer, _position, and MaxCapacity.
Referenced by WriteBool(), WriteByte(), WriteBytes(), WriteDouble(), WriteFloat(), WriteInt(), WriteLong(), WriteRawBytes(), WriteSByte(), WriteShort(), WriteString(), WriteUInt(), WriteULong(), and WriteUShort().
Get() [1/2]
MmWriter MercuryMessaging.Network.MmWriter.Get () static
Get a writer from the pool.
Must be disposed when done.
Definition at line 51 of file MmWriter.cs.
References MmWriter(), and Pool.
Referenced by MercuryMessaging.Network.MmBinarySerializer.SerializePooled().
Get() [2/2]
MmWriter MercuryMessaging.Network.MmWriter.Get (int capacityHint) static
Get a writer from the pool with initial capacity hint.
Definition at line 59 of file MmWriter.cs.
References MmWriter(), and Pool.
Reset()
void MercuryMessaging.Network.MmWriter.Reset () private
Definition at line 75 of file MmWriter.cs.
References _buffer, _disposed, _position, and DefaultCapacity.
ToArray()
byte[] MercuryMessaging.Network.MmWriter.ToArray ()
Get the written data as a new byte array.
This is the only allocation in steady state.
Definition at line 321 of file MmWriter.cs.
References _buffer, and _position.
WriteBool()
void MercuryMessaging.Network.MmWriter.WriteBool (bool value)
Definition at line 110 of file MmWriter.cs.
References _buffer, _position, and EnsureCapacity().
Referenced by MercuryMessaging.Network.MmBinarySerializer.WriteObjectValuePooled(), MercuryMessaging.Network.MmBinarySerializer.WritePayloadPooled(), and MercuryMessaging.Network.MmBinarySerializer.WriteTransformDataPooled().
WriteByte()
void MercuryMessaging.Network.MmWriter.WriteByte (byte value)
Definition at line 98 of file MmWriter.cs.
References _buffer, _position, and EnsureCapacity().
Referenced by WriteColor32(), and MercuryMessaging.Network.MmBinarySerializer.WriteObjectValuePooled().
WriteBytes()
void MercuryMessaging.Network.MmWriter.WriteBytes (byte[] value)
Write a byte array with length prefix (int).
Definition at line 238 of file MmWriter.cs.
References _buffer, _position, EnsureCapacity(), and WriteInt().
Referenced by MercuryMessaging.Network.MmBinarySerializer.WritePayloadPooled().
WriteColor()
void MercuryMessaging.Network.MmWriter.WriteColor (Color value)
Definition at line 297 of file MmWriter.cs.
References WriteFloat().
WriteColor32()
void MercuryMessaging.Network.MmWriter.WriteColor32 (Color32 value)
Definition at line 305 of file MmWriter.cs.
References WriteByte().
WriteDouble()
void MercuryMessaging.Network.MmWriter.WriteDouble (double value)
Definition at line 185 of file MmWriter.cs.
References _buffer, _position, and EnsureCapacity().
Referenced by MercuryMessaging.Network.MmBinarySerializer.WriteObjectValuePooled().
WriteFloat()
void MercuryMessaging.Network.MmWriter.WriteFloat (float value)
Definition at line 174 of file MmWriter.cs.
References _buffer, _position, and EnsureCapacity().
Referenced by WriteColor(), MercuryMessaging.Network.MmBinarySerializer.WriteObjectValuePooled(), MercuryMessaging.Network.MmBinarySerializer.WritePayloadPooled(), WriteQuaternion(), WriteVector2(), WriteVector3(), and WriteVector4().
WriteInt()
void MercuryMessaging.Network.MmWriter.WriteInt (int value)
Definition at line 130 of file MmWriter.cs.
References _buffer, _position, and EnsureCapacity().
Referenced by WriteBytes(), MercuryMessaging.Network.MmBinarySerializer.WriteObjectValuePooled(), MercuryMessaging.Network.MmBinarySerializer.WritePayloadPooled(), MercuryMessaging.Network.MmBinarySerializer.WriteSerializableDataPooled(), and MercuryMessaging.Network.MmBinarySerializer.WriteTransformListDataPooled().
WriteLong()
void MercuryMessaging.Network.MmWriter.WriteLong (long value)
Definition at line 148 of file MmWriter.cs.
References _buffer, _position, and EnsureCapacity().
Referenced by MercuryMessaging.Network.MmBinarySerializer.WriteObjectValuePooled().
WriteQuaternion()
void MercuryMessaging.Network.MmWriter.WriteQuaternion (Quaternion value)
Definition at line 289 of file MmWriter.cs.
References WriteFloat().
Referenced by MercuryMessaging.Network.MmBinarySerializer.WritePayloadPooled(), MercuryMessaging.Network.MmBinarySerializer.WriteTransformDataPooled(), and MercuryMessaging.Network.MmBinarySerializer.WriteTransformListDataPooled().
WriteRawBytes()
void MercuryMessaging.Network.MmWriter.WriteRawBytes (byte[] value, int offset, int count)
Write raw bytes without length prefix.
Definition at line 255 of file MmWriter.cs.
References _buffer, _position, and EnsureCapacity().
WriteSByte()
void MercuryMessaging.Network.MmWriter.WriteSByte (sbyte value)
Definition at line 104 of file MmWriter.cs.
References _buffer, _position, and EnsureCapacity().
WriteShort()
void MercuryMessaging.Network.MmWriter.WriteShort (short value)
Definition at line 116 of file MmWriter.cs.
References _buffer, _position, and EnsureCapacity().
Referenced by MercuryMessaging.Network.MmBinarySerializer.WriteObjectValuePooled().
WriteString()
void MercuryMessaging.Network.MmWriter.WriteString (string value)
Write a string with length prefix (ushort).
Null strings are written as empty strings.
Definition at line 208 of file MmWriter.cs.
References _buffer, _position, EnsureCapacity(), Utf8, and WriteUShort().
Referenced by MercuryMessaging.Network.MmBinarySerializer.WriteObjectValuePooled(), MercuryMessaging.Network.MmBinarySerializer.WritePayloadPooled(), and MercuryMessaging.Network.MmBinarySerializer.WriteSerializableDataPooled().
WriteUInt()
void MercuryMessaging.Network.MmWriter.WriteUInt (uint value)
Definition at line 139 of file MmWriter.cs.
References _buffer, _position, and EnsureCapacity().
Referenced by MercuryMessaging.Network.MmBinarySerializer.WritePayloadPooled().
WriteULong()
void MercuryMessaging.Network.MmWriter.WriteULong (ulong value)
Definition at line 161 of file MmWriter.cs.
References _buffer, _position, and EnsureCapacity().
WriteUShort()
void MercuryMessaging.Network.MmWriter.WriteUShort (ushort value)
Definition at line 123 of file MmWriter.cs.
References _buffer, _position, and EnsureCapacity().
Referenced by MercuryMessaging.Network.MmBinarySerializer.WriteSerializableDataPooled(), WriteString(), and MercuryMessaging.Network.MmTypeRegistry.WriteTo().
WriteVector2()
void MercuryMessaging.Network.MmWriter.WriteVector2 (Vector2 value)
Definition at line 268 of file MmWriter.cs.
References WriteFloat().
WriteVector3()
void MercuryMessaging.Network.MmWriter.WriteVector3 (Vector3 value)
Definition at line 274 of file MmWriter.cs.
References WriteFloat().
Referenced by MercuryMessaging.Network.MmBinarySerializer.WritePayloadPooled(), MercuryMessaging.Network.MmBinarySerializer.WriteTransformDataPooled(), and MercuryMessaging.Network.MmBinarySerializer.WriteTransformListDataPooled().
WriteVector4()
void MercuryMessaging.Network.MmWriter.WriteVector4 (Vector4 value)
Definition at line 281 of file MmWriter.cs.
References WriteFloat().
Referenced by MercuryMessaging.Network.MmBinarySerializer.WritePayloadPooled().
Member Data Documentation
_buffer
byte [] MercuryMessaging.Network.MmWriter._buffer private
Definition at line 34 of file MmWriter.cs.
Referenced by MmWriter(), AsSegment(), CopyTo(), Dispose(), EnsureCapacity(), Reset(), ToArray(), WriteBool(), WriteByte(), WriteBytes(), WriteDouble(), WriteFloat(), WriteInt(), WriteLong(), WriteRawBytes(), WriteSByte(), WriteShort(), WriteString(), WriteUInt(), WriteULong(), and WriteUShort().
_disposed
bool MercuryMessaging.Network.MmWriter._disposed private
Definition at line 36 of file MmWriter.cs.
Referenced by MmWriter(), Dispose(), and Reset().
_position
int MercuryMessaging.Network.MmWriter._position private
Definition at line 35 of file MmWriter.cs.
Referenced by MmWriter(), AsSegment(), CopyTo(), EnsureCapacity(), Reset(), ToArray(), WriteBool(), WriteByte(), WriteBytes(), WriteDouble(), WriteFloat(), WriteInt(), WriteLong(), WriteRawBytes(), WriteSByte(), WriteShort(), WriteString(), WriteUInt(), WriteULong(), and WriteUShort().
DefaultCapacity
const int MercuryMessaging.Network.MmWriter.DefaultCapacity = 256 static private
Definition at line 31 of file MmWriter.cs.
Referenced by MmWriter(), and Reset().
MaxCapacity
const int MercuryMessaging.Network.MmWriter.MaxCapacity = 1024 * 1024 static private
Definition at line 32 of file MmWriter.cs.
Referenced by EnsureCapacity().
Pool
readonly ObjectPool<MmWriter> MercuryMessaging.Network.MmWriter.Pool static private
Initial value:
= new ObjectPool<MmWriter>(
            () => new MmWriter(),
            writer => writer.Reset()
        )
Definition at line 43 of file MmWriter.cs.
Referenced by Dispose(), Get(), and Get().
Utf8
readonly Encoding MercuryMessaging.Network.MmWriter.Utf8 = Encoding.UTF8 static private
Definition at line 39 of file MmWriter.cs.
Referenced by WriteString().
Property Documentation
Capacity
int MercuryMessaging.Network.MmWriter.Capacity get
Current buffer capacity.
Definition at line 94 of file MmWriter.cs.
Position
int MercuryMessaging.Network.MmWriter.Position get
Current write position (number of bytes written).
Definition at line 89 of file MmWriter.cs.
The documentation for this class was generated from the following file:
Protocol/Network/MmWriter.cs