MercuryMessaging: MercuryMessaging.MmQuickNode Class Reference
MercuryMessaging.MmQuickNode Class Reference
Modification of the standard MmRelayNode that allows skipping of standard checks to allow for faster propagation.
Public Member Functions
override void MmInvoke (MmMessage message)
Override the basic functionality of MmRelayNode to allow for faster processing by skipping checks.
MmDeferredRoutingBuilder Build ()
Deferred routing builder for conditional/delayed execution.
override void Awake ()
Grab attached MmNetworkResponder, if present.
override void Start ()
Calls MmOnStartComplete through MmResponder Start.
void UpdateMessages (MmMessage message)
Debug tracking for messages - tracks message flow through the hierarchy.
virtual MmRoutingTableItem MmAddToRoutingTable (MmResponder mmResponder, MmLevelFilter level)
Add an MmResponder to the MmRoutingTable, with level designation.
virtual MmRoutingTableItem MmAddToRoutingTable (MmResponder mmResponder, string newName)
Add an MmResponder to the MmRoutingTable, with level designation.
bool SetFastHandler (MmResponder responder, System.Action< MmMessage > handler)
Set a fast handler delegate for a responder in this relay node's routing table.
bool ClearFastHandler (MmResponder responder)
Clear the fast handler for a responder, reverting to virtual dispatch.
bool HasFastHandler (MmResponder responder)
Check if a responder has a fast handler registered.
void MmRefreshResponders ()
Grab all MmResponders attached to the same GameObject.
void RefreshParents ()
Iterates through RoutingTable list and assigns this MmRelayNode as a parent to child MmResponders.
virtual void MmAddNodeToList (GameObject go)
Given a GameObject, extract an MmRelayNode if present and add it to this MmRelayNode's Responder list.
virtual void AddParent (MmRelayNode parent)
Given an MmRelayNode, add it as parent to this instance's MmRoutingTable.
void ClearListeners ()
Removes all listeners from this relay node.
virtual void MmInvoke (MmMethod mmMethod, MmMetadataBlock metadataBlock=null)
Invoke an MmMethod with no parameter.
virtual void MmInvoke (MmMethod mmMethod, MmMessage param, MmMessageType msgType, MmMetadataBlock metadataBlock=null)
Invoke a general MmMethod with parameter: MmMessage.
virtual void MmInvoke (MmMethod mmMethod, bool param, MmMetadataBlock metadataBlock=null)
Invoke an MmMethod with parameter: bool.
virtual void MmInvoke (MmMethod mmMethod, int param, MmMetadataBlock metadataBlock=null)
Invoke an MmMethod with parameter: int.
virtual void MmInvoke (MmMethod mmMethod, float param, MmMetadataBlock metadataBlock=null)
Invoke an MmMethod with parameter: float.
virtual void MmInvoke (MmMethod mmMethod, Vector3 param, MmMetadataBlock metadataBlock=null)
Invoke an MmMethod with parameter: Vector3.
virtual void MmInvoke (MmMethod mmMethod, Vector4 param, MmMetadataBlock metadataBlock=null)
Invoke an MmMethod with parameter: Vector4.
virtual void MmInvoke (MmMethod mmMethod, string param, MmMetadataBlock metadataBlock=null)
Invoke an MmMethod with parameter: string.
virtual void MmInvoke (MmMethod mmMethod, byte[] param, MmMetadataBlock metadataBlock=null)
Invoke an MmMethod with parameter: byte array.
virtual void MmInvoke (MmMethod mmMethod, MmTransform param, MmMetadataBlock metadataBlock=null)
Invoke an MmMethod with parameter: MmTransform.
virtual void MmInvoke (MmMethod mmMethod, List< MmTransform > param, MmMetadataBlock metadataBlock=null)
Invoke an MmMethod with parameter: List<MmTransform>.
virtual void MmInvoke (MmMethod mmMethod, IMmSerializable param, MmMetadataBlock metadataBlock=null)
Invoke an MmMethod with parameter: IMmSerializable.
virtual void MmInvoke (MmMethod mmMethod, GameObject param, MmMetadataBlock metadataBlock=null)
Invoke an MmMethod with parameter: GameObject.
virtual void MmInvoke (MmMethod mmMethod, Quaternion param, MmMetadataBlock metadataBlock=null)
Invoke an MmMethod with parameter: Quaternion.
virtual void MmInvokeWithPath (string path, MmMethod mmMethod, MmMetadataBlock metadataBlock=null)
Invokes a message using path specification for hierarchical routing.
virtual void MmInvokeWithPath (string path, MmMethod mmMethod, bool param, MmMetadataBlock metadataBlock=null)
Invokes a message with boolean parameter using path specification.
virtual void MmInvokeWithPath (string path, MmMethod mmMethod, int param, MmMetadataBlock metadataBlock=null)
Invokes a message with int parameter using path specification.
virtual void MmInvokeWithPath (string path, MmMethod mmMethod, string param, MmMetadataBlock metadataBlock=null)
Invokes a message with string parameter using path specification.
virtual void MmInvokeWithPath (string path, MmMessage message)
Invokes a pre-created message using path specification.
override MmRelayNode GetRelayNode ()
Implementation of IMmResponder's GetRelayNode, which returns this.
virtual List< MmRelayNode > ResolvePathTargets (string path)
Resolves a path specification string to a list of target relay nodes.
virtual void Update ()
Base Update of MmResponder Derived classes should always override.
virtual void MmOnAwakeComplete ()
Post Awake callback used between objects implementing this interface.
virtual void MmOnStartComplete ()
Post Start callback used between objects implementing this interface This allows for initialization steps that must occur before one instance's Start and its first Update.
virtual void MmRegisterAwakeCompleteCallback (IMmCallback callback)
It is possible that certain handles are not going to be in-place when registration of the OnAwakeComplete callback is invoked.
virtual void MmRegisterStartCompleteCallback (IMmCallback callback)
It is possible that certain handles are not going to be in-place when registration of the OnStartComplete callback is invoked.
Static Public Member Functions
static MmRelayNode GetRelayNode (IMmResponder iMmResponder)
Given an MmResponder, extract an MmRelayNode from it's GameObject, if one is present.
static MmRelayNode GetRelayNode (GameObject go)
Given a GameObject, extract the first MmRelayNode, if any are present.
Public Attributes
bool AllowStandardMmInvoke = false
MmRoutingChecks EnabledChecks = MmRoutingChecks.All
Controls which routing checks are performed during message dispatch.
Vector2 nodePosition = new Vector2(0, 0)
int layer
int messageHistorySize = 100
Size of the message history circular buffers.
MmCircularBuffer< string > messageInList
MmCircularBuffer< string > messageOutList
int maxMessageHops = 50
Maximum number of relay hops a message can make before being dropped.
bool enableCycleDetection = true
Enable cycle detection by tracking visited nodes.
Transform positionOffset
Queue< MmRoutingTableItem > MmRespondersToAdd
Queue of MmResponders to add once list is no longer in use by an MmInvoke.
bool doNotModifyRoutingTable
Flag to protect priority list from being modified while it's being iterated over.
bool FlipNetworkFlagOnSend = false
Does the node convert the message to a local message from networked on post send in order to guarantee that it does not send it over the network deeper in the hierarchy.
bool AllowNetworkPropagationLocally = false
Allows Node to pass a Network-only message into the hierarchy.
bool ReparentClonedRespondersToSelf = true
Indicates whether cloned MmResponders should be added as children to the MmRelayNode's GameObject.
bool Initialized
Indicates whether the MmRelayNode is ready for use This gets set either in Awake or on the first MmInvoke.
bool AutoGrabAttachedResponders = true
There may be an issue where a message is received before self responders have been added to the list.
MmRoutingTable RoutingTable
List of associated Mercury Responders.
Static Public Attributes
static bool PerformanceMode = false
Performance Mode - disables debug message tracking overhead.
static bool StrictMode = false
Strict Mode - enables fail-fast behavior for debugging.
Protected Member Functions
void InitializeNode ()
virtual MmLevelFilter LevelFilterAdjust (ref MmMessage message, MmLevelFilter direction)
If the level filter is designated 'Child', then it is recorded locally, but converted to a 'Child+Self' for use by the RoutingTable (which need to pass the message on to all children, but still need to be able to execute the message on their own responders, otherwise, it just goes to the terminal points of the graph without ever executing).
virtual MmActiveFilter ActiveFilterAdjust (ref MmMessage message)
Allows modification of active filter in message as it gets passed between MmRelayNodes.
virtual MmSelectedFilter SelectedFilterAdjust (ref MmMessage message)
Allows modification of selected filter in message as it gets passed between MmRelayNodes.
virtual MmNetworkFilter NetworkFilterAdjust (ref MmMessage message)
Allows modification of network filter in message as it gets passed between MmRelayNodes.
virtual bool ResponderCheck (MmLevelFilter levelFilter, MmActiveFilter activeFilter, MmSelectedFilter selectedFilter, MmNetworkFilter networkFilter, MmRoutingTableItem mmRoutingTableItem, MmMessage message)
This method determines if a particular MmResponder should receive a message via MmInvoke.
virtual bool TagCheck (MmRoutingTableItem mmRoutingTableItem, MmMessage message)
Determine if MmResponder passes MmRelayNode tag filter check using value embedded in MmMessage.
virtual bool LevelCheck (MmLevelFilter levelFilter, IMmResponder responder, MmLevelFilter responderLevel)
Determine if MmResponder passes MmRelayNode level filter check using value embedded in MmMessage.
virtual bool ActiveCheck (MmActiveFilter activeFilter, IMmResponder responder)
Determine if MmResponder passes MmRelayNode active filter check using value embedded in MmMessage.
virtual bool SelectedCheck (MmSelectedFilter selectedFilter, IMmResponder responder)
Determine if MmResponder passes MmRelayNode selected filter check using value embedded in MmMessage.
virtual bool NetworkCheck (MmRoutingTableItem mmRoutingTableItem, MmMessage message)
Checks if a responder should recieve a message based on the network flag in a control block.
virtual void HandleAdvancedRouting (MmMessage message, MmLevelFilter levelFilter)
Handles advanced routing for Phase 2.1 level filters.
virtual void HandleParentRouting (MmMessage message)
Routes message to direct parent relay nodes only.
virtual void CollectSiblings (List< MmRelayNode > siblings)
Collects sibling relay nodes (nodes sharing the same parent).
virtual void CollectCousins (List< MmRelayNode > cousins)
Collects cousin relay nodes (parent's siblings' children).
virtual void CollectDescendants (List< MmRelayNode > descendants, HashSet< int > visited=null)
Collects all descendant relay nodes recursively (all children, grandchildren, etc.).
virtual void CollectAncestors (List< MmRelayNode > ancestors, HashSet< int > visited=null)
Collects all ancestor relay nodes recursively (all parents, grandparents, etc.).
virtual void RouteLateral (MmMessage message, bool includeSiblings, bool includeCousins)
Routes message to lateral relatives (siblings/cousins).
virtual void RouteRecursive (MmMessage message, bool useDescendants)
Routes message to recursive descendants or ancestors.
virtual List< MmRelayNode > ApplyCustomFilter (System.Func< MmRelayNode, bool > customFilter)
Applies custom predicate filtering to routing table items.
Package Functions
void AddListener< T > (MmListenerSubscription< T > subscription)
Adds a typed listener subscription to this relay node.
void RemoveListener< T > (MmListenerSubscription< T > subscription)
Removes a typed listener subscription from this relay node.
Properties
IMmNetworkResponder MmNetworkResponder [get, private set]
Associated MmNetworkResponder.
MmRoutingBuilder To [get]
Property-based routing builder for shorter DSL syntax.
bool HasTagCheckEnabledResponders [get]
Cache whether we need to perform tag checks at all.
int ListenerCount [get]
Gets the number of active listeners on this relay node.
string Name [get]
MmRelayNode name: returns GameObject name.
GameObject MmGameObject [get]
Handle to an instance's GameObject.
MmTag Tag [get, set]
MmTags allow you to specify filters for execution in Mercury XM graphs.
bool TagCheckEnabled [get, set]
Determines whether tag checking is enabled for this IMmResponder.
bool ReceiveHandledMessages [get, set]
When true, this responder receives messages even if Handled=true.
Events
IMmCallback MmAwakeCompleteCallback
Event triggered in the MmResponder when this object is awoken.
IMmCallback MmStartCompleteCallback
Event triggered in the MmResponder when this object is started.
Private Member Functions
void UpdateItemAndPropagate (MmRoutingTableItem item, MmMessage message)
Part of debug tracking - updates message lists and propagates.
void InstantiateSubResponders ()
Iterate over RoutingTable items and instantiate any GameObjects that were marked as needing instantiating by the MmRoutingTable's creator.
void NotifyListeners (MmMessage message)
Notifies all registered listeners about a received message.
List< MmRelayNode > NavigateSegment (MmRelayNode node, PathSegment segment, HashSet< int > visited)
Navigates from a node according to a path segment.
Private Attributes
List< MmRelayNode > MmParentList
Parents of this relay node.
bool _executing
Indicates whether MmInvoke is currently executing a call.
int _tagCheckEnabledCount = 0
Tracks how many responders in the routing table have TagCheckEnabled.
List< IMmListenerSubscription > _listeners
DSL Phase 2.1: Listener registry for external message subscriptions.
MmTag _mmTag = MmTagHelper.Everything
Determines whether tag checking is enabled for this IMmResponder.
bool tagCheckEnabled = true
By default IMmResponders have this set to true so that they receive all messages.
bool receiveHandledMessages = false
When true, this responder receives messages even if Handled=true.
Detailed Description
Modification of the standard MmRelayNode that allows skipping of standard checks to allow for faster propagation.
OBSOLETE: Use MmRelayNode with EnabledChecks = MmRoutingChecks.None instead. This provides the same behavior (bypassing all routing checks) with more granular control.
Definition at line 48 of file MmQuickNode.cs.
Member Function Documentation
ActiveCheck()
virtual bool MercuryMessaging.MmRelayNode.ActiveCheck (MmActiveFilter activeFilter, IMmResponder responder) protected virtual inherited
Determine if MmResponder passes MmRelayNode active filter check using value embedded in MmMessage.
Parameters
activeFilter Active filter value extracted from MmMessage.
responder Observed MmResponder
Returns
Returns whether observed MmResponder has passed active filter check.
Definition at line 1647 of file MmRelayNode.cs.
References MercuryMessaging.IMmResponder.MmGameObject.
Referenced by ResponderCheck().
ActiveFilterAdjust()
virtual MmActiveFilter MercuryMessaging.MmRelayNode.ActiveFilterAdjust (ref MmMessage message) protected virtual inherited
Allows modification of active filter in message as it gets passed between MmRelayNodes.
Parameters
message MmMessage to be adjusted.
Returns
Base implementation returns messages's active filter.
Definition at line 1493 of file MmRelayNode.cs.
Referenced by MmInvoke().
AddListener< T >()
void MercuryMessaging.MmRelayNode.AddListener< T > (MmListenerSubscription< T > subscription) package inherited
Adds a typed listener subscription to this relay node.
Called internally by MmListenerBuilder.Execute().
Template Parameters
T The message type the listener handles.
Parameters
subscription The subscription to add.
Type Constraints
T : MmMessage
Definition at line 711 of file MmRelayNode.cs.
References _listeners.
AddParent()
virtual void MercuryMessaging.MmRelayNode.AddParent (MmRelayNode parent) virtual inherited
Given an MmRelayNode, add it as parent to this instance's MmRoutingTable.
Parameters
parent MmRelayNode to add as a parent.
Definition at line 693 of file MmRelayNode.cs.
References MmRelayNode(), MmAddToRoutingTable(), and MmParentList.
Referenced by MmAddToRoutingTable(), MercuryMessaging.MmHierarchyExtensions.MmSetParent(), MercuryMessaging.MmRoutingExtensions.RegisterWith(), MercuryMessaging.MmRoutingExtensions.RegisterWith(), MercuryMessaging.MmRoutingExtensions.RegisterWith(), and MercuryMessaging.MmHierarchyExtensions.ReparentTo().
ApplyCustomFilter()
virtual List< MmRelayNode > MercuryMessaging.MmRelayNode.ApplyCustomFilter (System.Func< MmRelayNode, bool > customFilter) protected virtual inherited
Applies custom predicate filtering to routing table items.
Part of Phase 2.1: Advanced Message Routing.
Parameters
customFilter Predicate function to apply
Returns
Filtered list of relay nodes
Definition at line 2045 of file MmRelayNode.cs.
References MmRelayNode(), and RoutingTable.
Referenced by HandleAdvancedRouting().
Awake()
override void MercuryMessaging.MmRelayNode.Awake () virtual inherited
Grab attached MmNetworkResponder, if present.
Detect and refresh parents. Instantiate any cloneable MmResponders.
Reimplemented from MercuryMessaging.MmResponder.
Reimplemented in MercuryMessaging.MmRelaySwitchNode.
Definition at line 334 of file MmRelayNode.cs.
References InitializeNode(), InstantiateSubResponders(), MercuryMessaging.MmLogger.LogFramework, messageHistorySize, messageInList, messageOutList, and MmNetworkResponder.
Build()
MmDeferredRoutingBuilder MercuryMessaging.MmRelayNode.Build () inherited
Deferred routing builder for conditional/delayed execution.
Unlike To which auto-executes, Build() requires explicit Execute(). Enables: var msg = relay.Build().ToChildren().Send("Hello"); if (ready) msg.Execute();
ClearFastHandler()
bool MercuryMessaging.MmRelayNode.ClearFastHandler (MmResponder responder) inherited
Clear the fast handler for a responder, reverting to virtual dispatch.
Parameters
responder The responder to clear the handler for.
Returns
True if handler was cleared, false if responder not found.
Definition at line 554 of file MmRelayNode.cs.
References SetFastHandler().
ClearListeners()
void MercuryMessaging.MmRelayNode.ClearListeners () inherited
Removes all listeners from this relay node.
Definition at line 750 of file MmRelayNode.cs.
References _listeners.
Referenced by MercuryMessaging.MmListenerExtensions.ClearAllListeners(), and MercuryMessaging.MmListenerExtensions.ClearAllListeners().
CollectAncestors()
virtual void MercuryMessaging.MmRelayNode.CollectAncestors (List< MmRelayNode > ancestors, HashSet< int > visited = null) protected virtual inherited
Collects all ancestor relay nodes recursively (all parents, grandparents, etc.).
Used for upward tree traversal (MmLevelFilter.Ancestors).
Parameters
ancestors Output list to populate with ancestor nodes
visited Set of visited nodes to prevent infinite loops
Definition at line 1945 of file MmRelayNode.cs.
References MmParentList.
Referenced by NavigateSegment(), and RouteRecursive().
CollectCousins()
virtual void MercuryMessaging.MmRelayNode.CollectCousins (List< MmRelayNode > cousins) protected virtual inherited
Collects cousin relay nodes (parent's siblings' children).
Used for extended family routing (MmLevelFilter.Cousins).
Parameters
cousins Output list to populate with cousin nodes
Definition at line 1864 of file MmRelayNode.cs.
References MmParentList.
Referenced by RouteLateral().
CollectDescendants()
virtual void MercuryMessaging.MmRelayNode.CollectDescendants (List< MmRelayNode > descendants, HashSet< int > visited = null) protected virtual inherited
Collects all descendant relay nodes recursively (all children, grandchildren, etc.).
Used for deep tree traversal (MmLevelFilter.Descendants).
Parameters
descendants Output list to populate with descendant nodes
visited Set of visited nodes to prevent infinite loops
Definition at line 1908 of file MmRelayNode.cs.
References RoutingTable.
Referenced by NavigateSegment(), and RouteRecursive().
CollectSiblings()
virtual void MercuryMessaging.MmRelayNode.CollectSiblings (List< MmRelayNode > siblings) protected virtual inherited
Collects sibling relay nodes (nodes sharing the same parent).
Used for lateral routing (MmLevelFilter.Siblings).
Parameters
siblings Output list to populate with sibling nodes
Definition at line 1830 of file MmRelayNode.cs.
References MmParentList.
Referenced by NavigateSegment(), and RouteLateral().
GetRelayNode() [1/3]
override MmRelayNode MercuryMessaging.MmRelayNode.GetRelayNode () inherited
Implementation of IMmResponder's GetRelayNode, which returns this.
Returns
Returns this MmRelayNode.
Implements MercuryMessaging.IMmResponder.
Definition at line 1704 of file MmRelayNode.cs.
References MmRelayNode().
GetRelayNode() [2/3]
MmRelayNode MercuryMessaging.MmRelayNode.GetRelayNode (GameObject go) static inherited
Given a GameObject, extract the first MmRelayNode, if any are present.
Parameters
go Observed GameObject.
Returns
First MmRelayNode on object, if any present.
Definition at line 2271 of file MmRelayNode.cs.
References MmRelayNode().
GetRelayNode() [3/3]
MmRelayNode MercuryMessaging.MmRelayNode.GetRelayNode (IMmResponder iMmResponder) static inherited
Given an MmResponder, extract an MmRelayNode from it's GameObject, if one is present.
Parameters
iMmResponder Observed MmResponder
Returns
an MmRelayNode if one is present on the same GameObject.
Definition at line 2252 of file MmRelayNode.cs.
References MmRelayNode(), and MercuryMessaging.MmLogger.LogError.
HandleAdvancedRouting()
virtual void MercuryMessaging.MmRelayNode.HandleAdvancedRouting (MmMessage message, MmLevelFilter levelFilter) protected virtual inherited
Handles advanced routing for Phase 2.1 level filters.
Processes Siblings, Cousins, Descendants, Ancestors, and Custom filters.
Parameters
message Message to route
levelFilter Level filter from message
Definition at line 1719 of file MmRelayNode.cs.
References MercuryMessaging.MmRoutingOptions.AllowLateralRouting, ApplyCustomFilter(), MercuryMessaging.MmMessage.Copy(), MercuryMessaging.MmRoutingOptions.CustomFilter, HandleParentRouting(), MercuryMessaging.MmLogger.LogFramework, MercuryMessaging.MmMessage.MetadataBlock, MercuryMessaging.MmMetadataBlock.Options, RouteLateral(), RouteRecursive(), and StrictMode.
Referenced by MmInvoke().
HandleParentRouting()
virtual void MercuryMessaging.MmRelayNode.HandleParentRouting (MmMessage message) protected virtual inherited
Routes message to direct parent relay nodes only.
Part of Phase 2.1: Advanced Message Routing - handles MmLevelFilter.Parent.
Parameters
message Message to route to parents
Definition at line 1806 of file MmRelayNode.cs.
References MmParentList.
Referenced by HandleAdvancedRouting().
HasFastHandler()
bool MercuryMessaging.MmRelayNode.HasFastHandler (MmResponder responder) inherited
Check if a responder has a fast handler registered.
Parameters
responder The responder to check.
Returns
True if responder has a handler, false otherwise.
Definition at line 564 of file MmRelayNode.cs.
References RoutingTable.
InitializeNode()
void MercuryMessaging.MmRelayNode.InitializeNode () protected inherited
Definition at line 428 of file MmRelayNode.cs.
References AutoGrabAttachedResponders, Initialized, MmRefreshResponders(), and RefreshParents().
Referenced by Awake(), MercuryMessaging.MmQuickNode.MmInvoke(), and MmInvoke().
InstantiateSubResponders()
void MercuryMessaging.MmRelayNode.InstantiateSubResponders () private inherited
Iterate over RoutingTable items and instantiate any GameObjects that were marked as needing instantiating by the MmRoutingTable's creator.
Definition at line 445 of file MmRelayNode.cs.
References ReparentClonedRespondersToSelf, and RoutingTable.
Referenced by Awake().
LevelCheck()
virtual bool MercuryMessaging.MmRelayNode.LevelCheck (MmLevelFilter levelFilter, IMmResponder responder, MmLevelFilter responderLevel) protected virtual inherited
Determine if MmResponder passes MmRelayNode level filter check using value embedded in MmMessage.
Parameters
levelFilter Level filter value extracted from MmMessage.
responder Observed MmResponder.
responderLevel Observed MmResponder Level.
Returns
Returns whether observed MmResponder has passed level filter check.
Definition at line 1635 of file MmRelayNode.cs.
LevelFilterAdjust()
virtual MmLevelFilter MercuryMessaging.MmRelayNode.LevelFilterAdjust (ref MmMessage message, MmLevelFilter direction) protected virtual inherited
If the level filter is designated 'Child', then it is recorded locally, but converted to a 'Child+Self' for use by the RoutingTable (which need to pass the message on to all children, but still need to be able to execute the message on their own responders, otherwise, it just goes to the terminal points of the graph without ever executing).
Parameters
message MmMessage to be adjusted.
direction Intended direction of message
Returns
Base implementation returns messages's level filter.
Definition at line 1481 of file MmRelayNode.cs.
MmAddNodeToList()
virtual void MercuryMessaging.MmRelayNode.MmAddNodeToList (GameObject go) virtual inherited
Given a GameObject, extract an MmRelayNode if present and add it to this MmRelayNode's Responder list.
Parameters
go GameObject that should have an MmRelayNode attached.
Definition at line 678 of file MmRelayNode.cs.
References MmRelayNode(), MercuryMessaging.MmLogger.LogError, and MmAddToRoutingTable().
MmAddToRoutingTable() [1/2]
virtual MmRoutingTableItem MercuryMessaging.MmRelayNode.MmAddToRoutingTable (MmResponder mmResponder, MmLevelFilter level) virtual inherited
Add an MmResponder to the MmRoutingTable, with level designation.
Parameters
mmResponder MmResponder to be added.
level Level designation of responder.
Returns
Reference to new MmRoutingTable item.
Definition at line 471 of file MmRelayNode.cs.
References _tagCheckEnabledCount, doNotModifyRoutingTable, MercuryMessaging.Level, MmRespondersToAdd, RoutingTable, MercuryMessaging.MmResponder.Tag, MercuryMessaging.MmResponder.TagCheckEnabled, and MercuryMessaging.MmResponder.tagCheckEnabled.
Referenced by MercuryMessaging.MmHierarchyExtensions.AddChildNode(), AddParent(), MercuryMessaging.MmHierarchyExtensions.AddSwitchChild(), MmAddNodeToList(), MmAddToRoutingTable(), MmInvoke(), MmRefreshResponders(), MercuryMessaging.MmHierarchyExtensions.MmSetParent(), RefreshParents(), MercuryMessaging.MmRoutingExtensions.RegisterWith(), MercuryMessaging.MmRoutingExtensions.RegisterWith(), MercuryMessaging.MmRoutingExtensions.RegisterWith(), and MercuryMessaging.MmHierarchyExtensions.ReparentTo().
MmAddToRoutingTable() [2/2]
virtual MmRoutingTableItem MercuryMessaging.MmRelayNode.MmAddToRoutingTable (MmResponder mmResponder, string newName) virtual inherited
Add an MmResponder to the MmRoutingTable, with level designation.
Parameters
mmResponder MmResponder to be added.
newName Name of MmResponder as it will appear in list.
Returns
Reference to new MmRoutingTable item.
Definition at line 509 of file MmRelayNode.cs.
References MmRelayNode(), AddParent(), and MmAddToRoutingTable().
MmInvoke() [1/15]
override void MercuryMessaging.MmQuickNode.MmInvoke (MmMessage message) virtual
Override the basic functionality of MmRelayNode to allow for faster processing by skipping checks.
Parameters
msgType Type of message. This specifies the type of the payload. This is important in networked scenarios, when proper deseriaization into the correct type requires knowing what was used to serialize the object originally.
message The message to send. This class builds on UNET's MessageBase so it is Auto [de]serialized by UNET.
Reimplemented from MercuryMessaging.MmResponder.
Definition at line 63 of file MmQuickNode.cs.
References MercuryMessaging.MmRelayNode.AllowNetworkPropagationLocally, AllowStandardMmInvoke, MercuryMessaging.MmRelayNode.InitializeNode(), MercuryMessaging.MmMessage.IsDeserialized, MercuryMessaging.MmMessage.MetadataBlock, MercuryMessaging.MmNetworkResponder.MmInvoke(), MercuryMessaging.MmRelayNode.MmNetworkResponder, MercuryMessaging.MmMetadataBlock.NetworkFilter, MercuryMessaging.MmRelayNode.NetworkFilterAdjust(), and MercuryMessaging.MmRelayNode.RoutingTable.
MmInvoke() [2/15]
virtual void MercuryMessaging.MmRelayNode.MmInvoke (MmMethod mmMethod, bool param, MmMetadataBlock metadataBlock = null) virtual inherited
Invoke an MmMethod with parameter: bool.
Parameters
mmMethod MmMethod Identifier - MmMethod
param MmMethod parameter: bool.
metadataBlock Object defining the routing of Mmessages through MercuryMessaging Hierarchies. MmMetadataBlock
Implements MercuryMessaging.IMmNode.
Definition at line 1122 of file MmRelayNode.cs.
References MercuryMessaging.MmMessagePool.GetBool(), MmInvoke(), and MercuryMessaging.MmMessagePool.Return().
MmInvoke() [3/15]
virtual void MercuryMessaging.MmRelayNode.MmInvoke (MmMethod mmMethod, byte[] param, MmMetadataBlock metadataBlock = null) virtual inherited
Invoke an MmMethod with parameter: byte array.
Parameters
mmMethod MmMethod Identifier - MmMethod
param MmMethod parameter: byte array.
metadataBlock Object defining the routing of Mmessages through MercuryMessaging Hierarchies. MmMetadataBlock
Implements MercuryMessaging.IMmNode.
Definition at line 1218 of file MmRelayNode.cs.
References MercuryMessaging.MmMessagePool.GetByteArray(), MmInvoke(), and MercuryMessaging.MmMessagePool.Return().
MmInvoke() [4/15]
virtual void MercuryMessaging.MmRelayNode.MmInvoke (MmMethod mmMethod, float param, MmMetadataBlock metadataBlock = null) virtual inherited
Invoke an MmMethod with parameter: float.
Parameters
mmMethod MmMethod Identifier - MmMethod
param MmMethod parameter: float.
metadataBlock Object defining the routing of Mmessages through MercuryMessaging Hierarchies. MmMetadataBlock
Implements MercuryMessaging.IMmNode.
Definition at line 1154 of file MmRelayNode.cs.
References MercuryMessaging.MmMessagePool.GetFloat(), MmInvoke(), and MercuryMessaging.MmMessagePool.Return().
MmInvoke() [5/15]
virtual void MercuryMessaging.MmRelayNode.MmInvoke (MmMethod mmMethod, GameObject param, MmMetadataBlock metadataBlock = null) virtual inherited
Invoke an MmMethod with parameter: GameObject.
Parameters
mmMethod MmMethod Identifier - MmMethod
param MmMethod parameter: GameObject. MmMessage
metadataBlock Object defining the routing of Mmessages through MercuryMessaging Hierarchies. MmMetadataBlock
Definition at line 1281 of file MmRelayNode.cs.
References MercuryMessaging.MmMessagePool.GetGameObject(), MmInvoke(), and MercuryMessaging.MmMessagePool.Return().
MmInvoke() [6/15]
virtual void MercuryMessaging.MmRelayNode.MmInvoke (MmMethod mmMethod, IMmSerializable param, MmMetadataBlock metadataBlock = null) virtual inherited
Invoke an MmMethod with parameter: IMmSerializable.
Parameters
mmMethod MmMethod Identifier - MmMethod
param MmMethod parameter: IMmSerializable. IMmSerializable
metadataBlock Object defining the routing of Mmessages through MercuryMessaging Hierarchies. MmMetadataBlock
Implements MercuryMessaging.IMmNode.
Definition at line 1266 of file MmRelayNode.cs.
References MercuryMessaging.MmMessagePool.GetSerializable(), MmInvoke(), and MercuryMessaging.MmMessagePool.Return().
MmInvoke() [7/15]
virtual void MercuryMessaging.MmRelayNode.MmInvoke (MmMethod mmMethod, int param, MmMetadataBlock metadataBlock = null) virtual inherited
Invoke an MmMethod with parameter: int.
Parameters
mmMethod MmMethod Identifier - MmMethod
param MmMethod parameter: int.
metadataBlock Object defining the routing of Mmessages through MercuryMessaging Hierarchies. MmMetadataBlock
Implements MercuryMessaging.IMmNode.
Definition at line 1138 of file MmRelayNode.cs.
References MercuryMessaging.MmMessagePool.GetInt(), MmInvoke(), and MercuryMessaging.MmMessagePool.Return().
MmInvoke() [8/15]
virtual void MercuryMessaging.MmRelayNode.MmInvoke (MmMethod mmMethod, List< MmTransform > param, MmMetadataBlock metadataBlock = null) virtual inherited
Invoke an MmMethod with parameter: List<MmTransform>.
Parameters
mmMethod MmMethod Identifier - MmMethod
param MmMethod parameter: List<MmTransform>.
metadataBlock Object defining the routing of Mmessages through MercuryMessaging Hierarchies. MmMetadataBlock
Implements MercuryMessaging.IMmNode.
Definition at line 1250 of file MmRelayNode.cs.
References MercuryMessaging.MmMessagePool.GetTransformList(), MmInvoke(), and MercuryMessaging.MmMessagePool.Return().
MmInvoke() [9/15]
virtual void MercuryMessaging.MmRelayNode.MmInvoke (MmMethod mmMethod, MmMessage param, MmMessageType msgType, MmMetadataBlock metadataBlock = null) virtual inherited
Invoke a general MmMethod with parameter: MmMessage.
Parameters
mmMethod MmMethod Identifier - MmMethod
param MmMethod parameter: MmMessage. MmMessage
metadataBlock Object defining the routing of Mmessages through MercuryMessaging Hierarchies. MmMetadataBlock
Implements MercuryMessaging.IMmNode.
Definition at line 1104 of file MmRelayNode.cs.
References MercuryMessaging.MmMessage.Copy(), and MmInvoke().
MmInvoke() [10/15]
virtual void MercuryMessaging.MmRelayNode.MmInvoke (MmMethod mmMethod, MmMetadataBlock metadataBlock = null) virtual inherited
Invoke an MmMethod with no parameter.
Parameters
mmMethod MmMethod Identifier - MmMethod
metadataBlock Object defining the routing of Mmessages through MercuryMessaging Hierarchies. MmMetadataBlock
Implements MercuryMessaging.IMmNode.
Definition at line 1090 of file MmRelayNode.cs.
References MercuryMessaging.MmMessagePool.Get(), MmInvoke(), and MercuryMessaging.MmMessagePool.Return().
MmInvoke() [11/15]
virtual void MercuryMessaging.MmRelayNode.MmInvoke (MmMethod mmMethod, MmTransform param, MmMetadataBlock metadataBlock = null) virtual inherited
Invoke an MmMethod with parameter: MmTransform.
Parameters
mmMethod MmMethod Identifier - MmMethod
param MmMethod parameter: MmTransform. MmTransform
metadataBlock Object defining the routing of Mmessages through MercuryMessaging Hierarchies. MmMetadataBlock
Implements MercuryMessaging.IMmNode.
Definition at line 1234 of file MmRelayNode.cs.
References MercuryMessaging.MmMessagePool.GetTransform(), MmInvoke(), and MercuryMessaging.MmMessagePool.Return().
MmInvoke() [12/15]
virtual void MercuryMessaging.MmRelayNode.MmInvoke (MmMethod mmMethod, Quaternion param, MmMetadataBlock metadataBlock = null) virtual inherited
Invoke an MmMethod with parameter: Quaternion.
Parameters
mmMethod MmMethod Identifier - MmMethod
param MmMethod parameter: Quaternion.
metadataBlock Object defining the routing of Mmessages through MercuryMessaging Hierarchies. MmMetadataBlock
Definition at line 1297 of file MmRelayNode.cs.
References MercuryMessaging.MmMessagePool.GetQuaternion(), MmInvoke(), and MercuryMessaging.MmMessagePool.Return().
MmInvoke() [13/15]
virtual void MercuryMessaging.MmRelayNode.MmInvoke (MmMethod mmMethod, string param, MmMetadataBlock metadataBlock = null) virtual inherited
Invoke an MmMethod with parameter: string.
Parameters
mmMethod MmMethod Identifier - MmMethod
param MmMethod parameter: string.
metadataBlock Object defining the routing of Mmessages through MercuryMessaging Hierarchies. MmMetadataBlock
Implements MercuryMessaging.IMmNode.
Definition at line 1202 of file MmRelayNode.cs.
References MercuryMessaging.MmMessagePool.GetString(), MmInvoke(), and MercuryMessaging.MmMessagePool.Return().
MmInvoke() [14/15]
virtual void MercuryMessaging.MmRelayNode.MmInvoke (MmMethod mmMethod, Vector3 param, MmMetadataBlock metadataBlock = null) virtual inherited
Invoke an MmMethod with parameter: Vector3.
Parameters
mmMethod MmMethod Identifier - MmMethod
param MmMethod parameter: Vector3.
metadataBlock Object defining the routing of Mmessages through MercuryMessaging Hierarchies. MmMetadataBlock
Implements MercuryMessaging.IMmNode.
Definition at line 1170 of file MmRelayNode.cs.
References MercuryMessaging.MmMessagePool.GetVector3(), MmInvoke(), and MercuryMessaging.MmMessagePool.Return().
MmInvoke() [15/15]
virtual void MercuryMessaging.MmRelayNode.MmInvoke (MmMethod mmMethod, Vector4 param, MmMetadataBlock metadataBlock = null) virtual inherited
Invoke an MmMethod with parameter: Vector4.
Parameters
mmMethod MmMethod Identifier - MmMethod
param MmMethod parameter: Vector4.
metadataBlock Object defining the routing of Mmessages through MercuryMessaging Hierarchies. MmMetadataBlock
Implements MercuryMessaging.IMmNode.
Definition at line 1186 of file MmRelayNode.cs.
References MercuryMessaging.MmMessagePool.GetVector4(), MmInvoke(), and MercuryMessaging.MmMessagePool.Return().
MmInvokeWithPath() [1/5]
virtual void MercuryMessaging.MmRelayNode.MmInvokeWithPath (string path, MmMessage message) virtual inherited
Invokes a pre-created message using path specification.
Definition at line 1448 of file MmRelayNode.cs.
References ResolvePathTargets().
MmInvokeWithPath() [2/5]
virtual void MercuryMessaging.MmRelayNode.MmInvokeWithPath (string path, MmMethod mmMethod, bool param, MmMetadataBlock metadataBlock = null) virtual inherited
Invokes a message with boolean parameter using path specification.
Definition at line 1358 of file MmRelayNode.cs.
References MercuryMessaging.MmTagHelper.Everything, and ResolvePathTargets().
MmInvokeWithPath() [3/5]
virtual void MercuryMessaging.MmRelayNode.MmInvokeWithPath (string path, MmMethod mmMethod, int param, MmMetadataBlock metadataBlock = null) virtual inherited
Invokes a message with int parameter using path specification.
Definition at line 1388 of file MmRelayNode.cs.
References MercuryMessaging.MmTagHelper.Everything, and ResolvePathTargets().
MmInvokeWithPath() [4/5]
virtual void MercuryMessaging.MmRelayNode.MmInvokeWithPath (string path, MmMethod mmMethod, MmMetadataBlock metadataBlock = null) virtual inherited
Invokes a message using path specification for hierarchical routing.
Path format: "parent/sibling/child" with wildcard support (*). Part of Phase 2.1: Advanced Message Routing.
Parameters
path Path string like "parent/sibling/child"
mmMethod Method to invoke on target nodes
metadataBlock Optional metadata (levelFilter will be overridden)
Definition at line 1314 of file MmRelayNode.cs.
References MercuryMessaging.MmTagHelper.Everything, MercuryMessaging.MmHashSetPool.Get(), ResolvePathTargets(), and MercuryMessaging.MmMessage.VisitedNodes.
MmInvokeWithPath() [5/5]
virtual void MercuryMessaging.MmRelayNode.MmInvokeWithPath (string path, MmMethod mmMethod, string param, MmMetadataBlock metadataBlock = null) virtual inherited
Invokes a message with string parameter using path specification.
Definition at line 1418 of file MmRelayNode.cs.
References MercuryMessaging.MmTagHelper.Everything, and ResolvePathTargets().
MmOnAwakeComplete()
virtual void MercuryMessaging.MmResponder.MmOnAwakeComplete () virtual inherited
Post Awake callback used between objects implementing this interface.
This allows for initialization steps that must occur before one instance's Awake and its Start.
Implements MercuryMessaging.IMmResponder.
Definition at line 150 of file MmResponder.cs.
References MmAwakeCompleteCallback.
Referenced by Awake().
MmOnStartComplete()
virtual void MercuryMessaging.MmResponder.MmOnStartComplete () virtual inherited
Post Start callback used between objects implementing this interface This allows for initialization steps that must occur before one instance's Start and its first Update.
Implements MercuryMessaging.IMmResponder.
Definition at line 161 of file MmResponder.cs.
References MmStartCompleteCallback.
Referenced by Start().
MmRefreshResponders()
void MercuryMessaging.MmRelayNode.MmRefreshResponders () inherited
Grab all MmResponders attached to the same GameObject.
Does not grab any other MmRelayNodes attached to the same GameObject.
Definition at line 578 of file MmRelayNode.cs.
References MmRelayNode(), _tagCheckEnabledCount, MmAddToRoutingTable(), and RoutingTable.
Referenced by InitializeNode().
MmRegisterAwakeCompleteCallback()
virtual void MercuryMessaging.MmResponder.MmRegisterAwakeCompleteCallback (IMmCallback callback) virtual inherited
It is possible that certain handles are not going to be in-place when registration of the OnAwakeComplete callback is invoked.
The is especially true in scenarios where MmRelayNodes are networked. This allows for a deferred registration, eliminating most instances where the Awake callback invocations fail.
Parameters
callback Callback to be registered.
Implements MercuryMessaging.IMmResponder.
Definition at line 175 of file MmResponder.cs.
References MercuryMessaging.IMmCallback(), and MmAwakeCompleteCallback.
MmRegisterStartCompleteCallback()
virtual void MercuryMessaging.MmResponder.MmRegisterStartCompleteCallback (IMmCallback callback) virtual inherited
It is possible that certain handles are not going to be in-place when registration of the OnStartComplete callback is invoked.
The is especially true in scenarios where MmRelayNodes are networked. This allows for a deferred registration, eliminating most instances where the Start callback invocations fail.
Parameters
callback Callback to be registered.
Implements MercuryMessaging.IMmResponder.
Definition at line 188 of file MmResponder.cs.
References MercuryMessaging.IMmCallback(), and MmStartCompleteCallback.
Referenced by MercuryMessaging.MmSwitchResponder.Awake().
NavigateSegment()
List< MmRelayNode > MercuryMessaging.MmRelayNode.NavigateSegment (MmRelayNode node, PathSegment segment, HashSet< int > visited) private inherited
Navigates from a node according to a path segment.
Definition at line 2168 of file MmRelayNode.cs.
References MmRelayNode(), CollectAncestors(), CollectDescendants(), CollectSiblings(), MercuryMessaging.MmLogger.LogError, MmParentList, and RoutingTable.
Referenced by ResolvePathTargets().
NetworkCheck()
virtual bool MercuryMessaging.MmRelayNode.NetworkCheck (MmRoutingTableItem mmRoutingTableItem, MmMessage message) protected virtual inherited
Checks if a responder should recieve a message based on the network flag in a control block.
Network messages can go to other nodes, but not to self responders.
Parameters
mmRoutingTableItem Observed MmResponder
message Input message.
Returns
Definition at line 1675 of file MmRelayNode.cs.
References MercuryMessaging.MmMessage.IsDeserialized, MercuryMessaging.MmRoutingTableItem.Level, MercuryMessaging.MmMessage.MetadataBlock, MmNetworkResponder, and MercuryMessaging.MmMetadataBlock.NetworkFilter.
Referenced by ResponderCheck().
NetworkFilterAdjust()
virtual MmNetworkFilter MercuryMessaging.MmRelayNode.NetworkFilterAdjust (ref MmMessage message) protected virtual inherited
Allows modification of network filter in message as it gets passed between MmRelayNodes.
Parameters
message MmMessage to be adjusted.
Returns
Base implementation returns messages's network filter.
Definition at line 1515 of file MmRelayNode.cs.
References FlipNetworkFlagOnSend.
Referenced by MercuryMessaging.MmQuickNode.MmInvoke(), and MmInvoke().
NotifyListeners()
void MercuryMessaging.MmRelayNode.NotifyListeners (MmMessage message) private inherited
Notifies all registered listeners about a received message.
Called from MmInvoke to dispatch to listeners.
Parameters
message The message to notify listeners about.
Definition at line 767 of file MmRelayNode.cs.
References _listeners.
Referenced by MmInvoke().
RefreshParents()
void MercuryMessaging.MmRelayNode.RefreshParents () inherited
Iterates through RoutingTable list and assigns this MmRelayNode as a parent to child MmResponders.
Definition at line 629 of file MmRelayNode.cs.
References MercuryMessaging.MmLogger.LogFramework, MmAddToRoutingTable(), MmParentList, and RoutingTable.
Referenced by MercuryMessaging.MmHierarchyExtensions.DetachFromParent(), InitializeNode(), and MercuryMessaging.MmHierarchyExtensions.MmSetParent().
RemoveListener< T >()
void MercuryMessaging.MmRelayNode.RemoveListener< T > (MmListenerSubscription< T > subscription) package inherited
Removes a typed listener subscription from this relay node.
Called internally by MmListenerSubscription.Dispose().
Template Parameters
T The message type the listener handles.
Parameters
subscription The subscription to remove.
Type Constraints
T : MmMessage
Definition at line 731 of file MmRelayNode.cs.
References _listeners.
ResolvePathTargets()
virtual List< MmRelayNode > MercuryMessaging.MmRelayNode.ResolvePathTargets (string path) virtual inherited
Resolves a path specification string to a list of target relay nodes.
Path format: "parent/sibling/child" with wildcard support (*). Part of Phase 2.1: Advanced Message Routing.
Parameters
path Path string like "parent/sibling/child"
Returns
List of relay nodes matching the path
Exceptions
MmInvalidPathException If path is invalid
Definition at line 2075 of file MmRelayNode.cs.
References NavigateSegment(), MercuryMessaging.MmPathSpecification.Parse(), and MercuryMessaging.ParsedPath.Segments.
Referenced by MmInvokeWithPath(), MmInvokeWithPath(), MmInvokeWithPath(), MmInvokeWithPath(), and MmInvokeWithPath().
ResponderCheck()
virtual bool MercuryMessaging.MmRelayNode.ResponderCheck (MmLevelFilter levelFilter, MmActiveFilter activeFilter, MmSelectedFilter selectedFilter, MmNetworkFilter networkFilter, MmRoutingTableItem mmRoutingTableItem, MmMessage message) protected virtual inherited
This method determines if a particular MmResponder should receive a message via MmInvoke.
This performs 4 checks: Tag Check, Level Check, Active Check, & Selected Check.
Parameters
levelFilter Extracted message level filter - before adjust.
activeFilter Extracted message active filter - before adjust.
selectedFilter Extracted message selected filter - before adjust.
networkFilter Extracted message network filter - before adjust.
mmRoutingTableItem RoutingTableItem of currently observed MmResponder
message MmMessage to be checked.
Returns
Returns whether responder has passed all checks.
Definition at line 1540 of file MmRelayNode.cs.
References ActiveCheck(), EnabledChecks, MercuryMessaging.MmTagHelper.Everything, HasTagCheckEnabledResponders, MercuryMessaging.MmMessage.IsDeserialized, MercuryMessaging.MmRoutingTableItem.Level, MercuryMessaging.MmMessage.MetadataBlock, NetworkCheck(), MercuryMessaging.MmRoutingTableItem.Responder, SelectedCheck(), MercuryMessaging.MmMetadataBlock.Tag, and TagCheck().
Referenced by MmInvoke().
RouteLateral()
virtual void MercuryMessaging.MmRelayNode.RouteLateral (MmMessage message, bool includeSiblings, bool includeCousins) protected virtual inherited
Routes message to lateral relatives (siblings/cousins).
Part of Phase 2.1: Advanced Message Routing.
Parameters
message Message to route
includeSiblings Include sibling nodes
includeCousins Include cousin nodes
Definition at line 1983 of file MmRelayNode.cs.
References CollectCousins(), CollectSiblings(), and MercuryMessaging.MmLevelFilterHelper.SelfAndChildren.
Referenced by HandleAdvancedRouting().
RouteRecursive()
virtual void MercuryMessaging.MmRelayNode.RouteRecursive (MmMessage message, bool useDescendants) protected virtual inherited
Routes message to recursive descendants or ancestors.
Part of Phase 2.1: Advanced Message Routing.
Parameters
message Message to route
useDescendants True for descendants, false for ancestors
Definition at line 2016 of file MmRelayNode.cs.
References CollectAncestors(), and CollectDescendants().
Referenced by HandleAdvancedRouting().
SelectedCheck()
virtual bool MercuryMessaging.MmRelayNode.SelectedCheck (MmSelectedFilter selectedFilter, IMmResponder responder) protected virtual inherited
Determine if MmResponder passes MmRelayNode selected filter check using value embedded in MmMessage.
Parameters
selectedFilter Selected filter value extracted from MmMessage.
responder Observed MmResponder
Returns
Returns whether observed MmResponder has passed selected filter check. In base MmRelayNode, this always returns true.
Reimplemented in MercuryMessaging.MmRelaySwitchNode.
Definition at line 1661 of file MmRelayNode.cs.
Referenced by ResponderCheck().
SelectedFilterAdjust()
virtual MmSelectedFilter MercuryMessaging.MmRelayNode.SelectedFilterAdjust (ref MmMessage message) protected virtual inherited
Allows modification of selected filter in message as it gets passed between MmRelayNodes.
Parameters
message MmMessage to be adjusted.
Returns
Base implementation returns messages's selected filter.
Definition at line 1504 of file MmRelayNode.cs.
Referenced by MmInvoke().
SetFastHandler()
bool MercuryMessaging.MmRelayNode.SetFastHandler (MmResponder responder, System.Action< MmMessage > handler) inherited
Set a fast handler delegate for a responder in this relay node's routing table.
When set, the handler is invoked directly (~1-4 ticks) instead of going through virtual dispatch (~8-10 ticks).
Usage: relay.SetFastHandler(myResponder, msg => HandleMessage(msg));
Note: Call this after the responder is registered with MmAddToRoutingTable.
Parameters
responder The responder to set the handler for.
handler The handler delegate to invoke directly.
Returns
True if handler was set, false if responder not found in routing table.
Definition at line 538 of file MmRelayNode.cs.
References RoutingTable.
Referenced by ClearFastHandler().
Start()
override void MercuryMessaging.MmRelayNode.Start () virtual inherited
Calls MmOnStartComplete through MmResponder Start.
Reimplemented from MercuryMessaging.MmResponder.
Reimplemented in MercuryMessaging.MmRelaySwitchNode.
Definition at line 359 of file MmRelayNode.cs.
References MercuryMessaging.MmLogger.LogFramework, and positionOffset.
TagCheck()
virtual bool MercuryMessaging.MmRelayNode.TagCheck (MmRoutingTableItem mmRoutingTableItem, MmMessage message) protected virtual inherited
Determine if MmResponder passes MmRelayNode tag filter check using value embedded in MmMessage.
Parameters
mmRoutingTableItem RoutingTableItem of currently observed MmResponder
message MmMessage to be checked.
Returns
Returns whether observed MmResponder has passed tag check.
Definition at line 1588 of file MmRelayNode.cs.
References MercuryMessaging.MmTagHelper.Everything, MercuryMessaging.MmMessage.MetadataBlock, MercuryMessaging.MmRoutingTableItem.Responder, MercuryMessaging.MmMetadataBlock.Tag, MercuryMessaging.MmResponder.TagCheckEnabled, and MercuryMessaging.MmRoutingTableItem.Tags.
Referenced by ResponderCheck().
Update()
virtual void MercuryMessaging.MmResponder.Update () virtual inherited
Base Update of MmResponder Derived classes should always override.
Reimplemented in MercuryMessaging.MmTransformResponder, and MercuryMessaging.Task.MmTaskResponder< T >.
Definition at line 140 of file MmResponder.cs.
UpdateItemAndPropagate()
void MercuryMessaging.MmRelayNode.UpdateItemAndPropagate (MmRoutingTableItem item, MmMessage message) private inherited
Part of debug tracking - updates message lists and propagates.
Phase 6: NoInlining keeps this out of hot path.
Definition at line 406 of file MmRelayNode.cs.
References MmRelayNode(), messageOutList, MercuryMessaging.MmMessage.MmMessageType, MercuryMessaging.MmRoutingTableItem.Name, and MercuryMessaging.MmRoutingTableItem.Responder.
Referenced by UpdateMessages().
UpdateMessages()
void MercuryMessaging.MmRelayNode.UpdateMessages (MmMessage message) inherited
Debug tracking for messages - tracks message flow through the hierarchy.
Phase 6 Optimization: Marked NoInlining to keep out of hot path. Only called when PerformanceMode = false (debug mode).
Definition at line 377 of file MmRelayNode.cs.
References MercuryMessaging.MmMetadataBlock.LevelFilter, MercuryMessaging.MmMessage.MetadataBlock, RoutingTable, MercuryMessaging.MmRoutingTableItem.Tags, and UpdateItemAndPropagate().
Referenced by MmInvoke().
Member Data Documentation
_executing
bool MercuryMessaging.MmRelayNode._executing private inherited
Indicates whether MmInvoke is currently executing a call.
Definition at line 240 of file MmRelayNode.cs.
_listeners
List<IMmListenerSubscription> MercuryMessaging.MmRelayNode._listeners private inherited
DSL Phase 2.1: Listener registry for external message subscriptions.
Stores active listener subscriptions that receive notifications when messages arrive.
Definition at line 294 of file MmRelayNode.cs.
Referenced by AddListener< T >(), ClearListeners(), NotifyListeners(), and RemoveListener< T >().
_mmTag
MmTag MercuryMessaging.MmResponder._mmTag = MmTagHelper.Everything private inherited
Determines whether tag checking is enabled for this IMmResponder.
Definition at line 62 of file MmResponder.cs.
_tagCheckEnabledCount
int MercuryMessaging.MmRelayNode._tagCheckEnabledCount = 0 private inherited
Tracks how many responders in the routing table have TagCheckEnabled.
When zero, tag checks can be skipped entirely for performance.
Definition at line 248 of file MmRelayNode.cs.
Referenced by MmAddToRoutingTable(), and MmRefreshResponders().
AllowNetworkPropagationLocally
bool MercuryMessaging.MmRelayNode.AllowNetworkPropagationLocally = false inherited
Allows Node to pass a Network-only message into the hierarchy.
Definition at line 207 of file MmRelayNode.cs.
Referenced by MercuryMessaging.MmQuickNode.MmInvoke(), and MmInvoke().
AllowStandardMmInvoke
bool MercuryMessaging.MmQuickNode.AllowStandardMmInvoke = false
Definition at line 50 of file MmQuickNode.cs.
Referenced by MmInvoke().
AutoGrabAttachedResponders
bool MercuryMessaging.MmRelayNode.AutoGrabAttachedResponders = true inherited
There may be an issue where a message is received before self responders have been added to the list.
In order to resolve that issue, we allow the node to automatically grab all responders. The consequence here is that you cannot have responders on a node that do not automatically get added to the list.
Definition at line 274 of file MmRelayNode.cs.
Referenced by InitializeNode().
doNotModifyRoutingTable
bool MercuryMessaging.MmRelayNode.doNotModifyRoutingTable inherited
Flag to protect priority list from being modified while it's being iterated over.
Definition at line 195 of file MmRelayNode.cs.
Referenced by MmAddToRoutingTable(), and MmInvoke().
enableCycleDetection
bool MercuryMessaging.MmRelayNode.enableCycleDetection = true inherited
Enable cycle detection by tracking visited nodes.
When enabled, messages track which nodes they've visited and stop if they revisit a node. More aggressive than hop counting, but uses more memory.
Definition at line 174 of file MmRelayNode.cs.
Referenced by MmInvoke().
EnabledChecks
MmRoutingChecks MercuryMessaging.MmRelayNode.EnabledChecks = MmRoutingChecks.All inherited
Controls which routing checks are performed during message dispatch.
Default: All checks enabled. Disable specific checks for performance. WARNING: Disabling checks means messages bypass those filters entirely.
Setting EnabledChecks to None makes this node behave like the legacy MmQuickNode, bypassing all filtering and sending messages to all registered responders.
Definition at line 136 of file MmRelayNode.cs.
Referenced by ResponderCheck().
FlipNetworkFlagOnSend
bool MercuryMessaging.MmRelayNode.FlipNetworkFlagOnSend = false inherited
Does the node convert the message to a local message from networked on post send in order to guarantee that it does not send it over the network deeper in the hierarchy.
Definition at line 202 of file MmRelayNode.cs.
Referenced by NetworkFilterAdjust().
Initialized
bool MercuryMessaging.MmRelayNode.Initialized inherited
Indicates whether the MmRelayNode is ready for use This gets set either in Awake or on the first MmInvoke.
Definition at line 263 of file MmRelayNode.cs.
Referenced by InitializeNode().
layer
int MercuryMessaging.MmRelayNode.layer inherited
Definition at line 141 of file MmRelayNode.cs.
maxMessageHops
int MercuryMessaging.MmRelayNode.maxMessageHops = 50 inherited
Maximum number of relay hops a message can make before being dropped.
Prevents infinite loops in circular or complex hierarchies. Valid range: 5-1000. Default: 50. Set to 0 to disable hop limit checking (not recommended).
Definition at line 166 of file MmRelayNode.cs.
Referenced by MmInvoke().
messageHistorySize
int MercuryMessaging.MmRelayNode.messageHistorySize = 100 inherited
Size of the message history circular buffers.
Controls how many recent incoming and outgoing messages are tracked for debugging. Valid range: 10-10000. Default: 100.
Definition at line 151 of file MmRelayNode.cs.
Referenced by Awake().
messageInList
MmCircularBuffer<string> MercuryMessaging.MmRelayNode.messageInList inherited
Definition at line 153 of file MmRelayNode.cs.
Referenced by Awake().
messageOutList
MmCircularBuffer<string> MercuryMessaging.MmRelayNode.messageOutList inherited
Definition at line 155 of file MmRelayNode.cs.
Referenced by Awake(), and UpdateItemAndPropagate().
MmParentList
List<MmRelayNode> MercuryMessaging.MmRelayNode.MmParentList private inherited
Initial value:
=
            new List<MmRelayNode>()
Parents of this relay node.
Definition at line 189 of file MmRelayNode.cs.
Referenced by AddParent(), CollectAncestors(), CollectCousins(), CollectSiblings(), HandleParentRouting(), NavigateSegment(), and RefreshParents().
MmRespondersToAdd
Queue<MmRoutingTableItem> MercuryMessaging.MmRelayNode.MmRespondersToAdd inherited
Initial value:
=
            new Queue<MmRoutingTableItem>()
Queue of MmResponders to add once list is no longer in use by an MmInvoke.
Definition at line 183 of file MmRelayNode.cs.
Referenced by MmAddToRoutingTable(), and MmInvoke().
nodePosition
Vector2 MercuryMessaging.MmRelayNode.nodePosition = new Vector2(0, 0) inherited
Definition at line 139 of file MmRelayNode.cs.
PerformanceMode
bool MercuryMessaging.MmRelayNode.PerformanceMode = false static inherited
Performance Mode - disables debug message tracking overhead.
Enable this during performance testing to remove UpdateMessages() overhead. When true: message history tracking (UpdateMessages) is disabled for performance. When false: Full debug visualization and message tracking enabled.
Definition at line 111 of file MmRelayNode.cs.
Referenced by MmInvoke().
positionOffset
Transform MercuryMessaging.MmRelayNode.positionOffset inherited
Definition at line 176 of file MmRelayNode.cs.
Referenced by Start().
receiveHandledMessages
bool MercuryMessaging.MmResponder.receiveHandledMessages = false private inherited
When true, this responder receives messages even if Handled=true.
Useful for logging, analytics, or handlers that need to see all messages. Default: false (responder skipped after message is handled). Similar to WPF's handledEventsToo parameter.
Definition at line 76 of file MmResponder.cs.
ReparentClonedRespondersToSelf
bool MercuryMessaging.MmRelayNode.ReparentClonedRespondersToSelf = true inherited
Indicates whether cloned MmResponders should be added as children to the MmRelayNode's GameObject.
Definition at line 213 of file MmRelayNode.cs.
Referenced by InstantiateSubResponders().
RoutingTable
MmRoutingTable MercuryMessaging.MmRelayNode.RoutingTable inherited
List of associated Mercury Responders.
Each Mercury Routing Table Item contains: MmResponder, Name, Level (Self, Child, Parent), Cloneable (Indicates whether the Responder should be cloned when MmRelayNode is awoken), MmTag (Multi-tag filter supported by Mercury XM).
Definition at line 288 of file MmRelayNode.cs.
Referenced by MmRelayNode(), ApplyCustomFilter(), MercuryMessaging.MmFluentMessage.CollectChildRelays(), CollectDescendants(), MercuryMessaging.MmFluentMessage.CollectParentRelays(), MercuryMessaging.MmFluentMessage.CollectSiblingRelays(), MercuryMessaging.MmRelaySwitchNodeExtensions.ConfigureStates(), MercuryMessaging.MmRelayNodeExtensions.FindTargetRelay(), MercuryMessaging.MmRelaySwitchNode.GetChildRelayNodes(), HasFastHandler(), InstantiateSubResponders(), MercuryMessaging.MmRelaySwitchNode.JumpTo(), MercuryMessaging.MmRelaySwitchNode.JumpTo(), MmAddToRoutingTable(), MercuryMessaging.MmQuickNode.MmInvoke(), MmInvoke(), MmRefreshResponders(), NavigateSegment(), RefreshParents(), MercuryMessaging.MmRoutingExtensions.RemoveFromRoutingTable(), SetFastHandler(), and UpdateMessages().
StrictMode
bool MercuryMessaging.MmRelayNode.StrictMode = false static inherited
Strict Mode - enables fail-fast behavior for debugging.
When enabled:
Throws exceptions instead of logging warnings for routing errors
Validates message parameters more strictly
Provides more detailed error messages Use during development to catch issues early. Disable in production for resilient message handling.
Definition at line 123 of file MmRelayNode.cs.
Referenced by HandleAdvancedRouting(), and MmInvoke().
tagCheckEnabled
bool MercuryMessaging.MmResponder.tagCheckEnabled = true private inherited
By default IMmResponders have this set to true so that they receive all messages.
Definition at line 68 of file MmResponder.cs.
Referenced by MercuryMessaging.MmRelayNode.MmAddToRoutingTable().
Property Documentation
HasTagCheckEnabledResponders
bool MercuryMessaging.MmRelayNode.HasTagCheckEnabledResponders get protected inherited
Cache whether we need to perform tag checks at all.
Updated when responders are added/removed.
Definition at line 254 of file MmRelayNode.cs.
Referenced by ResponderCheck().
ListenerCount
int MercuryMessaging.MmRelayNode.ListenerCount get inherited
Gets the number of active listeners on this relay node.
Definition at line 299 of file MmRelayNode.cs.
Referenced by MercuryMessaging.MmListenerExtensions.GetListenerCount(), and MercuryMessaging.MmListenerExtensions.GetListenerCount().
MmGameObject
GameObject MercuryMessaging.MmResponder.MmGameObject get inherited
Handle to an instance's GameObject.
Implements MercuryMessaging.IMmResponder.
Definition at line 81 of file MmResponder.cs.
MmNetworkResponder
IMmNetworkResponder MercuryMessaging.MmRelayNode.MmNetworkResponder get private set inherited
Associated MmNetworkResponder.
If an MmNetworkResponder is attached o the same GameObject, it will automatically attach to this MmRelayNode. This turns all MmMethod invocations into networked MmMethod invocations, with no additional effort.
Definition at line 222 of file MmRelayNode.cs.
Referenced by Awake(), MercuryMessaging.MmNetworkExtensions.HasNetworkSupport(), MercuryMessaging.MmNetworkExtensions.IsClientOnly(), MercuryMessaging.MmNetworkExtensions.IsHost(), MercuryMessaging.MmNetworkExtensions.IsServerOnly(), MercuryMessaging.MmQuickNode.MmInvoke(), MmInvoke(), and NetworkCheck().
Name
string MercuryMessaging.MmRelayNode.Name get inherited
MmRelayNode name: returns GameObject name.
Definition at line 308 of file MmRelayNode.cs.
ReceiveHandledMessages
bool MercuryMessaging.MmResponder.ReceiveHandledMessages get set inherited
When true, this responder receives messages even if Handled=true.
Useful for logging, analytics, or handlers that need to see all messages.
Definition at line 110 of file MmResponder.cs.
Tag
MmTag MercuryMessaging.MmResponder.Tag get set inherited
MmTags allow you to specify filters for execution in Mercury XM graphs.
Implements MercuryMessaging.IMmResponder.
Definition at line 90 of file MmResponder.cs.
Referenced by MercuryMessaging.MmTagExtensions.HasTag(), and MercuryMessaging.MmRelayNode.MmAddToRoutingTable().
TagCheckEnabled
bool MercuryMessaging.MmResponder.TagCheckEnabled get set inherited
Determines whether tag checking is enabled for this IMmResponder.
Implements MercuryMessaging.IMmResponder.
Definition at line 100 of file MmResponder.cs.
Referenced by MercuryMessaging.MmRelayNode.MmAddToRoutingTable(), and MercuryMessaging.MmRelayNode.TagCheck().
To
MmRoutingBuilder MercuryMessaging.MmRelayNode.To get inherited
Property-based routing builder for shorter DSL syntax.
Enables: relay.To.Children.Send("Hello")
Definition at line 228 of file MmRelayNode.cs.
Event Documentation
MmAwakeCompleteCallback
IMmCallback MercuryMessaging.MmResponder.MmAwakeCompleteCallback private inherited
Event triggered in the MmResponder when this object is awoken.
Definition at line 50 of file MmResponder.cs.
Referenced by MmOnAwakeComplete(), and MmRegisterAwakeCompleteCallback().
MmStartCompleteCallback
IMmCallback MercuryMessaging.MmResponder.MmStartCompleteCallback private inherited
Event triggered in the MmResponder when this object is started.
Definition at line 56 of file MmResponder.cs.
Referenced by MmOnStartComplete(), and MmRegisterStartCompleteCallback().
The documentation for this class was generated from the following file:
Protocol/Nodes/MmQuickNode.cs