MercuryMessaging: MercuryMessaging.Network.MmBinarySerializer Class Reference
MercuryMessaging.Network.MmBinarySerializer Class Reference
Efficient binary serializer for MercuryMessaging messages.
Static Public Member Functions
static byte[] Serialize (MmMessage message)
Serialize an MmMessage to a byte array.
static byte[] SerializePooled (MmMessage message)
Serialize an MmMessage using pooled MmWriter for zero allocations (except final array).
static MmMessage Deserialize (byte[] data)
Deserialize a byte array to an MmMessage.
static MmMessage DeserializePooled (byte[] data)
Deserialize a byte array using pooled MmReader for minimal allocations.
Static Public Attributes
const byte FormatVersion = 1
Current serialization format version.
const int HeaderSize = 17
Fixed header size in bytes.
Static Private Member Functions
static void WritePayloadPooled (MmWriter writer, MmMessage message)
Write type-specific payload using pooled MmWriter.
static void WriteTransformDataPooled (MmWriter writer, MmMessageTransform msg)
static void WriteTransformListDataPooled (MmWriter writer, MmMessageTransformList msg)
static void WriteSerializableDataPooled (MmWriter writer, MmMessageSerializable msg)
static void WriteObjectValuePooled (MmWriter writer, object value)
static uint PackMetadata (MmMetadataBlock metadata)
Pack metadata block into 3 bytes (stored as uint, only 18 bits used).
static void WritePayload (BinaryWriter writer, MmMessage message)
Write type-specific payload data.
static void ReadPayloadPooled (MmReader reader, MmMessage message)
Read type-specific payload using pooled MmReader.
static void ReadTransformDataPooled (MmReader reader, MmMessageTransform msg)
static void ReadTransformListDataPooled (MmReader reader, MmMessageTransformList msg)
static void ReadSerializableDataPooled (MmReader reader, MmMessageSerializable msg)
static object ReadObjectValuePooled (MmReader reader)
static bool ValidateMagic (byte[] magic)
Validate the magic number.
static MmMetadataBlock UnpackMetadata (uint packed)
Unpack metadata from 4 bytes (uint).
static MmMessage CreateMessage (MmMessageType type, MmMetadataBlock metadata)
Create an empty message of the appropriate type.
static void ReadPayload (BinaryReader reader, MmMessage message)
Read type-specific payload data.
static void WriteString (BinaryWriter writer, string value)
static void WriteVector3 (BinaryWriter writer, Vector3 value)
static void WriteVector4 (BinaryWriter writer, Vector4 value)
static void WriteQuaternion (BinaryWriter writer, Quaternion value)
static void WriteByteArray (BinaryWriter writer, byte[] value)
static void WriteTransformData (BinaryWriter writer, MmMessageTransform msg)
static void WriteTransformListData (BinaryWriter writer, MmMessageTransformList msg)
static void WriteGameObjectData (BinaryWriter writer, MmMessageGameObject msg)
static void WriteSerializableData (BinaryWriter writer, MmMessageSerializable msg)
static void WriteObjectValue (BinaryWriter writer, object value)
Write an object value to the binary stream with type information.
static string ReadString (BinaryReader reader)
static Vector3 ReadVector3 (BinaryReader reader)
static Vector4 ReadVector4 (BinaryReader reader)
static Quaternion ReadQuaternion (BinaryReader reader)
static byte[] ReadByteArray (BinaryReader reader)
static void ReadTransformData (BinaryReader reader, MmMessageTransform msg)
static void ReadTransformListData (BinaryReader reader, MmMessageTransformList msg)
static void ReadGameObjectData (BinaryReader reader, MmMessageGameObject msg)
static void ReadSerializableData (BinaryReader reader, MmMessageSerializable msg)
static object ReadObjectValue (BinaryReader reader)
Read an object value from the binary stream with type information.
Static Private Attributes
static readonly byte[] MagicNumber = { 0x4D, 0x4D, 0x53, 0x47 }
Magic number for message validation: "MMSG".
Detailed Description
Efficient binary serializer for MercuryMessaging messages.
Converts MmMessage objects to compact byte arrays for network transport. This replaces the previous object[] serialization which was inefficient and not portable across different networking backends.
Binary Format:
Header (15 bytes fixed):
Magic: 4 bytes "MMSG"
Version: 1 byte
MessageType: 2 bytes (short)
MmMethod: 2 bytes (short)
NetId: 4 bytes (uint)
Metadata: 2 bytes (packed filters + tag)
Payload: Variable length, type-specific
Definition at line 61 of file MmBinarySerializer.cs.
Member Function Documentation
CreateMessage()
MmMessage MercuryMessaging.Network.MmBinarySerializer.CreateMessage (MmMessageType type, MmMetadataBlock metadata) static private
Create an empty message of the appropriate type.
Definition at line 690 of file MmBinarySerializer.cs.
Referenced by Deserialize(), and DeserializePooled().
Deserialize()
MmMessage MercuryMessaging.Network.MmBinarySerializer.Deserialize (byte[] data) static
Deserialize a byte array to an MmMessage.
Uses MemoryStream internally. For zero-allocation deserialization, use DeserializePooled().
Parameters
data The byte array to deserialize
Returns
Deserialized MmMessage
Definition at line 404 of file MmBinarySerializer.cs.
References CreateMessage(), FormatVersion, HeaderSize, ReadPayload(), UnpackMetadata(), and ValidateMagic().
Referenced by MercuryMessaging.Network.MmNetworkBridge.HandleReceivedMessage().
DeserializePooled()
MmMessage MercuryMessaging.Network.MmBinarySerializer.DeserializePooled (byte[] data) static
Deserialize a byte array using pooled MmReader for minimal allocations.
This is the preferred method for high-performance scenarios.
Parameters
data The byte array to deserialize
Returns
Deserialized MmMessage
Definition at line 453 of file MmBinarySerializer.cs.
References CreateMessage(), FormatVersion, HeaderSize, MagicNumber, ReadPayloadPooled(), and UnpackMetadata().
PackMetadata()
uint MercuryMessaging.Network.MmBinarySerializer.PackMetadata (MmMetadataBlock metadata) static private
Pack metadata block into 3 bytes (stored as uint, only 18 bits used).
Bits 0-3: LevelFilter (4 bits) Bits 4-5: ActiveFilter (2 bits) Bits 6-7: SelectedFilter (2 bits) Bits 8-9: NetworkFilter (2 bits) Bits 10-17: Tag (8 bits - supports Tag0-Tag7, where Tag7 = 0x80)
Definition at line 317 of file MmBinarySerializer.cs.
Referenced by Serialize(), and SerializePooled().
ReadByteArray()
byte[] MercuryMessaging.Network.MmBinarySerializer.ReadByteArray (BinaryReader reader) static private
Definition at line 986 of file MmBinarySerializer.cs.
Referenced by ReadPayload().
ReadGameObjectData()
void MercuryMessaging.Network.MmBinarySerializer.ReadGameObjectData (BinaryReader reader, MmMessageGameObject msg) static private
Definition at line 1016 of file MmBinarySerializer.cs.
Referenced by ReadPayload().
ReadObjectValue()
object MercuryMessaging.Network.MmBinarySerializer.ReadObjectValue (BinaryReader reader) static private
Read an object value from the binary stream with type information.
Definition at line 1071 of file MmBinarySerializer.cs.
References ReadString().
Referenced by ReadSerializableData().
ReadObjectValuePooled()
object MercuryMessaging.Network.MmBinarySerializer.ReadObjectValuePooled (MmReader reader) static private
Definition at line 640 of file MmBinarySerializer.cs.
References MercuryMessaging.Network.MmReader.ReadBool(), MercuryMessaging.Network.MmReader.ReadByte(), MercuryMessaging.Network.MmReader.ReadDouble(), MercuryMessaging.Network.MmReader.ReadFloat(), MercuryMessaging.Network.MmReader.ReadInt(), MercuryMessaging.Network.MmReader.ReadLong(), MercuryMessaging.Network.MmReader.ReadShort(), and MercuryMessaging.Network.MmReader.ReadString().
Referenced by ReadSerializableDataPooled().
ReadPayload()
void MercuryMessaging.Network.MmBinarySerializer.ReadPayload (BinaryReader reader, MmMessage message) static private
Read type-specific payload data.
Definition at line 728 of file MmBinarySerializer.cs.
References MercuryMessaging.MmMessage.MmMessageType, ReadByteArray(), ReadGameObjectData(), ReadQuaternion(), ReadSerializableData(), ReadString(), ReadTransformData(), ReadTransformListData(), ReadVector3(), and ReadVector4().
Referenced by Deserialize().
ReadPayloadPooled()
void MercuryMessaging.Network.MmBinarySerializer.ReadPayloadPooled (MmReader reader, MmMessage message) static private
Read type-specific payload using pooled MmReader.
Definition at line 501 of file MmBinarySerializer.cs.
References MercuryMessaging.MmMessage.MmMessageType, MercuryMessaging.Network.MmReader.ReadBool(), MercuryMessaging.Network.MmReader.ReadBytes(), MercuryMessaging.Network.MmReader.ReadFloat(), MercuryMessaging.Network.MmReader.ReadInt(), MercuryMessaging.Network.MmReader.ReadQuaternion(), ReadSerializableDataPooled(), MercuryMessaging.Network.MmReader.ReadString(), ReadTransformDataPooled(), ReadTransformListDataPooled(), MercuryMessaging.Network.MmReader.ReadUInt(), MercuryMessaging.Network.MmReader.ReadVector3(), and MercuryMessaging.Network.MmReader.ReadVector4().
Referenced by DeserializePooled().
ReadQuaternion()
Quaternion MercuryMessaging.Network.MmBinarySerializer.ReadQuaternion (BinaryReader reader) static private
Definition at line 976 of file MmBinarySerializer.cs.
References MercuryMessaging.Network.Quaternion.
Referenced by ReadPayload(), ReadTransformData(), and ReadTransformListData().
ReadSerializableData()
void MercuryMessaging.Network.MmBinarySerializer.ReadSerializableData (BinaryReader reader, MmMessageSerializable msg) static private
Definition at line 1022 of file MmBinarySerializer.cs.
References ReadObjectValue(), and ReadString().
Referenced by ReadPayload().
ReadSerializableDataPooled()
void MercuryMessaging.Network.MmBinarySerializer.ReadSerializableDataPooled (MmReader reader, MmMessageSerializable msg) static private
Definition at line 581 of file MmBinarySerializer.cs.
References MercuryMessaging.Network.MmTypeRegistry.Create(), MercuryMessaging.Network.MmTypeRegistry.NullTypeId, MercuryMessaging.Network.MmReader.ReadInt(), ReadObjectValuePooled(), MercuryMessaging.Network.MmReader.ReadString(), and MercuryMessaging.Network.MmReader.ReadUShort().
Referenced by ReadPayloadPooled().
ReadString()
string MercuryMessaging.Network.MmBinarySerializer.ReadString (BinaryReader reader) static private
Definition at line 949 of file MmBinarySerializer.cs.
Referenced by ReadObjectValue(), ReadPayload(), and ReadSerializableData().
ReadTransformData()
void MercuryMessaging.Network.MmBinarySerializer.ReadTransformData (BinaryReader reader, MmMessageTransform msg) static private
Definition at line 993 of file MmBinarySerializer.cs.
References MercuryMessaging.MmTransform, ReadQuaternion(), and ReadVector3().
Referenced by ReadPayload().
ReadTransformDataPooled()
void MercuryMessaging.Network.MmBinarySerializer.ReadTransformDataPooled (MmReader reader, MmMessageTransform msg) static private
Definition at line 559 of file MmBinarySerializer.cs.
References MercuryMessaging.MmTransform, MercuryMessaging.Network.MmReader.ReadBool(), MercuryMessaging.Network.MmReader.ReadQuaternion(), and MercuryMessaging.Network.MmReader.ReadVector3().
Referenced by ReadPayloadPooled().
ReadTransformListData()
void MercuryMessaging.Network.MmBinarySerializer.ReadTransformListData (BinaryReader reader, MmMessageTransformList msg) static private
Definition at line 1003 of file MmBinarySerializer.cs.
References MercuryMessaging.MmTransform, ReadQuaternion(), ReadVector3(), and MercuryMessaging.MmMessageTransformList.transforms.
Referenced by ReadPayload().
ReadTransformListDataPooled()
void MercuryMessaging.Network.MmBinarySerializer.ReadTransformListDataPooled (MmReader reader, MmMessageTransformList msg) static private
Definition at line 568 of file MmBinarySerializer.cs.
References MercuryMessaging.MmTransform, MercuryMessaging.Network.MmReader.ReadInt(), MercuryMessaging.Network.MmReader.ReadQuaternion(), MercuryMessaging.Network.MmReader.ReadVector3(), and MercuryMessaging.MmMessageTransformList.transforms.
Referenced by ReadPayloadPooled().
ReadVector3()
Vector3 MercuryMessaging.Network.MmBinarySerializer.ReadVector3 (BinaryReader reader) static private
Definition at line 957 of file MmBinarySerializer.cs.
References MercuryMessaging.Network.Vector3.
Referenced by ReadPayload(), ReadTransformData(), and ReadTransformListData().
ReadVector4()
Vector4 MercuryMessaging.Network.MmBinarySerializer.ReadVector4 (BinaryReader reader) static private
Definition at line 966 of file MmBinarySerializer.cs.
References MercuryMessaging.Network.Vector4.
Referenced by ReadPayload().
Serialize()
byte[] MercuryMessaging.Network.MmBinarySerializer.Serialize (MmMessage message) static
Serialize an MmMessage to a byte array.
Uses MemoryStream internally (allocates each call). For zero-allocation serialization, use SerializePooled().
Parameters
message The message to serialize
Returns
Byte array representation of the message
Definition at line 89 of file MmBinarySerializer.cs.
References FormatVersion, MagicNumber, MercuryMessaging.MmMessage.MetadataBlock, MercuryMessaging.MmMessage.MmMessageType, MercuryMessaging.MmMessage.MmMethod, MercuryMessaging.MmMessage.NetId, PackMetadata(), and WritePayload().
Referenced by MercuryMessaging.Network.MmNetworkBridge.SendToAllClients(), MercuryMessaging.Network.MmNetworkBridge.SendToClient(), MercuryMessaging.Network.MmNetworkBridge.SendToServer(), and MercuryMessaging.Network.MmPoolExtensions.SerializePooled().
SerializePooled()
byte[] MercuryMessaging.Network.MmBinarySerializer.SerializePooled (MmMessage message) static
Serialize an MmMessage using pooled MmWriter for zero allocations (except final array).
This is the preferred method for high-performance scenarios.
Parameters
message The message to serialize
Returns
Byte array representation of the message
Definition at line 115 of file MmBinarySerializer.cs.
References FormatVersion, MercuryMessaging.Network.MmWriter.Get(), HeaderSize, MagicNumber, MercuryMessaging.MmMessage.MetadataBlock, MercuryMessaging.MmMessage.MmMessageType, MercuryMessaging.MmMessage.MmMethod, MercuryMessaging.MmMessage.NetId, PackMetadata(), and WritePayloadPooled().
UnpackMetadata()
MmMetadataBlock MercuryMessaging.Network.MmBinarySerializer.UnpackMetadata (uint packed) static private
Unpack metadata from 4 bytes (uint).
Definition at line 676 of file MmBinarySerializer.cs.
Referenced by Deserialize(), and DeserializePooled().
ValidateMagic()
bool MercuryMessaging.Network.MmBinarySerializer.ValidateMagic (byte[] magic) static private
Validate the magic number.
Definition at line 663 of file MmBinarySerializer.cs.
References MagicNumber.
Referenced by Deserialize().
WriteByteArray()
void MercuryMessaging.Network.MmBinarySerializer.WriteByteArray (BinaryWriter writer, byte[] value) static private
Definition at line 825 of file MmBinarySerializer.cs.
Referenced by WritePayload().
WriteGameObjectData()
void MercuryMessaging.Network.MmBinarySerializer.WriteGameObjectData (BinaryWriter writer, MmMessageGameObject msg) static private
Definition at line 859 of file MmBinarySerializer.cs.
References MercuryMessaging.MmMessageGameObject.GameObjectNetId.
Referenced by WritePayload().
WriteObjectValue()
void MercuryMessaging.Network.MmBinarySerializer.WriteObjectValue (BinaryWriter writer, object value) static private
Write an object value to the binary stream with type information.
Definition at line 896 of file MmBinarySerializer.cs.
References WriteString().
Referenced by WriteSerializableData().
WriteObjectValuePooled()
void MercuryMessaging.Network.MmBinarySerializer.WriteObjectValuePooled (MmWriter writer, object value) static private
Definition at line 260 of file MmBinarySerializer.cs.
References MercuryMessaging.Network.MmWriter.WriteBool(), MercuryMessaging.Network.MmWriter.WriteByte(), MercuryMessaging.Network.MmWriter.WriteDouble(), MercuryMessaging.Network.MmWriter.WriteFloat(), MercuryMessaging.Network.MmWriter.WriteInt(), MercuryMessaging.Network.MmWriter.WriteLong(), MercuryMessaging.Network.MmWriter.WriteShort(), and MercuryMessaging.Network.MmWriter.WriteString().
Referenced by WriteSerializableDataPooled().
WritePayload()
void MercuryMessaging.Network.MmBinarySerializer.WritePayload (BinaryWriter writer, MmMessage message) static private
Write type-specific payload data.
Definition at line 332 of file MmBinarySerializer.cs.
References MercuryMessaging.MmMessage.MmMessageType, WriteByteArray(), WriteGameObjectData(), WriteQuaternion(), WriteSerializableData(), WriteString(), WriteTransformData(), WriteTransformListData(), WriteVector3(), and WriteVector4().
Referenced by Serialize().
WritePayloadPooled()
void MercuryMessaging.Network.MmBinarySerializer.WritePayloadPooled (MmWriter writer, MmMessage message) static private
Write type-specific payload using pooled MmWriter.
Definition at line 137 of file MmBinarySerializer.cs.
References MercuryMessaging.MmMessage.MmMessageType, MercuryMessaging.Network.MmWriter.WriteBool(), MercuryMessaging.Network.MmWriter.WriteBytes(), MercuryMessaging.Network.MmWriter.WriteFloat(), MercuryMessaging.Network.MmWriter.WriteInt(), MercuryMessaging.Network.MmWriter.WriteQuaternion(), WriteSerializableDataPooled(), MercuryMessaging.Network.MmWriter.WriteString(), WriteTransformDataPooled(), WriteTransformListDataPooled(), MercuryMessaging.Network.MmWriter.WriteUInt(), MercuryMessaging.Network.MmWriter.WriteVector3(), and MercuryMessaging.Network.MmWriter.WriteVector4().
Referenced by SerializePooled().
WriteQuaternion()
void MercuryMessaging.Network.MmBinarySerializer.WriteQuaternion (BinaryWriter writer, Quaternion value) static private
Definition at line 817 of file MmBinarySerializer.cs.
Referenced by WritePayload(), WriteTransformData(), and WriteTransformListData().
WriteSerializableData()
void MercuryMessaging.Network.MmBinarySerializer.WriteSerializableData (BinaryWriter writer, MmMessageSerializable msg) static private
Definition at line 865 of file MmBinarySerializer.cs.
References MercuryMessaging.MmMessageSerializable.value, WriteObjectValue(), and WriteString().
Referenced by WritePayload().
WriteSerializableDataPooled()
void MercuryMessaging.Network.MmBinarySerializer.WriteSerializableDataPooled (MmWriter writer, MmMessageSerializable msg) static private
Definition at line 221 of file MmBinarySerializer.cs.
References MercuryMessaging.Network.MmTypeRegistry.GetTypeId(), MercuryMessaging.Network.MmTypeRegistry.NullTypeId, MercuryMessaging.MmMessageSerializable.value, MercuryMessaging.Network.MmWriter.WriteInt(), WriteObjectValuePooled(), MercuryMessaging.Network.MmWriter.WriteString(), and MercuryMessaging.Network.MmWriter.WriteUShort().
Referenced by WritePayloadPooled().
WriteString()
void MercuryMessaging.Network.MmBinarySerializer.WriteString (BinaryWriter writer, string value) static private
Definition at line 790 of file MmBinarySerializer.cs.
Referenced by WriteObjectValue(), WritePayload(), and WriteSerializableData().
WriteTransformData()
void MercuryMessaging.Network.MmBinarySerializer.WriteTransformData (BinaryWriter writer, MmMessageTransform msg) static private
Definition at line 836 of file MmBinarySerializer.cs.
References MercuryMessaging.MmMessageTransform.LocalTransform, MercuryMessaging.MmMessageTransform.MmTransform, MercuryMessaging.MmTransform.Rotation, MercuryMessaging.MmTransform.Scale, MercuryMessaging.MmTransform.Translation, WriteQuaternion(), and WriteVector3().
Referenced by WritePayload().
WriteTransformDataPooled()
void MercuryMessaging.Network.MmBinarySerializer.WriteTransformDataPooled (MmWriter writer, MmMessageTransform msg) static private
Definition at line 198 of file MmBinarySerializer.cs.
References MercuryMessaging.MmMessageTransform.LocalTransform, MercuryMessaging.MmMessageTransform.MmTransform, MercuryMessaging.MmTransform.Rotation, MercuryMessaging.MmTransform.Scale, MercuryMessaging.MmTransform.Translation, MercuryMessaging.Network.MmWriter.WriteBool(), MercuryMessaging.Network.MmWriter.WriteQuaternion(), and MercuryMessaging.Network.MmWriter.WriteVector3().
Referenced by WritePayloadPooled().
WriteTransformListData()
void MercuryMessaging.Network.MmBinarySerializer.WriteTransformListData (BinaryWriter writer, MmMessageTransformList msg) static private
Definition at line 844 of file MmBinarySerializer.cs.
References MercuryMessaging.MmMessageTransformList.transforms, WriteQuaternion(), and WriteVector3().
Referenced by WritePayload().
WriteTransformListDataPooled()
void MercuryMessaging.Network.MmBinarySerializer.WriteTransformListDataPooled (MmWriter writer, MmMessageTransformList msg) static private
Definition at line 206 of file MmBinarySerializer.cs.
References MercuryMessaging.MmMessageTransformList.transforms, MercuryMessaging.Network.MmWriter.WriteInt(), MercuryMessaging.Network.MmWriter.WriteQuaternion(), and MercuryMessaging.Network.MmWriter.WriteVector3().
Referenced by WritePayloadPooled().
WriteVector3()
void MercuryMessaging.Network.MmBinarySerializer.WriteVector3 (BinaryWriter writer, Vector3 value) static private
Definition at line 802 of file MmBinarySerializer.cs.
Referenced by WritePayload(), WriteTransformData(), and WriteTransformListData().
WriteVector4()
void MercuryMessaging.Network.MmBinarySerializer.WriteVector4 (BinaryWriter writer, Vector4 value) static private
Definition at line 809 of file MmBinarySerializer.cs.
Referenced by WritePayload().
Member Data Documentation
FormatVersion
const byte MercuryMessaging.Network.MmBinarySerializer.FormatVersion = 1 static
Current serialization format version.
Increment when making breaking changes to the format.
Definition at line 72 of file MmBinarySerializer.cs.
Referenced by Deserialize(), DeserializePooled(), Serialize(), and SerializePooled().
HeaderSize
const int MercuryMessaging.Network.MmBinarySerializer.HeaderSize = 17 static
Fixed header size in bytes.
Magic(4) + Version(1) + MsgType(2) + Method(2) + NetId(4) + Metadata(4) = 17
Definition at line 78 of file MmBinarySerializer.cs.
Referenced by Deserialize(), DeserializePooled(), and SerializePooled().
MagicNumber
readonly byte [] MercuryMessaging.Network.MmBinarySerializer.MagicNumber = { 0x4D, 0x4D, 0x53, 0x47 } static private
Magic number for message validation: "MMSG".
Definition at line 66 of file MmBinarySerializer.cs.
Referenced by DeserializePooled(), Serialize(), SerializePooled(), and ValidateMagic().
The documentation for this class was generated from the following file:
Protocol/Network/MmBinarySerializer.cs