MercuryMessaging: MercuryMessaging.AppStateBuilder Class Reference
MercuryMessaging.AppStateBuilder Class Reference
Fluent builder for configuring application states.
Classes
class StateConfig
Internal state configuration.
Public Member Functions
AppStateBuilder (MmRelaySwitchNode switchNode)
Create an app state builder for a switch node.
AppStateBuilder DefineState (string stateName)
Define or configure a state.
AppStateBuilder OnEnter (Action callback)
Set the entry callback for the current state.
AppStateBuilder OnExit (Action callback)
Set the exit callback for the current state.
AppStateBuilder OnTransition (Action onEnter, Action onExit)
Set both enter and exit callbacks for the current state.
AppStateBuilder CanTransitionTo (params string[] targetStates)
Define allowed transitions from current state.
AppStateBuilder StartWith (string stateName)
Set the initial state to start with.
AppStateBuilder OnAnyStateEnter (Action callback)
Set a callback for any state enter (global enter).
AppStateBuilder OnAnyStateExit (Action callback)
Set a callback for any state exit (global exit).
MmRelaySwitchNode Build ()
Build and apply the state configuration.
Private Member Functions
MmRoutingTableItem GetRoutingTableItem (string stateName)
void EnsureCurrentState ()
Private Attributes
readonly MmRelaySwitchNode _switchNode
readonly Dictionary< string, StateConfig > _stateConfigs = new Dictionary<string, StateConfig>()
string _currentStateName
string _initialState
Action _onGlobalEnter
Action _onGlobalExit
Detailed Description
Fluent builder for configuring application states.
Works with MmRelaySwitchNode.
Example Usage:
// Configure application states
MmAppState.Configure(switchNode)
    .DefineState("MainMenu")
        .OnEnter(() => ShowMenu())
        .OnExit(() => HideMenu())
    .DefineState("Gameplay")
        .OnEnter(() => StartGame())
        .OnExit(() => SaveProgress())
    .DefineState("Pause")
        .OnEnter(() => PauseGame())
        .OnExit(() => ResumeGame())
    .StartWith("MainMenu")
    .Build();
// Transitions
switchNode.GoTo("Gameplay");
switchNode.GoBack();
Definition at line 40 of file AppStateBuilder.cs.
Constructor & Destructor Documentation
AppStateBuilder()
MercuryMessaging.AppStateBuilder.AppStateBuilder (MmRelaySwitchNode switchNode)
Create an app state builder for a switch node.
Definition at line 52 of file AppStateBuilder.cs.
References _switchNode.
Referenced by CanTransitionTo(), DefineState(), OnAnyStateEnter(), OnAnyStateExit(), OnEnter(), OnExit(), OnTransition(), and StartWith().
Member Function Documentation
Build()
MmRelaySwitchNode MercuryMessaging.AppStateBuilder.Build ()
Build and apply the state configuration.
Definition at line 159 of file AppStateBuilder.cs.
References _initialState, _onGlobalEnter, _onGlobalExit, _stateConfigs, _switchNode, and GetRoutingTableItem().
CanTransitionTo()
AppStateBuilder MercuryMessaging.AppStateBuilder.CanTransitionTo (params string[] targetStates)
Define allowed transitions from current state.
Definition at line 111 of file AppStateBuilder.cs.
References AppStateBuilder(), _currentStateName, _stateConfigs, and EnsureCurrentState().
DefineState()
AppStateBuilder MercuryMessaging.AppStateBuilder.DefineState (string stateName)
Define or configure a state.
Definition at line 62 of file AppStateBuilder.cs.
References AppStateBuilder(), _currentStateName, and _stateConfigs.
EnsureCurrentState()
void MercuryMessaging.AppStateBuilder.EnsureCurrentState () private
Definition at line 266 of file AppStateBuilder.cs.
References _currentStateName.
Referenced by CanTransitionTo(), OnEnter(), OnExit(), and OnTransition().
GetRoutingTableItem()
MmRoutingTableItem MercuryMessaging.AppStateBuilder.GetRoutingTableItem (string stateName) private
Definition at line 243 of file AppStateBuilder.cs.
References _switchNode.
Referenced by Build().
OnAnyStateEnter()
AppStateBuilder MercuryMessaging.AppStateBuilder.OnAnyStateEnter (Action callback)
Set a callback for any state enter (global enter).
Definition at line 137 of file AppStateBuilder.cs.
References AppStateBuilder(), and _onGlobalEnter.
OnAnyStateExit()
AppStateBuilder MercuryMessaging.AppStateBuilder.OnAnyStateExit (Action callback)
Set a callback for any state exit (global exit).
Definition at line 146 of file AppStateBuilder.cs.
References AppStateBuilder(), and _onGlobalExit.
OnEnter()
AppStateBuilder MercuryMessaging.AppStateBuilder.OnEnter (Action callback)
Set the entry callback for the current state.
Definition at line 80 of file AppStateBuilder.cs.
References AppStateBuilder(), _currentStateName, _stateConfigs, and EnsureCurrentState().
OnExit()
AppStateBuilder MercuryMessaging.AppStateBuilder.OnExit (Action callback)
Set the exit callback for the current state.
Definition at line 90 of file AppStateBuilder.cs.
References AppStateBuilder(), _currentStateName, _stateConfigs, and EnsureCurrentState().
OnTransition()
AppStateBuilder MercuryMessaging.AppStateBuilder.OnTransition (Action onEnter, Action onExit)
Set both enter and exit callbacks for the current state.
Definition at line 100 of file AppStateBuilder.cs.
References AppStateBuilder(), _currentStateName, _stateConfigs, and EnsureCurrentState().
StartWith()
AppStateBuilder MercuryMessaging.AppStateBuilder.StartWith (string stateName)
Set the initial state to start with.
Definition at line 128 of file AppStateBuilder.cs.
References AppStateBuilder(), and _initialState.
Member Data Documentation
_currentStateName
string MercuryMessaging.AppStateBuilder._currentStateName private
Definition at line 44 of file AppStateBuilder.cs.
Referenced by CanTransitionTo(), DefineState(), EnsureCurrentState(), OnEnter(), OnExit(), and OnTransition().
_initialState
string MercuryMessaging.AppStateBuilder._initialState private
Definition at line 45 of file AppStateBuilder.cs.
Referenced by Build(), and StartWith().
_onGlobalEnter
Action MercuryMessaging.AppStateBuilder._onGlobalEnter private
Definition at line 46 of file AppStateBuilder.cs.
Referenced by Build(), and OnAnyStateEnter().
_onGlobalExit
Action MercuryMessaging.AppStateBuilder._onGlobalExit private
Definition at line 47 of file AppStateBuilder.cs.
Referenced by Build(), and OnAnyStateExit().
_stateConfigs
readonly Dictionary<string, StateConfig> MercuryMessaging.AppStateBuilder._stateConfigs = new Dictionary<string, StateConfig>() private
Definition at line 43 of file AppStateBuilder.cs.
Referenced by Build(), CanTransitionTo(), DefineState(), OnEnter(), OnExit(), and OnTransition().
_switchNode
readonly MmRelaySwitchNode MercuryMessaging.AppStateBuilder._switchNode private
Definition at line 42 of file AppStateBuilder.cs.
Referenced by AppStateBuilder(), Build(), and GetRoutingTableItem().
The documentation for this class was generated from the following file:
Protocol/DSL/AppStateBuilder.cs