MercuryMessaging: MercuryMessaging.Network.Backends.Fusion2TestManager Class Reference
MercuryMessaging.Network.Backends.Fusion2TestManager Class Reference
Photon Fusion 2 integration test manager for MercuryMessaging.
Public Member Functions
void Initialize ()
Initialize the test manager.
void Shutdown ()
Shutdown the test manager.
void SendTestString (string value)
Send a test string message through MmNetworkBridge (with NetId routing).
void SendTestInt (int value)
Send a test int message through MmNetworkBridge (with NetId routing).
void SendTestVector3 (Vector3 value)
Send a test Vector3 message through MmNetworkBridge (with NetId routing).
void BuildTestHierarchy ()
Build a test hierarchy using NetworkTestSceneBuilder.
void TestHierarchicalRouting ()
Test hierarchical message routing by sending a message to TestRoot and verifying all child responders receive it.
void TestAllMessageTypes ()
Test sending different message types through the hierarchy.
void ClearLog ()
void RefreshTargetNetId ()
Manually trigger NetId resolution (useful after scene changes).
Public Attributes
MmRelayNode targetRelayNode
bool useDirectBackend = false
Private Member Functions
void Awake ()
void Start ()
void Update ()
void OnDestroy ()
void ResolveTargetNetId ()
void EnsureNetworkTestResponder ()
Ensures the target relay node has a NetworkTestResponder component.
IEnumerator RefreshAfterFrame ()
void ValidateTestSetup ()
Validates the test setup and warns if no responders are found.
uint GetDeterministicId (GameObject go)
Generate a deterministic ID based on GameObject hierarchy path.
string GetHierarchyPath (GameObject go)
void UpdateStatus ()
void AddLog (string message)
void OnGUI ()
Private Attributes
bool isInitialized
bool isServer
bool isClient
int localClientId = -1
int connectedClients
uint targetNetId
int messagesSent
int messagesReceived
int messagesRoutedToResponders
List< string > messageLog = new List<string>()
bool _isActiveInstance
Vector2 _scrollPos
string _testString = "Hello Fusion 2!"
int _testInt = 42
Static Private Attributes
static Fusion2TestManager _instance
Detailed Description
Photon Fusion 2 integration test manager for MercuryMessaging.
This component tests end-to-end message routing through MmNetworkBridge. It uses the shared MmNetworkBridge instance (not its own backend) to ensure messages are properly routed to MmRelayNode responders via NetId.
Setup:
Create scene with NetworkRunner (Fusion 2)
Add MmFusion2Bridge prefab (spawned NetworkObject with RPC methods)
Add Fusion2BridgeSetup component (handles backend wiring)
Add this component for testing GUI
Use ParrelSync to run two Unity editors
Start as Host in one, Client in the other
Use the GUI to send test messages
Key Difference from FishNet:
Fusion 2 uses tick-based RPCs instead of FishNet broadcasts
MmFusion2Bridge handles RPC routing to Fusion2Backend
Uses TickAligned=false for immediate delivery
Definition at line 45 of file Fusion2TestManager.cs.
Member Function Documentation
AddLog()
void MercuryMessaging.Network.Backends.Fusion2TestManager.AddLog (string message) private
Definition at line 829 of file Fusion2TestManager.cs.
References messageLog.
Referenced by BuildTestHierarchy(), EnsureNetworkTestResponder(), Initialize(), RefreshAfterFrame(), ResolveTargetNetId(), SendTestInt(), SendTestString(), SendTestVector3(), Shutdown(), TestAllMessageTypes(), TestHierarchicalRouting(), and ValidateTestSetup().
Awake()
void MercuryMessaging.Network.Backends.Fusion2TestManager.Awake () private
Definition at line 79 of file Fusion2TestManager.cs.
References _instance, and _isActiveInstance.
BuildTestHierarchy()
void MercuryMessaging.Network.Backends.Fusion2TestManager.BuildTestHierarchy ()
Build a test hierarchy using NetworkTestSceneBuilder.
Creates: TestRoot (MmRelayNode) with multiple NetworkTestResponder children.
Definition at line 645 of file Fusion2TestManager.cs.
References AddLog(), GetDeterministicId(), MercuryMessaging.Network.MmNetworkBridge.Instance, MercuryMessaging.Network.Backends.NetworkTestResponder.ResetTotalCount(), targetNetId, and targetRelayNode.
Referenced by OnGUI().
ClearLog()
void MercuryMessaging.Network.Backends.Fusion2TestManager.ClearLog ()
Definition at line 842 of file Fusion2TestManager.cs.
References messageLog, messagesReceived, messagesRoutedToResponders, and messagesSent.
Referenced by OnGUI().
EnsureNetworkTestResponder()
void MercuryMessaging.Network.Backends.Fusion2TestManager.EnsureNetworkTestResponder () private
Ensures the target relay node has a NetworkTestResponder component.
Definition at line 263 of file Fusion2TestManager.cs.
References AddLog(), RefreshAfterFrame(), and targetRelayNode.
Referenced by Start().
GetDeterministicId()
uint MercuryMessaging.Network.Backends.Fusion2TestManager.GetDeterministicId (GameObject go) private
Generate a deterministic ID based on GameObject hierarchy path.
Must match Fusion2BridgeSetup.GetDeterministicId() for cross-instance routing.
Definition at line 329 of file Fusion2TestManager.cs.
References GetHierarchyPath().
Referenced by BuildTestHierarchy(), and ResolveTargetNetId().
GetHierarchyPath()
string MercuryMessaging.Network.Backends.Fusion2TestManager.GetHierarchyPath (GameObject go) private
Definition at line 336 of file Fusion2TestManager.cs.
Referenced by GetDeterministicId().
Initialize()
void MercuryMessaging.Network.Backends.Fusion2TestManager.Initialize ()
Initialize the test manager.
Uses MmNetworkBridge by default.
Definition at line 131 of file Fusion2TestManager.cs.
References _isActiveInstance, AddLog(), MercuryMessaging.Network.Backends.Fusion2Backend.Initialize(), MercuryMessaging.Network.MmNetworkBridge.Instance, isInitialized, ResolveTargetNetId(), and useDirectBackend.
Referenced by Start().
OnDestroy()
void MercuryMessaging.Network.Backends.Fusion2TestManager.OnDestroy () private
Definition at line 115 of file Fusion2TestManager.cs.
References _instance, and Shutdown().
OnGUI()
void MercuryMessaging.Network.Backends.Fusion2TestManager.OnGUI () private
Definition at line 986 of file Fusion2TestManager.cs.
References _isActiveInstance, _scrollPos, _testInt, _testString, BuildTestHierarchy(), ClearLog(), messageLog, MercuryMessaging.Network.None, RefreshTargetNetId(), SendTestInt(), SendTestString(), SendTestVector3(), targetRelayNode, TestAllMessageTypes(), and TestHierarchicalRouting().
RefreshAfterFrame()
IEnumerator MercuryMessaging.Network.Backends.Fusion2TestManager.RefreshAfterFrame () private
Definition at line 291 of file Fusion2TestManager.cs.
References AddLog(), and targetRelayNode.
Referenced by EnsureNetworkTestResponder().
RefreshTargetNetId()
void MercuryMessaging.Network.Backends.Fusion2TestManager.RefreshTargetNetId ()
Manually trigger NetId resolution (useful after scene changes).
Definition at line 853 of file Fusion2TestManager.cs.
References ResolveTargetNetId().
Referenced by OnGUI().
ResolveTargetNetId()
void MercuryMessaging.Network.Backends.Fusion2TestManager.ResolveTargetNetId () private
Definition at line 192 of file Fusion2TestManager.cs.
References AddLog(), GetDeterministicId(), MercuryMessaging.Network.MmNetworkBridge.Instance, targetNetId, and targetRelayNode.
Referenced by Initialize(), and RefreshTargetNetId().
SendTestInt()
void MercuryMessaging.Network.Backends.Fusion2TestManager.SendTestInt (int value)
Send a test int message through MmNetworkBridge (with NetId routing).
Definition at line 519 of file Fusion2TestManager.cs.
References AddLog(), MercuryMessaging.MmMetadataBlockHelper.Default, MercuryMessaging.Network.MmNetworkBridge.Instance, MercuryMessaging.Network.Backends.Fusion2Backend.IsConnected, messagesSent, targetNetId, and useDirectBackend.
Referenced by OnGUI().
SendTestString()
void MercuryMessaging.Network.Backends.Fusion2TestManager.SendTestString (string value)
Send a test string message through MmNetworkBridge (with NetId routing).
Definition at line 487 of file Fusion2TestManager.cs.
References AddLog(), MercuryMessaging.MmMetadataBlockHelper.Default, MercuryMessaging.Network.MmNetworkBridge.Instance, MercuryMessaging.Network.Backends.Fusion2Backend.IsConnected, messagesSent, targetNetId, and useDirectBackend.
Referenced by OnGUI(), and TestHierarchicalRouting().
SendTestVector3()
void MercuryMessaging.Network.Backends.Fusion2TestManager.SendTestVector3 (Vector3 value)
Send a test Vector3 message through MmNetworkBridge (with NetId routing).
Definition at line 551 of file Fusion2TestManager.cs.
References AddLog(), MercuryMessaging.MmMetadataBlockHelper.Default, MercuryMessaging.Network.MmNetworkBridge.Instance, MercuryMessaging.Network.Backends.Fusion2Backend.IsConnected, messagesSent, targetNetId, and useDirectBackend.
Referenced by OnGUI().
Shutdown()
void MercuryMessaging.Network.Backends.Fusion2TestManager.Shutdown ()
Shutdown the test manager.
Definition at line 171 of file Fusion2TestManager.cs.
References AddLog(), MercuryMessaging.Network.MmNetworkBridge.Instance, isInitialized, and MercuryMessaging.Network.Backends.Fusion2Backend.Shutdown().
Referenced by OnDestroy().
Start()
void MercuryMessaging.Network.Backends.Fusion2TestManager.Start () private
Definition at line 100 of file Fusion2TestManager.cs.
References _isActiveInstance, EnsureNetworkTestResponder(), and Initialize().
TestAllMessageTypes()
void MercuryMessaging.Network.Backends.Fusion2TestManager.TestAllMessageTypes ()
Test sending different message types through the hierarchy.
Definition at line 771 of file Fusion2TestManager.cs.
References AddLog(), MercuryMessaging.Network.Backends.NetworkTestResponder.ResetTotalCount(), MercuryMessaging.MmLevelFilterHelper.SelfAndChildren, targetRelayNode, MercuryMessaging.Network.Backends.NetworkTestResponder.TotalMessagesReceived, and MercuryMessaging.Network.Vector3.
Referenced by OnGUI().
TestHierarchicalRouting()
void MercuryMessaging.Network.Backends.Fusion2TestManager.TestHierarchicalRouting ()
Test hierarchical message routing by sending a message to TestRoot and verifying all child responders receive it.
Definition at line 694 of file Fusion2TestManager.cs.
References AddLog(), MercuryMessaging.Network.MmNetworkBridge.Instance, MercuryMessaging.Network.Backends.NetworkTestResponder.ResetTotalCount(), MercuryMessaging.MmLevelFilterHelper.SelfAndChildren, SendTestString(), targetRelayNode, and MercuryMessaging.Network.Backends.NetworkTestResponder.TotalMessagesReceived.
Referenced by OnGUI().
Update()
void MercuryMessaging.Network.Backends.Fusion2TestManager.Update () private
Definition at line 109 of file Fusion2TestManager.cs.
References _isActiveInstance, and UpdateStatus().
UpdateStatus()
void MercuryMessaging.Network.Backends.Fusion2TestManager.UpdateStatus () private
Definition at line 348 of file Fusion2TestManager.cs.
References connectedClients, MercuryMessaging.Network.MmNetworkBridge.Instance, MercuryMessaging.Network.Backends.Fusion2Backend.IsClient, isClient, MercuryMessaging.Network.Backends.Fusion2Backend.IsServer, isServer, MercuryMessaging.Network.Backends.Fusion2Backend.LocalClientId, and localClientId.
Referenced by Update().
ValidateTestSetup()
void MercuryMessaging.Network.Backends.Fusion2TestManager.ValidateTestSetup () private
Validates the test setup and warns if no responders are found.
Definition at line 304 of file Fusion2TestManager.cs.
References AddLog(), and targetRelayNode.
Member Data Documentation
_instance
Fusion2TestManager MercuryMessaging.Network.Backends.Fusion2TestManager._instance static private
Definition at line 74 of file Fusion2TestManager.cs.
Referenced by Awake(), and OnDestroy().
_isActiveInstance
bool MercuryMessaging.Network.Backends.Fusion2TestManager._isActiveInstance private
Definition at line 75 of file Fusion2TestManager.cs.
Referenced by Awake(), Initialize(), OnGUI(), Start(), and Update().
_scrollPos
Vector2 MercuryMessaging.Network.Backends.Fusion2TestManager._scrollPos private
Definition at line 982 of file Fusion2TestManager.cs.
Referenced by OnGUI().
_testInt
int MercuryMessaging.Network.Backends.Fusion2TestManager._testInt = 42 private
Definition at line 984 of file Fusion2TestManager.cs.
Referenced by OnGUI().
_testString
string MercuryMessaging.Network.Backends.Fusion2TestManager._testString = "Hello Fusion 2!" private
Definition at line 983 of file Fusion2TestManager.cs.
Referenced by OnGUI().
connectedClients
int MercuryMessaging.Network.Backends.Fusion2TestManager.connectedClients private
Definition at line 59 of file Fusion2TestManager.cs.
Referenced by UpdateStatus().
isClient
bool MercuryMessaging.Network.Backends.Fusion2TestManager.isClient private
Definition at line 57 of file Fusion2TestManager.cs.
Referenced by UpdateStatus().
isInitialized
bool MercuryMessaging.Network.Backends.Fusion2TestManager.isInitialized private
Definition at line 55 of file Fusion2TestManager.cs.
Referenced by Initialize(), and Shutdown().
isServer
bool MercuryMessaging.Network.Backends.Fusion2TestManager.isServer private
Definition at line 56 of file Fusion2TestManager.cs.
Referenced by UpdateStatus().
localClientId
int MercuryMessaging.Network.Backends.Fusion2TestManager.localClientId = -1 private
Definition at line 58 of file Fusion2TestManager.cs.
Referenced by UpdateStatus().
messageLog
List<string> MercuryMessaging.Network.Backends.Fusion2TestManager.messageLog = new List<string>() private
Definition at line 66 of file Fusion2TestManager.cs.
Referenced by AddLog(), ClearLog(), and OnGUI().
messagesReceived
int MercuryMessaging.Network.Backends.Fusion2TestManager.messagesReceived private
Definition at line 64 of file Fusion2TestManager.cs.
Referenced by ClearLog().
messagesRoutedToResponders
int MercuryMessaging.Network.Backends.Fusion2TestManager.messagesRoutedToResponders private
Definition at line 65 of file Fusion2TestManager.cs.
Referenced by ClearLog().
messagesSent
int MercuryMessaging.Network.Backends.Fusion2TestManager.messagesSent private
Definition at line 63 of file Fusion2TestManager.cs.
Referenced by ClearLog(), SendTestInt(), SendTestString(), and SendTestVector3().
targetNetId
uint MercuryMessaging.Network.Backends.Fusion2TestManager.targetNetId private
Definition at line 60 of file Fusion2TestManager.cs.
Referenced by BuildTestHierarchy(), ResolveTargetNetId(), SendTestInt(), SendTestString(), and SendTestVector3().
targetRelayNode
MmRelayNode MercuryMessaging.Network.Backends.Fusion2TestManager.targetRelayNode
Definition at line 49 of file Fusion2TestManager.cs.
Referenced by BuildTestHierarchy(), EnsureNetworkTestResponder(), OnGUI(), RefreshAfterFrame(), ResolveTargetNetId(), TestAllMessageTypes(), TestHierarchicalRouting(), and ValidateTestSetup().
useDirectBackend
bool MercuryMessaging.Network.Backends.Fusion2TestManager.useDirectBackend = false
Definition at line 52 of file Fusion2TestManager.cs.
Referenced by Initialize(), SendTestInt(), SendTestString(), and SendTestVector3().
The documentation for this class was generated from the following file:
Protocol/Network/Backends/Fusion2TestManager.cs