MercuryMessaging: MercuryMessaging.Network.Backends.Fusion2Resolver Class Reference
MercuryMessaging.Network.Backends.Fusion2Resolver Class Reference
IMmGameObjectResolver implementation for Photon Fusion 2.
Public Member Functions
bool TryGetNetworkId (GameObject gameObject, out uint networkId)
Get the network ID for a GameObject.
Parameters
gameObject The GameObject to get an ID for
networkId The resolved network ID (output)
Returns
True if the GameObject has a valid network ID, false otherwise
Returns false if:
GameObject is null
GameObject doesn't have required network component (PhotonView, NetworkObject, etc.)
Network component isn't properly initialized
bool TryGetGameObject (uint networkId, out GameObject gameObject)
Get the GameObject for a network ID.
Parameters
networkId The network ID to resolve
gameObject The resolved GameObject (output)
Returns
True if a valid GameObject was found, false otherwise
Returns false if:
Network ID is invalid (0 or not registered)
Referenced object has been destroyed
Object hasn't spawned on this client yet
uint GetNetworkId (GameObject gameObject)
Get the network ID for a GameObject (non-Try version).
Parameters
gameObject The GameObject to get an ID for
Returns
Network ID, or 0 if not found
GameObject GetGameObject (uint networkId)
Get the GameObject for a network ID (non-Try version).
Parameters
networkId The network ID to resolve
Returns
GameObject, or null if not found
bool TryGetRelayNode (uint networkId, out MmRelayNode relayNode)
Get the MmRelayNode for a network ID.Convenience method that resolves GameObject and gets its MmRelayNode component.
Parameters
networkId The network ID to resolve
relayNode The resolved MmRelayNode (output)
Returns
True if a valid MmRelayNode was found, false otherwise
Properties
string ResolverName [get]
Human-readable name of this resolver (e.g., "PhotonResolver", "FishNetResolver").
Detailed Description
IMmGameObjectResolver implementation for Photon Fusion 2.
Uses NetworkObject.Id.Raw to map between network IDs and GameObjects. Fusion 2 uses NetworkId struct which has a Raw uint property for serialization.
Fusion 2 specifics:
Uses NetworkObject.Id.Raw (compare with FishNet's ObjectId)
NetworkRunner maintains the spawned object registry
NetworkId.Raw of 0 indicates invalid/unspawned object
Both scene objects and spawned objects use the same ID system
Definition at line 55 of file Fusion2Resolver.cs.
Member Function Documentation
GetGameObject()
GameObject MercuryMessaging.Network.Backends.Fusion2Resolver.GetGameObject (uint networkId)
Get the GameObject for a network ID (non-Try version).
Parameters
networkId The network ID to resolve
Returns
GameObject, or null if not found
Implements MercuryMessaging.Network.IMmGameObjectResolver.
Definition at line 135 of file Fusion2Resolver.cs.
References TryGetGameObject().
GetNetworkId()
uint MercuryMessaging.Network.Backends.Fusion2Resolver.GetNetworkId (GameObject gameObject)
Get the network ID for a GameObject (non-Try version).
Parameters
gameObject The GameObject to get an ID for
Returns
Network ID, or 0 if not found
Implements MercuryMessaging.Network.IMmGameObjectResolver.
Definition at line 128 of file Fusion2Resolver.cs.
References TryGetNetworkId().
TryGetGameObject()
bool MercuryMessaging.Network.Backends.Fusion2Resolver.TryGetGameObject (uint networkId, out GameObject gameObject)
Get the GameObject for a network ID.
Parameters
networkId The network ID to resolve
gameObject The resolved GameObject (output)
Returns
True if a valid GameObject was found, false otherwise
Returns false if:
Network ID is invalid (0 or not registered)
Referenced object has been destroyed
Object hasn't spawned on this client yet
Implements MercuryMessaging.Network.IMmGameObjectResolver.
Definition at line 106 of file Fusion2Resolver.cs.
Referenced by GetGameObject(), and TryGetRelayNode().
TryGetNetworkId()
bool MercuryMessaging.Network.Backends.Fusion2Resolver.TryGetNetworkId (GameObject gameObject, out uint networkId)
Get the network ID for a GameObject.
Parameters
gameObject The GameObject to get an ID for
networkId The resolved network ID (output)
Returns
True if the GameObject has a valid network ID, false otherwise
Returns false if:
GameObject is null
GameObject doesn't have required network component (PhotonView, NetworkObject, etc.)
Network component isn't properly initialized
Implements MercuryMessaging.Network.IMmGameObjectResolver.
Definition at line 87 of file Fusion2Resolver.cs.
Referenced by GetNetworkId().
TryGetRelayNode()
bool MercuryMessaging.Network.Backends.Fusion2Resolver.TryGetRelayNode (uint networkId, out MmRelayNode relayNode)
Get the MmRelayNode for a network ID.Convenience method that resolves GameObject and gets its MmRelayNode component.
Parameters
networkId The network ID to resolve
relayNode The resolved MmRelayNode (output)
Returns
True if a valid MmRelayNode was found, false otherwise
Implements MercuryMessaging.Network.IMmGameObjectResolver.
Definition at line 142 of file Fusion2Resolver.cs.
References TryGetGameObject().
Property Documentation
ResolverName
string MercuryMessaging.Network.Backends.Fusion2Resolver.ResolverName get
Human-readable name of this resolver (e.g., "PhotonResolver", "FishNetResolver").
Implements MercuryMessaging.Network.IMmGameObjectResolver.
Definition at line 58 of file Fusion2Resolver.cs.
The documentation for this class was generated from the following file:
Protocol/Network/Backends/Fusion2Resolver.cs