MercuryMessaging: MercuryMessaging.MatrixUtilities Class Reference
MercuryMessaging.MatrixUtilities Class Reference
Some helpful matrix functions if creating applications using MercuryMessaging.
Static Public Member Functions
static Matrix CreateTranslationMatrix (Vector3 translation)
Create translation matrix from vector 3.
static Matrix CreateTranslationMatrix (float x, float y, float z)
Create translation matrix from 3 floats.
static Matrix CreateRotationMatrix (Quaternion rotation)
Create rotation matrix from quaternion.
static Matrix CreateRotationMatrix (float x, float y, float z)
Create rotation from euler angles provided in 3 floats.
static Matrix CreateScaleMatrix (Vector3 scale)
Create scale matrix from vector3.
static Quaternion GetRotation (this Matrix matrix)
Get quaternion from matrix.
static Matrix SubtractMatrix (this Matrix lhs, Matrix rhs)
Subtract one matrix from another.
static Matrix AddMatrix (this Matrix lhs, Matrix rhs)
Add two matricies together.
static Vector3 GetPosition (this Matrix4x4 m)
Position from matrix.
static Vector3 ScaleFromMatrix (this Matrix4x4 m)
Scale from matrix.
static void AssignGlobalTransform (GameObject gameObject, Matrix mat)
Assign matrix into Transform's global transformation.
static void AssignLocalTransform (GameObject gameObject, Matrix mat)
Assign matrix into Transform's local transformation.
static void AssignTransform (GameObject gameObject, Matrix mat, bool useGlobal)
Assign matrix into Transform's local or global transformation.
static void GetTRS (this Matrix m, out Vector3 trans, out Quaternion rot, out Vector3 scale)
Extract Translation, Rotation, and Scale given a Matrix.
static void MatrixPrint (this Matrix4x4 mat, string name)
Print Matrix Debug Log based on conversion to Row-major systems Note that Unity is Column Major - but accessors below are still Row,Column.
static string MatrixPrintS (this Matrix4x4 mat, string name)
Print Matrix String based on conversion to Row-major systems Note that Unity is Column Major - but accessors below are still Row,Column.
static void PrintFullMatrixTransRotDecomp (this Matrix4x4 trans, string name)
Prints the full matrix transformation decomposition for translation and rotation.
static void PrintTransRot (string name, Vector3 pos, Quaternion rot)
Prints the full matrix transformation decomposition for translation and rotation.
Detailed Description
Some helpful matrix functions if creating applications using MercuryMessaging.
Definition at line 43 of file MatrixUtilities.cs.
Member Function Documentation
AddMatrix()
Matrix MercuryMessaging.MatrixUtilities.AddMatrix (this Matrix lhs, Matrix rhs) static
Add two matricies together.
Parameters
lhs Left-hand side.
rhs Right-hand side
Returns
Sum.
Definition at line 135 of file MatrixUtilities.cs.
AssignGlobalTransform()
void MercuryMessaging.MatrixUtilities.AssignGlobalTransform (GameObject gameObject, Matrix mat) static
Assign matrix into Transform's global transformation.
Parameters
gameObject Target GameObject.
mat Values from this matrix will be applied to the GameObject.
Definition at line 179 of file MatrixUtilities.cs.
Referenced by AssignTransform().
AssignLocalTransform()
void MercuryMessaging.MatrixUtilities.AssignLocalTransform (GameObject gameObject, Matrix mat) static
Assign matrix into Transform's local transformation.
Parameters
gameObject Target GameObject.
mat Values from this matrix will be applied to the GameObject.
Definition at line 191 of file MatrixUtilities.cs.
Referenced by AssignTransform().
AssignTransform()
void MercuryMessaging.MatrixUtilities.AssignTransform (GameObject gameObject, Matrix mat, bool useGlobal) static
Assign matrix into Transform's local or global transformation.
Parameters
gameObject Target GameObject.
mat Values from this matrix will be applied to the GameObject.
useGlobal Whether to assign to global or local transform components.
Definition at line 204 of file MatrixUtilities.cs.
References AssignGlobalTransform(), and AssignLocalTransform().
CreateRotationMatrix() [1/2]
Matrix MercuryMessaging.MatrixUtilities.CreateRotationMatrix (float x, float y, float z) static
Create rotation from euler angles provided in 3 floats.
Parameters
x X-value
y Y-value
z Z-value
Returns
Rotation matrix.
Definition at line 84 of file MatrixUtilities.cs.
CreateRotationMatrix() [2/2]
Matrix MercuryMessaging.MatrixUtilities.CreateRotationMatrix (Quaternion rotation) static
Create rotation matrix from quaternion.
Parameters
rotation Input rotation.
Returns
Rotation Matrix.
Definition at line 72 of file MatrixUtilities.cs.
Referenced by MercuryMessaging.StandardLibrary.Animation.InterpolatorMatrix.Apply(), and MercuryMessaging.StandardLibrary.Animation.InterpolatorOrbit.Apply().
CreateScaleMatrix()
Matrix MercuryMessaging.MatrixUtilities.CreateScaleMatrix (Vector3 scale) static
Create scale matrix from vector3.
Parameters
scale Input scale.
Returns
Scale Matrix.
Definition at line 94 of file MatrixUtilities.cs.
CreateTranslationMatrix() [1/2]
Matrix MercuryMessaging.MatrixUtilities.CreateTranslationMatrix (float x, float y, float z) static
Create translation matrix from 3 floats.
Parameters
x X-value
y Y-value
z Z-value
Returns
Translation Matrix.
Definition at line 62 of file MatrixUtilities.cs.
CreateTranslationMatrix() [2/2]
Matrix MercuryMessaging.MatrixUtilities.CreateTranslationMatrix (Vector3 translation) static
Create translation matrix from vector 3.
Parameters
translation Input translation.
Returns
Definition at line 50 of file MatrixUtilities.cs.
Referenced by MercuryMessaging.StandardLibrary.Animation.InterpolatorMatrix.Apply(), and MercuryMessaging.StandardLibrary.Animation.InterpolatorOrbit.Apply().
GetPosition()
Vector3 MercuryMessaging.MatrixUtilities.GetPosition (this Matrix4x4 m) static
Position from matrix.
http://answers.unity3d.com/questions/11363/converting-matrix4x4-to-quaternion-vector3.html
Parameters
m Input matrix.
Returns
The from matrix.
Definition at line 153 of file MatrixUtilities.cs.
GetRotation()
Quaternion MercuryMessaging.MatrixUtilities.GetRotation (this Matrix matrix) static
Get quaternion from matrix.
Parameters
matrix Input matrix.
Returns
Rotation in quaternion form.
Definition at line 104 of file MatrixUtilities.cs.
GetTRS()
void MercuryMessaging.MatrixUtilities.GetTRS (this Matrix m, out Vector3 trans, out Quaternion rot, out Vector3 scale) static
Extract Translation, Rotation, and Scale given a Matrix.
Parameters
m Input Matrix.
trans Output translation.
rot Output rotation.
scale Output scale.
Definition at line 219 of file MatrixUtilities.cs.
MatrixPrint()
void MercuryMessaging.MatrixUtilities.MatrixPrint (this Matrix4x4 mat, string name) static
Print Matrix Debug Log based on conversion to Row-major systems Note that Unity is Column Major - but accessors below are still Row,Column.
Parameters
mat Matrix to print.
name Name of Matrix.
Definition at line 232 of file MatrixUtilities.cs.
MatrixPrintS()
string MercuryMessaging.MatrixUtilities.MatrixPrintS (this Matrix4x4 mat, string name) static
Print Matrix String based on conversion to Row-major systems Note that Unity is Column Major - but accessors below are still Row,Column.
Parameters
mat Matrix to print.
name Name of matrix.
Definition at line 261 of file MatrixUtilities.cs.
PrintFullMatrixTransRotDecomp()
void MercuryMessaging.MatrixUtilities.PrintFullMatrixTransRotDecomp (this Matrix4x4 trans, string name) static
Prints the full matrix transformation decomposition for translation and rotation.
Parameters
trans Print Matrix Transformation.
name Print Matrix Name.
Definition at line 289 of file MatrixUtilities.cs.
PrintTransRot()
void MercuryMessaging.MatrixUtilities.PrintTransRot (string name, Vector3 pos, Quaternion rot) static
Prints the full matrix transformation decomposition for translation and rotation.
Parameters
name Print Matrix Name.
trans Print Matrix Transformation.
Definition at line 303 of file MatrixUtilities.cs.
ScaleFromMatrix()
Vector3 MercuryMessaging.MatrixUtilities.ScaleFromMatrix (this Matrix4x4 m) static
Scale from matrix.
http://answers.unity3d.com/questions/402280/how-to-decompose-a-trs-matrix.html
Parameters
m Input matrix.
Returns
The from matrix.
Definition at line 164 of file MatrixUtilities.cs.
SubtractMatrix()
Matrix MercuryMessaging.MatrixUtilities.SubtractMatrix (this Matrix lhs, Matrix rhs) static
Subtract one matrix from another.
Parameters
lhs Left-hand side.
rhs Right-hand side
Returns
Difference.
Definition at line 117 of file MatrixUtilities.cs.
The documentation for this class was generated from the following file:
Protocol/Core/Extensions/MatrixUtilities.cs