MercuryMessaging: MercuryMessaging.MmExtendableResponder Class Reference
MercuryMessaging.MmExtendableResponder Class Reference
Base responder with extensible custom method handling via registration API.
Public Member Functions
override void MmInvoke (MmMessage message)
Hybrid fast/slow path message dispatch.
virtual void SetActive (bool active)
Handle MmMethod: SetActive.
virtual void Initialize ()
Handle MmMethod: Initialize Initialize allows you to provide additional initialization logic in-between calls to Monobehavior provided Awake() and Start() calls.
virtual void Refresh (List< MmTransform > transformList)
Handle MmMethod: Refresh.
override MmRelayNode GetRelayNode ()
Implementation of IMmResponder's GetRelayNode.
virtual void Awake ()
Awake: Invokes MmOnAwakeComplete.
virtual void Start ()
Start: Invokes MmOnStartComplete.
virtual void Update ()
Base Update of MmResponder Derived classes should always override.
virtual void MmOnAwakeComplete ()
Post Awake callback used between objects implementing this interface.
virtual void MmOnStartComplete ()
Post Start callback used between objects implementing this interface This allows for initialization steps that must occur before one instance's Start and its first Update.
virtual void MmRegisterAwakeCompleteCallback (IMmCallback callback)
It is possible that certain handles are not going to be in-place when registration of the OnAwakeComplete callback is invoked.
virtual void MmRegisterStartCompleteCallback (IMmCallback callback)
It is possible that certain handles are not going to be in-place when registration of the OnStartComplete callback is invoked.
Protected Member Functions
void RegisterCustomHandler (MmMethod method, Action< MmMessage > handler)
Register a handler for a custom method (>= 1000).
void UnregisterCustomHandler (MmMethod method)
Unregister a custom handler.
bool HasCustomHandler (MmMethod method)
Check if a custom handler is registered for a method.
virtual void OnUnhandledCustomMethod (MmMessage message)
Called when a custom method has no registered handler.
virtual void Switch (string iName)
Handle MmMethod: Switch.
virtual void Complete (bool active)
Handle MmMethod: Switch.
virtual void ApplyTaskInfo (IMmSerializable serializableValue)
Handle MmMethod: TaskInfo Given a IMmSerializable, extract TaskInfo.
virtual void ReceivedMessage (MmMessage message)
Handle MmMethod: Base MmMessage.
virtual void ReceivedMessage (MmMessageBool message)
Handle MmMethod: MessageBool.
virtual void ReceivedMessage (MmMessageByteArray message)
Handle MmMethod: MessageByteArray.
virtual void ReceivedMessage (MmMessageFloat message)
Handle MmMethod: MessageFloat.
virtual void ReceivedMessage (MmMessageInt message)
Handle MmMethod: MessageInt.
virtual void ReceivedMessage (MmMessageSerializable message)
Handle MmMethod: MessageSerializable.
virtual void ReceivedMessage (MmMessageString message)
Handle MmMethod: MessageString Override this to handle Mercury's string messages.
virtual void ReceivedMessage (MmMessageTransform message)
Handle MmMethod: MessageTransform Override this to handle Mercury's transform messages.
virtual void ReceivedMessage (MmMessageTransformList message)
Handle MmMethod: MessageTransformList Override this to handle Mercury's transform list messages.
virtual void ReceivedMessage (MmMessageVector3 message)
Handle MmMethod: MessageVector3 Override this to handle Mercury's Vector3 messages.
virtual void ReceivedMessage (MmMessageVector4 message)
Handle MmMethod: MessageVector4 Override this to handle Mercury's Vector4 messages.
virtual void ReceivedMessage (MmMessageQuaternion message)
Handle MmMethod: MessageQuaternion Override this to handle Mercury's Quaternion messages.
Properties
GameObject MmGameObject [get]
Handle to an instance's GameObject.
MmTag Tag [get, set]
MmTags allow you to specify filters for execution in Mercury XM graphs.
bool TagCheckEnabled [get, set]
Determines whether tag checking is enabled for this IMmResponder.
bool ReceiveHandledMessages [get, set]
When true, this responder receives messages even if Handled=true.
Events
IMmCallback MmAwakeCompleteCallback
Event triggered in the MmResponder when this object is awoken.
IMmCallback MmStartCompleteCallback
Event triggered in the MmResponder when this object is started.
Private Attributes
Dictionary< MmMethod, Action< MmMessage > > customHandlers
Dictionary storing custom method handlers.
MmTag _mmTag = MmTagHelper.Everything
Determines whether tag checking is enabled for this IMmResponder.
bool tagCheckEnabled = true
By default IMmResponders have this set to true so that they receive all messages.
bool receiveHandledMessages = false
When true, this responder receives messages even if Handled=true.
Detailed Description
Base responder with extensible custom method handling via registration API.
Provides hybrid fast/slow path: standard methods (0-999) use fast switch, custom methods (1000+) use dictionary lookup with handler registration.
This class eliminates boilerplate switch statements for custom methods and prevents common errors like forgetting to call base.MmInvoke().
Performance Characteristics:
Standard methods (0-999): ~100-150ns (same as MmBaseResponder)
Custom methods (1000+): ~300-500ns (dictionary lookup overhead)
Memory overhead: ~8 bytes (null reference) until first handler registered
Memory overhead: ~320 bytes with 3 custom handlers
Usage Guidelines:
Use this class when implementing custom methods (>= 1000)
Register handlers in Awake() for best performance
Use MmBaseResponder if only using standard methods (0-18)
public class MyCustomResponder : MmExtendableResponder
{
    protected override void Awake()
    {
        base.Awake();
        // Register custom method handlers
        RegisterCustomHandler((MmMethod)1000, OnCustomColor);
        RegisterCustomHandler((MmMethod)1001, OnCustomScale);
    }
    private void OnCustomColor(MmMessage msg)
    {
        var colorMsg = (ColorMessage)msg;
        GetComponent<Renderer>().material.color = colorMsg.color;
    }
    private void OnCustomScale(MmMessage msg)
    {
        var scaleMsg = (ScaleMessage)msg;
        transform.localScale = scaleMsg.scale;
    }
}
Definition at line 95 of file MmExtendableResponder.cs.
Member Function Documentation
ApplyTaskInfo()
virtual void MercuryMessaging.MmBaseResponder.ApplyTaskInfo (IMmSerializable serializableValue) protected virtual inherited
Handle MmMethod: TaskInfo Given a IMmSerializable, extract TaskInfo.
Parameters
serializableValue Serializable class containing MmTask Info
Definition at line 202 of file MmBaseResponder.cs.
Referenced by MmInvoke().
Awake()
virtual void MercuryMessaging.MmResponder.Awake () virtual inherited
Awake: Invokes MmOnAwakeComplete.
Reimplemented in MercuryMessaging.MmGuiResponder, MercuryMessaging.MmRelayAppStateNode, MercuryMessaging.MmRelayNode, MercuryMessaging.MmRelaySwitchNode, MercuryMessaging.MmSwitchResponder, MercuryMessaging.Task.MmTaskManager< U >, and MercuryMessaging.Task.MmTaskResponder< T >.
Definition at line 119 of file MmResponder.cs.
References MercuryMessaging.MmLogger.LogResponder, and MmOnAwakeComplete().
Complete()
virtual void MercuryMessaging.MmBaseResponder.Complete (bool active) protected virtual inherited
Handle MmMethod: Switch.
Parameters
active Can be used to indicate active state of object that triggered complete message
Definition at line 193 of file MmBaseResponder.cs.
Referenced by MmInvoke().
GetRelayNode()
override MmRelayNode MercuryMessaging.MmBaseResponder.GetRelayNode () inherited
Implementation of IMmResponder's GetRelayNode.
Returns
Returns MmRelayNode if one attached to GameObject, Otherwise returns NULL.
Implements MercuryMessaging.IMmResponder.
Definition at line 320 of file MmBaseResponder.cs.
Referenced by MercuryMessaging.MmMessagingExtensions.BroadcastInitialize(), MercuryMessaging.MmMessagingExtensions.BroadcastRefresh(), MercuryMessaging.MmMessagingExtensions.BroadcastSetActive(), MercuryMessaging.MmMessagingExtensions.BroadcastSwitch(), MercuryMessaging.MmMessagingExtensions.BroadcastValue(), MercuryMessaging.MmMessagingExtensions.BroadcastValue(), MercuryMessaging.MmMessagingExtensions.BroadcastValue(), MercuryMessaging.MmMessagingExtensions.BroadcastValue(), MercuryMessaging.MmResponderExtensions.Build(), MercuryMessaging.MmListenerExtensions.ClearAllListeners(), MercuryMessaging.MmQueryExtensions.FindByName(), MercuryMessaging.MmQueryExtensions.FindByPattern(), MercuryMessaging.MmListenerExtensions.GetListenerCount(), MercuryMessaging.MmQueryExtensions.HasSiblings(), MercuryMessaging.MmListenerExtensions.ListenFor(), MercuryMessaging.MmMessagingExtensions.NotifyComplete(), MercuryMessaging.MmMessagingExtensions.NotifyValue(), MercuryMessaging.MmMessagingExtensions.NotifyValue(), MercuryMessaging.MmMessagingExtensions.NotifyValue(), MercuryMessaging.MmMessagingExtensions.NotifyValue(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.On6DOF(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnAxis(), MercuryMessaging.MmListenerExtensions.OnBool(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnButton(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnClick(), MercuryMessaging.MmListenerExtensions.OnComplete(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnDrag(), MercuryMessaging.MmListenerExtensions.OnFloat(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnFocus(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnGaze(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnGesture(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnHover(), MercuryMessaging.MmListenerExtensions.OnInitialize(), MercuryMessaging.MmListenerExtensions.OnInt(), MercuryMessaging.MmListenerExtensions.OnRefresh(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnScroll(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnSelect(), MercuryMessaging.MmListenerExtensions.OnSetActive(), MercuryMessaging.MmListenerExtensions.OnString(), MercuryMessaging.MmListenerExtensions.OnSwitch(), MercuryMessaging.MmListenerExtensions.OnVector3(), MercuryMessaging.MmQueryExtensions.Query(), MercuryMessaging.MmRoutingExtensions.RegisterWith(), MercuryMessaging.MmMessagingExtensions.Send(), MercuryMessaging.MmMessagingExtensions.Send(), MercuryMessaging.MmMessagingExtensions.Send(), MercuryMessaging.MmQueryExtensions.SiblingCount(), MercuryMessaging.MmResponderExtensions.To(), MercuryMessaging.MmRoutingExtensions.UnregisterFrom(), and MercuryMessaging.MmTransformResponder.Update().
HasCustomHandler()
bool MercuryMessaging.MmExtendableResponder.HasCustomHandler (MmMethod method) protected
Check if a custom handler is registered for a method.
Useful for conditional logic based on handler availability.
Parameters
method The method to check
Returns
True if a handler is registered for this method, false otherwise
This method is useful for:
Runtime validation of handler registration
Conditional message sending based on handler availability
Debugging handler registration issues
if (HasCustomHandler((MmMethod)1000))
{
    relay.MmInvoke((MmMethod)1000, customData);
}
else
{
    Debug.LogWarning("Handler not registered yet");
}
Definition at line 290 of file MmExtendableResponder.cs.
References customHandlers.
Initialize()
virtual void MercuryMessaging.MmBaseResponder.Initialize () virtual inherited
Handle MmMethod: Initialize Initialize allows you to provide additional initialization logic in-between calls to Monobehavior provided Awake() and Start() calls.
Reimplemented in MercuryMessaging.Network.Backends.NetworkTestResponder.
Definition at line 166 of file MmBaseResponder.cs.
References MercuryMessaging.MmLogger.LogResponder.
Referenced by MmInvoke().
MmInvoke()
override void MercuryMessaging.MmExtendableResponder.MmInvoke (MmMessage message) virtual
Hybrid fast/slow path message dispatch.
Standard methods (0-999) are routed via base.MmInvoke() switch statement for maximum performance. Custom methods (1000+) are routed via dictionary lookup for flexibility and clean code.
Parameters
message The message to process. MmMessage
This implementation provides optimal performance for both standard and custom methods:
Fast path: Standard methods execute with ~100-150ns latency via switch statement
Slow path: Custom methods execute with ~300-500ns latency via dictionary lookup
Handler exceptions are caught and logged without disrupting other handlers
Unhandled custom methods invoke OnUnhandledCustomMethod() for custom error handling
Reimplemented from MercuryMessaging.MmBaseResponder.
Definition at line 120 of file MmExtendableResponder.cs.
References customHandlers, MercuryMessaging.MmMessage.MmMethod, and OnUnhandledCustomMethod().
MmOnAwakeComplete()
virtual void MercuryMessaging.MmResponder.MmOnAwakeComplete () virtual inherited
Post Awake callback used between objects implementing this interface.
This allows for initialization steps that must occur before one instance's Awake and its Start.
Implements MercuryMessaging.IMmResponder.
Definition at line 150 of file MmResponder.cs.
References MmAwakeCompleteCallback.
Referenced by Awake().
MmOnStartComplete()
virtual void MercuryMessaging.MmResponder.MmOnStartComplete () virtual inherited
Post Start callback used between objects implementing this interface This allows for initialization steps that must occur before one instance's Start and its first Update.
Implements MercuryMessaging.IMmResponder.
Definition at line 161 of file MmResponder.cs.
References MmStartCompleteCallback.
Referenced by Start().
MmRegisterAwakeCompleteCallback()
virtual void MercuryMessaging.MmResponder.MmRegisterAwakeCompleteCallback (IMmCallback callback) virtual inherited
It is possible that certain handles are not going to be in-place when registration of the OnAwakeComplete callback is invoked.
The is especially true in scenarios where MmRelayNodes are networked. This allows for a deferred registration, eliminating most instances where the Awake callback invocations fail.
Parameters
callback Callback to be registered.
Implements MercuryMessaging.IMmResponder.
Definition at line 175 of file MmResponder.cs.
References MercuryMessaging.IMmCallback(), and MmAwakeCompleteCallback.
MmRegisterStartCompleteCallback()
virtual void MercuryMessaging.MmResponder.MmRegisterStartCompleteCallback (IMmCallback callback) virtual inherited
It is possible that certain handles are not going to be in-place when registration of the OnStartComplete callback is invoked.
The is especially true in scenarios where MmRelayNodes are networked. This allows for a deferred registration, eliminating most instances where the Start callback invocations fail.
Parameters
callback Callback to be registered.
Implements MercuryMessaging.IMmResponder.
Definition at line 188 of file MmResponder.cs.
References MercuryMessaging.IMmCallback(), and MmStartCompleteCallback.
Referenced by MercuryMessaging.MmSwitchResponder.Awake().
OnUnhandledCustomMethod()
virtual void MercuryMessaging.MmExtendableResponder.OnUnhandledCustomMethod (MmMessage message) protected virtual
Called when a custom method has no registered handler.
Override to customize behavior (e.g., ignore vs. warn vs. error). Default implementation logs a helpful warning with registration instructions.
Parameters
message The unhandled message
Common override patterns:
Silent ignore: Override with empty method (no warning)
Strict error: Override to throw exception instead of logging warning
Fallback behavior: Override to provide default handling
Debug mode: Override to provide additional debugging information
// Example 1: Silent ignore (no warnings)
protected override void OnUnhandledCustomMethod(MmMessage message)
{
    // Do nothing - silently ignore unhandled messages
}
// Example 2: Strict error handling
protected override void OnUnhandledCustomMethod(MmMessage message)
{
    throw new InvalidOperationException(
        $"No handler registered for method {message.MmMethod}");
}
// Example 3: Fallback behavior
protected override void OnUnhandledCustomMethod(MmMessage message)
{
    // Provide default handling for all unregistered methods
    Debug.Log($"Using default handler for {message.MmMethod}");
}
Definition at line 335 of file MmExtendableResponder.cs.
References MercuryMessaging.MmMessage.MmMethod.
Referenced by MmInvoke().
ReceivedMessage() [1/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessage message) protected virtual inherited
Handle MmMethod: Base MmMessage.
Override this to handle base Mercury Messages.
Parameters
message MmMessage
Definition at line 211 of file MmBaseResponder.cs.
Referenced by MmInvoke().
ReceivedMessage() [2/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageBool message) protected virtual inherited
Handle MmMethod: MessageBool.
Override this to handle Mercury's bool messages.
Parameters
message MmMessageBool
Reimplemented in MercuryMessaging.Network.Backends.NetworkTestResponder.
Definition at line 220 of file MmBaseResponder.cs.
ReceivedMessage() [3/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageByteArray message) protected virtual inherited
Handle MmMethod: MessageByteArray.
Override this to handle Mercury's byte array messages.
Parameters
message MmMessageByteArray
Definition at line 229 of file MmBaseResponder.cs.
ReceivedMessage() [4/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageFloat message) protected virtual inherited
Handle MmMethod: MessageFloat.
Override this to handle Mercury's float messages.
Parameters
message MmMessageFloat
Reimplemented in MercuryMessaging.Network.Backends.NetworkTestResponder.
Definition at line 238 of file MmBaseResponder.cs.
ReceivedMessage() [5/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageInt message) protected virtual inherited
Handle MmMethod: MessageInt.
Override this to handle Mercury's int messages.
Parameters
message MmMessageInt
Reimplemented in MercuryMessaging.Network.Backends.NetworkTestResponder.
Definition at line 247 of file MmBaseResponder.cs.
ReceivedMessage() [6/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageQuaternion message) protected virtual inherited
Handle MmMethod: MessageQuaternion Override this to handle Mercury's Quaternion messages.
Parameters
message MmMessageQuaternion
Definition at line 310 of file MmBaseResponder.cs.
ReceivedMessage() [7/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageSerializable message) protected virtual inherited
Handle MmMethod: MessageSerializable.
Override this to handle Mercury's serializable messages.
Parameters
message MmMessageSerializable
Definition at line 256 of file MmBaseResponder.cs.
ReceivedMessage() [8/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageString message) protected virtual inherited
Handle MmMethod: MessageString Override this to handle Mercury's string messages.
Parameters
message MmMessageString
Reimplemented in MercuryMessaging.MmGuiResponder, and MercuryMessaging.Network.Backends.NetworkTestResponder.
Definition at line 265 of file MmBaseResponder.cs.
ReceivedMessage() [9/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageTransform message) protected virtual inherited
Handle MmMethod: MessageTransform Override this to handle Mercury's transform messages.
Parameters
message MmMessageTransform
Definition at line 274 of file MmBaseResponder.cs.
ReceivedMessage() [10/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageTransformList message) protected virtual inherited
Handle MmMethod: MessageTransformList Override this to handle Mercury's transform list messages.
Parameters
message MmMessageTransformList
Definition at line 283 of file MmBaseResponder.cs.
ReceivedMessage() [11/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageVector3 message) protected virtual inherited
Handle MmMethod: MessageVector3 Override this to handle Mercury's Vector3 messages.
Parameters
message MmMessageVector3
Reimplemented in MercuryMessaging.Network.Backends.NetworkTestResponder.
Definition at line 292 of file MmBaseResponder.cs.
ReceivedMessage() [12/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageVector4 message) protected virtual inherited
Handle MmMethod: MessageVector4 Override this to handle Mercury's Vector4 messages.
Parameters
message MmMessageVector4
Definition at line 301 of file MmBaseResponder.cs.
Refresh()
virtual void MercuryMessaging.MmBaseResponder.Refresh (List< MmTransform > transformList) virtual inherited
Handle MmMethod: Refresh.
Parameters
transformList List of transforms needed in refreshing an MmResponder.
Reimplemented in MercuryMessaging.Network.Backends.NetworkTestResponder.
Definition at line 175 of file MmBaseResponder.cs.
References MercuryMessaging.MmLogger.LogResponder.
Referenced by MmInvoke().
RegisterCustomHandler()
void MercuryMessaging.MmExtendableResponder.RegisterCustomHandler (MmMethod method, Action< MmMessage > handler) protected
Register a handler for a custom method (>= 1000).
Call this in Awake() to set up custom message handling.
Parameters
method Custom method enum (must be >= 1000). Values 0-999 are reserved for framework methods.
handler Handler function to invoke for this method. Receives the full MmMessage for type casting.
Exceptions
ArgumentException Thrown if method value is less than 1000
ArgumentNullException Thrown if handler is null
Registration best practices:
Register handlers in Awake() for optimal performance
Use method values >= 1000 (values 0-999 reserved for framework)
Duplicate registration overwrites the existing handler
Keep handler methods private for encapsulation
Type cast the message parameter inside the handler as needed
protected override void Awake()
{
    base.Awake();
    RegisterCustomHandler((MmMethod)1000, OnCustomMethod);
}
private void OnCustomMethod(MmMessage msg)
{
    var customMsg = (MyCustomMessage)msg;
    // Handle the custom message
}
Definition at line 190 of file MmExtendableResponder.cs.
References customHandlers, and MercuryMessaging.MmLogger.LogFramework.
SetActive()
virtual void MercuryMessaging.MmBaseResponder.SetActive (bool active) virtual inherited
Handle MmMethod: SetActive.
Parameters
active Value of active state.
Reimplemented in MercuryMessaging.MmGuiResponder, and MercuryMessaging.Network.Backends.NetworkTestResponder.
Definition at line 154 of file MmBaseResponder.cs.
References MercuryMessaging.MmLogger.LogResponder.
Referenced by MmInvoke().
Start()
virtual void MercuryMessaging.MmResponder.Start () virtual inherited
Start: Invokes MmOnStartComplete.
Reimplemented in MercuryMessaging.MmAppStateSwitchResponder, MercuryMessaging.MmRelayNode, MercuryMessaging.MmRelaySwitchNode, MercuryMessaging.MmSwitchResponder, and MercuryMessaging.Task.MmTaskManager< U >.
Definition at line 129 of file MmResponder.cs.
References MercuryMessaging.MmLogger.LogResponder, and MmOnStartComplete().
Switch()
virtual void MercuryMessaging.MmBaseResponder.Switch (string iName) protected virtual inherited
Handle MmMethod: Switch.
Parameters
iName Name of value in which to active.
Reimplemented in MercuryMessaging.MmSwitchResponder.
Definition at line 184 of file MmBaseResponder.cs.
Referenced by MmInvoke().
UnregisterCustomHandler()
void MercuryMessaging.MmExtendableResponder.UnregisterCustomHandler (MmMethod method) protected
Unregister a custom handler.
Useful for dynamic behavior changes. Safe to call even if the handler was never registered.
Parameters
method The custom method to unregister
Use cases for unregistration:
Dynamic behavior switching based on game state
Disabling handlers during cleanup
Replacing a handler with a different implementation
Note: This method is safe to call even if the method was never registered. No exception will be thrown.
// Temporarily disable a handler
UnregisterCustomHandler((MmMethod)1000);
// Re-register with different implementation
RegisterCustomHandler((MmMethod)1000, OnDifferentBehavior);
Definition at line 254 of file MmExtendableResponder.cs.
References customHandlers, and MercuryMessaging.MmLogger.LogFramework.
Update()
virtual void MercuryMessaging.MmResponder.Update () virtual inherited
Base Update of MmResponder Derived classes should always override.
Reimplemented in MercuryMessaging.MmTransformResponder, and MercuryMessaging.Task.MmTaskResponder< T >.
Definition at line 140 of file MmResponder.cs.
Member Data Documentation
_mmTag
MmTag MercuryMessaging.MmResponder._mmTag = MmTagHelper.Everything private inherited
Determines whether tag checking is enabled for this IMmResponder.
Definition at line 62 of file MmResponder.cs.
customHandlers
Dictionary<MmMethod, Action<MmMessage> > MercuryMessaging.MmExtendableResponder.customHandlers private
Dictionary storing custom method handlers.
Lazy-initialized on first RegisterCustomHandler() call to minimize memory overhead.
Definition at line 101 of file MmExtendableResponder.cs.
Referenced by HasCustomHandler(), MmInvoke(), RegisterCustomHandler(), and UnregisterCustomHandler().
receiveHandledMessages
bool MercuryMessaging.MmResponder.receiveHandledMessages = false private inherited
When true, this responder receives messages even if Handled=true.
Useful for logging, analytics, or handlers that need to see all messages. Default: false (responder skipped after message is handled). Similar to WPF's handledEventsToo parameter.
Definition at line 76 of file MmResponder.cs.
tagCheckEnabled
bool MercuryMessaging.MmResponder.tagCheckEnabled = true private inherited
By default IMmResponders have this set to true so that they receive all messages.
Definition at line 68 of file MmResponder.cs.
Referenced by MercuryMessaging.MmRelayNode.MmAddToRoutingTable().
Property Documentation
MmGameObject
GameObject MercuryMessaging.MmResponder.MmGameObject get inherited
Handle to an instance's GameObject.
Implements MercuryMessaging.IMmResponder.
Definition at line 81 of file MmResponder.cs.
ReceiveHandledMessages
bool MercuryMessaging.MmResponder.ReceiveHandledMessages get set inherited
When true, this responder receives messages even if Handled=true.
Useful for logging, analytics, or handlers that need to see all messages.
Definition at line 110 of file MmResponder.cs.
Tag
MmTag MercuryMessaging.MmResponder.Tag get set inherited
MmTags allow you to specify filters for execution in Mercury XM graphs.
Implements MercuryMessaging.IMmResponder.
Definition at line 90 of file MmResponder.cs.
Referenced by MercuryMessaging.MmTagExtensions.HasTag(), and MercuryMessaging.MmRelayNode.MmAddToRoutingTable().
TagCheckEnabled
bool MercuryMessaging.MmResponder.TagCheckEnabled get set inherited
Determines whether tag checking is enabled for this IMmResponder.
Implements MercuryMessaging.IMmResponder.
Definition at line 100 of file MmResponder.cs.
Referenced by MercuryMessaging.MmRelayNode.MmAddToRoutingTable(), and MercuryMessaging.MmRelayNode.TagCheck().
Event Documentation
MmAwakeCompleteCallback
IMmCallback MercuryMessaging.MmResponder.MmAwakeCompleteCallback private inherited
Event triggered in the MmResponder when this object is awoken.
Definition at line 50 of file MmResponder.cs.
Referenced by MmOnAwakeComplete(), and MmRegisterAwakeCompleteCallback().
MmStartCompleteCallback
IMmCallback MercuryMessaging.MmResponder.MmStartCompleteCallback private inherited
Event triggered in the MmResponder when this object is started.
Definition at line 56 of file MmResponder.cs.
Referenced by MmOnStartComplete(), and MmRegisterStartCompleteCallback().
The documentation for this class was generated from the following file:
Protocol/Responders/MmExtendableResponder.cs