MercuryMessaging: MercuryMessaging.Task.MmTaskSequenceBuilder< T > Class Template Reference
MercuryMessaging.Task.MmTaskSequenceBuilder< T > Class Template Reference
Fluent builder for configuring task sequences.
Public Member Functions
MmTaskSequenceBuilder< T > From (MmTaskManager< T > taskManager)
Set the task manager to configure.
MmTaskSequenceBuilder< T > OnTaskStart (Action< T > callback)
Set callback for when a task starts.
MmTaskSequenceBuilder< T > OnTaskComplete (Action< T > callback)
Set callback for when a task completes.
MmTaskSequenceBuilder< T > OnTaskChange (Action< T, T > callback)
Set callback for when task changes (provides previous and new task).
MmTaskSequenceBuilder< T > OnTaskChange (Action callback)
Set callback for when task changes (simplified, no parameters).
MmTaskSequenceBuilder< T > OnSequenceStart (Action callback)
Set callback for when the sequence starts.
MmTaskSequenceBuilder< T > OnSequenceComplete (Action callback)
Set callback for when all tasks are complete.
MmTaskSequenceBuilder< T > Where (Func< T, bool > predicate)
Filter which tasks are included in the sequence.
MmTaskSequenceBuilder< T > AutoAdvance ()
Enable auto-advance to next task when current completes.
MmTaskSequenceHandler< T > Build ()
Build and return a configured task sequence handler.
Private Attributes
MmTaskManager< T > _taskManager
Action< T > _onTaskStart
Action< T > _onTaskComplete
Action _onSequenceStart
Action _onSequenceComplete
Action< T, T > _onTaskChange
Func< T, bool > _taskFilter
bool _autoAdvance = false
Detailed Description
Fluent builder for configuring task sequences.
Provides a clean, chainable API for setting up task progression callbacks.
Example Usage:
MmTaskSequence.Create&lt;MmTaskInfo&gt;()
    .From(taskManager)
    .OnTaskStart(task => Debug.Log($"Started: {task.TaskName}"))
    .OnTaskComplete(task => SaveProgress())
    .OnSequenceComplete(() => ShowResults())
    .Build();
Template Parameters
T The task info type implementing IMmTaskInfo
Type Constraints
T : class
T : IMmTaskInfo
T : new()
Definition at line 28 of file MmTaskSequenceBuilder.cs.
Member Function Documentation
AutoAdvance()
MmTaskSequenceBuilder< T > MercuryMessaging.Task.MmTaskSequenceBuilder< T >.AutoAdvance ()
Enable auto-advance to next task when current completes.
Definition at line 120 of file MmTaskSequenceBuilder.cs.
References _autoAdvance.
Referenced by Build().
Build()
MmTaskSequenceHandler< T > MercuryMessaging.Task.MmTaskSequenceBuilder< T >.Build ()
Build and return a configured task sequence handler.
Definition at line 133 of file MmTaskSequenceBuilder.cs.
References _autoAdvance, _onSequenceComplete, _onSequenceStart, _onTaskChange, _onTaskComplete, _onTaskStart, _taskFilter, _taskManager, AutoAdvance(), OnSequenceComplete(), OnSequenceStart(), OnTaskChange(), OnTaskComplete(), and OnTaskStart().
From()
MmTaskSequenceBuilder< T > MercuryMessaging.Task.MmTaskSequenceBuilder< T >.From (MmTaskManager< T > taskManager)
Set the task manager to configure.
Definition at line 42 of file MmTaskSequenceBuilder.cs.
References _taskManager.
OnSequenceComplete()
MmTaskSequenceBuilder< T > MercuryMessaging.Task.MmTaskSequenceBuilder< T >.OnSequenceComplete (Action callback)
Set callback for when all tasks are complete.
Definition at line 98 of file MmTaskSequenceBuilder.cs.
References _onSequenceComplete.
Referenced by Build().
OnSequenceStart()
MmTaskSequenceBuilder< T > MercuryMessaging.Task.MmTaskSequenceBuilder< T >.OnSequenceStart (Action callback)
Set callback for when the sequence starts.
Definition at line 89 of file MmTaskSequenceBuilder.cs.
References _onSequenceStart.
Referenced by Build().
OnTaskChange() [1/2]
MmTaskSequenceBuilder< T > MercuryMessaging.Task.MmTaskSequenceBuilder< T >.OnTaskChange (Action callback)
Set callback for when task changes (simplified, no parameters).
Definition at line 80 of file MmTaskSequenceBuilder.cs.
References _onTaskChange.
OnTaskChange() [2/2]
MmTaskSequenceBuilder< T > MercuryMessaging.Task.MmTaskSequenceBuilder< T >.OnTaskChange (Action< T, T > callback)
Set callback for when task changes (provides previous and new task).
Definition at line 71 of file MmTaskSequenceBuilder.cs.
References _onTaskChange.
Referenced by Build().
OnTaskComplete()
MmTaskSequenceBuilder< T > MercuryMessaging.Task.MmTaskSequenceBuilder< T >.OnTaskComplete (Action< T > callback)
Set callback for when a task completes.
Definition at line 62 of file MmTaskSequenceBuilder.cs.
References _onTaskComplete.
Referenced by Build().
OnTaskStart()
MmTaskSequenceBuilder< T > MercuryMessaging.Task.MmTaskSequenceBuilder< T >.OnTaskStart (Action< T > callback)
Set callback for when a task starts.
Definition at line 53 of file MmTaskSequenceBuilder.cs.
References _onTaskStart.
Referenced by Build().
Where()
MmTaskSequenceBuilder< T > MercuryMessaging.Task.MmTaskSequenceBuilder< T >.Where (Func< T, bool > predicate)
Filter which tasks are included in the sequence.
Definition at line 111 of file MmTaskSequenceBuilder.cs.
References _taskFilter.
Member Data Documentation
_autoAdvance
bool MercuryMessaging.Task.MmTaskSequenceBuilder< T >._autoAdvance = false private
Definition at line 37 of file MmTaskSequenceBuilder.cs.
Referenced by AutoAdvance(), and Build().
_onSequenceComplete
Action MercuryMessaging.Task.MmTaskSequenceBuilder< T >._onSequenceComplete private
Definition at line 34 of file MmTaskSequenceBuilder.cs.
Referenced by Build(), and OnSequenceComplete().
_onSequenceStart
Action MercuryMessaging.Task.MmTaskSequenceBuilder< T >._onSequenceStart private
Definition at line 33 of file MmTaskSequenceBuilder.cs.
Referenced by Build(), and OnSequenceStart().
_onTaskChange
Action<T, T> MercuryMessaging.Task.MmTaskSequenceBuilder< T >._onTaskChange private
Definition at line 35 of file MmTaskSequenceBuilder.cs.
Referenced by Build(), OnTaskChange(), and OnTaskChange().
_onTaskComplete
Action<T> MercuryMessaging.Task.MmTaskSequenceBuilder< T >._onTaskComplete private
Definition at line 32 of file MmTaskSequenceBuilder.cs.
Referenced by Build(), and OnTaskComplete().
_onTaskStart
Action<T> MercuryMessaging.Task.MmTaskSequenceBuilder< T >._onTaskStart private
Definition at line 31 of file MmTaskSequenceBuilder.cs.
Referenced by Build(), and OnTaskStart().
_taskFilter
Func<T, bool> MercuryMessaging.Task.MmTaskSequenceBuilder< T >._taskFilter private
Definition at line 36 of file MmTaskSequenceBuilder.cs.
Referenced by Build(), and Where().
_taskManager
MmTaskManager<T> MercuryMessaging.Task.MmTaskSequenceBuilder< T >._taskManager private
Definition at line 30 of file MmTaskSequenceBuilder.cs.
Referenced by Build(), and From().
The documentation for this class was generated from the following file:
Task/MmTaskSequenceBuilder.cs