MercuryMessaging: MercuryMessaging.StandardLibrary.UI.MmUIResponder Class Reference
MercuryMessaging.StandardLibrary.UI.MmUIResponder Class Reference
Base responder for handling Standard Library UI messages.
Public Member Functions
override void MmInvoke (MmMessage message)
Routes messages to appropriate handlers.
virtual void SetActive (bool active)
Handle MmMethod: SetActive.
virtual void Initialize ()
Handle MmMethod: Initialize Initialize allows you to provide additional initialization logic in-between calls to Monobehavior provided Awake() and Start() calls.
virtual void Refresh (List< MmTransform > transformList)
Handle MmMethod: Refresh.
override MmRelayNode GetRelayNode ()
Implementation of IMmResponder's GetRelayNode.
virtual void Awake ()
Awake: Invokes MmOnAwakeComplete.
virtual void Start ()
Start: Invokes MmOnStartComplete.
virtual void Update ()
Base Update of MmResponder Derived classes should always override.
virtual void MmOnAwakeComplete ()
Post Awake callback used between objects implementing this interface.
virtual void MmOnStartComplete ()
Post Start callback used between objects implementing this interface This allows for initialization steps that must occur before one instance's Start and its first Update.
virtual void MmRegisterAwakeCompleteCallback (IMmCallback callback)
It is possible that certain handles are not going to be in-place when registration of the OnAwakeComplete callback is invoked.
virtual void MmRegisterStartCompleteCallback (IMmCallback callback)
It is possible that certain handles are not going to be in-place when registration of the OnStartComplete callback is invoked.
Protected Member Functions
virtual void ReceivedClick (MmUIClickMessage message)
Called when a click message is received.
virtual void ReceivedHover (MmUIHoverMessage message)
Called when a hover message is received.
virtual void ReceivedDrag (MmUIDragMessage message)
Called when a drag message is received.
virtual void ReceivedScroll (MmUIScrollMessage message)
Called when a scroll message is received.
virtual void ReceivedFocus (MmUIFocusMessage message)
Called when a focus message is received.
virtual void ReceivedSelect (MmUISelectMessage message)
Called when a select message is received.
virtual void ReceivedSubmit (MmUISubmitMessage message)
Called when a submit message is received.
virtual void ReceivedCancel (MmUICancelMessage message)
Called when a cancel message is received.
virtual void OnUnhandledUIMethod (MmMessage message)
Called when an unrecognized UI method is received.
virtual void Switch (string iName)
Handle MmMethod: Switch.
virtual void Complete (bool active)
Handle MmMethod: Switch.
virtual void ApplyTaskInfo (IMmSerializable serializableValue)
Handle MmMethod: TaskInfo Given a IMmSerializable, extract TaskInfo.
virtual void ReceivedMessage (MmMessage message)
Handle MmMethod: Base MmMessage.
virtual void ReceivedMessage (MmMessageBool message)
Handle MmMethod: MessageBool.
virtual void ReceivedMessage (MmMessageByteArray message)
Handle MmMethod: MessageByteArray.
virtual void ReceivedMessage (MmMessageFloat message)
Handle MmMethod: MessageFloat.
virtual void ReceivedMessage (MmMessageInt message)
Handle MmMethod: MessageInt.
virtual void ReceivedMessage (MmMessageSerializable message)
Handle MmMethod: MessageSerializable.
virtual void ReceivedMessage (MmMessageString message)
Handle MmMethod: MessageString Override this to handle Mercury's string messages.
virtual void ReceivedMessage (MmMessageTransform message)
Handle MmMethod: MessageTransform Override this to handle Mercury's transform messages.
virtual void ReceivedMessage (MmMessageTransformList message)
Handle MmMethod: MessageTransformList Override this to handle Mercury's transform list messages.
virtual void ReceivedMessage (MmMessageVector3 message)
Handle MmMethod: MessageVector3 Override this to handle Mercury's Vector3 messages.
virtual void ReceivedMessage (MmMessageVector4 message)
Handle MmMethod: MessageVector4 Override this to handle Mercury's Vector4 messages.
virtual void ReceivedMessage (MmMessageQuaternion message)
Handle MmMethod: MessageQuaternion Override this to handle Mercury's Quaternion messages.
Properties
GameObject MmGameObject [get]
Handle to an instance's GameObject.
MmTag Tag [get, set]
MmTags allow you to specify filters for execution in Mercury XM graphs.
bool TagCheckEnabled [get, set]
Determines whether tag checking is enabled for this IMmResponder.
bool ReceiveHandledMessages [get, set]
When true, this responder receives messages even if Handled=true.
Events
IMmCallback MmAwakeCompleteCallback
Event triggered in the MmResponder when this object is awoken.
IMmCallback MmStartCompleteCallback
Event triggered in the MmResponder when this object is started.
Private Member Functions
void DispatchUIMessage (MmMessage message)
Dispatches UI messages to the appropriate virtual handler.
Private Attributes
MmTag _mmTag = MmTagHelper.Everything
Determines whether tag checking is enabled for this IMmResponder.
bool tagCheckEnabled = true
By default IMmResponders have this set to true so that they receive all messages.
bool receiveHandledMessages = false
When true, this responder receives messages even if Handled=true.
Detailed Description
Base responder for handling Standard Library UI messages.
Extends MmBaseResponder with type-safe handling for UI events.
UI messages use MmMethod values 100-199, which are routed through MmInvoke and dispatched to virtual handler methods.
Usage: Extend this class and override the relevant virtual methods to handle UI events. All handlers are virtual and do nothing by default.
Performance: UI method dispatch uses a switch statement for efficiency, similar to standard MmBaseResponder message handling.
public class MyUIHandler : MmUIResponder
{
    protected override void ReceivedClick(MmUIClickMessage msg)
    {
        Debug.Log($"Click at {msg.Position}");
        if (msg.IsDoubleClick) OpenItem();
    }
    protected override void ReceivedHover(MmUIHoverMessage msg)
    {
        if (msg.IsEnter) ShowTooltip();
        else HideTooltip();
    }
    protected override void ReceivedDrag(MmUIDragMessage msg)
    {
        if (msg.Phase == MmDragPhase.Move)
            transform.position += (Vector3)msg.Delta;
    }
}
Definition at line 55 of file MmUIResponder.cs.
Member Function Documentation
ApplyTaskInfo()
virtual void MercuryMessaging.MmBaseResponder.ApplyTaskInfo (IMmSerializable serializableValue) protected virtual inherited
Handle MmMethod: TaskInfo Given a IMmSerializable, extract TaskInfo.
Parameters
serializableValue Serializable class containing MmTask Info
Definition at line 202 of file MmBaseResponder.cs.
Referenced by MmInvoke().
Awake()
virtual void MercuryMessaging.MmResponder.Awake () virtual inherited
Awake: Invokes MmOnAwakeComplete.
Reimplemented in MercuryMessaging.MmGuiResponder, MercuryMessaging.MmRelayAppStateNode, MercuryMessaging.MmRelayNode, MercuryMessaging.MmRelaySwitchNode, MercuryMessaging.MmSwitchResponder, MercuryMessaging.Task.MmTaskManager< U >, and MercuryMessaging.Task.MmTaskResponder< T >.
Definition at line 119 of file MmResponder.cs.
References MercuryMessaging.MmLogger.LogResponder, and MmOnAwakeComplete().
Complete()
virtual void MercuryMessaging.MmBaseResponder.Complete (bool active) protected virtual inherited
Handle MmMethod: Switch.
Parameters
active Can be used to indicate active state of object that triggered complete message
Definition at line 193 of file MmBaseResponder.cs.
Referenced by MmInvoke().
DispatchUIMessage()
void MercuryMessaging.StandardLibrary.UI.MmUIResponder.DispatchUIMessage (MmMessage message) private
Dispatches UI messages to the appropriate virtual handler.
Definition at line 83 of file MmUIResponder.cs.
References MercuryMessaging.MmMessage.MmMethod, OnUnhandledUIMethod(), ReceivedCancel(), ReceivedClick(), ReceivedDrag(), ReceivedFocus(), ReceivedHover(), ReceivedScroll(), ReceivedSelect(), and ReceivedSubmit().
Referenced by MmInvoke().
GetRelayNode()
override MmRelayNode MercuryMessaging.MmBaseResponder.GetRelayNode () inherited
Implementation of IMmResponder's GetRelayNode.
Returns
Returns MmRelayNode if one attached to GameObject, Otherwise returns NULL.
Implements MercuryMessaging.IMmResponder.
Definition at line 320 of file MmBaseResponder.cs.
Referenced by MercuryMessaging.MmMessagingExtensions.BroadcastInitialize(), MercuryMessaging.MmMessagingExtensions.BroadcastRefresh(), MercuryMessaging.MmMessagingExtensions.BroadcastSetActive(), MercuryMessaging.MmMessagingExtensions.BroadcastSwitch(), MercuryMessaging.MmMessagingExtensions.BroadcastValue(), MercuryMessaging.MmMessagingExtensions.BroadcastValue(), MercuryMessaging.MmMessagingExtensions.BroadcastValue(), MercuryMessaging.MmMessagingExtensions.BroadcastValue(), MercuryMessaging.MmResponderExtensions.Build(), MercuryMessaging.MmListenerExtensions.ClearAllListeners(), MercuryMessaging.MmQueryExtensions.FindByName(), MercuryMessaging.MmQueryExtensions.FindByPattern(), MercuryMessaging.MmListenerExtensions.GetListenerCount(), MercuryMessaging.MmQueryExtensions.HasSiblings(), MercuryMessaging.MmListenerExtensions.ListenFor(), MercuryMessaging.MmMessagingExtensions.NotifyComplete(), MercuryMessaging.MmMessagingExtensions.NotifyValue(), MercuryMessaging.MmMessagingExtensions.NotifyValue(), MercuryMessaging.MmMessagingExtensions.NotifyValue(), MercuryMessaging.MmMessagingExtensions.NotifyValue(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.On6DOF(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnAxis(), MercuryMessaging.MmListenerExtensions.OnBool(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnButton(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnClick(), MercuryMessaging.MmListenerExtensions.OnComplete(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnDrag(), MercuryMessaging.MmListenerExtensions.OnFloat(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnFocus(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnGaze(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnGesture(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnHover(), MercuryMessaging.MmListenerExtensions.OnInitialize(), MercuryMessaging.MmListenerExtensions.OnInt(), MercuryMessaging.MmListenerExtensions.OnRefresh(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnScroll(), MercuryMessaging.StandardLibrary.MmStandardLibraryListenerExtensions.OnSelect(), MercuryMessaging.MmListenerExtensions.OnSetActive(), MercuryMessaging.MmListenerExtensions.OnString(), MercuryMessaging.MmListenerExtensions.OnSwitch(), MercuryMessaging.MmListenerExtensions.OnVector3(), MercuryMessaging.MmQueryExtensions.Query(), MercuryMessaging.MmRoutingExtensions.RegisterWith(), MercuryMessaging.MmMessagingExtensions.Send(), MercuryMessaging.MmMessagingExtensions.Send(), MercuryMessaging.MmMessagingExtensions.Send(), MercuryMessaging.MmQueryExtensions.SiblingCount(), MercuryMessaging.MmResponderExtensions.To(), MercuryMessaging.MmRoutingExtensions.UnregisterFrom(), and MercuryMessaging.MmTransformResponder.Update().
Initialize()
virtual void MercuryMessaging.MmBaseResponder.Initialize () virtual inherited
Handle MmMethod: Initialize Initialize allows you to provide additional initialization logic in-between calls to Monobehavior provided Awake() and Start() calls.
Reimplemented in MercuryMessaging.Network.Backends.NetworkTestResponder.
Definition at line 166 of file MmBaseResponder.cs.
References MercuryMessaging.MmLogger.LogResponder.
Referenced by MmInvoke().
MmInvoke()
override void MercuryMessaging.StandardLibrary.UI.MmUIResponder.MmInvoke (MmMessage message) virtual
Routes messages to appropriate handlers.
UI messages (100-199) are handled by this class; all others are passed to base MmBaseResponder.
Parameters
message The message to process
Reimplemented from MercuryMessaging.MmBaseResponder.
Definition at line 65 of file MmUIResponder.cs.
References DispatchUIMessage(), and MercuryMessaging.MmMessage.MmMethod.
MmOnAwakeComplete()
virtual void MercuryMessaging.MmResponder.MmOnAwakeComplete () virtual inherited
Post Awake callback used between objects implementing this interface.
This allows for initialization steps that must occur before one instance's Awake and its Start.
Implements MercuryMessaging.IMmResponder.
Definition at line 150 of file MmResponder.cs.
References MmAwakeCompleteCallback.
Referenced by Awake().
MmOnStartComplete()
virtual void MercuryMessaging.MmResponder.MmOnStartComplete () virtual inherited
Post Start callback used between objects implementing this interface This allows for initialization steps that must occur before one instance's Start and its first Update.
Implements MercuryMessaging.IMmResponder.
Definition at line 161 of file MmResponder.cs.
References MmStartCompleteCallback.
Referenced by Start().
MmRegisterAwakeCompleteCallback()
virtual void MercuryMessaging.MmResponder.MmRegisterAwakeCompleteCallback (IMmCallback callback) virtual inherited
It is possible that certain handles are not going to be in-place when registration of the OnAwakeComplete callback is invoked.
The is especially true in scenarios where MmRelayNodes are networked. This allows for a deferred registration, eliminating most instances where the Awake callback invocations fail.
Parameters
callback Callback to be registered.
Implements MercuryMessaging.IMmResponder.
Definition at line 175 of file MmResponder.cs.
References MercuryMessaging.IMmCallback(), and MmAwakeCompleteCallback.
MmRegisterStartCompleteCallback()
virtual void MercuryMessaging.MmResponder.MmRegisterStartCompleteCallback (IMmCallback callback) virtual inherited
It is possible that certain handles are not going to be in-place when registration of the OnStartComplete callback is invoked.
The is especially true in scenarios where MmRelayNodes are networked. This allows for a deferred registration, eliminating most instances where the Start callback invocations fail.
Parameters
callback Callback to be registered.
Implements MercuryMessaging.IMmResponder.
Definition at line 188 of file MmResponder.cs.
References MercuryMessaging.IMmCallback(), and MmStartCompleteCallback.
Referenced by MercuryMessaging.MmSwitchResponder.Awake().
OnUnhandledUIMethod()
virtual void MercuryMessaging.StandardLibrary.UI.MmUIResponder.OnUnhandledUIMethod (MmMessage message) protected virtual
Called when an unrecognized UI method is received.
Override to customize handling of unknown UI methods.
Parameters
message The unhandled message
Definition at line 214 of file MmUIResponder.cs.
References MercuryMessaging.MmLogger.LogFramework.
Referenced by DispatchUIMessage().
ReceivedCancel()
virtual void MercuryMessaging.StandardLibrary.UI.MmUIResponder.ReceivedCancel (MmUICancelMessage message) protected virtual
Called when a cancel message is received.
Override to handle cancellation events.
Parameters
message The cancel message with optional reason
Definition at line 204 of file MmUIResponder.cs.
Referenced by DispatchUIMessage().
ReceivedClick()
virtual void MercuryMessaging.StandardLibrary.UI.MmUIResponder.ReceivedClick (MmUIClickMessage message) protected virtual
Called when a click message is received.
Override to handle click/tap events.
Parameters
message The click message with position, click count, and button info
Definition at line 134 of file MmUIResponder.cs.
Referenced by DispatchUIMessage().
ReceivedDrag()
virtual void MercuryMessaging.StandardLibrary.UI.MmUIResponder.ReceivedDrag (MmUIDragMessage message) protected virtual
Called when a drag message is received.
Override to handle drag begin/move/end events.
Parameters
message The drag message with position, delta, and phase
Definition at line 154 of file MmUIResponder.cs.
Referenced by DispatchUIMessage().
ReceivedFocus()
virtual void MercuryMessaging.StandardLibrary.UI.MmUIResponder.ReceivedFocus (MmUIFocusMessage message) protected virtual
Called when a focus message is received.
Override to handle focus gained/lost events.
Parameters
message The focus message with focus state and element ID
Definition at line 174 of file MmUIResponder.cs.
Referenced by DispatchUIMessage().
ReceivedHover()
virtual void MercuryMessaging.StandardLibrary.UI.MmUIResponder.ReceivedHover (MmUIHoverMessage message) protected virtual
Called when a hover message is received.
Override to handle pointer enter/exit events.
Parameters
message The hover message with position and enter/exit state
Definition at line 144 of file MmUIResponder.cs.
Referenced by DispatchUIMessage().
ReceivedMessage() [1/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessage message) protected virtual inherited
Handle MmMethod: Base MmMessage.
Override this to handle base Mercury Messages.
Parameters
message MmMessage
Definition at line 211 of file MmBaseResponder.cs.
Referenced by MmInvoke().
ReceivedMessage() [2/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageBool message) protected virtual inherited
Handle MmMethod: MessageBool.
Override this to handle Mercury's bool messages.
Parameters
message MmMessageBool
Reimplemented in MercuryMessaging.Network.Backends.NetworkTestResponder.
Definition at line 220 of file MmBaseResponder.cs.
ReceivedMessage() [3/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageByteArray message) protected virtual inherited
Handle MmMethod: MessageByteArray.
Override this to handle Mercury's byte array messages.
Parameters
message MmMessageByteArray
Definition at line 229 of file MmBaseResponder.cs.
ReceivedMessage() [4/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageFloat message) protected virtual inherited
Handle MmMethod: MessageFloat.
Override this to handle Mercury's float messages.
Parameters
message MmMessageFloat
Reimplemented in MercuryMessaging.Network.Backends.NetworkTestResponder.
Definition at line 238 of file MmBaseResponder.cs.
ReceivedMessage() [5/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageInt message) protected virtual inherited
Handle MmMethod: MessageInt.
Override this to handle Mercury's int messages.
Parameters
message MmMessageInt
Reimplemented in MercuryMessaging.Network.Backends.NetworkTestResponder.
Definition at line 247 of file MmBaseResponder.cs.
ReceivedMessage() [6/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageQuaternion message) protected virtual inherited
Handle MmMethod: MessageQuaternion Override this to handle Mercury's Quaternion messages.
Parameters
message MmMessageQuaternion
Definition at line 310 of file MmBaseResponder.cs.
ReceivedMessage() [7/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageSerializable message) protected virtual inherited
Handle MmMethod: MessageSerializable.
Override this to handle Mercury's serializable messages.
Parameters
message MmMessageSerializable
Definition at line 256 of file MmBaseResponder.cs.
ReceivedMessage() [8/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageString message) protected virtual inherited
Handle MmMethod: MessageString Override this to handle Mercury's string messages.
Parameters
message MmMessageString
Reimplemented in MercuryMessaging.MmGuiResponder, and MercuryMessaging.Network.Backends.NetworkTestResponder.
Definition at line 265 of file MmBaseResponder.cs.
ReceivedMessage() [9/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageTransform message) protected virtual inherited
Handle MmMethod: MessageTransform Override this to handle Mercury's transform messages.
Parameters
message MmMessageTransform
Definition at line 274 of file MmBaseResponder.cs.
ReceivedMessage() [10/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageTransformList message) protected virtual inherited
Handle MmMethod: MessageTransformList Override this to handle Mercury's transform list messages.
Parameters
message MmMessageTransformList
Definition at line 283 of file MmBaseResponder.cs.
ReceivedMessage() [11/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageVector3 message) protected virtual inherited
Handle MmMethod: MessageVector3 Override this to handle Mercury's Vector3 messages.
Parameters
message MmMessageVector3
Reimplemented in MercuryMessaging.Network.Backends.NetworkTestResponder.
Definition at line 292 of file MmBaseResponder.cs.
ReceivedMessage() [12/12]
virtual void MercuryMessaging.MmBaseResponder.ReceivedMessage (MmMessageVector4 message) protected virtual inherited
Handle MmMethod: MessageVector4 Override this to handle Mercury's Vector4 messages.
Parameters
message MmMessageVector4
Definition at line 301 of file MmBaseResponder.cs.
ReceivedScroll()
virtual void MercuryMessaging.StandardLibrary.UI.MmUIResponder.ReceivedScroll (MmUIScrollMessage message) protected virtual
Called when a scroll message is received.
Override to handle scroll wheel or touch scroll events.
Parameters
message The scroll message with position and scroll delta
Definition at line 164 of file MmUIResponder.cs.
Referenced by DispatchUIMessage().
ReceivedSelect()
virtual void MercuryMessaging.StandardLibrary.UI.MmUIResponder.ReceivedSelect (MmUISelectMessage message) protected virtual
Called when a select message is received.
Override to handle selection change events.
Parameters
message The select message with selected index and value
Definition at line 184 of file MmUIResponder.cs.
Referenced by DispatchUIMessage().
ReceivedSubmit()
virtual void MercuryMessaging.StandardLibrary.UI.MmUIResponder.ReceivedSubmit (MmUISubmitMessage message) protected virtual
Called when a submit message is received.
Override to handle form submission or confirmation events.
Parameters
message The submit message with optional data
Definition at line 194 of file MmUIResponder.cs.
Referenced by DispatchUIMessage().
Refresh()
virtual void MercuryMessaging.MmBaseResponder.Refresh (List< MmTransform > transformList) virtual inherited
Handle MmMethod: Refresh.
Parameters
transformList List of transforms needed in refreshing an MmResponder.
Reimplemented in MercuryMessaging.Network.Backends.NetworkTestResponder.
Definition at line 175 of file MmBaseResponder.cs.
References MercuryMessaging.MmLogger.LogResponder.
Referenced by MmInvoke().
SetActive()
virtual void MercuryMessaging.MmBaseResponder.SetActive (bool active) virtual inherited
Handle MmMethod: SetActive.
Parameters
active Value of active state.
Reimplemented in MercuryMessaging.MmGuiResponder, and MercuryMessaging.Network.Backends.NetworkTestResponder.
Definition at line 154 of file MmBaseResponder.cs.
References MercuryMessaging.MmLogger.LogResponder.
Referenced by MmInvoke().
Start()
virtual void MercuryMessaging.MmResponder.Start () virtual inherited
Start: Invokes MmOnStartComplete.
Reimplemented in MercuryMessaging.MmAppStateSwitchResponder, MercuryMessaging.MmRelayNode, MercuryMessaging.MmRelaySwitchNode, MercuryMessaging.MmSwitchResponder, and MercuryMessaging.Task.MmTaskManager< U >.
Definition at line 129 of file MmResponder.cs.
References MercuryMessaging.MmLogger.LogResponder, and MmOnStartComplete().
Switch()
virtual void MercuryMessaging.MmBaseResponder.Switch (string iName) protected virtual inherited
Handle MmMethod: Switch.
Parameters
iName Name of value in which to active.
Reimplemented in MercuryMessaging.MmSwitchResponder.
Definition at line 184 of file MmBaseResponder.cs.
Referenced by MmInvoke().
Update()
virtual void MercuryMessaging.MmResponder.Update () virtual inherited
Base Update of MmResponder Derived classes should always override.
Reimplemented in MercuryMessaging.MmTransformResponder, and MercuryMessaging.Task.MmTaskResponder< T >.
Definition at line 140 of file MmResponder.cs.
Member Data Documentation
_mmTag
MmTag MercuryMessaging.MmResponder._mmTag = MmTagHelper.Everything private inherited
Determines whether tag checking is enabled for this IMmResponder.
Definition at line 62 of file MmResponder.cs.
receiveHandledMessages
bool MercuryMessaging.MmResponder.receiveHandledMessages = false private inherited
When true, this responder receives messages even if Handled=true.
Useful for logging, analytics, or handlers that need to see all messages. Default: false (responder skipped after message is handled). Similar to WPF's handledEventsToo parameter.
Definition at line 76 of file MmResponder.cs.
tagCheckEnabled
bool MercuryMessaging.MmResponder.tagCheckEnabled = true private inherited
By default IMmResponders have this set to true so that they receive all messages.
Definition at line 68 of file MmResponder.cs.
Referenced by MercuryMessaging.MmRelayNode.MmAddToRoutingTable().
Property Documentation
MmGameObject
GameObject MercuryMessaging.MmResponder.MmGameObject get inherited
Handle to an instance's GameObject.
Implements MercuryMessaging.IMmResponder.
Definition at line 81 of file MmResponder.cs.
ReceiveHandledMessages
bool MercuryMessaging.MmResponder.ReceiveHandledMessages get set inherited
When true, this responder receives messages even if Handled=true.
Useful for logging, analytics, or handlers that need to see all messages.
Definition at line 110 of file MmResponder.cs.
Tag
MmTag MercuryMessaging.MmResponder.Tag get set inherited
MmTags allow you to specify filters for execution in Mercury XM graphs.
Implements MercuryMessaging.IMmResponder.
Definition at line 90 of file MmResponder.cs.
Referenced by MercuryMessaging.MmTagExtensions.HasTag(), and MercuryMessaging.MmRelayNode.MmAddToRoutingTable().
TagCheckEnabled
bool MercuryMessaging.MmResponder.TagCheckEnabled get set inherited
Determines whether tag checking is enabled for this IMmResponder.
Implements MercuryMessaging.IMmResponder.
Definition at line 100 of file MmResponder.cs.
Referenced by MercuryMessaging.MmRelayNode.MmAddToRoutingTable(), and MercuryMessaging.MmRelayNode.TagCheck().
Event Documentation
MmAwakeCompleteCallback
IMmCallback MercuryMessaging.MmResponder.MmAwakeCompleteCallback private inherited
Event triggered in the MmResponder when this object is awoken.
Definition at line 50 of file MmResponder.cs.
Referenced by MmOnAwakeComplete(), and MmRegisterAwakeCompleteCallback().
MmStartCompleteCallback
IMmCallback MercuryMessaging.MmResponder.MmStartCompleteCallback private inherited
Event triggered in the MmResponder when this object is started.
Definition at line 56 of file MmResponder.cs.
Referenced by MmOnStartComplete(), and MmRegisterStartCompleteCallback().
The documentation for this class was generated from the following file:
StandardLibrary/UI/MmUIResponder.cs