MercuryMessaging: MercuryMessaging.Network.MmStateTracker Class Reference
MercuryMessaging.Network.MmStateTracker Class Reference
Tracks state for a single networked object and computes deltas.
Public Member Functions
MmStateTracker (uint netId)
void RegisterField (ushort fieldId, MmDeltaFieldType type)
Register a field to be tracked.
void SetFieldValue (ushort fieldId, object value)
Update a tracked field's value.
MmStateDelta ComputeDelta ()
Compute delta between current and last sent state.
MmStateDelta CreateFullSnapshot ()
Create a full state snapshot (for new connections or resync).
void MarkAsSent ()
Mark current state as sent (update baseline for next delta).
void ApplyDelta (MmStateDelta delta)
Apply a delta to the current state.
bool TryGetFieldValue< T > (ushort fieldId, out T value)
Get current value of a field.
Properties
uint NetId [get]
Network ID of the tracked object.
uint CurrentSequence [get, private set]
Current sequence number for this tracker.
uint AckedSequence [get, set]
Last acknowledged sequence number by remote.
Private Member Functions
bool ValuesEqual (object a, object b)
byte[] SerializeValue (object value, MmDeltaFieldType type)
object DeserializeValue (byte[] data, MmDeltaFieldType type)
Private Attributes
readonly Dictionary< ushort, object > _currentState = new Dictionary<ushort, object>()
readonly Dictionary< ushort, object > _lastSentState = new Dictionary<ushort, object>()
readonly Dictionary< ushort, MmDeltaFieldType > _fieldTypes = new Dictionary<ushort, MmDeltaFieldType>()
Detailed Description
Tracks state for a single networked object and computes deltas.
Definition at line 100 of file MmStateDelta.cs.
Constructor & Destructor Documentation
MmStateTracker()
MercuryMessaging.Network.MmStateTracker.MmStateTracker (uint netId)
Definition at line 121 of file MmStateDelta.cs.
References AckedSequence, CurrentSequence, and NetId.
Member Function Documentation
ApplyDelta()
void MercuryMessaging.Network.MmStateTracker.ApplyDelta (MmStateDelta delta)
Apply a delta to the current state.
Definition at line 237 of file MmStateDelta.cs.
References _currentState, and DeserializeValue().
ComputeDelta()
MmStateDelta MercuryMessaging.Network.MmStateTracker.ComputeDelta ()
Compute delta between current and last sent state.
Returns
Delta containing only changed fields, or null if no changes
Definition at line 148 of file MmStateDelta.cs.
References _currentState, _fieldTypes, _lastSentState, AckedSequence, CurrentSequence, NetId, SerializeValue(), and ValuesEqual().
CreateFullSnapshot()
MmStateDelta MercuryMessaging.Network.MmStateTracker.CreateFullSnapshot ()
Create a full state snapshot (for new connections or resync).
Definition at line 192 of file MmStateDelta.cs.
References _currentState, _fieldTypes, CurrentSequence, NetId, and SerializeValue().
DeserializeValue()
object MercuryMessaging.Network.MmStateTracker.DeserializeValue (byte[] data, MmDeltaFieldType type) private
Definition at line 343 of file MmStateDelta.cs.
References MercuryMessaging.MmTransform, MercuryMessaging.Network.Quaternion, MercuryMessaging.Network.Vector3, and MercuryMessaging.Network.Vector4.
Referenced by ApplyDelta().
MarkAsSent()
void MercuryMessaging.Network.MmStateTracker.MarkAsSent ()
Mark current state as sent (update baseline for next delta).
Definition at line 225 of file MmStateDelta.cs.
References _currentState, and _lastSentState.
RegisterField()
void MercuryMessaging.Network.MmStateTracker.RegisterField (ushort fieldId, MmDeltaFieldType type)
Register a field to be tracked.
Definition at line 131 of file MmStateDelta.cs.
References _fieldTypes.
SerializeValue()
byte[] MercuryMessaging.Network.MmStateTracker.SerializeValue (object value, MmDeltaFieldType type) private
Definition at line 279 of file MmStateDelta.cs.
References MercuryMessaging.Network.Quaternion, MercuryMessaging.Network.Vector3, and MercuryMessaging.Network.Vector4.
Referenced by ComputeDelta(), and CreateFullSnapshot().
SetFieldValue()
void MercuryMessaging.Network.MmStateTracker.SetFieldValue (ushort fieldId, object value)
Update a tracked field's value.
Definition at line 139 of file MmStateDelta.cs.
References _currentState.
TryGetFieldValue< T >()
bool MercuryMessaging.Network.MmStateTracker.TryGetFieldValue< T > (ushort fieldId, out T value)
Get current value of a field.
Definition at line 248 of file MmStateDelta.cs.
References _currentState.
ValuesEqual()
bool MercuryMessaging.Network.MmStateTracker.ValuesEqual (object a, object b) private
Definition at line 259 of file MmStateDelta.cs.
References MercuryMessaging.Network.Quaternion, and MercuryMessaging.Network.Vector3.
Referenced by ComputeDelta().
Member Data Documentation
_currentState
readonly Dictionary<ushort, object> MercuryMessaging.Network.MmStateTracker._currentState = new Dictionary<ushort, object>() private
Definition at line 102 of file MmStateDelta.cs.
Referenced by ApplyDelta(), ComputeDelta(), CreateFullSnapshot(), MarkAsSent(), SetFieldValue(), and TryGetFieldValue< T >().
_fieldTypes
readonly Dictionary<ushort, MmDeltaFieldType> MercuryMessaging.Network.MmStateTracker._fieldTypes = new Dictionary<ushort, MmDeltaFieldType>() private
Definition at line 104 of file MmStateDelta.cs.
Referenced by ComputeDelta(), CreateFullSnapshot(), and RegisterField().
_lastSentState
readonly Dictionary<ushort, object> MercuryMessaging.Network.MmStateTracker._lastSentState = new Dictionary<ushort, object>() private
Definition at line 103 of file MmStateDelta.cs.
Referenced by ComputeDelta(), and MarkAsSent().
Property Documentation
AckedSequence
uint MercuryMessaging.Network.MmStateTracker.AckedSequence get set
Last acknowledged sequence number by remote.
Definition at line 119 of file MmStateDelta.cs.
Referenced by MmStateTracker(), and ComputeDelta().
CurrentSequence
uint MercuryMessaging.Network.MmStateTracker.CurrentSequence get private set
Current sequence number for this tracker.
Definition at line 114 of file MmStateDelta.cs.
Referenced by MmStateTracker(), ComputeDelta(), and CreateFullSnapshot().
NetId
uint MercuryMessaging.Network.MmStateTracker.NetId get
Network ID of the tracked object.
Definition at line 109 of file MmStateDelta.cs.
Referenced by MmStateTracker(), ComputeDelta(), and CreateFullSnapshot().
The documentation for this class was generated from the following file:
Protocol/Network/MmStateDelta.cs