MercuryMessaging: MercuryMessaging.Network.MmReader Class Reference
MercuryMessaging.Network.MmReader Class Reference sealed
High-performance binary reader for deserialization.
Public Member Functions
MmReader (byte[] buffer)
Create a reader wrapping the given byte array.
MmReader (byte[] buffer, int offset, int count)
Create a reader for a portion of a byte array.
byte ReadByte ()
sbyte ReadSByte ()
bool ReadBool ()
short ReadShort ()
ushort ReadUShort ()
int ReadInt ()
uint ReadUInt ()
long ReadLong ()
ulong ReadULong ()
float ReadFloat ()
double ReadDouble ()
string ReadString ()
Read a string with length prefix (ushort).
byte[] ReadBytes ()
Read a byte array with length prefix (int).
void ReadRawBytes (byte[] destination, int destinationOffset, int count)
Read raw bytes without length prefix.
void Skip (int count)
Skip a number of bytes without reading them.
Vector2 ReadVector2 ()
Vector3 ReadVector3 ()
Vector4 ReadVector4 ()
Quaternion ReadQuaternion ()
Color ReadColor ()
Color32 ReadColor32 ()
void Reset ()
Reset the reader position to the start.
void Seek (int position)
Seek to a specific position.
Properties
int Position [get]
Current read position.
int Length [get]
Total length of readable data.
int Remaining [get]
Number of bytes remaining to read.
bool IsAtEnd [get]
Whether we've reached the end of the buffer.
Private Member Functions
void EnsureAvailable (int count)
Private Attributes
readonly byte[] _buffer
readonly int _length
int _position
Static Private Attributes
static readonly Encoding Utf8 = Encoding.UTF8
Detailed Description
High-performance binary reader for deserialization.
Operates directly on the source byte array without additional allocations.
Usage:
var reader = new MmReader(data);
int value = reader.ReadInt();
string text = reader.ReadString();
Definition at line 24 of file MmReader.cs.
Constructor & Destructor Documentation
MmReader() [1/2]
MercuryMessaging.Network.MmReader.MmReader (byte[] buffer)
Create a reader wrapping the given byte array.
Definition at line 36 of file MmReader.cs.
References _buffer, _length, and _position.
MmReader() [2/2]
MercuryMessaging.Network.MmReader.MmReader (byte[] buffer, int offset, int count)
Create a reader for a portion of a byte array.
Definition at line 46 of file MmReader.cs.
References _buffer, _length, and _position.
Member Function Documentation
EnsureAvailable()
void MercuryMessaging.Network.MmReader.EnsureAvailable (int count) private
Definition at line 278 of file MmReader.cs.
References _length, and _position.
Referenced by ReadBool(), ReadByte(), ReadBytes(), ReadDouble(), ReadFloat(), ReadInt(), ReadLong(), ReadRawBytes(), ReadSByte(), ReadShort(), ReadString(), ReadUInt(), ReadULong(), ReadUShort(), and Skip().
ReadBool()
bool MercuryMessaging.Network.MmReader.ReadBool ()
Definition at line 92 of file MmReader.cs.
References _buffer, _position, and EnsureAvailable().
Referenced by MercuryMessaging.Network.MmBinarySerializer.ReadObjectValuePooled(), MercuryMessaging.Network.MmBinarySerializer.ReadPayloadPooled(), and MercuryMessaging.Network.MmBinarySerializer.ReadTransformDataPooled().
ReadByte()
byte MercuryMessaging.Network.MmReader.ReadByte ()
Definition at line 80 of file MmReader.cs.
References _buffer, _position, and EnsureAvailable().
Referenced by ReadColor32(), and MercuryMessaging.Network.MmBinarySerializer.ReadObjectValuePooled().
ReadBytes()
byte[] MercuryMessaging.Network.MmReader.ReadBytes ()
Read a byte array with length prefix (int).
Definition at line 209 of file MmReader.cs.
References _buffer, _position, EnsureAvailable(), and ReadInt().
Referenced by MercuryMessaging.Network.MmBinarySerializer.ReadPayloadPooled().
ReadColor()
Color MercuryMessaging.Network.MmReader.ReadColor ()
Definition at line 264 of file MmReader.cs.
References ReadFloat().
ReadColor32()
Color32 MercuryMessaging.Network.MmReader.ReadColor32 ()
Definition at line 269 of file MmReader.cs.
References ReadByte().
ReadDouble()
double MercuryMessaging.Network.MmReader.ReadDouble ()
Definition at line 175 of file MmReader.cs.
References _buffer, _position, and EnsureAvailable().
Referenced by MercuryMessaging.Network.MmBinarySerializer.ReadObjectValuePooled().
ReadFloat()
float MercuryMessaging.Network.MmReader.ReadFloat ()
Definition at line 166 of file MmReader.cs.
References _buffer, _position, and EnsureAvailable().
Referenced by ReadColor(), MercuryMessaging.Network.MmBinarySerializer.ReadObjectValuePooled(), MercuryMessaging.Network.MmBinarySerializer.ReadPayloadPooled(), ReadQuaternion(), ReadVector2(), ReadVector3(), and ReadVector4().
ReadInt()
int MercuryMessaging.Network.MmReader.ReadInt ()
Definition at line 114 of file MmReader.cs.
References _buffer, _position, and EnsureAvailable().
Referenced by ReadBytes(), MercuryMessaging.Network.MmBinarySerializer.ReadObjectValuePooled(), MercuryMessaging.Network.MmBinarySerializer.ReadPayloadPooled(), MercuryMessaging.Network.MmBinarySerializer.ReadSerializableDataPooled(), and MercuryMessaging.Network.MmBinarySerializer.ReadTransformListDataPooled().
ReadLong()
long MercuryMessaging.Network.MmReader.ReadLong ()
Definition at line 136 of file MmReader.cs.
References _buffer, _position, and EnsureAvailable().
Referenced by MercuryMessaging.Network.MmBinarySerializer.ReadObjectValuePooled().
ReadQuaternion()
Quaternion MercuryMessaging.Network.MmReader.ReadQuaternion ()
Definition at line 259 of file MmReader.cs.
References MercuryMessaging.Network.Quaternion, and ReadFloat().
Referenced by MercuryMessaging.Network.MmBinarySerializer.ReadPayloadPooled(), MercuryMessaging.Network.MmBinarySerializer.ReadTransformDataPooled(), and MercuryMessaging.Network.MmBinarySerializer.ReadTransformListDataPooled().
ReadRawBytes()
void MercuryMessaging.Network.MmReader.ReadRawBytes (byte[] destination, int destinationOffset, int count)
Read raw bytes without length prefix.
Definition at line 224 of file MmReader.cs.
References _buffer, _position, and EnsureAvailable().
ReadSByte()
sbyte MercuryMessaging.Network.MmReader.ReadSByte ()
Definition at line 86 of file MmReader.cs.
References _buffer, _position, and EnsureAvailable().
ReadShort()
short MercuryMessaging.Network.MmReader.ReadShort ()
Definition at line 98 of file MmReader.cs.
References _buffer, _position, and EnsureAvailable().
Referenced by MercuryMessaging.Network.MmBinarySerializer.ReadObjectValuePooled().
ReadString()
string MercuryMessaging.Network.MmReader.ReadString ()
Read a string with length prefix (ushort).
Definition at line 191 of file MmReader.cs.
References _buffer, _position, EnsureAvailable(), ReadUShort(), and Utf8.
Referenced by MercuryMessaging.Network.MmBinarySerializer.ReadObjectValuePooled(), MercuryMessaging.Network.MmBinarySerializer.ReadPayloadPooled(), and MercuryMessaging.Network.MmBinarySerializer.ReadSerializableDataPooled().
ReadUInt()
uint MercuryMessaging.Network.MmReader.ReadUInt ()
Definition at line 125 of file MmReader.cs.
References _buffer, _position, and EnsureAvailable().
Referenced by MercuryMessaging.Network.MmBinarySerializer.ReadPayloadPooled().
ReadULong()
ulong MercuryMessaging.Network.MmReader.ReadULong ()
Definition at line 151 of file MmReader.cs.
References _buffer, _position, and EnsureAvailable().
ReadUShort()
ushort MercuryMessaging.Network.MmReader.ReadUShort ()
Definition at line 106 of file MmReader.cs.
References _buffer, _position, and EnsureAvailable().
Referenced by MercuryMessaging.Network.MmTypeRegistry.ReadFrom(), MercuryMessaging.Network.MmBinarySerializer.ReadSerializableDataPooled(), and ReadString().
ReadVector2()
Vector2 MercuryMessaging.Network.MmReader.ReadVector2 ()
Definition at line 244 of file MmReader.cs.
References ReadFloat().
ReadVector3()
Vector3 MercuryMessaging.Network.MmReader.ReadVector3 ()
Definition at line 249 of file MmReader.cs.
References ReadFloat(), and MercuryMessaging.Network.Vector3.
Referenced by MercuryMessaging.Network.MmBinarySerializer.ReadPayloadPooled(), MercuryMessaging.Network.MmBinarySerializer.ReadTransformDataPooled(), and MercuryMessaging.Network.MmBinarySerializer.ReadTransformListDataPooled().
ReadVector4()
Vector4 MercuryMessaging.Network.MmReader.ReadVector4 ()
Definition at line 254 of file MmReader.cs.
References ReadFloat(), and MercuryMessaging.Network.Vector4.
Referenced by MercuryMessaging.Network.MmBinarySerializer.ReadPayloadPooled().
Reset()
void MercuryMessaging.Network.MmReader.Reset ()
Reset the reader position to the start.
Definition at line 291 of file MmReader.cs.
References _position.
Seek()
void MercuryMessaging.Network.MmReader.Seek (int position)
Seek to a specific position.
Definition at line 299 of file MmReader.cs.
References _length, and _position.
Skip()
void MercuryMessaging.Network.MmReader.Skip (int count)
Skip a number of bytes without reading them.
Definition at line 234 of file MmReader.cs.
References _position, and EnsureAvailable().
Member Data Documentation
_buffer
readonly byte [] MercuryMessaging.Network.MmReader._buffer private
Definition at line 26 of file MmReader.cs.
Referenced by MmReader(), MmReader(), ReadBool(), ReadByte(), ReadBytes(), ReadDouble(), ReadFloat(), ReadInt(), ReadLong(), ReadRawBytes(), ReadSByte(), ReadShort(), ReadString(), ReadUInt(), ReadULong(), and ReadUShort().
_length
readonly int MercuryMessaging.Network.MmReader._length private
Definition at line 27 of file MmReader.cs.
Referenced by MmReader(), MmReader(), EnsureAvailable(), and Seek().
_position
int MercuryMessaging.Network.MmReader._position private
Definition at line 28 of file MmReader.cs.
Referenced by MmReader(), MmReader(), EnsureAvailable(), ReadBool(), ReadByte(), ReadBytes(), ReadDouble(), ReadFloat(), ReadInt(), ReadLong(), ReadRawBytes(), ReadSByte(), ReadShort(), ReadString(), ReadUInt(), ReadULong(), ReadUShort(), Reset(), Seek(), and Skip().
Utf8
readonly Encoding MercuryMessaging.Network.MmReader.Utf8 = Encoding.UTF8 static private
Definition at line 31 of file MmReader.cs.
Referenced by ReadString().
Property Documentation
IsAtEnd
bool MercuryMessaging.Network.MmReader.IsAtEnd get
Whether we've reached the end of the buffer.
Definition at line 76 of file MmReader.cs.
Length
int MercuryMessaging.Network.MmReader.Length get
Total length of readable data.
Definition at line 66 of file MmReader.cs.
Position
int MercuryMessaging.Network.MmReader.Position get
Current read position.
Definition at line 61 of file MmReader.cs.
Remaining
int MercuryMessaging.Network.MmReader.Remaining get
Number of bytes remaining to read.
Definition at line 71 of file MmReader.cs.
The documentation for this class was generated from the following file:
Protocol/Network/MmReader.cs