MercuryMessaging: MercuryMessaging.Network.Backends.FishNetResolver Class Reference
MercuryMessaging.Network.Backends.FishNetResolver Class Reference
IMmGameObjectResolver implementation for FishNet.
Public Member Functions
bool TryGetNetworkId (GameObject gameObject, out uint networkId)
Get the network ID for a GameObject.
Parameters
gameObject The GameObject to get an ID for
networkId The resolved network ID (output)
Returns
True if the GameObject has a valid network ID, false otherwise
Returns false if:
GameObject is null
GameObject doesn't have required network component (PhotonView, NetworkObject, etc.)
Network component isn't properly initialized
bool TryGetGameObject (uint networkId, out GameObject gameObject)
Get the GameObject for a network ID.
Parameters
networkId The network ID to resolve
gameObject The resolved GameObject (output)
Returns
True if a valid GameObject was found, false otherwise
Returns false if:
Network ID is invalid (0 or not registered)
Referenced object has been destroyed
Object hasn't spawned on this client yet
uint GetNetworkId (GameObject gameObject)
Get the network ID for a GameObject (non-Try version).
Parameters
gameObject The GameObject to get an ID for
Returns
Network ID, or 0 if not found
GameObject GetGameObject (uint networkId)
Get the GameObject for a network ID (non-Try version).
Parameters
networkId The network ID to resolve
Returns
GameObject, or null if not found
bool TryGetRelayNode (uint networkId, out MmRelayNode relayNode)
Get the MmRelayNode for a network ID.Convenience method that resolves GameObject and gets its MmRelayNode component.
Parameters
networkId The network ID to resolve
relayNode The resolved MmRelayNode (output)
Returns
True if a valid MmRelayNode was found, false otherwise
Properties
string ResolverName [get]
Human-readable name of this resolver (e.g., "PhotonResolver", "FishNetResolver").
Detailed Description
IMmGameObjectResolver implementation for FishNet.
Uses NetworkObject.ObjectId to map between network IDs and GameObjects. FishNet maintains separate spawned object dictionaries for server and client, so this resolver checks both paths.
FishNet specifics:
Uses NetworkObject.ObjectId for identification
Has separate server/client spawned dictionaries
Compare with Fusion2Resolver which uses NetworkObject.Id.Raw
Definition at line 56 of file FishNetResolver.cs.
Member Function Documentation
GetGameObject()
GameObject MercuryMessaging.Network.Backends.FishNetResolver.GetGameObject (uint networkId)
Get the GameObject for a network ID (non-Try version).
Parameters
networkId The network ID to resolve
Returns
GameObject, or null if not found
Implements MercuryMessaging.Network.IMmGameObjectResolver.
Definition at line 123 of file FishNetResolver.cs.
References TryGetGameObject().
GetNetworkId()
uint MercuryMessaging.Network.Backends.FishNetResolver.GetNetworkId (GameObject gameObject)
Get the network ID for a GameObject (non-Try version).
Parameters
gameObject The GameObject to get an ID for
Returns
Network ID, or 0 if not found
Implements MercuryMessaging.Network.IMmGameObjectResolver.
Definition at line 116 of file FishNetResolver.cs.
References TryGetNetworkId().
TryGetGameObject()
bool MercuryMessaging.Network.Backends.FishNetResolver.TryGetGameObject (uint networkId, out GameObject gameObject)
Get the GameObject for a network ID.
Parameters
networkId The network ID to resolve
gameObject The resolved GameObject (output)
Returns
True if a valid GameObject was found, false otherwise
Returns false if:
Network ID is invalid (0 or not registered)
Referenced object has been destroyed
Object hasn't spawned on this client yet
Implements MercuryMessaging.Network.IMmGameObjectResolver.
Definition at line 82 of file FishNetResolver.cs.
Referenced by GetGameObject(), and TryGetRelayNode().
TryGetNetworkId()
bool MercuryMessaging.Network.Backends.FishNetResolver.TryGetNetworkId (GameObject gameObject, out uint networkId)
Get the network ID for a GameObject.
Parameters
gameObject The GameObject to get an ID for
networkId The resolved network ID (output)
Returns
True if the GameObject has a valid network ID, false otherwise
Returns false if:
GameObject is null
GameObject doesn't have required network component (PhotonView, NetworkObject, etc.)
Network component isn't properly initialized
Implements MercuryMessaging.Network.IMmGameObjectResolver.
Definition at line 62 of file FishNetResolver.cs.
Referenced by GetNetworkId().
TryGetRelayNode()
bool MercuryMessaging.Network.Backends.FishNetResolver.TryGetRelayNode (uint networkId, out MmRelayNode relayNode)
Get the MmRelayNode for a network ID.Convenience method that resolves GameObject and gets its MmRelayNode component.
Parameters
networkId The network ID to resolve
relayNode The resolved MmRelayNode (output)
Returns
True if a valid MmRelayNode was found, false otherwise
Implements MercuryMessaging.Network.IMmGameObjectResolver.
Definition at line 130 of file FishNetResolver.cs.
References TryGetGameObject().
Property Documentation
ResolverName
string MercuryMessaging.Network.Backends.FishNetResolver.ResolverName get
Human-readable name of this resolver (e.g., "PhotonResolver", "FishNetResolver").
Implements MercuryMessaging.Network.IMmGameObjectResolver.
Definition at line 59 of file FishNetResolver.cs.
The documentation for this class was generated from the following file:
Protocol/Network/Backends/FishNetResolver.cs