MercuryMessaging: MercuryMessaging.MmMessagePool Class Reference
MercuryMessaging.MmMessagePool Class Reference
High-performance message pooling using Unity's ObjectPool.
Static Public Member Functions
static MmMessage Get (MmMethod method=default, MmMetadataBlock metadataBlock=null)
Get a base message from the pool (for NoOp, Initialize, Refresh, Complete, Switch).
static MmMessageBool GetBool (bool value, MmMethod method=MmMethod.MessageBool, MmMetadataBlock metadataBlock=null)
Get a bool message from the pool.
static MmMessageInt GetInt (int value, MmMethod method=MmMethod.MessageInt, MmMetadataBlock metadataBlock=null)
Get an int message from the pool.
static MmMessageFloat GetFloat (float value, MmMethod method=MmMethod.MessageFloat, MmMetadataBlock metadataBlock=null)
Get a float message from the pool.
static MmMessageString GetString (string value, MmMethod method=MmMethod.MessageString, MmMetadataBlock metadataBlock=null)
Get a string message from the pool.
static MmMessageVector3 GetVector3 (Vector3 value, MmMethod method=MmMethod.MessageVector3, MmMetadataBlock metadataBlock=null)
Get a Vector3 message from the pool.
static MmMessageVector4 GetVector4 (Vector4 value, MmMethod method=MmMethod.MessageVector4, MmMetadataBlock metadataBlock=null)
Get a Vector4 message from the pool.
static MmMessageQuaternion GetQuaternion (Quaternion value, MmMethod method=MmMethod.MessageQuaternion, MmMetadataBlock metadataBlock=null)
Get a Quaternion message from the pool.
static MmMessageTransform GetTransform (MmTransform value, MmMethod method=MmMethod.MessageTransform, MmMetadataBlock metadataBlock=null)
Get a Transform message from the pool.
static MmMessageTransformList GetTransformList (System.Collections.Generic.List< MmTransform > value, MmMethod method=MmMethod.MessageTransformList, MmMetadataBlock metadataBlock=null)
Get a TransformList message from the pool.
static MmMessageByteArray GetByteArray (byte[] value, MmMethod method=MmMethod.MessageByteArray, MmMetadataBlock metadataBlock=null)
Get a ByteArray message from the pool.
static MmMessageSerializable GetSerializable (IMmSerializable value, MmMethod method=MmMethod.Message, MmMetadataBlock metadataBlock=null)
Get a Serializable message from the pool.
static MmMessageGameObject GetGameObject (GameObject value, MmMethod method=MmMethod.MessageGameObject, MmMetadataBlock metadataBlock=null)
Get a GameObject message from the pool.
static bool Return (MmMessage message)
Return a message to the appropriate pool based on its type.
static string GetStatistics ()
Get pool statistics for debugging.
Static Public Attributes
const int DEFAULT_CAPACITY = 50
Default pool capacity for each message type.
const int MAX_SIZE = 500
Maximum pool size.
Static Private Member Functions
static void ResetMessage (MmMessage msg)
Resets a message to clean state for reuse.
Static Private Attributes
const bool COLLECTION_CHECK = true
Enable collection checks in editor for debugging pool misuse.
static readonly ObjectPool< MmMessage > _messagePool
static readonly ObjectPool< MmMessageBool > _boolPool
static readonly ObjectPool< MmMessageInt > _intPool
static readonly ObjectPool< MmMessageFloat > _floatPool
static readonly ObjectPool< MmMessageString > _stringPool
static readonly ObjectPool< MmMessageVector3 > _vector3Pool
static readonly ObjectPool< MmMessageVector4 > _vector4Pool
static readonly ObjectPool< MmMessageQuaternion > _quaternionPool
static readonly ObjectPool< MmMessageTransform > _transformPool
static readonly ObjectPool< MmMessageTransformList > _transformListPool
static readonly ObjectPool< MmMessageByteArray > _byteArrayPool
static readonly ObjectPool< MmMessageSerializable > _serializablePool
static readonly ObjectPool< MmMessageGameObject > _gameObjectPool
Detailed Description
High-performance message pooling using Unity's ObjectPool.
Eliminates per-message allocations in hot paths.
Usage: var msg = MmMessagePool.GetInt(42, MmMethod.MessageInt, metadata); // ... use message ... MmMessagePool.Return(msg); // Called automatically at end of routing
Definition at line 51 of file MmMessagePool.cs.
Member Function Documentation
Get()
MmMessage MercuryMessaging.MmMessagePool.Get (MmMethod method = default, MmMetadataBlock metadataBlock = null) static
Get a base message from the pool (for NoOp, Initialize, Refresh, Complete, Switch).
Definition at line 243 of file MmMessagePool.cs.
References _messagePool.
Referenced by MercuryMessaging.MmRelayNode.MmInvoke().
GetBool()
MmMessageBool MercuryMessaging.MmMessagePool.GetBool (bool value, MmMethod method = MmMethod::MessageBool, MmMetadataBlock metadataBlock = null) static
Get a bool message from the pool.
Definition at line 256 of file MmMessagePool.cs.
References _boolPool.
Referenced by MercuryMessaging.MmRelayNode.MmInvoke().
GetByteArray()
MmMessageByteArray MercuryMessaging.MmMessagePool.GetByteArray (byte[] value, MmMethod method = MmMethod::MessageByteArray, MmMetadataBlock metadataBlock = null) static
Get a ByteArray message from the pool.
Definition at line 382 of file MmMessagePool.cs.
References _byteArrayPool.
Referenced by MercuryMessaging.MmRelayNode.MmInvoke().
GetFloat()
MmMessageFloat MercuryMessaging.MmMessagePool.GetFloat (float value, MmMethod method = MmMethod::MessageFloat, MmMetadataBlock metadataBlock = null) static
Get a float message from the pool.
Definition at line 284 of file MmMessagePool.cs.
References _floatPool.
Referenced by MercuryMessaging.MmRelayNode.MmInvoke().
GetGameObject()
MmMessageGameObject MercuryMessaging.MmMessagePool.GetGameObject (GameObject value, MmMethod method = MmMethod::MessageGameObject, MmMetadataBlock metadataBlock = null) static
Get a GameObject message from the pool.
Definition at line 410 of file MmMessagePool.cs.
References _gameObjectPool.
Referenced by MercuryMessaging.MmRelayNode.MmInvoke().
GetInt()
MmMessageInt MercuryMessaging.MmMessagePool.GetInt (int value, MmMethod method = MmMethod::MessageInt, MmMetadataBlock metadataBlock = null) static
Get an int message from the pool.
Definition at line 270 of file MmMessagePool.cs.
References _intPool.
Referenced by MercuryMessaging.MmRelayNode.MmInvoke(), MercuryMessaging.MmRelayNodeExtensions.Query(), and MercuryMessaging.MmTemporalExtensions.RequestAsync< T >().
GetQuaternion()
MmMessageQuaternion MercuryMessaging.MmMessagePool.GetQuaternion (Quaternion value, MmMethod method = MmMethod::MessageQuaternion, MmMetadataBlock metadataBlock = null) static
Get a Quaternion message from the pool.
Definition at line 340 of file MmMessagePool.cs.
References _quaternionPool.
Referenced by MercuryMessaging.MmRelayNode.MmInvoke().
GetSerializable()
MmMessageSerializable MercuryMessaging.MmMessagePool.GetSerializable (IMmSerializable value, MmMethod method = MmMethod::Message, MmMetadataBlock metadataBlock = null) static
Get a Serializable message from the pool.
Definition at line 396 of file MmMessagePool.cs.
References _serializablePool.
Referenced by MercuryMessaging.MmRelayNode.MmInvoke().
GetStatistics()
string MercuryMessaging.MmMessagePool.GetStatistics () static
Get pool statistics for debugging.
Definition at line 497 of file MmMessagePool.cs.
GetString()
MmMessageString MercuryMessaging.MmMessagePool.GetString (string value, MmMethod method = MmMethod::MessageString, MmMetadataBlock metadataBlock = null) static
Get a string message from the pool.
Definition at line 298 of file MmMessagePool.cs.
References _stringPool.
Referenced by MercuryMessaging.MmRelayNode.MmInvoke().
GetTransform()
MmMessageTransform MercuryMessaging.MmMessagePool.GetTransform (MmTransform value, MmMethod method = MmMethod::MessageTransform, MmMetadataBlock metadataBlock = null) static
Get a Transform message from the pool.
Definition at line 354 of file MmMessagePool.cs.
References _transformPool.
Referenced by MercuryMessaging.MmRelayNode.MmInvoke().
GetTransformList()
MmMessageTransformList MercuryMessaging.MmMessagePool.GetTransformList (System.Collections.Generic.List< MmTransform > value, MmMethod method = MmMethod::MessageTransformList, MmMetadataBlock metadataBlock = null) static
Get a TransformList message from the pool.
Definition at line 368 of file MmMessagePool.cs.
References _transformListPool.
Referenced by MercuryMessaging.MmRelayNode.MmInvoke().
GetVector3()
MmMessageVector3 MercuryMessaging.MmMessagePool.GetVector3 (Vector3 value, MmMethod method = MmMethod::MessageVector3, MmMetadataBlock metadataBlock = null) static
Get a Vector3 message from the pool.
Definition at line 312 of file MmMessagePool.cs.
References _vector3Pool.
Referenced by MercuryMessaging.MmRelayNode.MmInvoke().
GetVector4()
MmMessageVector4 MercuryMessaging.MmMessagePool.GetVector4 (Vector4 value, MmMethod method = MmMethod::MessageVector4, MmMetadataBlock metadataBlock = null) static
Get a Vector4 message from the pool.
Definition at line 326 of file MmMessagePool.cs.
References _vector4Pool.
Referenced by MercuryMessaging.MmRelayNode.MmInvoke().
ResetMessage()
void MercuryMessaging.MmMessagePool.ResetMessage (MmMessage msg) static private
Resets a message to clean state for reuse.
Definition at line 217 of file MmMessagePool.cs.
References MercuryMessaging.MmHashSetPool.Return(), and MercuryMessaging.MmMessage.VisitedNodes.
Return()
bool MercuryMessaging.MmMessagePool.Return (MmMessage message) static
Return a message to the appropriate pool based on its type.
Call this at the end of message routing (in root invocation only).
Parameters
message The message to return to the pool.
Returns
True if returned to pool, false if message was null or deserialized (network messages are not pooled).
Definition at line 431 of file MmMessagePool.cs.
References _boolPool, _byteArrayPool, _floatPool, _gameObjectPool, _intPool, _messagePool, _quaternionPool, _serializablePool, _stringPool, _transformListPool, _transformPool, _vector3Pool, _vector4Pool, MercuryMessaging.MmMessage.IsDeserialized, and MercuryMessaging.MmMessage.MmMessageType.
Referenced by MercuryMessaging.MmRelayNode.MmInvoke(), MercuryMessaging.MmRelayNode.MmInvoke(), MercuryMessaging.MmRelayNode.MmInvoke(), MercuryMessaging.MmRelayNode.MmInvoke(), MercuryMessaging.MmRelayNode.MmInvoke(), MercuryMessaging.MmRelayNode.MmInvoke(), MercuryMessaging.MmRelayNode.MmInvoke(), MercuryMessaging.MmRelayNode.MmInvoke(), MercuryMessaging.MmRelayNode.MmInvoke(), MercuryMessaging.MmRelayNode.MmInvoke(), MercuryMessaging.MmRelayNode.MmInvoke(), MercuryMessaging.MmRelayNode.MmInvoke(), MercuryMessaging.MmRelayNode.MmInvoke(), MercuryMessaging.MmRelayNodeExtensions.Query(), and MercuryMessaging.MmTemporalExtensions.RequestAsync< T >().
Member Data Documentation
_boolPool
readonly ObjectPool<MmMessageBool> MercuryMessaging.MmMessagePool._boolPool static private
Initial value:
= new ObjectPool<MmMessageBool>(
            createFunc: () => new MmMessageBool(),
            actionOnGet: msg => ResetMessage(msg),
            actionOnRelease: null,
            actionOnDestroy: null,
            collectionCheck: COLLECTION_CHECK,
            defaultCapacity: DEFAULT_CAPACITY,
            maxSize: MAX_SIZE
        )
Definition at line 90 of file MmMessagePool.cs.
Referenced by GetBool(), and Return().
_byteArrayPool
readonly ObjectPool<MmMessageByteArray> MercuryMessaging.MmMessagePool._byteArrayPool static private
Initial value:
= new ObjectPool<MmMessageByteArray>(
            createFunc: () => new MmMessageByteArray(),
            actionOnGet: msg => ResetMessage(msg),
            actionOnRelease: null,
            actionOnDestroy: null,
            collectionCheck: COLLECTION_CHECK,
            defaultCapacity: DEFAULT_CAPACITY / 2,
            maxSize: MAX_SIZE / 2
        )
Definition at line 180 of file MmMessagePool.cs.
Referenced by GetByteArray(), and Return().
_floatPool
readonly ObjectPool<MmMessageFloat> MercuryMessaging.MmMessagePool._floatPool static private
Initial value:
= new ObjectPool<MmMessageFloat>(
            createFunc: () => new MmMessageFloat(),
            actionOnGet: msg => ResetMessage(msg),
            actionOnRelease: null,
            actionOnDestroy: null,
            collectionCheck: COLLECTION_CHECK,
            defaultCapacity: DEFAULT_CAPACITY,
            maxSize: MAX_SIZE
        )
Definition at line 110 of file MmMessagePool.cs.
Referenced by GetFloat(), and Return().
_gameObjectPool
readonly ObjectPool<MmMessageGameObject> MercuryMessaging.MmMessagePool._gameObjectPool static private
Initial value:
= new ObjectPool<MmMessageGameObject>(
            createFunc: () => new MmMessageGameObject(),
            actionOnGet: msg => ResetMessage(msg),
            actionOnRelease: null,
            actionOnDestroy: null,
            collectionCheck: COLLECTION_CHECK,
            defaultCapacity: DEFAULT_CAPACITY,
            maxSize: MAX_SIZE
        )
Definition at line 200 of file MmMessagePool.cs.
Referenced by GetGameObject(), and Return().
_intPool
readonly ObjectPool<MmMessageInt> MercuryMessaging.MmMessagePool._intPool static private
Initial value:
= new ObjectPool<MmMessageInt>(
            createFunc: () => new MmMessageInt(),
            actionOnGet: msg => ResetMessage(msg),
            actionOnRelease: null,
            actionOnDestroy: null,
            collectionCheck: COLLECTION_CHECK,
            defaultCapacity: DEFAULT_CAPACITY,
            maxSize: MAX_SIZE
        )
Definition at line 100 of file MmMessagePool.cs.
Referenced by GetInt(), and Return().
_messagePool
readonly ObjectPool<MmMessage> MercuryMessaging.MmMessagePool._messagePool static private
Initial value:
= new ObjectPool<MmMessage>(
            createFunc: () => new MmMessage(),
            actionOnGet: ResetMessage,
            actionOnRelease: null,
            actionOnDestroy: null,
            collectionCheck: COLLECTION_CHECK,
            defaultCapacity: DEFAULT_CAPACITY,
            maxSize: MAX_SIZE
        )
Definition at line 79 of file MmMessagePool.cs.
Referenced by Get(), and Return().
_quaternionPool
readonly ObjectPool<MmMessageQuaternion> MercuryMessaging.MmMessagePool._quaternionPool static private
Initial value:
= new ObjectPool<MmMessageQuaternion>(
            createFunc: () => new MmMessageQuaternion(),
            actionOnGet: msg => ResetMessage(msg),
            actionOnRelease: null,
            actionOnDestroy: null,
            collectionCheck: COLLECTION_CHECK,
            defaultCapacity: DEFAULT_CAPACITY,
            maxSize: MAX_SIZE
        )
Definition at line 150 of file MmMessagePool.cs.
Referenced by GetQuaternion(), and Return().
_serializablePool
readonly ObjectPool<MmMessageSerializable> MercuryMessaging.MmMessagePool._serializablePool static private
Initial value:
= new ObjectPool<MmMessageSerializable>(
            createFunc: () => new MmMessageSerializable(),
            actionOnGet: msg => ResetMessage(msg),
            actionOnRelease: null,
            actionOnDestroy: null,
            collectionCheck: COLLECTION_CHECK,
            defaultCapacity: DEFAULT_CAPACITY / 2,
            maxSize: MAX_SIZE / 2
        )
Definition at line 190 of file MmMessagePool.cs.
Referenced by GetSerializable(), and Return().
_stringPool
readonly ObjectPool<MmMessageString> MercuryMessaging.MmMessagePool._stringPool static private
Initial value:
= new ObjectPool<MmMessageString>(
            createFunc: () => new MmMessageString(),
            actionOnGet: msg => ResetMessage(msg),
            actionOnRelease: null,
            actionOnDestroy: null,
            collectionCheck: COLLECTION_CHECK,
            defaultCapacity: DEFAULT_CAPACITY,
            maxSize: MAX_SIZE
        )
Definition at line 120 of file MmMessagePool.cs.
Referenced by GetString(), and Return().
_transformListPool
readonly ObjectPool<MmMessageTransformList> MercuryMessaging.MmMessagePool._transformListPool static private
Initial value:
= new ObjectPool<MmMessageTransformList>(
            createFunc: () => new MmMessageTransformList(),
            actionOnGet: msg => ResetMessage(msg),
            actionOnRelease: null,
            actionOnDestroy: null,
            collectionCheck: COLLECTION_CHECK,
            defaultCapacity: DEFAULT_CAPACITY / 2,
            maxSize: MAX_SIZE / 2
        )
Definition at line 170 of file MmMessagePool.cs.
Referenced by GetTransformList(), and Return().
_transformPool
readonly ObjectPool<MmMessageTransform> MercuryMessaging.MmMessagePool._transformPool static private
Initial value:
= new ObjectPool<MmMessageTransform>(
            createFunc: () => new MmMessageTransform(),
            actionOnGet: msg => ResetMessage(msg),
            actionOnRelease: null,
            actionOnDestroy: null,
            collectionCheck: COLLECTION_CHECK,
            defaultCapacity: DEFAULT_CAPACITY,
            maxSize: MAX_SIZE
        )
Definition at line 160 of file MmMessagePool.cs.
Referenced by GetTransform(), and Return().
_vector3Pool
readonly ObjectPool<MmMessageVector3> MercuryMessaging.MmMessagePool._vector3Pool static private
Initial value:
= new ObjectPool<MmMessageVector3>(
            createFunc: () => new MmMessageVector3(),
            actionOnGet: msg => ResetMessage(msg),
            actionOnRelease: null,
            actionOnDestroy: null,
            collectionCheck: COLLECTION_CHECK,
            defaultCapacity: DEFAULT_CAPACITY,
            maxSize: MAX_SIZE
        )
Definition at line 130 of file MmMessagePool.cs.
Referenced by GetVector3(), and Return().
_vector4Pool
readonly ObjectPool<MmMessageVector4> MercuryMessaging.MmMessagePool._vector4Pool static private
Initial value:
= new ObjectPool<MmMessageVector4>(
            createFunc: () => new MmMessageVector4(),
            actionOnGet: msg => ResetMessage(msg),
            actionOnRelease: null,
            actionOnDestroy: null,
            collectionCheck: COLLECTION_CHECK,
            defaultCapacity: DEFAULT_CAPACITY,
            maxSize: MAX_SIZE
        )
Definition at line 140 of file MmMessagePool.cs.
Referenced by GetVector4(), and Return().
COLLECTION_CHECK
const bool MercuryMessaging.MmMessagePool.COLLECTION_CHECK = true static private
Enable collection checks in editor for debugging pool misuse.
Definition at line 69 of file MmMessagePool.cs.
DEFAULT_CAPACITY
const int MercuryMessaging.MmMessagePool.DEFAULT_CAPACITY = 50 static
Default pool capacity for each message type.
Definition at line 58 of file MmMessagePool.cs.
MAX_SIZE
const int MercuryMessaging.MmMessagePool.MAX_SIZE = 500 static
Maximum pool size.
Messages beyond this are garbage collected.
Definition at line 63 of file MmMessagePool.cs.
The documentation for this class was generated from the following file:
Protocol/Core/MmMessagePool.cs