MercuryMessaging: MercuryMessaging.Network.MmRegistryResolver Class Reference
MercuryMessaging.Network.MmRegistryResolver Class Reference
Simple registry-based GameObject resolver.
Public Member Functions
uint Register (GameObject gameObject)
Register a GameObject with an auto-generated network ID.
void RegisterWithId (uint networkId, GameObject gameObject)
Register a GameObject with a specific network ID.
void Unregister (GameObject gameObject)
Unregister a GameObject.
void Unregister (uint networkId)
Unregister by network ID.
void Clear ()
Clear all registrations.
bool TryGetNetworkId (GameObject gameObject, out uint networkId)
Get the network ID for a GameObject.
Parameters
gameObject The GameObject to get an ID for
networkId The resolved network ID (output)
Returns
True if the GameObject has a valid network ID, false otherwise
Returns false if:
GameObject is null
GameObject doesn't have required network component (PhotonView, NetworkObject, etc.)
Network component isn't properly initialized
bool TryGetGameObject (uint networkId, out GameObject gameObject)
Get the GameObject for a network ID.
Parameters
networkId The network ID to resolve
gameObject The resolved GameObject (output)
Returns
True if a valid GameObject was found, false otherwise
Returns false if:
Network ID is invalid (0 or not registered)
Referenced object has been destroyed
Object hasn't spawned on this client yet
uint GetNetworkId (GameObject gameObject)
Get the network ID for a GameObject (non-Try version).
Parameters
gameObject The GameObject to get an ID for
Returns
Network ID, or 0 if not found
GameObject GetGameObject (uint networkId)
Get the GameObject for a network ID (non-Try version).
Parameters
networkId The network ID to resolve
Returns
GameObject, or null if not found
bool TryGetRelayNode (uint networkId, out MmRelayNode relayNode)
Get the MmRelayNode for a network ID.Convenience method that resolves GameObject and gets its MmRelayNode component.
Parameters
networkId The network ID to resolve
relayNode The resolved MmRelayNode (output)
Returns
True if a valid MmRelayNode was found, false otherwise
Properties
string ResolverName [get]
Human-readable name of this resolver (e.g., "PhotonResolver", "FishNetResolver").
int Count [get]
Number of registered GameObjects.
Private Attributes
readonly Dictionary< uint, GameObject > _idToGameObject = new Dictionary<uint, GameObject>()
readonly Dictionary< GameObject, uint > _gameObjectToId = new Dictionary<GameObject, uint>()
uint _nextId = 1
Detailed Description
Simple registry-based GameObject resolver.
Uses a dictionary to map network IDs to GameObjects. Suitable for testing and scenarios where manual registration is acceptable.
For production use with networking backends, prefer backend-specific resolvers (PhotonResolver, FishNetResolver, etc.) that use the backend's native ID system.
Definition at line 49 of file MmRegistryResolver.cs.
Member Function Documentation
Clear()
void MercuryMessaging.Network.MmRegistryResolver.Clear ()
Clear all registrations.
Definition at line 140 of file MmRegistryResolver.cs.
References _gameObjectToId, _idToGameObject, and _nextId.
GetGameObject()
GameObject MercuryMessaging.Network.MmRegistryResolver.GetGameObject (uint networkId)
Get the GameObject for a network ID (non-Try version).
Parameters
networkId The network ID to resolve
Returns
GameObject, or null if not found
Implements MercuryMessaging.Network.IMmGameObjectResolver.
Definition at line 200 of file MmRegistryResolver.cs.
References TryGetGameObject().
GetNetworkId()
uint MercuryMessaging.Network.MmRegistryResolver.GetNetworkId (GameObject gameObject)
Get the network ID for a GameObject (non-Try version).
Parameters
gameObject The GameObject to get an ID for
Returns
Network ID, or 0 if not found
Implements MercuryMessaging.Network.IMmGameObjectResolver.
Definition at line 193 of file MmRegistryResolver.cs.
References TryGetNetworkId().
Register()
uint MercuryMessaging.Network.MmRegistryResolver.Register (GameObject gameObject)
Register a GameObject with an auto-generated network ID.
Parameters
gameObject The GameObject to register
Returns
The assigned network ID
Definition at line 65 of file MmRegistryResolver.cs.
References _gameObjectToId, _nextId, and RegisterWithId().
RegisterWithId()
void MercuryMessaging.Network.MmRegistryResolver.RegisterWithId (uint networkId, GameObject gameObject)
Register a GameObject with a specific network ID.
Parameters
networkId The network ID to assign
gameObject The GameObject to register
Definition at line 85 of file MmRegistryResolver.cs.
References _gameObjectToId, _idToGameObject, and _nextId.
Referenced by Register().
TryGetGameObject()
bool MercuryMessaging.Network.MmRegistryResolver.TryGetGameObject (uint networkId, out GameObject gameObject)
Get the GameObject for a network ID.
Parameters
networkId The network ID to resolve
gameObject The resolved GameObject (output)
Returns
True if a valid GameObject was found, false otherwise
Returns false if:
Network ID is invalid (0 or not registered)
Referenced object has been destroyed
Object hasn't spawned on this client yet
Implements MercuryMessaging.Network.IMmGameObjectResolver.
Definition at line 168 of file MmRegistryResolver.cs.
References _idToGameObject.
Referenced by GetGameObject(), and TryGetRelayNode().
TryGetNetworkId()
bool MercuryMessaging.Network.MmRegistryResolver.TryGetNetworkId (GameObject gameObject, out uint networkId)
Get the network ID for a GameObject.
Parameters
gameObject The GameObject to get an ID for
networkId The resolved network ID (output)
Returns
True if the GameObject has a valid network ID, false otherwise
Returns false if:
GameObject is null
GameObject doesn't have required network component (PhotonView, NetworkObject, etc.)
Network component isn't properly initialized
Implements MercuryMessaging.Network.IMmGameObjectResolver.
Definition at line 157 of file MmRegistryResolver.cs.
References _gameObjectToId.
Referenced by GetNetworkId().
TryGetRelayNode()
bool MercuryMessaging.Network.MmRegistryResolver.TryGetRelayNode (uint networkId, out MmRelayNode relayNode)
Get the MmRelayNode for a network ID.Convenience method that resolves GameObject and gets its MmRelayNode component.
Parameters
networkId The network ID to resolve
relayNode The resolved MmRelayNode (output)
Returns
True if a valid MmRelayNode was found, false otherwise
Implements MercuryMessaging.Network.IMmGameObjectResolver.
Definition at line 207 of file MmRegistryResolver.cs.
References TryGetGameObject().
Unregister() [1/2]
void MercuryMessaging.Network.MmRegistryResolver.Unregister (GameObject gameObject)
Unregister a GameObject.
Parameters
gameObject The GameObject to unregister
Definition at line 113 of file MmRegistryResolver.cs.
References _gameObjectToId, and _idToGameObject.
Unregister() [2/2]
void MercuryMessaging.Network.MmRegistryResolver.Unregister (uint networkId)
Unregister by network ID.
Parameters
networkId The network ID to unregister
Definition at line 128 of file MmRegistryResolver.cs.
References _gameObjectToId, and _idToGameObject.
Member Data Documentation
_gameObjectToId
readonly Dictionary<GameObject, uint> MercuryMessaging.Network.MmRegistryResolver._gameObjectToId = new Dictionary<GameObject, uint>() private
Definition at line 52 of file MmRegistryResolver.cs.
Referenced by Clear(), Register(), RegisterWithId(), TryGetNetworkId(), Unregister(), and Unregister().
_idToGameObject
readonly Dictionary<uint, GameObject> MercuryMessaging.Network.MmRegistryResolver._idToGameObject = new Dictionary<uint, GameObject>() private
Definition at line 51 of file MmRegistryResolver.cs.
Referenced by Clear(), RegisterWithId(), TryGetGameObject(), Unregister(), and Unregister().
_nextId
uint MercuryMessaging.Network.MmRegistryResolver._nextId = 1 private
Definition at line 53 of file MmRegistryResolver.cs.
Referenced by Clear(), Register(), and RegisterWithId().
Property Documentation
Count
int MercuryMessaging.Network.MmRegistryResolver.Count get
Number of registered GameObjects.
Definition at line 150 of file MmRegistryResolver.cs.
ResolverName
string MercuryMessaging.Network.MmRegistryResolver.ResolverName get
Human-readable name of this resolver (e.g., "PhotonResolver", "FishNetResolver").
Implements MercuryMessaging.Network.IMmGameObjectResolver.
Definition at line 56 of file MmRegistryResolver.cs.
The documentation for this class was generated from the following file:
Protocol/Network/MmRegistryResolver.cs