MercuryMessaging: MercuryMessaging.StandardLibrary.Animation.MaterialChanger< T, TI > Class Template Reference
MercuryMessaging.StandardLibrary.Animation.MaterialChanger< T, TI > Class Template Reference
Public Member Functions
virtual void Awake ()
virtual void Change ()
virtual void Reverse ()
virtual void Refresh ()
virtual void Cleanup ()
Public Attributes
T Target
float Duration = 1
Private Types
enum MaterialState { Normal , Changed }
Private Attributes
readonly Dictionary< T, TI > interpolators = new Dictionary<T, TI>()
TI selectedInterpolator
readonly FiniteStateMachine< MaterialState > materialFSM = new FiniteStateMachine<MaterialState>("MaterialState")
MeshRenderer[] meshRenderers
Detailed Description
Type Constraints
TI : Interpolator<T>
TI : InterpolatorMaterial<T>
Definition at line 41 of file MaterialChanger.cs.
Member Enumeration Documentation
MaterialState
enum MercuryMessaging.StandardLibrary.Animation.MaterialChanger-2-g.MaterialState private
Enumerator
Normal
Changed
Definition at line 51 of file MaterialChanger.cs.
Member Function Documentation
Awake()
virtual void MercuryMessaging.StandardLibrary.Animation.MaterialChanger< T, TI >.Awake () virtual
Definition at line 62 of file MaterialChanger.cs.
References MercuryMessaging.StandardLibrary.Input.KeyboardHandler.AddEntry(), Change(), Cleanup(), interpolators, materialFSM, meshRenderers, Refresh(), and Reverse().
Change()
virtual void MercuryMessaging.StandardLibrary.Animation.MaterialChanger< T, TI >.Change () virtual
Definition at line 91 of file MaterialChanger.cs.
References materialFSM.
Referenced by Awake().
Cleanup()
virtual void MercuryMessaging.StandardLibrary.Animation.MaterialChanger< T, TI >.Cleanup () virtual
Definition at line 152 of file MaterialChanger.cs.
References interpolators.
Referenced by Awake().
Refresh()
virtual void MercuryMessaging.StandardLibrary.Animation.MaterialChanger< T, TI >.Refresh () virtual
Definition at line 101 of file MaterialChanger.cs.
References Duration, interpolators, meshRenderers, selectedInterpolator, and Target.
Referenced by Awake().
Reverse()
virtual void MercuryMessaging.StandardLibrary.Animation.MaterialChanger< T, TI >.Reverse () virtual
Definition at line 96 of file MaterialChanger.cs.
References materialFSM.
Referenced by Awake().
Member Data Documentation
Duration
float MercuryMessaging.StandardLibrary.Animation.MaterialChanger< T, TI >.Duration = 1
Definition at line 45 of file MaterialChanger.cs.
Referenced by Refresh().
interpolators
readonly Dictionary<T, TI> MercuryMessaging.StandardLibrary.Animation.MaterialChanger< T, TI >.interpolators = new Dictionary<T, TI>() private
Definition at line 47 of file MaterialChanger.cs.
Referenced by Awake(), Cleanup(), and Refresh().
materialFSM
readonly FiniteStateMachine<MaterialState> MercuryMessaging.StandardLibrary.Animation.MaterialChanger< T, TI >.materialFSM = new FiniteStateMachine<MaterialState>("MaterialState") private
Definition at line 57 of file MaterialChanger.cs.
Referenced by Awake(), Change(), and Reverse().
meshRenderers
MeshRenderer [] MercuryMessaging.StandardLibrary.Animation.MaterialChanger< T, TI >.meshRenderers private
Definition at line 60 of file MaterialChanger.cs.
Referenced by Awake(), and Refresh().
selectedInterpolator
TI MercuryMessaging.StandardLibrary.Animation.MaterialChanger< T, TI >.selectedInterpolator private
Definition at line 49 of file MaterialChanger.cs.
Referenced by Refresh().
Target
T MercuryMessaging.StandardLibrary.Animation.MaterialChanger< T, TI >.Target
Definition at line 44 of file MaterialChanger.cs.
Referenced by Refresh().
The documentation for this class was generated from the following file:
StandardLibrary/Animation/MaterialChanger.cs