MercuryMessaging: MercuryMessaging.MmTagHelper Class Reference
MercuryMessaging.MmTagHelper Class Reference
Static Public Member Functions
static string ToString (MmTag tag)
Static Public Attributes
const MmTag Everything = (MmTag) (-1)
const MmTag Nothing = 0
Detailed Description
Definition at line 53 of file MmTag.cs.
Member Function Documentation
ToString()
string MercuryMessaging.MmTagHelper.ToString (MmTag tag) static
Definition at line 58 of file MmTag.cs.
References Everything.
Member Data Documentation
Everything
const MmTag MercuryMessaging.MmTagHelper.Everything = (MmTag) (-1) static
Definition at line 55 of file MmTag.cs.
Referenced by MercuryMessaging.MmDeferredRoutingBuilder.MmDeferredRoutingBuilder(), MercuryMessaging.MmFluentMessage.MmFluentMessage(), MercuryMessaging.MmMetadataBlock.MmMetadataBlock(), MercuryMessaging.MmRouteBuilder.MmRouteBuilder(), MercuryMessaging.MmRoutingBuilder.MmRoutingBuilder(), MercuryMessaging.MmFluentMessage.AnyTag(), MercuryMessaging.MmRouteBuilder.Build(), MercuryMessaging.MmFluentMessage.CreateMetadata(), MercuryMessaging.MmQuery< T >.EnumerateDirect(), MercuryMessaging.MmDeferredRoutingBuilder.Execute(), MercuryMessaging.MmRoutingBuilder.Execute(), MercuryMessaging.MmFluentMessage.ExecuteWithPredicates(), MercuryMessaging.MmFluentMessage.ExecuteWithTargetCollection(), MercuryMessaging.MmRelayNode.MmInvokeWithPath(), MercuryMessaging.MmRelayNode.MmInvokeWithPath(), MercuryMessaging.MmRelayNode.MmInvokeWithPath(), MercuryMessaging.MmRelayNode.MmInvokeWithPath(), MercuryMessaging.MmListenerBuilder< T >.MmListenerBuilder(), MercuryMessaging.MmQuery< T >.MmQuery(), MercuryMessaging.MmRelayNode.ResponderCheck(), MercuryMessaging.MmRelayNode.TagCheck(), ToString(), and MercuryMessaging.MmListenerSubscription< T >.TryInvoke().
Nothing
const MmTag MercuryMessaging.MmTagHelper.Nothing = 0 static
Definition at line 56 of file MmTag.cs.
Referenced by MercuryMessaging.MmTagExtensions.ClearTags(), MercuryMessaging.MmFluentMessage.NoTags(), MercuryMessaging.MmFluentMessage.WithTags(), and MercuryMessaging.MmTagExtensions.WithTags().
The documentation for this class was generated from the following file:
Protocol/Filters/MmTag.cs