MercuryMessaging: MercuryMessaging.Network.MmMessagePoolManager Class Reference
MercuryMessaging.Network.MmMessagePoolManager Class Reference
Central message pool manager.
Public Member Functions
byte[] GetByteArray (int minSize)
Get a byte array from the pool.
void ReturnByteArray (byte[] array)
Return a byte array to the pool.
MmPooledMessage GetPooledMessage ()
Get a pooled message wrapper.
void ReturnPooledMessage (MmPooledMessage msg)
Return a pooled message wrapper.
List< MmStateDelta > GetDeltaList ()
Get a delta list from the pool.
void ReturnDeltaList (List< MmStateDelta > list)
Return a delta list to the pool.
void ClearAll ()
Clear all pools.
string GetAllStats ()
Get comprehensive statistics.
void Prewarm (int byteArraysPerBucket=10, int pooledMessages=50, int deltaLists=20)
Prewarm pools for expected usage.
Properties
static MmMessagePoolManager Instance = new MmMessagePoolManager() [get]
Singleton instance.
MmByteArrayPool ByteArrayPool = new MmByteArrayPool() [get]
Pool for byte arrays.
MmObjectPool< MmPooledMessage > PooledMessagePool [get]
Pool for pooled message wrappers.
MmObjectPool< List< MmStateDelta > > DeltaListPool [get]
Pool for list of MmStateDelta.
MmObjectPool< List< MmQueuedMessage > > QueuedMessageListPool [get]
Pool for list of MmQueuedMessage.
Private Member Functions
MmMessagePoolManager ()
Detailed Description
Central message pool manager.
Provides unified access to all network-related pools.
Definition at line 369 of file MmMessagePool.cs.
Constructor & Destructor Documentation
MmMessagePoolManager()
MercuryMessaging.Network.MmMessagePoolManager.MmMessagePoolManager () private
Definition at line 396 of file MmMessagePool.cs.
References MercuryMessaging.Network.MmObjectPool< T >.Clear(), DeltaListPool, PooledMessagePool, and QueuedMessageListPool.
Member Function Documentation
ClearAll()
void MercuryMessaging.Network.MmMessagePoolManager.ClearAll ()
Clear all pools.
Definition at line 454 of file MmMessagePool.cs.
References ByteArrayPool, DeltaListPool, PooledMessagePool, and QueuedMessageListPool.
GetAllStats()
string MercuryMessaging.Network.MmMessagePoolManager.GetAllStats ()
Get comprehensive statistics.
Definition at line 465 of file MmMessagePool.cs.
References ByteArrayPool, DeltaListPool, PooledMessagePool, and QueuedMessageListPool.
GetByteArray()
byte[] MercuryMessaging.Network.MmMessagePoolManager.GetByteArray (int minSize)
Get a byte array from the pool.
Definition at line 406 of file MmMessagePool.cs.
References ByteArrayPool.
GetDeltaList()
List< MmStateDelta > MercuryMessaging.Network.MmMessagePoolManager.GetDeltaList ()
Get a delta list from the pool.
Definition at line 438 of file MmMessagePool.cs.
References DeltaListPool.
GetPooledMessage()
MmPooledMessage MercuryMessaging.Network.MmMessagePoolManager.GetPooledMessage ()
Get a pooled message wrapper.
Definition at line 422 of file MmMessagePool.cs.
References PooledMessagePool.
Referenced by MercuryMessaging.Network.MmPoolExtensions.SerializePooled().
Prewarm()
void MercuryMessaging.Network.MmMessagePoolManager.Prewarm (int byteArraysPerBucket = 10, int pooledMessages = 50, int deltaLists = 20)
Prewarm pools for expected usage.
Call during initialization.
Definition at line 480 of file MmMessagePool.cs.
References DeltaListPool, PooledMessagePool, and QueuedMessageListPool.
ReturnByteArray()
void MercuryMessaging.Network.MmMessagePoolManager.ReturnByteArray (byte[] array)
Return a byte array to the pool.
Definition at line 414 of file MmMessagePool.cs.
References ByteArrayPool.
Referenced by MercuryMessaging.Network.MmPoolExtensions.ReturnToPool().
ReturnDeltaList()
void MercuryMessaging.Network.MmMessagePoolManager.ReturnDeltaList (List< MmStateDelta > list)
Return a delta list to the pool.
Definition at line 446 of file MmMessagePool.cs.
References DeltaListPool.
ReturnPooledMessage()
void MercuryMessaging.Network.MmMessagePoolManager.ReturnPooledMessage (MmPooledMessage msg)
Return a pooled message wrapper.
Definition at line 430 of file MmMessagePool.cs.
References PooledMessagePool.
Referenced by MercuryMessaging.Network.MmPoolExtensions.ReturnToPool().
Property Documentation
ByteArrayPool
MmByteArrayPool MercuryMessaging.Network.MmMessagePoolManager.ByteArrayPool = new MmByteArrayPool() get
Pool for byte arrays.
Definition at line 379 of file MmMessagePool.cs.
Referenced by ClearAll(), GetAllStats(), GetByteArray(), and ReturnByteArray().
DeltaListPool
MmObjectPool<List<MmStateDelta> > MercuryMessaging.Network.MmMessagePoolManager.DeltaListPool get
Pool for list of MmStateDelta.
Definition at line 389 of file MmMessagePool.cs.
Referenced by MmMessagePoolManager(), ClearAll(), GetAllStats(), GetDeltaList(), Prewarm(), and ReturnDeltaList().
Instance
MmMessagePoolManager MercuryMessaging.Network.MmMessagePoolManager.Instance = new MmMessagePoolManager() static get
Singleton instance.
Definition at line 374 of file MmMessagePool.cs.
Referenced by MercuryMessaging.Network.MmPoolExtensions.ReturnToPool(), and MercuryMessaging.Network.MmPoolExtensions.SerializePooled().
PooledMessagePool
MmObjectPool<MmPooledMessage> MercuryMessaging.Network.MmMessagePoolManager.PooledMessagePool get
Pool for pooled message wrappers.
Definition at line 384 of file MmMessagePool.cs.
Referenced by MmMessagePoolManager(), ClearAll(), GetAllStats(), GetPooledMessage(), Prewarm(), and ReturnPooledMessage().
QueuedMessageListPool
MmObjectPool<List<MmQueuedMessage> > MercuryMessaging.Network.MmMessagePoolManager.QueuedMessageListPool get
Pool for list of MmQueuedMessage.
Definition at line 394 of file MmMessagePool.cs.
Referenced by MmMessagePoolManager(), ClearAll(), GetAllStats(), and Prewarm().
The documentation for this class was generated from the following file:
Protocol/Network/MmMessagePool.cs