MercuryMessaging: MercuryMessaging.MmRelaySwitchNodeExtensions Class Reference
MercuryMessaging.MmRelaySwitchNodeExtensions Class Reference
Extension methods for MmRelaySwitchNode to enable fluent FSM configuration.
Static Public Member Functions
static FsmConfigBuilder< MmRoutingTableItem > ConfigureStates (this MmRelaySwitchNode switchNode)
Start configuring the FSM states with a fluent builder.
static void GoTo (this MmRelaySwitchNode switchNode, string stateName)
Quick transition to a named state.
static void GoTo (this MmRelaySwitchNode switchNode, MmRelayNode state)
Quick transition to a state by relay node reference.
static bool GoToPrevious (this MmRelaySwitchNode switchNode)
Transition to the previous state (if available).
static bool IsInState (this MmRelaySwitchNode switchNode, string stateName)
Check if the FSM is currently in a specific state.
static bool IsInState (this MmRelaySwitchNode switchNode, MmRelayNode state)
Check if the FSM is currently in a specific state.
static string GetCurrentStateName (this MmRelaySwitchNode switchNode)
Get the name of the current state.
static string GetPreviousStateName (this MmRelaySwitchNode switchNode)
Get the name of the previous state.
static void OnStateEnter (this MmRelaySwitchNode switchNode, string stateName, Action callback)
Quick registration of enter handler for a state.
static void OnStateExit (this MmRelaySwitchNode switchNode, string stateName, Action callback)
Quick registration of exit handler for a state.
Detailed Description
Extension methods for MmRelaySwitchNode to enable fluent FSM configuration.
Provides a clean, chainable API for setting up state machine event handlers.
Example Usage:
// Configure state handlers fluently
switchNode.ConfigureStates()
    .OnGlobalEnter(() => Debug.Log("State changed"))
    .OnEnter("MainMenu", () => ShowMenu())
    .OnExit("MainMenu", () => HideMenu())
    .OnEnter("Gameplay", () => StartGame())
    .StartWith("MainMenu")
    .Build();
// Quick state transitions
switchNode.GoTo("Gameplay");
switchNode.GoToNext();
switchNode.GoToPrevious();
Definition at line 33 of file MmRelaySwitchNodeExtensions.cs.
Member Function Documentation
ConfigureStates()
FsmConfigBuilder< MmRoutingTableItem > MercuryMessaging.MmRelaySwitchNodeExtensions.ConfigureStates (this MmRelaySwitchNode switchNode) static
Start configuring the FSM states with a fluent builder.
Parameters
switchNode The switch node to configure.
Returns
A fluent builder for FSM configuration.
Definition at line 42 of file MmRelaySwitchNodeExtensions.cs.
References MercuryMessaging.MmRelaySwitchNode.RespondersFSM, and MercuryMessaging.MmRelayNode.RoutingTable.
GetCurrentStateName()
string MercuryMessaging.MmRelaySwitchNodeExtensions.GetCurrentStateName (this MmRelaySwitchNode switchNode) static
Get the name of the current state.
Definition at line 134 of file MmRelaySwitchNodeExtensions.cs.
References MercuryMessaging.MmRelaySwitchNode.CurrentName.
GetPreviousStateName()
string MercuryMessaging.MmRelaySwitchNodeExtensions.GetPreviousStateName (this MmRelaySwitchNode switchNode) static
Get the name of the previous state.
Definition at line 142 of file MmRelaySwitchNodeExtensions.cs.
References MercuryMessaging.FiniteStateMachine< T >.Previous, and MercuryMessaging.MmRelaySwitchNode.RespondersFSM.
GoTo() [1/2]
void MercuryMessaging.MmRelaySwitchNodeExtensions.GoTo (this MmRelaySwitchNode switchNode, MmRelayNode state) static
Quick transition to a state by relay node reference.
Definition at line 83 of file MmRelaySwitchNodeExtensions.cs.
References MercuryMessaging.MmRelaySwitchNode.JumpTo().
GoTo() [2/2]
void MercuryMessaging.MmRelaySwitchNodeExtensions.GoTo (this MmRelaySwitchNode switchNode, string stateName) static
Quick transition to a named state.
Equivalent to switchNode.JumpTo(stateName) but with cleaner naming.
Definition at line 75 of file MmRelaySwitchNodeExtensions.cs.
References MercuryMessaging.MmRelaySwitchNode.JumpTo().
GoToPrevious()
bool MercuryMessaging.MmRelaySwitchNodeExtensions.GoToPrevious (this MmRelaySwitchNode switchNode) static
Transition to the previous state (if available).
Definition at line 91 of file MmRelaySwitchNodeExtensions.cs.
References MercuryMessaging.FiniteStateMachine< T >.JumpTo(), MercuryMessaging.FiniteStateMachine< T >.Previous, and MercuryMessaging.MmRelaySwitchNode.RespondersFSM.
IsInState() [1/2]
bool MercuryMessaging.MmRelaySwitchNodeExtensions.IsInState (this MmRelaySwitchNode switchNode, MmRelayNode state) static
Check if the FSM is currently in a specific state.
Definition at line 123 of file MmRelaySwitchNodeExtensions.cs.
IsInState() [2/2]
bool MercuryMessaging.MmRelaySwitchNodeExtensions.IsInState (this MmRelaySwitchNode switchNode, string stateName) static
Check if the FSM is currently in a specific state.
Definition at line 112 of file MmRelaySwitchNodeExtensions.cs.
OnStateEnter()
void MercuryMessaging.MmRelaySwitchNodeExtensions.OnStateEnter (this MmRelaySwitchNode switchNode, string stateName, Action callback) static
Quick registration of enter handler for a state.
For complex configurations, use ConfigureStates() instead.
Definition at line 155 of file MmRelaySwitchNodeExtensions.cs.
References MercuryMessaging.Transition().
OnStateExit()
void MercuryMessaging.MmRelaySwitchNodeExtensions.OnStateExit (this MmRelaySwitchNode switchNode, string stateName, Action callback) static
Quick registration of exit handler for a state.
For complex configurations, use ConfigureStates() instead.
Definition at line 168 of file MmRelaySwitchNodeExtensions.cs.
References MercuryMessaging.Transition().
The documentation for this class was generated from the following file:
Protocol/DSL/MmRelaySwitchNodeExtensions.cs