MercuryMessaging: MercuryMessaging.HierarchyBuilder Class Reference
MercuryMessaging.HierarchyBuilder Class Reference
Fluent builder for constructing MercuryMessaging hierarchies programmatically.
Classes
class NodeBuilder
Internal node builder.
Public Member Functions
HierarchyBuilder (string rootName)
Create a new hierarchy builder with a root node.
HierarchyBuilder (MmRelayNode existingRoot)
Create a builder attached to an existing relay node.
HierarchyBuilder AddChild (string name)
Add a child node to the current node.
HierarchyBuilder AddChild< T > (string name)
Add a child node with a custom component type.
HierarchyBuilder Parent ()
Navigate back to the parent node.
HierarchyBuilder Root ()
Navigate back to the root node.
HierarchyBuilder WithTag (MmTag tag)
Set the tag for the current node.
HierarchyBuilder OnLayer (int layer)
Set the layer for the current node.
HierarchyBuilder AtPosition (Vector3 position)
Set the position for the current node.
HierarchyBuilder WithResponder< T > ()
Add a responder component to the current node.
HierarchyBuilder Configure (Action< MmRelayNode > configure)
Add an action to run after the node is created.
HierarchyBuilder Inactive ()
Set this node as inactive by default.
HierarchyBuilder AsSwitchNode ()
Make this a switch node (MmRelaySwitchNode).
MmRelayNode Build ()
Build the hierarchy and return the root relay node.
MmRelayNode BuildUnder (Transform parent)
Build the hierarchy under an existing parent.
Private Member Functions
MmRelayNode BuildNode (NodeBuilder builder, Transform parent)
Private Attributes
readonly NodeBuilder _root
NodeBuilder _current
readonly Stack< NodeBuilder > _parentStack = new Stack<NodeBuilder>()
Detailed Description
Fluent builder for constructing MercuryMessaging hierarchies programmatically.
Handles GameObject creation, MmRelayNode setup, and routing table registration.
Example Usage:
// Build a message hierarchy
var root = MmHierarchy.Create("GameManager")
    .AddChild("UIController")
        .AddChild("MainMenu")
        .AddChild("GameplayUI")
        .Parent()
    .AddChild("GameLogic")
        .AddChild("PlayerManager")
        .AddChild("EnemyManager")
        .Parent()
    .Build();
// Add to existing hierarchy
MmHierarchy.AttachTo(existingRelay)
    .AddChild("NewChild")
    .Build();
Definition at line 40 of file HierarchyBuilder.cs.
Constructor & Destructor Documentation
HierarchyBuilder() [1/2]
MercuryMessaging.HierarchyBuilder.HierarchyBuilder (string rootName)
Create a new hierarchy builder with a root node.
Definition at line 49 of file HierarchyBuilder.cs.
References _current, and _root.
Referenced by AddChild(), AddChild< T >(), AsSwitchNode(), AtPosition(), Configure(), Inactive(), OnLayer(), Parent(), Root(), WithResponder< T >(), and WithTag().
HierarchyBuilder() [2/2]
MercuryMessaging.HierarchyBuilder.HierarchyBuilder (MmRelayNode existingRoot)
Create a builder attached to an existing relay node.
Definition at line 58 of file HierarchyBuilder.cs.
References _current, and _root.
Member Function Documentation
AddChild()
HierarchyBuilder MercuryMessaging.HierarchyBuilder.AddChild (string name)
Add a child node to the current node.
The new child becomes the current node.
Definition at line 70 of file HierarchyBuilder.cs.
References HierarchyBuilder(), _current, and _parentStack.
Referenced by AddChild< T >().
AddChild< T >()
HierarchyBuilder MercuryMessaging.HierarchyBuilder.AddChild< T > (string name)
Add a child node with a custom component type.
Type Constraints
T : MmBaseResponder
Definition at line 82 of file HierarchyBuilder.cs.
References HierarchyBuilder(), and AddChild().
AsSwitchNode()
HierarchyBuilder MercuryMessaging.HierarchyBuilder.AsSwitchNode ()
Make this a switch node (MmRelaySwitchNode).
Definition at line 174 of file HierarchyBuilder.cs.
References HierarchyBuilder().
AtPosition()
HierarchyBuilder MercuryMessaging.HierarchyBuilder.AtPosition (Vector3 position)
Set the position for the current node.
Definition at line 138 of file HierarchyBuilder.cs.
References HierarchyBuilder().
Build()
MmRelayNode MercuryMessaging.HierarchyBuilder.Build ()
Build the hierarchy and return the root relay node.
Definition at line 187 of file HierarchyBuilder.cs.
References _root, and BuildNode().
BuildNode()
MmRelayNode MercuryMessaging.HierarchyBuilder.BuildNode (NodeBuilder builder, Transform parent) private
Definition at line 201 of file HierarchyBuilder.cs.
References BuildNode(), MercuryMessaging.HierarchyBuilder.NodeBuilder.ConfigureAction, MercuryMessaging.HierarchyBuilder.NodeBuilder.ExistingRelay, MercuryMessaging.HierarchyBuilder.NodeBuilder.IsSwitchNode, MercuryMessaging.HierarchyBuilder.NodeBuilder.Layer, MercuryMessaging.HierarchyBuilder.NodeBuilder.Name, MercuryMessaging.HierarchyBuilder.NodeBuilder.Position, MercuryMessaging.HierarchyBuilder.NodeBuilder.ResponderType, MercuryMessaging.HierarchyBuilder.NodeBuilder.StartActive, and MercuryMessaging.HierarchyBuilder.NodeBuilder.Tag.
Referenced by Build(), BuildNode(), and BuildUnder().
BuildUnder()
MmRelayNode MercuryMessaging.HierarchyBuilder.BuildUnder (Transform parent)
Build the hierarchy under an existing parent.
Definition at line 195 of file HierarchyBuilder.cs.
References _root, and BuildNode().
Configure()
HierarchyBuilder MercuryMessaging.HierarchyBuilder.Configure (Action< MmRelayNode > configure)
Add an action to run after the node is created.
Definition at line 156 of file HierarchyBuilder.cs.
References HierarchyBuilder().
Inactive()
HierarchyBuilder MercuryMessaging.HierarchyBuilder.Inactive ()
Set this node as inactive by default.
Definition at line 165 of file HierarchyBuilder.cs.
References HierarchyBuilder().
OnLayer()
HierarchyBuilder MercuryMessaging.HierarchyBuilder.OnLayer (int layer)
Set the layer for the current node.
Definition at line 129 of file HierarchyBuilder.cs.
References HierarchyBuilder().
Parent()
HierarchyBuilder MercuryMessaging.HierarchyBuilder.Parent ()
Navigate back to the parent node.
Definition at line 92 of file HierarchyBuilder.cs.
References HierarchyBuilder(), _current, and _parentStack.
Root()
HierarchyBuilder MercuryMessaging.HierarchyBuilder.Root ()
Navigate back to the root node.
Definition at line 104 of file HierarchyBuilder.cs.
References HierarchyBuilder(), _current, and _parentStack.
WithResponder< T >()
HierarchyBuilder MercuryMessaging.HierarchyBuilder.WithResponder< T > ()
Add a responder component to the current node.
Type Constraints
T : MmBaseResponder
Definition at line 147 of file HierarchyBuilder.cs.
References HierarchyBuilder().
WithTag()
HierarchyBuilder MercuryMessaging.HierarchyBuilder.WithTag (MmTag tag)
Set the tag for the current node.
Definition at line 120 of file HierarchyBuilder.cs.
References HierarchyBuilder().
Member Data Documentation
_current
NodeBuilder MercuryMessaging.HierarchyBuilder._current private
Definition at line 43 of file HierarchyBuilder.cs.
Referenced by HierarchyBuilder(), HierarchyBuilder(), AddChild(), Parent(), and Root().
_parentStack
readonly Stack<NodeBuilder> MercuryMessaging.HierarchyBuilder._parentStack = new Stack<NodeBuilder>() private
Definition at line 44 of file HierarchyBuilder.cs.
Referenced by AddChild(), Parent(), and Root().
_root
readonly NodeBuilder MercuryMessaging.HierarchyBuilder._root private
Definition at line 42 of file HierarchyBuilder.cs.
Referenced by HierarchyBuilder(), HierarchyBuilder(), Build(), and BuildUnder().
The documentation for this class was generated from the following file:
Protocol/DSL/HierarchyBuilder.cs