MercuryMessaging: MercuryMessaging.Network.MmDeltaSerializer Class Reference
MercuryMessaging.Network.MmDeltaSerializer Class Reference
Serializes and deserializes MmStateDelta objects for network transmission.
Static Public Member Functions
static byte[] Serialize (MmStateDelta delta)
Serialize a single delta to bytes.
static byte[] SerializeBatch (IList< MmStateDelta > deltas)
Serialize multiple deltas to a single packet (batching).
static MmStateDelta Deserialize (byte[] data)
Deserialize a single delta from bytes.
static List< MmStateDelta > DeserializeBatch (byte[] data)
Deserialize a batch of deltas from bytes.
static bool IsDeltaBatchPacket (byte[] data)
Check if data is a delta batch packet.
Static Public Attributes
const ushort DeltaPacketHeader = 0xDD01
Magic header for delta packets to identify packet type.
Static Private Member Functions
static void WriteDelta (BinaryWriter writer, MmStateDelta delta)
static MmStateDelta ReadDelta (BinaryReader reader)
static void WriteField (BinaryWriter writer, MmDeltaField field)
static MmDeltaField ReadField (BinaryReader reader)
Detailed Description
Serializes and deserializes MmStateDelta objects for network transmission.
Uses compact binary format to minimize bandwidth.
Definition at line 17 of file MmDeltaSerializer.cs.
Member Function Documentation
Deserialize()
MmStateDelta MercuryMessaging.Network.MmDeltaSerializer.Deserialize (byte[] data) static
Deserialize a single delta from bytes.
Definition at line 64 of file MmDeltaSerializer.cs.
References ReadDelta().
DeserializeBatch()
List< MmStateDelta > MercuryMessaging.Network.MmDeltaSerializer.DeserializeBatch (byte[] data) static
Deserialize a batch of deltas from bytes.
Definition at line 76 of file MmDeltaSerializer.cs.
References DeltaPacketHeader, and ReadDelta().
IsDeltaBatchPacket()
bool MercuryMessaging.Network.MmDeltaSerializer.IsDeltaBatchPacket (byte[] data) static
Check if data is a delta batch packet.
Definition at line 105 of file MmDeltaSerializer.cs.
References DeltaPacketHeader.
ReadDelta()
MmStateDelta MercuryMessaging.Network.MmDeltaSerializer.ReadDelta (BinaryReader reader) static private
Definition at line 131 of file MmDeltaSerializer.cs.
References ReadField().
Referenced by Deserialize(), and DeserializeBatch().
ReadField()
MmDeltaField MercuryMessaging.Network.MmDeltaSerializer.ReadField (BinaryReader reader) static private
Definition at line 163 of file MmDeltaSerializer.cs.
Referenced by ReadDelta().
Serialize()
byte[] MercuryMessaging.Network.MmDeltaSerializer.Serialize (MmStateDelta delta) static
Serialize a single delta to bytes.
Definition at line 27 of file MmDeltaSerializer.cs.
References WriteDelta().
SerializeBatch()
byte[] MercuryMessaging.Network.MmDeltaSerializer.SerializeBatch (IList< MmStateDelta > deltas) static
Serialize multiple deltas to a single packet (batching).
Definition at line 40 of file MmDeltaSerializer.cs.
References DeltaPacketHeader, and WriteDelta().
WriteDelta()
void MercuryMessaging.Network.MmDeltaSerializer.WriteDelta (BinaryWriter writer, MmStateDelta delta) static private
Definition at line 112 of file MmDeltaSerializer.cs.
References MercuryMessaging.Network.MmStateDelta.BaselineSequence, MercuryMessaging.Network.MmStateDelta.ChangedFields, MercuryMessaging.Network.MmStateDelta.DeltaId, MercuryMessaging.Network.MmStateDelta.IsFullSnapshot, MercuryMessaging.Network.MmStateDelta.NetId, MercuryMessaging.Network.MmStateDelta.Timestamp, and WriteField().
Referenced by Serialize(), and SerializeBatch().
WriteField()
void MercuryMessaging.Network.MmDeltaSerializer.WriteField (BinaryWriter writer, MmDeltaField field) static private
Definition at line 155 of file MmDeltaSerializer.cs.
References MercuryMessaging.Network.MmDeltaField.FieldId, MercuryMessaging.Network.MmDeltaField.FieldType, and MercuryMessaging.Network.MmDeltaField.Value.
Referenced by WriteDelta().
Member Data Documentation
DeltaPacketHeader
const ushort MercuryMessaging.Network.MmDeltaSerializer.DeltaPacketHeader = 0xDD01 static
Magic header for delta packets to identify packet type.
Definition at line 22 of file MmDeltaSerializer.cs.
Referenced by DeserializeBatch(), IsDeltaBatchPacket(), and SerializeBatch().
The documentation for this class was generated from the following file:
Protocol/Network/MmDeltaSerializer.cs