MercuryMessaging: MercuryMessaging.Network.MmCompression Class Reference
MercuryMessaging.Network.MmCompression Class Reference
Provides compression and decompression for network data.
Static Public Member Functions
static byte[] Compress (byte[] data, MmCompressionConfig config)
Compress data using the specified configuration.
static byte[] Decompress (byte[] data)
Decompress data, automatically detecting compression.
static bool IsCompressed (byte[] data)
Check if data is compressed.
static float GetCompressionRatio (byte[] original, byte[] compressed)
Get compression ratio for the given data.
Static Public Attributes
const byte CompressedPacketMarker = 0xC0
Magic header for compressed packets.
const byte UncompressedPacketMarker = 0x00
Magic header for uncompressed packets.
Static Private Member Functions
static byte[] WrapUncompressed (byte[] data)
static byte[] WrapCompressed (byte[] compressed, MmCompressionType type, int originalLength)
static byte[] CompressInternal (byte[] data, MmCompressionConfig config)
static byte[] DecompressInternal (byte[] data, MmCompressionType type, int originalLength)
Detailed Description
Provides compression and decompression for network data.
Definition at line 106 of file MmCompression.cs.
Member Function Documentation
Compress()
byte[] MercuryMessaging.Network.MmCompression.Compress (byte[] data, MmCompressionConfig config) static
Compress data using the specified configuration.
Returns original data if compression isn't beneficial.
Definition at line 122 of file MmCompression.cs.
References CompressInternal(), MercuryMessaging.Network.MmCompressionConfig.Default, MercuryMessaging.Network.MmCompressionConfig.MinCompressionRatio, MercuryMessaging.Network.MmCompressionConfig.MinSizeToCompress, MercuryMessaging.Network.MmCompressionConfig.Type, WrapCompressed(), and WrapUncompressed().
CompressInternal()
byte[] MercuryMessaging.Network.MmCompression.CompressInternal (byte[] data, MmCompressionConfig config) static private
Definition at line 220 of file MmCompression.cs.
References MercuryMessaging.Network.Deflate, MercuryMessaging.Network.Fastest, MercuryMessaging.Network.GZip, and MercuryMessaging.Network.Optimal.
Referenced by Compress().
Decompress()
byte[] MercuryMessaging.Network.MmCompression.Decompress (byte[] data) static
Decompress data, automatically detecting compression.
Definition at line 146 of file MmCompression.cs.
References CompressedPacketMarker, DecompressInternal(), and UncompressedPacketMarker.
DecompressInternal()
byte[] MercuryMessaging.Network.MmCompression.DecompressInternal (byte[] data, MmCompressionType type, int originalLength) static private
Definition at line 247 of file MmCompression.cs.
References MercuryMessaging.Network.Deflate, and MercuryMessaging.Network.GZip.
Referenced by Decompress().
GetCompressionRatio()
float MercuryMessaging.Network.MmCompression.GetCompressionRatio (byte[] original, byte[] compressed) static
Get compression ratio for the given data.
Definition at line 195 of file MmCompression.cs.
IsCompressed()
bool MercuryMessaging.Network.MmCompression.IsCompressed (byte[] data) static
Check if data is compressed.
Definition at line 187 of file MmCompression.cs.
References CompressedPacketMarker.
WrapCompressed()
byte[] MercuryMessaging.Network.MmCompression.WrapCompressed (byte[] compressed, MmCompressionType type, int originalLength) static private
Definition at line 209 of file MmCompression.cs.
References CompressedPacketMarker.
Referenced by Compress().
WrapUncompressed()
byte[] MercuryMessaging.Network.MmCompression.WrapUncompressed (byte[] data) static private
Definition at line 201 of file MmCompression.cs.
References UncompressedPacketMarker.
Referenced by Compress().
Member Data Documentation
CompressedPacketMarker
const byte MercuryMessaging.Network.MmCompression.CompressedPacketMarker = 0xC0 static
Magic header for compressed packets.
Definition at line 111 of file MmCompression.cs.
Referenced by Decompress(), IsCompressed(), and WrapCompressed().
UncompressedPacketMarker
const byte MercuryMessaging.Network.MmCompression.UncompressedPacketMarker = 0x00 static
Magic header for uncompressed packets.
Definition at line 116 of file MmCompression.cs.
Referenced by Decompress(), and WrapUncompressed().
The documentation for this class was generated from the following file:
Protocol/Network/MmCompression.cs