MercuryMessaging: MercuryMessaging.Network.MmPoolExtensions Class Reference
MercuryMessaging.Network.MmPoolExtensions Class Reference
Extension methods for pooled operations.
Static Public Member Functions
static MmPooledMessage SerializePooled (this MmMessage message)
Serialize message using pooled byte array.
static void ReturnToPool (this MmPooledMessage pooled)
Return pooled message and its data.
Detailed Description
Extension methods for pooled operations.
Definition at line 491 of file MmMessagePool.cs.
Member Function Documentation
ReturnToPool()
void MercuryMessaging.Network.MmPoolExtensions.ReturnToPool (this MmPooledMessage pooled) static
Return pooled message and its data.
Definition at line 507 of file MmMessagePool.cs.
References MercuryMessaging.Network.MmMessagePoolManager.Instance, MercuryMessaging.Network.MmMessagePoolManager.ReturnByteArray(), MercuryMessaging.Network.MmMessagePoolManager.ReturnPooledMessage(), and MercuryMessaging.Network.MmPooledMessage.SerializedData.
SerializePooled()
MmPooledMessage MercuryMessaging.Network.MmPoolExtensions.SerializePooled (this MmMessage message) static
Serialize message using pooled byte array.
Definition at line 496 of file MmMessagePool.cs.
References MercuryMessaging.Network.MmMessagePoolManager.GetPooledMessage(), MercuryMessaging.Network.MmMessagePoolManager.Instance, and MercuryMessaging.Network.MmBinarySerializer.Serialize().
The documentation for this class was generated from the following file:
Protocol/Network/MmMessagePool.cs