MercuryMessaging: MercuryMessaging.MmNetworkExtensions Class Reference
MercuryMessaging.MmNetworkExtensions Class Reference
Extension methods for network-aware messaging.
Static Public Member Functions
static bool IsNetworkMessage (this MmRelayNode relay, MmMessage message)
Check if a message originated from the network (was deserialized).
static bool HasNetworkSupport (this MmRelayNode relay)
Check if this node has network capability.
static bool IsHost (this MmRelayNode relay)
Check if this node is running as a host (both client and server).
static bool IsClientOnly (this MmRelayNode relay)
Check if this node is a client only (not server).
static bool IsServerOnly (this MmRelayNode relay)
Check if this node is a server only (not client).
static MmFluentMessage SendNetworked (this MmRelayNode relay, MmMethod method)
Send a message over the network (locally + remote).
static MmFluentMessage SendNetworked (this MmRelayNode relay, string value)
Send a string message over the network.
static MmFluentMessage SendNetworked (this MmRelayNode relay, int value)
Send an int message over the network.
static MmFluentMessage SendNetworked (this MmRelayNode relay, float value)
Send a float message over the network.
static MmFluentMessage SendNetworked (this MmRelayNode relay, bool value)
Send a bool message over the network.
static MmFluentMessage SendNetworked (this MmRelayNode relay, Vector3 value)
Send a Vector3 message over the network.
static void IfFromNetwork (this MmRelayNode relay, MmMessage message, Action action)
Execute action only if message came from network.
static void IfLocal (this MmRelayNode relay, MmMessage message, Action action)
Execute action only if message is local (not from network).
static void IfHost (this MmRelayNode relay, Action action)
Execute action only if this node is the host.
static void IfClient (this MmRelayNode relay, Action action)
Execute action only if this node is a client (not server).
static void IfServer (this MmRelayNode relay, Action action)
Execute action only if this node is a server (not client).
static bool IsNetworkMessage (this MmBaseResponder responder, MmMessage message)
Check if a message originated from the network (for responders).
static void IfFromNetwork (this MmBaseResponder responder, MmMessage message, Action action)
Execute action only if message came from network (for responders).
static void IfLocal (this MmBaseResponder responder, MmMessage message, Action action)
Execute action only if message is local (for responders).
Detailed Description
Extension methods for network-aware messaging.
Provides convenient patterns for handling networked messages.
Example Usage:
// Send message to all clients (from host/server)
relay.BroadcastToClients(MmMethod.MessageString, "Hello clients");
// Send to server (from client)
relay.SendToServer(MmMethod.MessageInt, 42);
// Check if message came from network
if (relay.IsNetworkMessage(message))
{
    // Handle network-origin message differently
}
// Send with automatic host handling
relay.SendNetworked("StateUpdate").ToDescendants().Execute();
Definition at line 34 of file MmNetworkExtensions.cs.
Member Function Documentation
HasNetworkSupport()
bool MercuryMessaging.MmNetworkExtensions.HasNetworkSupport (this MmRelayNode relay) static
Check if this node has network capability.
Definition at line 50 of file MmNetworkExtensions.cs.
References MercuryMessaging.MmRelayNode.MmNetworkResponder.
IfClient()
void MercuryMessaging.MmNetworkExtensions.IfClient (this MmRelayNode relay, Action action) static
Execute action only if this node is a client (not server).
Definition at line 180 of file MmNetworkExtensions.cs.
IfFromNetwork() [1/2]
void MercuryMessaging.MmNetworkExtensions.IfFromNetwork (this MmBaseResponder responder, MmMessage message, Action action) static
Execute action only if message came from network (for responders).
Definition at line 214 of file MmNetworkExtensions.cs.
References MercuryMessaging.MmMessage.IsDeserialized.
IfFromNetwork() [2/2]
void MercuryMessaging.MmNetworkExtensions.IfFromNetwork (this MmRelayNode relay, MmMessage message, Action action) static
Execute action only if message came from network.
relay.IfFromNetwork(message, () => { // Handle network message });
Definition at line 147 of file MmNetworkExtensions.cs.
References MercuryMessaging.MmMessage.IsDeserialized.
IfHost()
void MercuryMessaging.MmNetworkExtensions.IfHost (this MmRelayNode relay, Action action) static
Execute action only if this node is the host.
Definition at line 169 of file MmNetworkExtensions.cs.
IfLocal() [1/2]
void MercuryMessaging.MmNetworkExtensions.IfLocal (this MmBaseResponder responder, MmMessage message, Action action) static
Execute action only if message is local (for responders).
Definition at line 225 of file MmNetworkExtensions.cs.
References MercuryMessaging.MmMessage.IsDeserialized.
IfLocal() [2/2]
void MercuryMessaging.MmNetworkExtensions.IfLocal (this MmRelayNode relay, MmMessage message, Action action) static
Execute action only if message is local (not from network).
Definition at line 158 of file MmNetworkExtensions.cs.
References MercuryMessaging.MmMessage.IsDeserialized.
IfServer()
void MercuryMessaging.MmNetworkExtensions.IfServer (this MmRelayNode relay, Action action) static
Execute action only if this node is a server (not client).
Definition at line 191 of file MmNetworkExtensions.cs.
IsClientOnly()
bool MercuryMessaging.MmNetworkExtensions.IsClientOnly (this MmRelayNode relay) static
Check if this node is a client only (not server).
Definition at line 67 of file MmNetworkExtensions.cs.
References MercuryMessaging.MmRelayNode.MmNetworkResponder, and MercuryMessaging.IMmNetworkResponder.OnServer.
IsHost()
bool MercuryMessaging.MmNetworkExtensions.IsHost (this MmRelayNode relay) static
Check if this node is running as a host (both client and server).
Definition at line 58 of file MmNetworkExtensions.cs.
References MercuryMessaging.MmRelayNode.MmNetworkResponder, and MercuryMessaging.IMmNetworkResponder.OnServer.
IsNetworkMessage() [1/2]
bool MercuryMessaging.MmNetworkExtensions.IsNetworkMessage (this MmBaseResponder responder, MmMessage message) static
Check if a message originated from the network (for responders).
Definition at line 206 of file MmNetworkExtensions.cs.
References MercuryMessaging.MmMessage.IsDeserialized.
IsNetworkMessage() [2/2]
bool MercuryMessaging.MmNetworkExtensions.IsNetworkMessage (this MmRelayNode relay, MmMessage message) static
Check if a message originated from the network (was deserialized).
Useful for distinguishing local vs. remote message sources.
Definition at line 42 of file MmNetworkExtensions.cs.
References MercuryMessaging.MmMessage.IsDeserialized.
IsServerOnly()
bool MercuryMessaging.MmNetworkExtensions.IsServerOnly (this MmRelayNode relay) static
Check if this node is a server only (not client).
Definition at line 76 of file MmNetworkExtensions.cs.
References MercuryMessaging.MmRelayNode.MmNetworkResponder, and MercuryMessaging.IMmNetworkResponder.OnServer.
SendNetworked() [1/6]
MmFluentMessage MercuryMessaging.MmNetworkExtensions.SendNetworked (this MmRelayNode relay, bool value) static
Send a bool message over the network.
Definition at line 122 of file MmNetworkExtensions.cs.
References MercuryMessaging.MmFluentMessage.OverNetwork(), and MercuryMessaging.MmFluentExtensions.Send().
SendNetworked() [2/6]
MmFluentMessage MercuryMessaging.MmNetworkExtensions.SendNetworked (this MmRelayNode relay, float value) static
Send a float message over the network.
Definition at line 114 of file MmNetworkExtensions.cs.
References MercuryMessaging.MmFluentMessage.OverNetwork(), and MercuryMessaging.MmFluentExtensions.Send().
SendNetworked() [3/6]
MmFluentMessage MercuryMessaging.MmNetworkExtensions.SendNetworked (this MmRelayNode relay, int value) static
Send an int message over the network.
Definition at line 106 of file MmNetworkExtensions.cs.
References MercuryMessaging.MmFluentMessage.OverNetwork(), and MercuryMessaging.MmFluentExtensions.Send().
SendNetworked() [4/6]
MmFluentMessage MercuryMessaging.MmNetworkExtensions.SendNetworked (this MmRelayNode relay, MmMethod method) static
Send a message over the network (locally + remote).
Convenient shorthand for Send().OverNetwork().
Definition at line 90 of file MmNetworkExtensions.cs.
References MercuryMessaging.MmFluentMessage.OverNetwork(), and MercuryMessaging.MmFluentExtensions.Send().
SendNetworked() [5/6]
MmFluentMessage MercuryMessaging.MmNetworkExtensions.SendNetworked (this MmRelayNode relay, string value) static
Send a string message over the network.
Definition at line 98 of file MmNetworkExtensions.cs.
References MercuryMessaging.MmFluentMessage.OverNetwork(), and MercuryMessaging.MmFluentExtensions.Send().
SendNetworked() [6/6]
MmFluentMessage MercuryMessaging.MmNetworkExtensions.SendNetworked (this MmRelayNode relay, Vector3 value) static
Send a Vector3 message over the network.
Definition at line 130 of file MmNetworkExtensions.cs.
References MercuryMessaging.MmFluentMessage.OverNetwork(), and MercuryMessaging.MmFluentExtensions.Send().
The documentation for this class was generated from the following file:
Protocol/DSL/MmNetworkExtensions.cs