MercuryMessaging: MercuryMessaging.MmRelayNodeExtensions Class Reference
MercuryMessaging.MmRelayNodeExtensions Class Reference
Convenience extension methods for MmRelayNode to simplify common messaging patterns.
Static Public Member Functions
static void Broadcast (this MmRelayNode relay, MmMethod method)
Broadcast a message to self and all descendants (children and their children recursively).
static void Broadcast (this MmRelayNode relay, MmMethod method, bool value)
Broadcast a boolean message to self and all descendants.
static void Broadcast (this MmRelayNode relay, MmMethod method, int value)
Broadcast an integer message to self and all descendants.
static void Broadcast (this MmRelayNode relay, MmMethod method, float value)
Broadcast a float message to self and all descendants.
static void Broadcast (this MmRelayNode relay, MmMethod method, string value)
Broadcast a string message to self and all descendants.
static void Broadcast (this MmRelayNode relay, MmMethod method, Vector3 value)
Broadcast a Vector3 message to self and all descendants.
static void Broadcast (this MmRelayNode relay, MmMessage message)
Broadcast a message object to self and all descendants.
static void Notify (this MmRelayNode relay, MmMethod method)
Notify parent nodes of an event (upward communication).
static void Notify (this MmRelayNode relay, MmMethod method, bool value)
Notify parents with a boolean value.
static void Notify (this MmRelayNode relay, MmMethod method, int value)
Notify parents with an integer value.
static void Notify (this MmRelayNode relay, MmMethod method, float value)
Notify parents with a float value.
static void Notify (this MmRelayNode relay, MmMethod method, string value)
Notify parents with a string value.
static void Notify (this MmRelayNode relay, MmMessage message)
Notify parents with a message object.
static void NotifyAncestors (this MmRelayNode relay, MmMethod method)
Notify all ancestors (recursive upward) with a method.
static void SendTo (this MmRelayNode relay, string targetName, MmMethod method)
Send a message to a specifically named target in the hierarchy.
static void SendTo (this MmRelayNode relay, string targetName, MmMethod method, bool value)
Send a boolean message to a named target.
static void SendTo (this MmRelayNode relay, string targetName, MmMethod method, int value)
Send an integer message to a named target.
static void SendTo (this MmRelayNode relay, string targetName, MmMethod method, float value)
Send a float message to a named target.
static void SendTo (this MmRelayNode relay, string targetName, MmMethod method, string value)
Send a string message to a named target.
static void SendTo (this MmRelayNode relay, string targetName, MmMessage message)
Send a message object to a named target.
static void SendTo (this MmRelayNode relay, MmRelayNode target, MmMethod method)
Send a message directly to a specific relay node reference.
static void SendTo (this MmRelayNode relay, MmRelayNode target, MmMessage message)
Send a message directly to a specific relay node reference.
static int Query (this MmRelayNode relay, MmMethod method, Action< MmMessage > onResponse)
Send a query and register a callback for the response.
static int QueryDescendants (this MmRelayNode relay, MmMethod method, Action< MmMessage > onResponse)
Send a query to descendants and register a callback.
static void Respond (this MmRelayNode relay, int queryId, MmMessage response)
Send a response to a pending query.
static void Respond (this MmRelayNode relay, int queryId, int value)
Respond to a query with an integer value.
static void Respond (this MmRelayNode relay, int queryId, float value)
Respond to a query with a float value.
static void Respond (this MmRelayNode relay, int queryId, string value)
Respond to a query with a string value.
static void Respond (this MmRelayNode relay, int queryId, bool value)
Respond to a query with a boolean value.
static bool CancelQuery (int queryId)
Cancel a pending query.
static void ClearPendingQueries ()
Clear all pending queries.
static bool TryFindTarget (this MmRelayNode relay, string targetName, out MmRelayNode target)
Try to find a relay node by name, returning whether it was found.
static bool HasTarget (this MmRelayNode relay, string targetName)
Check if a target exists in the hierarchy.
Static Private Member Functions
static MmRelayNode FindTargetRelay (MmRelayNode source, string targetName)
Find a relay node by name in the hierarchy (searches descendants).
Static Private Attributes
static readonly Dictionary< int, Action< MmMessage > > _pendingQueries
static int _nextQueryId = 1
Detailed Description
Convenience extension methods for MmRelayNode to simplify common messaging patterns.
Provides high-level abstractions over the fluent API and standard MmInvoke calls.
Phase 3 - Task 3.2: Convenience Extensions
NOTE: These methods use the fluent API internally for proper routing. The fluent API properly transforms level filters so responders receive messages.
RECOMMENDATION: For shorter code, consider using MmQuickExtensions:
relay.Init() instead of relay.Broadcast(MmMethod.Initialize)
relay.Tell(value) instead of relay.Broadcast(MmMethod.MessageX, value)
relay.Done() instead of relay.NotifyComplete()
relay.Report(value) instead of relay.Notify(MmMethod.MessageX, value)
Definition at line 26 of file MmRelayNodeExtensions.cs.
Member Function Documentation
Broadcast() [1/7]
void MercuryMessaging.MmRelayNodeExtensions.Broadcast (this MmRelayNode relay, MmMessage message) static
Broadcast a message object to self and all descendants.
Definition at line 119 of file MmRelayNodeExtensions.cs.
References MercuryMessaging.MmRelayNode.MmInvoke(), and MercuryMessaging.MmLevelFilterHelper.SelfAndChildren.
Broadcast() [2/7]
void MercuryMessaging.MmRelayNodeExtensions.Broadcast (this MmRelayNode relay, MmMethod method) static
Broadcast a message to self and all descendants (children and their children recursively).
Uses SelfAndChildren routing so responders on the same object receive the message.
Definition at line 35 of file MmRelayNodeExtensions.cs.
References MercuryMessaging.MmRelayNode.MmInvoke(), and MercuryMessaging.MmLevelFilterHelper.SelfAndChildren.
Broadcast() [3/7]
void MercuryMessaging.MmRelayNodeExtensions.Broadcast (this MmRelayNode relay, MmMethod method, bool value) static
Broadcast a boolean message to self and all descendants.
Definition at line 49 of file MmRelayNodeExtensions.cs.
References MercuryMessaging.MmRelayNode.MmInvoke(), and MercuryMessaging.MmLevelFilterHelper.SelfAndChildren.
Broadcast() [4/7]
void MercuryMessaging.MmRelayNodeExtensions.Broadcast (this MmRelayNode relay, MmMethod method, float value) static
Broadcast a float message to self and all descendants.
Definition at line 77 of file MmRelayNodeExtensions.cs.
References MercuryMessaging.MmRelayNode.MmInvoke(), and MercuryMessaging.MmLevelFilterHelper.SelfAndChildren.
Broadcast() [5/7]
void MercuryMessaging.MmRelayNodeExtensions.Broadcast (this MmRelayNode relay, MmMethod method, int value) static
Broadcast an integer message to self and all descendants.
Definition at line 63 of file MmRelayNodeExtensions.cs.
References MercuryMessaging.MmRelayNode.MmInvoke(), and MercuryMessaging.MmLevelFilterHelper.SelfAndChildren.
Broadcast() [6/7]
void MercuryMessaging.MmRelayNodeExtensions.Broadcast (this MmRelayNode relay, MmMethod method, string value) static
Broadcast a string message to self and all descendants.
Definition at line 91 of file MmRelayNodeExtensions.cs.
References MercuryMessaging.MmRelayNode.MmInvoke(), and MercuryMessaging.MmLevelFilterHelper.SelfAndChildren.
Broadcast() [7/7]
void MercuryMessaging.MmRelayNodeExtensions.Broadcast (this MmRelayNode relay, MmMethod method, Vector3 value) static
Broadcast a Vector3 message to self and all descendants.
Definition at line 105 of file MmRelayNodeExtensions.cs.
References MercuryMessaging.MmRelayNode.MmInvoke(), and MercuryMessaging.MmLevelFilterHelper.SelfAndChildren.
CancelQuery()
bool MercuryMessaging.MmRelayNodeExtensions.CancelQuery (int queryId) static
Cancel a pending query.
Definition at line 461 of file MmRelayNodeExtensions.cs.
References _pendingQueries.
ClearPendingQueries()
void MercuryMessaging.MmRelayNodeExtensions.ClearPendingQueries () static
Clear all pending queries.
Definition at line 469 of file MmRelayNodeExtensions.cs.
References _pendingQueries.
FindTargetRelay()
MmRelayNode MercuryMessaging.MmRelayNodeExtensions.FindTargetRelay (MmRelayNode source, string targetName) static private
Find a relay node by name in the hierarchy (searches descendants).
Definition at line 481 of file MmRelayNodeExtensions.cs.
References FindTargetRelay(), and MercuryMessaging.MmRelayNode.RoutingTable.
Referenced by FindTargetRelay(), HasTarget(), SendTo(), SendTo(), SendTo(), SendTo(), SendTo(), SendTo(), and TryFindTarget().
HasTarget()
bool MercuryMessaging.MmRelayNodeExtensions.HasTarget (this MmRelayNode relay, string targetName) static
Check if a target exists in the hierarchy.
Definition at line 527 of file MmRelayNodeExtensions.cs.
References FindTargetRelay().
Notify() [1/6]
void MercuryMessaging.MmRelayNodeExtensions.Notify (this MmRelayNode relay, MmMessage message) static
Notify parents with a message object.
Definition at line 187 of file MmRelayNodeExtensions.cs.
Notify() [2/6]
void MercuryMessaging.MmRelayNodeExtensions.Notify (this MmRelayNode relay, MmMethod method) static
Notify parent nodes of an event (upward communication).
Uses the fluent API internally for proper routing.
Definition at line 142 of file MmRelayNodeExtensions.cs.
References MercuryMessaging.MmFluentMessage.Execute(), and MercuryMessaging.MmFluentMessage.ToParents().
Notify() [3/6]
void MercuryMessaging.MmRelayNodeExtensions.Notify (this MmRelayNode relay, MmMethod method, bool value) static
Notify parents with a boolean value.
Definition at line 151 of file MmRelayNodeExtensions.cs.
References MercuryMessaging.MmFluentMessage.Execute(), and MercuryMessaging.MmFluentMessage.ToParents().
Notify() [4/6]
void MercuryMessaging.MmRelayNodeExtensions.Notify (this MmRelayNode relay, MmMethod method, float value) static
Notify parents with a float value.
Definition at line 169 of file MmRelayNodeExtensions.cs.
References MercuryMessaging.MmFluentMessage.Execute(), and MercuryMessaging.MmFluentMessage.ToParents().
Notify() [5/6]
void MercuryMessaging.MmRelayNodeExtensions.Notify (this MmRelayNode relay, MmMethod method, int value) static
Notify parents with an integer value.
Definition at line 160 of file MmRelayNodeExtensions.cs.
References MercuryMessaging.MmFluentMessage.Execute(), and MercuryMessaging.MmFluentMessage.ToParents().
Notify() [6/6]
void MercuryMessaging.MmRelayNodeExtensions.Notify (this MmRelayNode relay, MmMethod method, string value) static
Notify parents with a string value.
Definition at line 178 of file MmRelayNodeExtensions.cs.
References MercuryMessaging.MmFluentMessage.Execute(), and MercuryMessaging.MmFluentMessage.ToParents().
NotifyAncestors()
void MercuryMessaging.MmRelayNodeExtensions.NotifyAncestors (this MmRelayNode relay, MmMethod method) static
Notify all ancestors (recursive upward) with a method.
Definition at line 196 of file MmRelayNodeExtensions.cs.
References MercuryMessaging.MmFluentMessage.Execute(), and MercuryMessaging.MmFluentMessage.ToAncestors().
Query()
int MercuryMessaging.MmRelayNodeExtensions.Query (this MmRelayNode relay, MmMethod method, Action< MmMessage > onResponse) static
Send a query and register a callback for the response.
Definition at line 383 of file MmRelayNodeExtensions.cs.
References _nextQueryId, _pendingQueries, MercuryMessaging.MmMessagePool.GetInt(), MercuryMessaging.MmRelayNode.MmInvoke(), MercuryMessaging.MmMessagePool.Return(), and MercuryMessaging.MmLevelFilterHelper.SelfAndChildren.
QueryDescendants()
int MercuryMessaging.MmRelayNodeExtensions.QueryDescendants (this MmRelayNode relay, MmMethod method, Action< MmMessage > onResponse) static
Send a query to descendants and register a callback.
Definition at line 404 of file MmRelayNodeExtensions.cs.
References _nextQueryId, _pendingQueries, MercuryMessaging.MmFluentMessage.Execute(), and MercuryMessaging.MmFluentMessage.ToDescendants().
Respond() [1/5]
void MercuryMessaging.MmRelayNodeExtensions.Respond (this MmRelayNode relay, int queryId, bool value) static
Respond to a query with a boolean value.
Definition at line 453 of file MmRelayNodeExtensions.cs.
References Respond().
Respond() [2/5]
void MercuryMessaging.MmRelayNodeExtensions.Respond (this MmRelayNode relay, int queryId, float value) static
Respond to a query with a float value.
Definition at line 437 of file MmRelayNodeExtensions.cs.
References Respond().
Respond() [3/5]
void MercuryMessaging.MmRelayNodeExtensions.Respond (this MmRelayNode relay, int queryId, int value) static
Respond to a query with an integer value.
Definition at line 429 of file MmRelayNodeExtensions.cs.
References Respond().
Respond() [4/5]
void MercuryMessaging.MmRelayNodeExtensions.Respond (this MmRelayNode relay, int queryId, MmMessage response) static
Send a response to a pending query.
Definition at line 417 of file MmRelayNodeExtensions.cs.
References _pendingQueries.
Referenced by Respond(), Respond(), Respond(), and Respond().
Respond() [5/5]
void MercuryMessaging.MmRelayNodeExtensions.Respond (this MmRelayNode relay, int queryId, string value) static
Respond to a query with a string value.
Definition at line 445 of file MmRelayNodeExtensions.cs.
References Respond().
SendTo() [1/8]
void MercuryMessaging.MmRelayNodeExtensions.SendTo (this MmRelayNode relay, MmRelayNode target, MmMessage message) static
Send a message directly to a specific relay node reference.
Definition at line 358 of file MmRelayNodeExtensions.cs.
References MercuryMessaging.MmRelayNode.MmInvoke(), and MercuryMessaging.MmLevelFilterHelper.SelfAndChildren.
SendTo() [2/8]
void MercuryMessaging.MmRelayNodeExtensions.SendTo (this MmRelayNode relay, MmRelayNode target, MmMethod method) static
Send a message directly to a specific relay node reference.
Definition at line 341 of file MmRelayNodeExtensions.cs.
References MercuryMessaging.MmRelayNode.MmInvoke(), and MercuryMessaging.MmLevelFilterHelper.SelfAndChildren.
SendTo() [3/8]
void MercuryMessaging.MmRelayNodeExtensions.SendTo (this MmRelayNode relay, string targetName, MmMessage message) static
Send a message object to a named target.
Definition at line 318 of file MmRelayNodeExtensions.cs.
References FindTargetRelay(), and MercuryMessaging.MmLevelFilterHelper.SelfAndChildren.
SendTo() [4/8]
void MercuryMessaging.MmRelayNodeExtensions.SendTo (this MmRelayNode relay, string targetName, MmMethod method) static
Send a message to a specifically named target in the hierarchy.
Searches descendants for a GameObject with the given name.
Definition at line 212 of file MmRelayNodeExtensions.cs.
References FindTargetRelay(), and MercuryMessaging.MmLevelFilterHelper.SelfAndChildren.
SendTo() [5/8]
void MercuryMessaging.MmRelayNodeExtensions.SendTo (this MmRelayNode relay, string targetName, MmMethod method, bool value) static
Send a boolean message to a named target.
Definition at line 234 of file MmRelayNodeExtensions.cs.
References FindTargetRelay(), and MercuryMessaging.MmLevelFilterHelper.SelfAndChildren.
SendTo() [6/8]
void MercuryMessaging.MmRelayNodeExtensions.SendTo (this MmRelayNode relay, string targetName, MmMethod method, float value) static
Send a float message to a named target.
Definition at line 276 of file MmRelayNodeExtensions.cs.
References FindTargetRelay(), and MercuryMessaging.MmLevelFilterHelper.SelfAndChildren.
SendTo() [7/8]
void MercuryMessaging.MmRelayNodeExtensions.SendTo (this MmRelayNode relay, string targetName, MmMethod method, int value) static
Send an integer message to a named target.
Definition at line 255 of file MmRelayNodeExtensions.cs.
References FindTargetRelay(), and MercuryMessaging.MmLevelFilterHelper.SelfAndChildren.
SendTo() [8/8]
void MercuryMessaging.MmRelayNodeExtensions.SendTo (this MmRelayNode relay, string targetName, MmMethod method, string value) static
Send a string message to a named target.
Definition at line 297 of file MmRelayNodeExtensions.cs.
References FindTargetRelay(), and MercuryMessaging.MmLevelFilterHelper.SelfAndChildren.
TryFindTarget()
bool MercuryMessaging.MmRelayNodeExtensions.TryFindTarget (this MmRelayNode relay, string targetName, out MmRelayNode target) static
Try to find a relay node by name, returning whether it was found.
Definition at line 518 of file MmRelayNodeExtensions.cs.
References FindTargetRelay().
Member Data Documentation
_nextQueryId
int MercuryMessaging.MmRelayNodeExtensions._nextQueryId = 1 static private
Definition at line 378 of file MmRelayNodeExtensions.cs.
Referenced by Query(), and QueryDescendants().
_pendingQueries
readonly Dictionary<int, Action<MmMessage> > MercuryMessaging.MmRelayNodeExtensions._pendingQueries static private
Initial value:
=
            new Dictionary<int, Action<MmMessage>>()
Definition at line 376 of file MmRelayNodeExtensions.cs.
Referenced by CancelQuery(), ClearPendingQueries(), Query(), QueryDescendants(), and Respond().
The documentation for this class was generated from the following file:
Protocol/DSL/MmRelayNodeExtensions.cs