MercuryMessaging: MercuryMessaging.TransformExtensions Class Reference
MercuryMessaging.TransformExtensions Class Reference
Collection of GameObject extensions useful if creating applications using MercuryMessaging.
Static Public Member Functions
static void SetPosition (this Transform transform, Vector3 position, bool useGlobal)
Set global or local position member of transform.
static void SetRotation (this Transform transform, Quaternion rotation, bool useGlobal)
Set global or local rotation member of transform.
static void SetPosRot (this Transform transform, Vector3 position, Quaternion rotation, bool useGlobal)
Set global or local position and rotation members of transform.
static void SetPosRotScale (this Transform transform, Vector3 position, Quaternion rotation, Vector3 scale, bool useGlobal)
Set global or local position and rotation members of transform.
static Vector3 GetPosition (this Transform transform, bool useGlobal)
Get global or local position member of transform.
static Quaternion GetRotation (this Transform transform, bool useGlobal)
Get global or local rotation member of transform.
static Vector3 GetScale (this Transform transform, bool useGlobal)
Get global or local scale member of transform.
static void GetPosRot (this Transform transform, out Vector3 position, out Quaternion rotation, bool useGlobal)
Returns position and rotation of the transformation in a single function call.
static void GetPosRotScale (this Transform transform, out Vector3 position, out Quaternion rotation, out Vector3 scale, bool useGlobal)
Returns position, rotation, and scale of the transformation in a single function call.
static void CopyPosition (this Transform transform, Transform other, bool setGlobal)
Copy position of another transformation.
static void CopyRotation (this Transform transform, Transform other, bool setGlobal)
Copy rotation of another transformation.
static void CopyTransform (this Transform transform, Transform other, bool setGlobal)
Copy position and rotation of another transformation.
static string ToCSV (this Vector3 v, char delim=',', string format="0.0000")
Create CSV formatted string from Vector3.
static string ToCSV (this Vector2 v, char delim=',', string format="0.0000")
Create CSV formatted string from Vector2.
static string ToCSV (this Quaternion q, char delim=',', string format="0.0000")
Create CSV formatted string from Quaternion.
static Quaternion CSV2Quaternion (string s, char delim=',')
Get Quaternion from CSV formatted string.
static Vector3 CSV2Vector3 (string s, char delim=',')
Get Vector3 from CSV formatted string.
static Vector3 CSV2Vector2 (string s, char delim=',')
Get Vector2 from CSV formatted string.
Detailed Description
Collection of GameObject extensions useful if creating applications using MercuryMessaging.
Definition at line 42 of file TransformExtensions.cs.
Member Function Documentation
CopyPosition()
void MercuryMessaging.TransformExtensions.CopyPosition (this Transform transform, Transform other, bool setGlobal) static
Copy position of another transformation.
Parameters
transform Target Transform.
other Source Transform.
setGlobal Whether to use global or local transformation values.
Definition at line 201 of file TransformExtensions.cs.
Referenced by CopyTransform().
CopyRotation()
void MercuryMessaging.TransformExtensions.CopyRotation (this Transform transform, Transform other, bool setGlobal) static
Copy rotation of another transformation.
Parameters
transform Target Transform.
other Source trasnform.
setGlobal Whether to use global or local transformation values.
Definition at line 219 of file TransformExtensions.cs.
Referenced by CopyTransform().
CopyTransform()
void MercuryMessaging.TransformExtensions.CopyTransform (this Transform transform, Transform other, bool setGlobal) static
Copy position and rotation of another transformation.
Parameters
transform Target Transform.
other Source transform.
setGlobal Whether to use global or local transformation values.
Definition at line 237 of file TransformExtensions.cs.
References CopyPosition(), and CopyRotation().
CSV2Quaternion()
Quaternion MercuryMessaging.TransformExtensions.CSV2Quaternion (string s, char delim = ',') static
Get Quaternion from CSV formatted string.
Parameters
s Input string.
delim Delimiter.
Returns
New Quaternion.
Definition at line 306 of file TransformExtensions.cs.
Referenced by MercuryMessaging.Task.MmLookAtTaskInfo.Parse().
CSV2Vector2()
Vector3 MercuryMessaging.TransformExtensions.CSV2Vector2 (string s, char delim = ',') static
Get Vector2 from CSV formatted string.
Parameters
s Input string.
delim Delimiter.
Returns
New Vector2.
Definition at line 341 of file TransformExtensions.cs.
CSV2Vector3()
Vector3 MercuryMessaging.TransformExtensions.CSV2Vector3 (string s, char delim = ',') static
Get Vector3 from CSV formatted string.
Parameters
s Input string.
delim Delimiter.
Returns
New Vector3.
Definition at line 324 of file TransformExtensions.cs.
Referenced by MercuryMessaging.Task.MmLookAtTaskInfo.Parse().
GetPosition()
Vector3 MercuryMessaging.TransformExtensions.GetPosition (this Transform transform, bool useGlobal) static
Get global or local position member of transform.
Parameters
transform Target Transform.
useGlobal Whether to use global or local transformation values.
Returns
Position of transform.
Definition at line 115 of file TransformExtensions.cs.
GetPosRot()
void MercuryMessaging.TransformExtensions.GetPosRot (this Transform transform, out Vector3 position, out Quaternion rotation, bool useGlobal) static
Returns position and rotation of the transformation in a single function call.
Parameters
transform Observed Transform.
position Target position.
rotation Target rotation.
useGlobal Whether to use global or local transformation values.
Definition at line 171 of file TransformExtensions.cs.
GetPosRotScale()
void MercuryMessaging.TransformExtensions.GetPosRotScale (this Transform transform, out Vector3 position, out Quaternion rotation, out Vector3 scale, bool useGlobal) static
Returns position, rotation, and scale of the transformation in a single function call.
Parameters
transform Observed Transform.
position Target position.
rotation Target rotation.
scale Target scale.
useGlobal Whether to use global or local transformation values.
Definition at line 187 of file TransformExtensions.cs.
GetRotation()
Quaternion MercuryMessaging.TransformExtensions.GetRotation (this Transform transform, bool useGlobal) static
Get global or local rotation member of transform.
Parameters
transform Observed Transform.
useGlobal Whether to use global or local transformation values.
Returns
Rotation as Quaternion.
Definition at line 133 of file TransformExtensions.cs.
GetScale()
Vector3 MercuryMessaging.TransformExtensions.GetScale (this Transform transform, bool useGlobal) static
Get global or local scale member of transform.
Parameters
transform Observed Transform.
useGlobal Whether to use global or local transformation values.
Returns
Get scale of transform.
Definition at line 151 of file TransformExtensions.cs.
SetPosition()
void MercuryMessaging.TransformExtensions.SetPosition (this Transform transform, Vector3 position, bool useGlobal) static
Set global or local position member of transform.
Parameters
transform Target Transform.
position Input position.
useGlobal Whether to use global or local transformation values.
Definition at line 50 of file TransformExtensions.cs.
Referenced by SetPosRot(), and SetPosRotScale().
SetPosRot()
void MercuryMessaging.TransformExtensions.SetPosRot (this Transform transform, Vector3 position, Quaternion rotation, bool useGlobal) static
Set global or local position and rotation members of transform.
Parameters
transform Target Transform.
position Input Position.
rotation Input Rotation.
useGlobal Whether to use global or local transformation values.
Definition at line 87 of file TransformExtensions.cs.
References SetPosition(), and SetRotation().
SetPosRotScale()
void MercuryMessaging.TransformExtensions.SetPosRotScale (this Transform transform, Vector3 position, Quaternion rotation, Vector3 scale, bool useGlobal) static
Set global or local position and rotation members of transform.
Parameters
transform Target Transform.
position Input Position.
rotation Input Rotation.
useGlobal Whether to use global or local transformation values.
Definition at line 101 of file TransformExtensions.cs.
References SetPosition(), and SetRotation().
SetRotation()
void MercuryMessaging.TransformExtensions.SetRotation (this Transform transform, Quaternion rotation, bool useGlobal) static
Set global or local rotation member of transform.
Parameters
transform Target Transform.
rotation Input Rotation.
useGlobal Whether to use global or local transformation values.
Definition at line 68 of file TransformExtensions.cs.
Referenced by SetPosRot(), and SetPosRotScale().
ToCSV() [1/3]
string MercuryMessaging.TransformExtensions.ToCSV (this Quaternion q, char delim = ',', string format = "0.0000") static
Create CSV formatted string from Quaternion.
Parameters
q Source Vector3.
delim Delimiter.
format String format.
Returns
Formatted string.
Definition at line 290 of file TransformExtensions.cs.
ToCSV() [2/3]
string MercuryMessaging.TransformExtensions.ToCSV (this Vector2 v, char delim = ',', string format = "0.0000") static
Create CSV formatted string from Vector2.
Parameters
v Source Vector3.
delim Delimiter.
format String format.
Returns
Formatted string.
Definition at line 275 of file TransformExtensions.cs.
ToCSV() [3/3]
string MercuryMessaging.TransformExtensions.ToCSV (this Vector3 v, char delim = ',', string format = "0.0000") static
Create CSV formatted string from Vector3.
Parameters
v Source Vector3.
delim Delimiter.
format String format.
Returns
Formatted string.
Definition at line 259 of file TransformExtensions.cs.
The documentation for this class was generated from the following file:
Protocol/Core/Extensions/TransformExtensions.cs