MercuryMessaging: MercuryMessaging.MmTemporalExtensions Class Reference
MercuryMessaging.MmTemporalExtensions Class Reference
Temporal extension methods for MmRelayNode providing time-based messaging patterns.
Static Public Member Functions
static MmTemporalHandle After (this MmRelayNode relay, float delay, MmMethod method)
Send a message after a delay.
static MmTemporalHandle After (this MmRelayNode relay, float delay, MmMethod method, MmMetadataBlock metadata)
Send a message after a delay with metadata.
static MmTemporalHandle After (this MmRelayNode relay, float delay, MmMethod method, bool value)
Send a boolean message after a delay.
static MmTemporalHandle After (this MmRelayNode relay, float delay, MmMethod method, int value)
Send an integer message after a delay.
static MmTemporalHandle After (this MmRelayNode relay, float delay, MmMethod method, float value)
Send a float message after a delay.
static MmTemporalHandle After (this MmRelayNode relay, float delay, MmMethod method, string value)
Send a string message after a delay.
static MmTemporalHandle After (this MmRelayNode relay, float delay, MmMessage message)
Send a message object after a delay.
static MmTemporalHandle Every (this MmRelayNode relay, float interval, MmMethod method, int repeatCount=0)
Send a message repeatedly at an interval.
static MmTemporalHandle Every (this MmRelayNode relay, float interval, MmMethod method, MmMetadataBlock metadata, int repeatCount=0)
Send a message repeatedly with metadata.
static MmTemporalHandle Every (this MmRelayNode relay, float interval, MmMethod method, bool value, int repeatCount=0)
Send a boolean message repeatedly.
static MmTemporalHandle Every (this MmRelayNode relay, float interval, MmMethod method, int value, int repeatCount=0)
Send an integer message repeatedly.
static MmTemporalHandle Every (this MmRelayNode relay, float interval, MmMessage message, int repeatCount=0)
Send a message repeatedly.
static MmTemporalHandle When (this MmRelayNode relay, Func< bool > condition, MmMethod method, float timeout=0f)
Send a message when a condition becomes true.
static MmTemporalHandle When (this MmRelayNode relay, Func< bool > condition, MmMessage message, float timeout=0f)
Send a message when a condition becomes true.
static MmTemporalHandle When (this MmRelayNode relay, Func< bool > condition, Action action, float timeout=0f)
Execute an action when a condition becomes true.
static async Task< T > RequestAsync< T > (this MmRelayNode relay, MmMethod method, float timeout=5f, CancellationToken cancellationToken=default)
Async request with response.
static async Task< T > RequestAsync< T > (this MmRelayNode relay, MmMethod method, MmMetadataBlock metadata, float timeout=5f, CancellationToken cancellationToken=default)
Async request with custom metadata.
static void RespondAsync< T > (this MmRelayNode relay, int queryId, T response)
Send an async response to a request.
static MmTemporalBuilder Schedule (this MmRelayNode relay, MmMethod method)
Start a temporal message builder for fluent delayed/repeating operations.
static MmTemporalBuilder Schedule (this MmRelayNode relay, MmMethod method, object payload)
Start a temporal message builder with a payload.
Static Private Member Functions
static IEnumerator DelayedInvokeCoroutine (MmRelayNode relay, float delay, Action action, CancellationToken token)
static IEnumerator RepeatingInvokeCoroutine (MmRelayNode relay, float interval, Action action, int repeatCount, CancellationToken token)
static IEnumerator ConditionalInvokeCoroutine (MmRelayNode relay, Func< bool > condition, Action action, float timeout, CancellationToken token)
static int RegisterAsyncQuery< T > (TaskCompletionSource< T > tcs)
static void UnregisterAsyncQuery (int queryId)
static void ResolveAsyncQuery< T > (int queryId, T response)
Static Private Attributes
static readonly Dictionary< int, object > _asyncQueries = new Dictionary<int, object>()
static int _asyncQueryId = 1
static readonly object _queryLock = new object()
Detailed Description
Temporal extension methods for MmRelayNode providing time-based messaging patterns.
Includes delayed execution, repeating messages, and async request/response patterns.
Phase 3 - Task 3.3 (Async/Await Support) and Task 3.4 (Temporal Extensions)
Definition at line 16 of file MmTemporalExtensions.cs.
Member Function Documentation
After() [1/7]
MmTemporalHandle MercuryMessaging.MmTemporalExtensions.After (this MmRelayNode relay, float delay, MmMessage message) static
Send a message object after a delay.
Definition at line 100 of file MmTemporalExtensions.cs.
References DelayedInvokeCoroutine(), MercuryMessaging.MmTemporalRunner.Instance, and MercuryMessaging.MmRelayNode.MmInvoke().
After() [2/7]
MmTemporalHandle MercuryMessaging.MmTemporalExtensions.After (this MmRelayNode relay, float delay, MmMethod method) static
Send a message after a delay.
Returns a handle that can be used to cancel the delayed send.
Parameters
relay The source relay node.
delay Delay in seconds before sending.
method The message method to send.
Returns
A handle to cancel the delayed operation.
var handle = relay.After(2f, MmMethod.Initialize); // Later: handle.Cancel();
Definition at line 32 of file MmTemporalExtensions.cs.
References After(), and MercuryMessaging.MmMetadataBlockHelper.Default.
Referenced by After().
After() [3/7]
MmTemporalHandle MercuryMessaging.MmTemporalExtensions.After (this MmRelayNode relay, float delay, MmMethod method, bool value) static
Send a boolean message after a delay.
Definition at line 52 of file MmTemporalExtensions.cs.
References MercuryMessaging.MmMetadataBlockHelper.Default, DelayedInvokeCoroutine(), MercuryMessaging.MmTemporalRunner.Instance, and MercuryMessaging.MmRelayNode.MmInvoke().
After() [4/7]
MmTemporalHandle MercuryMessaging.MmTemporalExtensions.After (this MmRelayNode relay, float delay, MmMethod method, float value) static
Send a float message after a delay.
Definition at line 76 of file MmTemporalExtensions.cs.
References MercuryMessaging.MmMetadataBlockHelper.Default, DelayedInvokeCoroutine(), MercuryMessaging.MmTemporalRunner.Instance, and MercuryMessaging.MmRelayNode.MmInvoke().
After() [5/7]
MmTemporalHandle MercuryMessaging.MmTemporalExtensions.After (this MmRelayNode relay, float delay, MmMethod method, int value) static
Send an integer message after a delay.
Definition at line 64 of file MmTemporalExtensions.cs.
References MercuryMessaging.MmMetadataBlockHelper.Default, DelayedInvokeCoroutine(), MercuryMessaging.MmTemporalRunner.Instance, and MercuryMessaging.MmRelayNode.MmInvoke().
After() [6/7]
MmTemporalHandle MercuryMessaging.MmTemporalExtensions.After (this MmRelayNode relay, float delay, MmMethod method, MmMetadataBlock metadata) static
Send a message after a delay with metadata.
Definition at line 40 of file MmTemporalExtensions.cs.
References DelayedInvokeCoroutine(), MercuryMessaging.MmTemporalRunner.Instance, and MercuryMessaging.MmRelayNode.MmInvoke().
After() [7/7]
MmTemporalHandle MercuryMessaging.MmTemporalExtensions.After (this MmRelayNode relay, float delay, MmMethod method, string value) static
Send a string message after a delay.
Definition at line 88 of file MmTemporalExtensions.cs.
References MercuryMessaging.MmMetadataBlockHelper.Default, DelayedInvokeCoroutine(), MercuryMessaging.MmTemporalRunner.Instance, and MercuryMessaging.MmRelayNode.MmInvoke().
ConditionalInvokeCoroutine()
IEnumerator MercuryMessaging.MmTemporalExtensions.ConditionalInvokeCoroutine (MmRelayNode relay, Func< bool > condition, Action action, float timeout, CancellationToken token) static private
Definition at line 261 of file MmTemporalExtensions.cs.
Referenced by When(), When(), and When().
DelayedInvokeCoroutine()
IEnumerator MercuryMessaging.MmTemporalExtensions.DelayedInvokeCoroutine (MmRelayNode relay, float delay, Action action, CancellationToken token) static private
Definition at line 109 of file MmTemporalExtensions.cs.
Referenced by After(), After(), After(), After(), After(), and After().
Every() [1/5]
MmTemporalHandle MercuryMessaging.MmTemporalExtensions.Every (this MmRelayNode relay, float interval, MmMessage message, int repeatCount = 0) static
Send a message repeatedly.
Definition at line 180 of file MmTemporalExtensions.cs.
References MercuryMessaging.MmTemporalRunner.Instance, MercuryMessaging.MmRelayNode.MmInvoke(), and RepeatingInvokeCoroutine().
Every() [2/5]
MmTemporalHandle MercuryMessaging.MmTemporalExtensions.Every (this MmRelayNode relay, float interval, MmMethod method, bool value, int repeatCount = 0) static
Send a boolean message repeatedly.
Definition at line 156 of file MmTemporalExtensions.cs.
References MercuryMessaging.MmMetadataBlockHelper.Default, MercuryMessaging.MmTemporalRunner.Instance, MercuryMessaging.MmRelayNode.MmInvoke(), and RepeatingInvokeCoroutine().
Every() [3/5]
MmTemporalHandle MercuryMessaging.MmTemporalExtensions.Every (this MmRelayNode relay, float interval, MmMethod method, int repeatCount = 0) static
Send a message repeatedly at an interval.
Returns a handle to stop the repeating messages.
Parameters
relay The source relay node.
interval Interval in seconds between sends.
method The message method to send.
repeatCount Optional max repeat count (0 = infinite).
Returns
A handle to cancel the repeating operation.
var handle = relay.Every(1f, MmMethod.Refresh); // Later: handle.Cancel();
Definition at line 136 of file MmTemporalExtensions.cs.
References MercuryMessaging.MmMetadataBlockHelper.Default, and Every().
Referenced by Every().
Every() [4/5]
MmTemporalHandle MercuryMessaging.MmTemporalExtensions.Every (this MmRelayNode relay, float interval, MmMethod method, int value, int repeatCount = 0) static
Send an integer message repeatedly.
Definition at line 168 of file MmTemporalExtensions.cs.
References MercuryMessaging.MmMetadataBlockHelper.Default, MercuryMessaging.MmTemporalRunner.Instance, MercuryMessaging.MmRelayNode.MmInvoke(), and RepeatingInvokeCoroutine().
Every() [5/5]
MmTemporalHandle MercuryMessaging.MmTemporalExtensions.Every (this MmRelayNode relay, float interval, MmMethod method, MmMetadataBlock metadata, int repeatCount = 0) static
Send a message repeatedly with metadata.
Definition at line 144 of file MmTemporalExtensions.cs.
References MercuryMessaging.MmTemporalRunner.Instance, MercuryMessaging.MmRelayNode.MmInvoke(), and RepeatingInvokeCoroutine().
RegisterAsyncQuery< T >()
int MercuryMessaging.MmTemporalExtensions.RegisterAsyncQuery< T > (TaskCompletionSource< T > tcs) static private
Type Constraints
T : MmMessage
Definition at line 363 of file MmTemporalExtensions.cs.
References _asyncQueries, _asyncQueryId, and _queryLock.
Referenced by RequestAsync< T >().
RepeatingInvokeCoroutine()
IEnumerator MercuryMessaging.MmTemporalExtensions.RepeatingInvokeCoroutine (MmRelayNode relay, float interval, Action action, int repeatCount, CancellationToken token) static private
Definition at line 189 of file MmTemporalExtensions.cs.
Referenced by Every(), Every(), Every(), and Every().
RequestAsync< T >() [1/2]
async Task< T > MercuryMessaging.MmTemporalExtensions.RequestAsync< T > (this MmRelayNode relay, MmMethod method, float timeout = 5f, CancellationToken cancellationToken = default) static
Async request with response.
Uses Task-based async pattern. Note: Prefer callback-based Query() for Unity performance.
Template Parameters
T Expected response message type.
Parameters
relay The source relay node.
method The query method.
timeout Timeout in seconds.
cancellationToken Optional cancellation token.
Returns
The response message.
var response = await relay.RequestAsync<MmMessageInt>(MmMethod.MessageInt, timeout: 2f); Debug.Log($"Got value: {response.value}");
Type Constraints
T : MmMessage
Definition at line 302 of file MmTemporalExtensions.cs.
References MercuryMessaging.MmMetadataBlockHelper.Default, and RequestAsync< T >().
Referenced by RequestAsync< T >().
RequestAsync< T >() [2/2]
async Task< T > MercuryMessaging.MmTemporalExtensions.RequestAsync< T > (this MmRelayNode relay, MmMethod method, MmMetadataBlock metadata, float timeout = 5f, CancellationToken cancellationToken = default) static
Async request with custom metadata.
Type Constraints
T : MmMessage
Definition at line 314 of file MmTemporalExtensions.cs.
References MercuryMessaging.MmMessagePool.GetInt(), RegisterAsyncQuery< T >(), MercuryMessaging.MmMessagePool.Return(), and UnregisterAsyncQuery().
ResolveAsyncQuery< T >()
void MercuryMessaging.MmTemporalExtensions.ResolveAsyncQuery< T > (int queryId, T response) static private
Type Constraints
T : MmMessage
Definition at line 381 of file MmTemporalExtensions.cs.
References _asyncQueries, and _queryLock.
RespondAsync< T >()
void MercuryMessaging.MmTemporalExtensions.RespondAsync< T > (this MmRelayNode relay, int queryId, T response) static
Send an async response to a request.
Type Constraints
T : MmMessage
Definition at line 353 of file MmTemporalExtensions.cs.
Schedule() [1/2]
MmTemporalBuilder MercuryMessaging.MmTemporalExtensions.Schedule (this MmRelayNode relay, MmMethod method) static
Start a temporal message builder for fluent delayed/repeating operations.
Parameters
relay The source relay node.
method The message method.
Returns
A temporal builder for chaining.
relay.Schedule(MmMethod.Refresh) .ToDescendants() .After(2f) .Execute();
Definition at line 409 of file MmTemporalExtensions.cs.
Schedule() [2/2]
MmTemporalBuilder MercuryMessaging.MmTemporalExtensions.Schedule (this MmRelayNode relay, MmMethod method, object payload) static
Start a temporal message builder with a payload.
Definition at line 417 of file MmTemporalExtensions.cs.
UnregisterAsyncQuery()
void MercuryMessaging.MmTemporalExtensions.UnregisterAsyncQuery (int queryId) static private
Definition at line 373 of file MmTemporalExtensions.cs.
References _asyncQueries, and _queryLock.
Referenced by RequestAsync< T >().
When() [1/3]
MmTemporalHandle MercuryMessaging.MmTemporalExtensions.When (this MmRelayNode relay, Func< bool > condition, Action action, float timeout = 0f) static
Execute an action when a condition becomes true.
Definition at line 252 of file MmTemporalExtensions.cs.
References ConditionalInvokeCoroutine(), and MercuryMessaging.MmTemporalRunner.Instance.
When() [2/3]
MmTemporalHandle MercuryMessaging.MmTemporalExtensions.When (this MmRelayNode relay, Func< bool > condition, MmMessage message, float timeout = 0f) static
Send a message when a condition becomes true.
Definition at line 240 of file MmTemporalExtensions.cs.
References ConditionalInvokeCoroutine(), MercuryMessaging.MmTemporalRunner.Instance, and MercuryMessaging.MmRelayNode.MmInvoke().
When() [3/3]
MmTemporalHandle MercuryMessaging.MmTemporalExtensions.When (this MmRelayNode relay, Func< bool > condition, MmMethod method, float timeout = 0f) static
Send a message when a condition becomes true.
Polls the condition each frame until it returns true.
Parameters
relay The source relay node.
condition The condition to check.
method The message method to send when condition is met.
timeout Optional timeout in seconds (0 = no timeout).
Returns
A handle to cancel the operation.
relay.When(() => player.IsReady, MmMethod.Initialize);
Definition at line 228 of file MmTemporalExtensions.cs.
References ConditionalInvokeCoroutine(), MercuryMessaging.MmMetadataBlockHelper.Default, MercuryMessaging.MmTemporalRunner.Instance, and MercuryMessaging.MmRelayNode.MmInvoke().
Member Data Documentation
_asyncQueries
readonly Dictionary<int, object> MercuryMessaging.MmTemporalExtensions._asyncQueries = new Dictionary<int, object>() static private
Definition at line 359 of file MmTemporalExtensions.cs.
Referenced by RegisterAsyncQuery< T >(), ResolveAsyncQuery< T >(), and UnregisterAsyncQuery().
_asyncQueryId
int MercuryMessaging.MmTemporalExtensions._asyncQueryId = 1 static private
Definition at line 360 of file MmTemporalExtensions.cs.
Referenced by RegisterAsyncQuery< T >().
_queryLock
readonly object MercuryMessaging.MmTemporalExtensions._queryLock = new object() static private
Definition at line 361 of file MmTemporalExtensions.cs.
Referenced by RegisterAsyncQuery< T >(), ResolveAsyncQuery< T >(), and UnregisterAsyncQuery().
The documentation for this class was generated from the following file:
Protocol/DSL/MmTemporalExtensions.cs