MercuryMessaging: MercuryMessaging.MmResponderExtensions Class Reference
MercuryMessaging.MmResponderExtensions Class Reference
Extension methods for MmExtendableResponder to enable fluent handler configuration.
Static Public Member Functions
static ResponderHandlerBuilder ConfigureHandlers (this MmExtendableResponder responder)
Start configuring handlers with a fluent builder.
static void QuickRegister (this MmExtendableResponder responder, int methodId, Action< MmMessage > handler)
Quick register a custom method handler.
static void QuickRegister< T > (this MmExtendableResponder responder, int methodId, Action< T > handler)
Quick register a custom method handler with typed message.
static void QuickUnregister (this MmExtendableResponder responder, int methodId)
Quick unregister a custom method handler.
static void RegisterHandlers (this MmExtendableResponder responder, params(int methodId, Action< MmMessage > handler)[] handlers)
Register multiple handlers at once.
static void UnregisterHandlers (this MmExtendableResponder responder, params int[] methodIds)
Unregister multiple handlers at once.
static bool IsHandlerRegistered (this MmExtendableResponder responder, int methodId)
Check if a handler is registered for a method.
static MmRelayNode GetRelayNode (this MmBaseResponder responder)
Get the relay node associated with this responder (if any).
static MmRoutingBuilder To (this MmBaseResponder responder)
Property-based routing builder for shorter DSL syntax.
static MmDeferredRoutingBuilder Build (this MmBaseResponder responder)
Deferred routing builder for conditional/delayed execution.
static MmRelayNode GetOrCreateRelayNode (this MmBaseResponder responder)
Get the relay node associated with this responder, creating one if needed.
Detailed Description
Extension methods for MmExtendableResponder to enable fluent handler configuration.
Provides convenient methods for setting up message handlers.
Example Usage:
// Fluent configuration
responder.ConfigureHandlers()
    .OnCustomMethod(1000, msg => HandleCustom(msg))
    .OnInitialize(() => Debug.Log("Initialized"))
    .OnSetActive(active => ToggleEffects(active))
    .Build();
// Quick handler registration
responder.QuickRegister(1000, HandleCustomMethod);
responder.QuickRegister(1001, HandleAnotherMethod);
// Batch registration
responder.RegisterHandlers(
    (1000, HandleMethodA),
    (1001, HandleMethodB),
    (1002, HandleMethodC)
);
Definition at line 36 of file MmResponderExtensions.cs.
Member Function Documentation
Build()
MmDeferredRoutingBuilder MercuryMessaging.MmResponderExtensions.Build (this MmBaseResponder responder) static
Deferred routing builder for conditional/delayed execution.
Unlike To() which auto-executes, Build() requires explicit Execute(). Enables: var msg = responder.Build().ToChildren().Send("Hello"); if (ready) msg.Execute(); Null-safe: returns default struct that no-ops if responder has no relay node.
Definition at line 181 of file MmResponderExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
ConfigureHandlers()
ResponderHandlerBuilder MercuryMessaging.MmResponderExtensions.ConfigureHandlers (this MmExtendableResponder responder) static
Start configuring handlers with a fluent builder.
Definition at line 43 of file MmResponderExtensions.cs.
GetOrCreateRelayNode()
MmRelayNode MercuryMessaging.MmResponderExtensions.GetOrCreateRelayNode (this MmBaseResponder responder) static
Get the relay node associated with this responder, creating one if needed.
Definition at line 190 of file MmResponderExtensions.cs.
GetRelayNode()
MmRelayNode MercuryMessaging.MmResponderExtensions.GetRelayNode (this MmBaseResponder responder) static
Get the relay node associated with this responder (if any).
Returns null if no relay node is present on the GameObject.
Definition at line 159 of file MmResponderExtensions.cs.
IsHandlerRegistered()
bool MercuryMessaging.MmResponderExtensions.IsHandlerRegistered (this MmExtendableResponder responder, int methodId) static
Check if a handler is registered for a method.
Definition at line 139 of file MmResponderExtensions.cs.
QuickRegister()
void MercuryMessaging.MmResponderExtensions.QuickRegister (this MmExtendableResponder responder, int methodId, Action< MmMessage > handler) static
Quick register a custom method handler.
Uses reflection to access protected RegisterCustomHandler.
Definition at line 59 of file MmResponderExtensions.cs.
Referenced by QuickRegister< T >().
QuickRegister< T >()
void MercuryMessaging.MmResponderExtensions.QuickRegister< T > (this MmExtendableResponder responder, int methodId, Action< T > handler) static
Quick register a custom method handler with typed message.
Type Constraints
T : MmMessage
Definition at line 78 of file MmResponderExtensions.cs.
References QuickRegister().
QuickUnregister()
void MercuryMessaging.MmResponderExtensions.QuickUnregister (this MmExtendableResponder responder, int methodId) static
Quick unregister a custom method handler.
Definition at line 87 of file MmResponderExtensions.cs.
RegisterHandlers()
void MercuryMessaging.MmResponderExtensions.RegisterHandlers (this MmExtendableResponder responder, params(int methodId, Action< MmMessage > handler)[] handlers) static
Register multiple handlers at once.
Definition at line 106 of file MmResponderExtensions.cs.
To()
MmRoutingBuilder MercuryMessaging.MmResponderExtensions.To (this MmBaseResponder responder) static
Property-based routing builder for shorter DSL syntax.
Enables: responder.To().Children.Send("Hello") Null-safe: returns default struct that no-ops if responder has no relay node.
Definition at line 169 of file MmResponderExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
UnregisterHandlers()
void MercuryMessaging.MmResponderExtensions.UnregisterHandlers (this MmExtendableResponder responder, params int[] methodIds) static
Unregister multiple handlers at once.
Definition at line 121 of file MmResponderExtensions.cs.
The documentation for this class was generated from the following file:
Protocol/DSL/MmResponderExtensions.cs