MercuryMessaging: MercuryMessaging.Task.MmTaskSequenceHandler< T > Class Template Reference
MercuryMessaging.Task.MmTaskSequenceHandler< T > Class Template Reference
Handler for task sequence events.
Public Member Functions
MmTaskSequenceHandler (MmTaskManager< T > taskManager)
void Start ()
Start the task sequence.
void Next ()
Advance to the next task.
void CompleteCurrentTask ()
Complete the current task (optionally auto-advance).
Properties
Action< T > OnTaskStart [get, set]
Action< T > OnTaskComplete [get, set]
Action< T, T > OnTaskChange [get, set]
Action OnSequenceStart [get, set]
Action OnSequenceComplete [get, set]
Func< T, bool > TaskFilter [get, set]
bool AutoAdvance [get, set]
bool HasNextTask [get]
Check if there are more tasks.
T CurrentTask [get]
Get current task info.
Private Member Functions
void NotifyTaskStart ()
void NotifyTaskComplete ()
Private Attributes
readonly MmTaskManager< T > _taskManager
T _previousTask
Detailed Description
Handler for task sequence events.
Created by MmTaskSequenceBuilder.
Type Constraints
T : class
T : IMmTaskInfo
T : new()
Definition at line 159 of file MmTaskSequenceBuilder.cs.
Member Function Documentation
CompleteCurrentTask()
void MercuryMessaging.Task.MmTaskSequenceHandler< T >.CompleteCurrentTask ()
Complete the current task (optionally auto-advance).
Definition at line 211 of file MmTaskSequenceBuilder.cs.
References AutoAdvance, Next(), and NotifyTaskComplete().
MmTaskSequenceHandler()
MercuryMessaging.Task.MmTaskSequenceHandler< T >.MmTaskSequenceHandler (MmTaskManager< T > taskManager)
Definition at line 172 of file MmTaskSequenceBuilder.cs.
References _taskManager.
Next()
void MercuryMessaging.Task.MmTaskSequenceHandler< T >.Next ()
Advance to the next task.
Definition at line 190 of file MmTaskSequenceBuilder.cs.
References _previousTask, _taskManager, NotifyTaskComplete(), NotifyTaskStart(), OnSequenceComplete, and OnTaskChange.
Referenced by CompleteCurrentTask().
NotifyTaskComplete()
void MercuryMessaging.Task.MmTaskSequenceHandler< T >.NotifyTaskComplete () private
Definition at line 230 of file MmTaskSequenceBuilder.cs.
References _taskManager, OnTaskComplete, and TaskFilter.
Referenced by CompleteCurrentTask(), and Next().
NotifyTaskStart()
void MercuryMessaging.Task.MmTaskSequenceHandler< T >.NotifyTaskStart () private
Definition at line 221 of file MmTaskSequenceBuilder.cs.
References _taskManager, OnTaskStart, and TaskFilter.
Referenced by Next(), and Start().
Start()
void MercuryMessaging.Task.MmTaskSequenceHandler< T >.Start ()
Start the task sequence.
Definition at line 180 of file MmTaskSequenceBuilder.cs.
References _taskManager, NotifyTaskStart(), and OnSequenceStart.
Member Data Documentation
_previousTask
T MercuryMessaging.Task.MmTaskSequenceHandler< T >._previousTask private
Definition at line 162 of file MmTaskSequenceBuilder.cs.
Referenced by Next().
_taskManager
readonly MmTaskManager<T> MercuryMessaging.Task.MmTaskSequenceHandler< T >._taskManager private
Definition at line 161 of file MmTaskSequenceBuilder.cs.
Referenced by MmTaskSequenceHandler(), Next(), NotifyTaskComplete(), NotifyTaskStart(), and Start().
Property Documentation
AutoAdvance
bool MercuryMessaging.Task.MmTaskSequenceHandler< T >.AutoAdvance get set
Definition at line 170 of file MmTaskSequenceBuilder.cs.
Referenced by CompleteCurrentTask().
CurrentTask
T MercuryMessaging.Task.MmTaskSequenceHandler< T >.CurrentTask get
Get current task info.
Definition at line 247 of file MmTaskSequenceBuilder.cs.
HasNextTask
bool MercuryMessaging.Task.MmTaskSequenceHandler< T >.HasNextTask get
Check if there are more tasks.
Definition at line 242 of file MmTaskSequenceBuilder.cs.
OnSequenceComplete
Action MercuryMessaging.Task.MmTaskSequenceHandler< T >.OnSequenceComplete get set
Definition at line 168 of file MmTaskSequenceBuilder.cs.
Referenced by Next().
OnSequenceStart
Action MercuryMessaging.Task.MmTaskSequenceHandler< T >.OnSequenceStart get set
Definition at line 167 of file MmTaskSequenceBuilder.cs.
Referenced by Start().
OnTaskChange
Action<T, T> MercuryMessaging.Task.MmTaskSequenceHandler< T >.OnTaskChange get set
Definition at line 166 of file MmTaskSequenceBuilder.cs.
Referenced by Next().
OnTaskComplete
Action<T> MercuryMessaging.Task.MmTaskSequenceHandler< T >.OnTaskComplete get set
Definition at line 165 of file MmTaskSequenceBuilder.cs.
Referenced by NotifyTaskComplete().
OnTaskStart
Action<T> MercuryMessaging.Task.MmTaskSequenceHandler< T >.OnTaskStart get set
Definition at line 164 of file MmTaskSequenceBuilder.cs.
Referenced by NotifyTaskStart().
TaskFilter
Func<T, bool> MercuryMessaging.Task.MmTaskSequenceHandler< T >.TaskFilter get set
Definition at line 169 of file MmTaskSequenceBuilder.cs.
Referenced by NotifyTaskComplete(), and NotifyTaskStart().
The documentation for this class was generated from the following file:
Task/MmTaskSequenceBuilder.cs