MercuryMessaging: MercuryMessaging.Network.MmMessagePriorityQueue Class Reference
MercuryMessaging.Network.MmMessagePriorityQueue Class Reference
Priority queue for outgoing messages.
Public Member Functions
void Enqueue (byte[] data, MmMessagePriority priority, int targetClient, MmReliability reliability, double currentTime)
Enqueue a message with priority.
bool TryDequeue (out MmQueuedMessage message)
Dequeue the highest priority message.
bool TryPeek (out MmQueuedMessage message)
Peek at the highest priority message without removing.
List< MmQueuedMessage > DequeueBatch (int maxBytes)
Dequeue multiple messages up to a byte limit.
int DropLowPriority (int maxToKeep)
Drop low priority messages to free up queue space.
void Clear ()
Clear all messages from the queue.
Properties
int Count [get]
Number of messages in the queue.
int TotalBytes [get]
Total bytes of all queued messages.
Private Member Functions
void HeapifyUp (int index)
void HeapifyDown (int index)
Private Attributes
readonly List< MmQueuedMessage > _heap = new List<MmQueuedMessage>()
readonly object _lock = new object()
Detailed Description
Priority queue for outgoing messages.
Ensures high-priority messages are sent first under bandwidth constraints.
Definition at line 253 of file MmDeltaSerializer.cs.
Member Function Documentation
Clear()
void MercuryMessaging.Network.MmMessagePriorityQueue.Clear ()
Clear all messages from the queue.
Definition at line 428 of file MmDeltaSerializer.cs.
References _heap, and _lock.
DequeueBatch()
List< MmQueuedMessage > MercuryMessaging.Network.MmMessagePriorityQueue.DequeueBatch (int maxBytes)
Dequeue multiple messages up to a byte limit.
Definition at line 362 of file MmDeltaSerializer.cs.
References _heap, _lock, and TryDequeue().
DropLowPriority()
int MercuryMessaging.Network.MmMessagePriorityQueue.DropLowPriority (int maxToKeep)
Drop low priority messages to free up queue space.
Definition at line 391 of file MmDeltaSerializer.cs.
References _heap, _lock, and HeapifyUp().
Enqueue()
void MercuryMessaging.Network.MmMessagePriorityQueue.Enqueue (byte[] data, MmMessagePriority priority, int targetClient, MmReliability reliability, double currentTime)
Enqueue a message with priority.
Definition at line 294 of file MmDeltaSerializer.cs.
References _heap, _lock, and HeapifyUp().
HeapifyDown()
void MercuryMessaging.Network.MmMessagePriorityQueue.HeapifyDown (int index) private
Definition at line 455 of file MmDeltaSerializer.cs.
References _heap.
Referenced by TryDequeue().
HeapifyUp()
void MercuryMessaging.Network.MmMessagePriorityQueue.HeapifyUp (int index) private
Definition at line 436 of file MmDeltaSerializer.cs.
References _heap.
Referenced by DropLowPriority(), and Enqueue().
TryDequeue()
bool MercuryMessaging.Network.MmMessagePriorityQueue.TryDequeue (out MmQueuedMessage message)
Dequeue the highest priority message.
Definition at line 315 of file MmDeltaSerializer.cs.
References _heap, _lock, and HeapifyDown().
Referenced by DequeueBatch().
TryPeek()
bool MercuryMessaging.Network.MmMessagePriorityQueue.TryPeek (out MmQueuedMessage message)
Peek at the highest priority message without removing.
Definition at line 344 of file MmDeltaSerializer.cs.
References _heap, and _lock.
Member Data Documentation
_heap
readonly List<MmQueuedMessage> MercuryMessaging.Network.MmMessagePriorityQueue._heap = new List<MmQueuedMessage>() private
Definition at line 255 of file MmDeltaSerializer.cs.
Referenced by Clear(), DequeueBatch(), DropLowPriority(), Enqueue(), HeapifyDown(), HeapifyUp(), TryDequeue(), and TryPeek().
_lock
readonly object MercuryMessaging.Network.MmMessagePriorityQueue._lock = new object() private
Definition at line 256 of file MmDeltaSerializer.cs.
Referenced by Clear(), DequeueBatch(), DropLowPriority(), Enqueue(), TryDequeue(), and TryPeek().
Property Documentation
Count
int MercuryMessaging.Network.MmMessagePriorityQueue.Count get
Number of messages in the queue.
Definition at line 261 of file MmDeltaSerializer.cs.
TotalBytes
int MercuryMessaging.Network.MmMessagePriorityQueue.TotalBytes get
Total bytes of all queued messages.
Definition at line 275 of file MmDeltaSerializer.cs.
The documentation for this class was generated from the following file:
Protocol/Network/MmDeltaSerializer.cs