MercuryMessaging: MercuryMessaging.FiniteStateMachine< T > Class Template Reference
MercuryMessaging.FiniteStateMachine< T > Class Template Reference
Finite State Machine, supporting generic types states.
Public Member Functions
delegate void Transition ()
FiniteStateMachine (string name)
This constructor assumes your FiniteStateMachine has been created with Enums.
FiniteStateMachine (string name, List< T > collection)
This constructor allows you to pass in a list of the values you would like to initialize.
void JumpTo (T newState)
Go to state "newState".
void StartTransitionTo (T newState)
Called when entering new state.
bool CancelStateChange ()
Stop state transition.
void EnterNext ()
Enter the next state, stored in "Next" member.
void Reset ()
void ResetTo (T current)
K GetKey (int idx)
Returns the key at the specified index.
V GetValue (int idx)
Returns the value at the specified index.
int IndexOf (K key)
Get the index of a particular key.
int IndexOf (KeyValuePair< K, V > kvp)
Given the key-value pair, find the index.
void Clear ()
Clears all entries in the KeyedList.
bool ContainsKey (K key)
Test if the KeyedList contains the key.
bool Contains (KeyValuePair< K, V > kvp)
Test if the KeyedList contains the key in the key-value pair.
void Add (K key, V value)
Adds a key-value pair to the KeyedList.
void Add (KeyValuePair< K, V > kvp)
Adds a key-value pair to the KeyedList.
void CopyTo (KeyValuePair< K, V >[] kvpa, int idx)
Copy the entire key-value pairs to the KeyValuePair array, starting at the specified index of the target array.
void Insert (int idx, K key, V value)
Insert the key-value at the specified index.
void Insert (int idx, KeyValuePair< K, V > kvp)
Insert the key-value pair at the specified index location.
bool Remove (K key)
Remove the entry.
bool Remove (KeyValuePair< K, V > kvp)
Remove the key in the specified KeyValuePair instance.
void RemoveAt (int idx)
Remove the entry at the specified index.
bool TryGetValue (K key, out V val)
Attempt to get the value, given the key, without throwing an exception if not found.
Public Attributes
readonly string Name
Transition GlobalEnter
Transition GlobalExit
Properties
T Current [get, private set]
Current state.
T Previous [get, private set]
Previous state.
T Next [get, private set]
Next state.
MmLogger.LogFunc LogMessage [get, set]
bool IsReadOnly [get]
Returns false.
int Count [get]
Returns the number of entries in the KeyedList.
KeyValuePair< K, V > this[int idx] [get, set]
Get/Set the value at the specified index.
virtual V this[K key] [get, set]
Get/Set the value associated with the specified key.
ICollection< K > Keys [get]
Get an unordered list of keys.
ICollection< V > Values [get]
Get an unordered list of values.
List< K > OrderedKeys [get]
Get the ordered list of keys.
List< V > OrderedValues [get]
Get the ordered list of values.
Dictionary< K, V > ObjectTable [get]
Gets the Dictionary class backing the KeyedList.
StateEvents this[T key] [get, set]
int Count [get]
Private Member Functions
void StartLeaving ()
IEnumerator IEnumerable. GetEnumerator ()
Returns an ordered System.Collections KeyValuePair objects.
IEnumerator< KeyValuePair< K, V > > IEnumerable< KeyValuePair< K, V > >. GetEnumerator ()
Returns an ordered KeyValuePair enumerator.
Private Attributes
bool isTransitioning
readonly Dictionary< K, V > objectTable = new Dictionary<K, V>()
readonly List< KeyValuePair< K, V > > objectList = new List<KeyValuePair<K, V>>()
Detailed Description
Finite State Machine, supporting generic types states.
Useful for creating applications with MercuryMessaging.
Template Parameters
T State Type
Definition at line 44 of file FiniteStateMachine.cs.
Member Function Documentation
Add() [1/2]
void MercuryMessaging.KeyedList< K, V >.Add (K key, V value) inherited
Adds a key-value pair to the KeyedList.
Parameters
key The key.
value The associated value.
Definition at line 259 of file KeyedList.cs.
References objectList, and objectTable.
Referenced by Add(), MercuryMessaging.FiniteStateMachine< T >.FiniteStateMachine(), and MercuryMessaging.FiniteStateMachine< T >.FiniteStateMachine().
Add() [2/2]
void MercuryMessaging.KeyedList< K, V >.Add (KeyValuePair< K, V > kvp) inherited
Adds a key-value pair to the KeyedList.
Parameters
kvp The KeyValuePair instance.
Definition at line 269 of file KeyedList.cs.
References Add().
CancelStateChange()
bool MercuryMessaging.FiniteStateMachine< T >.CancelStateChange ()
Stop state transition.
Returns
Whether cancellation succeeded.
Implements MercuryMessaging.IFiniteStateMachine< T >.
Definition at line 127 of file FiniteStateMachine.cs.
References isTransitioning, and Next.
Clear()
void MercuryMessaging.KeyedList< K, V >.Clear () inherited
Clears all entries in the KeyedList.
Definition at line 228 of file KeyedList.cs.
References objectList, and objectTable.
Contains()
bool MercuryMessaging.KeyedList< K, V >.Contains (KeyValuePair< K, V > kvp) inherited
Test if the KeyedList contains the key in the key-value pair.
Parameters
kvp The key-value pair.
Returns
True if the key is found.
Definition at line 249 of file KeyedList.cs.
References objectTable.
ContainsKey()
bool MercuryMessaging.KeyedList< K, V >.ContainsKey (K key) inherited
Test if the KeyedList contains the key.
Parameters
key The key.
Returns
True if the key is found.
Definition at line 239 of file KeyedList.cs.
References objectTable.
CopyTo()
void MercuryMessaging.KeyedList< K, V >.CopyTo (KeyValuePair< K, V >[] kvpa, int idx) inherited
Copy the entire key-value pairs to the KeyValuePair array, starting at the specified index of the target array.
The array is populated as an ordered list.
Parameters
kvpa The KeyValuePair array.
idx The position to start the copy.
Definition at line 281 of file KeyedList.cs.
References objectList.
EnterNext()
void MercuryMessaging.FiniteStateMachine< T >.EnterNext ()
Enter the next state, stored in "Next" member.
Implements MercuryMessaging.IFiniteStateMachine< T >.
Definition at line 137 of file FiniteStateMachine.cs.
References Current, GlobalEnter, isTransitioning, LogMessage, Name, Next, and Previous.
Referenced by JumpTo().
FiniteStateMachine() [1/2]
MercuryMessaging.FiniteStateMachine< T >.FiniteStateMachine (string name)
This constructor assumes your FiniteStateMachine has been created with Enums.
Parameters
name
Definition at line 70 of file FiniteStateMachine.cs.
References MercuryMessaging.KeyedList< K, V >.Add(), and Name.
FiniteStateMachine() [2/2]
MercuryMessaging.FiniteStateMachine< T >.FiniteStateMachine (string name, List< T > collection)
This constructor allows you to pass in a list of the values you would like to initialize.
Parameters
name
collection
Definition at line 95 of file FiniteStateMachine.cs.
References MercuryMessaging.KeyedList< K, V >.Add(), and Name.
GetEnumerator() [1/2]
IEnumerator< KeyValuePair< K, V > > IEnumerable< KeyValuePair< K, V > >. MercuryMessaging.KeyedList< K, V >.GetEnumerator () private inherited
Returns an ordered KeyValuePair enumerator.
Definition at line 384 of file KeyedList.cs.
References objectList.
GetEnumerator() [2/2]
IEnumerator IEnumerable. MercuryMessaging.KeyedList< K, V >.GetEnumerator () private inherited
Returns an ordered System.Collections KeyValuePair objects.
Definition at line 376 of file KeyedList.cs.
References objectList.
GetKey()
K MercuryMessaging.KeyedList< K, V >.GetKey (int idx) inherited
Returns the key at the specified index.
Parameters
idx The index.
Returns
The key at the index.
Definition at line 161 of file KeyedList.cs.
References Count, and objectList.
GetValue()
V MercuryMessaging.KeyedList< K, V >.GetValue (int idx) inherited
Returns the value at the specified index.
Parameters
idx The index.
Returns
The value at the index.
Definition at line 176 of file KeyedList.cs.
References Count, and objectList.
IndexOf() [1/2]
int MercuryMessaging.KeyedList< K, V >.IndexOf (K key) inherited
Get the index of a particular key.
Parameters
key The key to find the index of.
Returns
The index of the key, or -1 if not found.
Definition at line 191 of file KeyedList.cs.
References objectList.
Referenced by IndexOf(), and Remove().
IndexOf() [2/2]
int MercuryMessaging.KeyedList< K, V >.IndexOf (KeyValuePair< K, V > kvp) inherited
Given the key-value pair, find the index.
Parameters
kvp The key-value pair.
Returns
The index, or -1 if not found.
Definition at line 212 of file KeyedList.cs.
References IndexOf().
Insert() [1/2]
void MercuryMessaging.KeyedList< K, V >.Insert (int idx, K key, V value) inherited
Insert the key-value at the specified index.
Parameters
idx The zero-based insert point.
key The key.
value The value.
Definition at line 292 of file KeyedList.cs.
References Count, objectList, and objectTable.
Insert() [2/2]
void MercuryMessaging.KeyedList< K, V >.Insert (int idx, KeyValuePair< K, V > kvp) inherited
Insert the key-value pair at the specified index location.
Parameters
idx The key.
kvp The value.
Definition at line 308 of file KeyedList.cs.
References Count, objectList, and objectTable.
JumpTo()
void MercuryMessaging.FiniteStateMachine< T >.JumpTo (T newState)
Go to state "newState".
Parameters
newState Target state.
Implements MercuryMessaging.IFiniteStateMachine< T >.
Definition at line 109 of file FiniteStateMachine.cs.
References Current, EnterNext(), Next, and StartLeaving().
Referenced by MercuryMessaging.MmRelaySwitchNodeExtensions.GoToPrevious().
Remove() [1/2]
bool MercuryMessaging.KeyedList< K, V >.Remove (K key) inherited
Remove the entry.
Parameters
key The key identifying the key-value pair.
Returns
True if removed.
Definition at line 324 of file KeyedList.cs.
References IndexOf(), objectList, and objectTable.
Referenced by Remove().
Remove() [2/2]
bool MercuryMessaging.KeyedList< K, V >.Remove (KeyValuePair< K, V > kvp) inherited
Remove the key in the specified KeyValuePair instance.
The Value property is ignored.
Parameters
kvp The key-value identifying the entry.
Returns
True if removed.
Definition at line 342 of file KeyedList.cs.
References Remove().
RemoveAt()
void MercuryMessaging.KeyedList< K, V >.RemoveAt (int idx) inherited
Remove the entry at the specified index.
Parameters
idx The index to the entry to be removed.
Definition at line 351 of file KeyedList.cs.
References Count, objectList, and objectTable.
Reset()
void MercuryMessaging.FiniteStateMachine< T >.Reset ()
Definition at line 154 of file FiniteStateMachine.cs.
References Previous.
ResetTo()
void MercuryMessaging.FiniteStateMachine< T >.ResetTo (T current)
Definition at line 159 of file FiniteStateMachine.cs.
References Current, and Previous.
StartLeaving()
void MercuryMessaging.FiniteStateMachine< T >.StartLeaving () private
Definition at line 169 of file FiniteStateMachine.cs.
References Current, GlobalExit, and isTransitioning.
Referenced by JumpTo(), and StartTransitionTo().
StartTransitionTo()
void MercuryMessaging.FiniteStateMachine< T >.StartTransitionTo (T newState)
Called when entering new state.
Parameters
newState Target State.
Implements MercuryMessaging.IFiniteStateMachine< T >.
Definition at line 120 of file FiniteStateMachine.cs.
References Next, and StartLeaving().
Transition()
delegate void MercuryMessaging.FiniteStateMachine< T >.Transition ()
TryGetValue()
bool MercuryMessaging.KeyedList< K, V >.TryGetValue (K key, out V val) inherited
Attempt to get the value, given the key, without throwing an exception if not found.
Parameters
key The key indentifying the entry.
val The value, if found.
Returns
True if found.
Definition at line 368 of file KeyedList.cs.
References objectTable.
Member Data Documentation
GlobalEnter
Transition MercuryMessaging.FiniteStateMachine< T >.GlobalEnter
Definition at line 56 of file FiniteStateMachine.cs.
Referenced by EnterNext().
GlobalExit
Transition MercuryMessaging.FiniteStateMachine< T >.GlobalExit
Definition at line 57 of file FiniteStateMachine.cs.
Referenced by StartLeaving().
isTransitioning
bool MercuryMessaging.FiniteStateMachine< T >.isTransitioning private
Definition at line 59 of file FiniteStateMachine.cs.
Referenced by CancelStateChange(), EnterNext(), and StartLeaving().
Name
readonly string MercuryMessaging.FiniteStateMachine< T >.Name
Definition at line 50 of file FiniteStateMachine.cs.
Referenced by EnterNext(), FiniteStateMachine(), and FiniteStateMachine().
objectList
readonly List<KeyValuePair<K, V> > MercuryMessaging.KeyedList< K, V >.objectList = new List<KeyValuePair<K, V>>() private inherited
Definition at line 46 of file KeyedList.cs.
Referenced by Add(), Clear(), CopyTo(), GetEnumerator(), GetKey(), GetValue(), IndexOf(), Insert(), Insert(), Remove(), and RemoveAt().
objectTable
readonly Dictionary<K, V> MercuryMessaging.KeyedList< K, V >.objectTable = new Dictionary<K, V>() private inherited
Definition at line 45 of file KeyedList.cs.
Referenced by Add(), Clear(), Contains(), ContainsKey(), Insert(), Insert(), Remove(), RemoveAt(), and TryGetValue().
Property Documentation
Count [1/2]
int MercuryMessaging.IFiniteStateMachine< T >.Count get inherited
Definition at line 83 of file IFiniteStateMachine.cs.
Count [2/2]
int MercuryMessaging.KeyedList< K, V >.Count get inherited
Returns the number of entries in the KeyedList.
Definition at line 59 of file KeyedList.cs.
Referenced by GetKey(), GetValue(), Insert(), Insert(), and RemoveAt().
Current
T MercuryMessaging.FiniteStateMachine< T >.Current get private set
Current state.
Implements MercuryMessaging.IFiniteStateMachine< T >.
Definition at line 51 of file FiniteStateMachine.cs.
Referenced by EnterNext(), JumpTo(), ResetTo(), and StartLeaving().
IsReadOnly
bool MercuryMessaging.KeyedList< K, V >.IsReadOnly get inherited
Returns false.
Definition at line 51 of file KeyedList.cs.
Keys
ICollection<K> MercuryMessaging.KeyedList< K, V >.Keys get inherited
Get an unordered list of keys.
This collection refers back to the keys in the original Dictionary.
Definition at line 118 of file KeyedList.cs.
LogMessage
MmLogger.LogFunc MercuryMessaging.FiniteStateMachine< T >.LogMessage get set
Definition at line 54 of file FiniteStateMachine.cs.
Referenced by EnterNext().
Next
T MercuryMessaging.FiniteStateMachine< T >.Next get private set
Next state.
Implements MercuryMessaging.IFiniteStateMachine< T >.
Definition at line 53 of file FiniteStateMachine.cs.
Referenced by CancelStateChange(), EnterNext(), JumpTo(), and StartTransitionTo().
ObjectTable
Dictionary<K, V> MercuryMessaging.KeyedList< K, V >.ObjectTable get inherited
Gets the Dictionary class backing the KeyedList.
Definition at line 220 of file KeyedList.cs.
OrderedKeys
List<K> MercuryMessaging.KeyedList< K, V >.OrderedKeys get inherited
Get the ordered list of keys.
This is a copy of the keys in the original Dictionary.
Definition at line 136 of file KeyedList.cs.
OrderedValues
List<V> MercuryMessaging.KeyedList< K, V >.OrderedValues get inherited
Get the ordered list of values.
This is a copy of the values in the original Dictionary.
Definition at line 148 of file KeyedList.cs.
Previous
T MercuryMessaging.FiniteStateMachine< T >.Previous get private set
Previous state.
Implements MercuryMessaging.IFiniteStateMachine< T >.
Definition at line 52 of file FiniteStateMachine.cs.
Referenced by EnterNext(), MercuryMessaging.MmRelaySwitchNodeExtensions.GetPreviousStateName(), MercuryMessaging.MmRelaySwitchNodeExtensions.GoToPrevious(), Reset(), and ResetTo().
this[int idx]
KeyValuePair<K, V> MercuryMessaging.KeyedList< K, V >.this[int idx] get set inherited
Get/Set the value at the specified index.
Parameters
idx The index.
Returns
The value.
Definition at line 69 of file KeyedList.cs.
this[K key]
virtual V MercuryMessaging.KeyedList< K, V >.this[K key] get set inherited
Get/Set the value associated with the specified key.
Parameters
key The key.
Returns
The associated value.
Definition at line 97 of file KeyedList.cs.
this[T key]
StateEvents MercuryMessaging.IFiniteStateMachine< T >.this[T key] get set inherited
Definition at line 81 of file IFiniteStateMachine.cs.
Values
ICollection<V> MercuryMessaging.KeyedList< K, V >.Values get inherited
Get an unordered list of values.
This collection refers back to the values in the original Dictionary.
Definition at line 127 of file KeyedList.cs.
The documentation for this class was generated from the following file:
Protocol/FSM/FiniteStateMachine.cs