MercuryMessaging: MercuryMessaging.MmRoutingOptions Class Reference
MercuryMessaging.MmRoutingOptions Class Reference
Configuration options for advanced message routing behavior.
Public Member Functions
MmRoutingOptions ()
Creates routing options with default settings (backward-compatible).
MmRoutingOptions (bool enableHistoryTracking=false, int historyCacheSizeMs=100, int maxRoutingHops=50, bool allowLateralRouting=false, Func< MmRelayNode, bool > customFilter=null, bool enableProfiling=false, float profilingThresholdMs=1.0f)
Creates routing options with specified settings.
MmRoutingOptions Clone ()
Creates a copy of the routing options.
string Validate ()
Validates routing options and returns error message if invalid.
override string ToString ()
Static Public Member Functions
static MmRoutingOptions WithHistoryTracking (int cacheSizeMs=100)
Creates routing options with history tracking enabled (for cycle detection).
static MmRoutingOptions WithLateralRouting ()
Creates routing options with lateral routing enabled (siblings/cousins).
static MmRoutingOptions WithCustomFilter (Func< MmRelayNode, bool > filter)
Creates routing options with custom filter predicate.
static MmRoutingOptions WithProfiling (float thresholdMs=1.0f)
Creates routing options with performance profiling enabled.
static MmRoutingOptions AllFeaturesEnabled ()
Creates routing options with all advanced features enabled (for testing/debugging).
Public Attributes
bool EnableHistoryTracking = false
Enable message history tracking for improved cycle detection.
int HistoryCacheSizeMs = 100
Time window in milliseconds for message history cache.
int MaxRoutingHops = 50
Maximum number of hops a message can traverse before being dropped.
bool AllowLateralRouting = false
Enable routing to sibling and cousin nodes.
Func< MmRelayNode, bool > CustomFilter = null
Custom predicate function for filtering relay nodes during routing.
bool EnableProfiling = false
Enable performance profiling hooks for this routing operation.
float ProfilingThresholdMs = 1.0f
Log profiling data only if routing time exceeds this threshold (milliseconds).
Detailed Description
Configuration options for advanced message routing behavior.
Provides fine-grained control over routing algorithms, history tracking, and custom filtering logic.
Usage:
Attach to MmMetadataBlock for per-message configuration
Set on MmRelayNode for per-node defaults
All options default to backward-compatible behavior
Definition at line 22 of file MmRoutingOptions.cs.
Constructor & Destructor Documentation
MmRoutingOptions() [1/2]
MercuryMessaging.MmRoutingOptions.MmRoutingOptions ()
Creates routing options with default settings (backward-compatible).
Definition at line 108 of file MmRoutingOptions.cs.
Referenced by AllFeaturesEnabled(), Clone(), WithCustomFilter(), WithHistoryTracking(), WithLateralRouting(), and WithProfiling().
MmRoutingOptions() [2/2]
MercuryMessaging.MmRoutingOptions.MmRoutingOptions (bool enableHistoryTracking = false, int historyCacheSizeMs = 100, int maxRoutingHops = 50, bool allowLateralRouting = false, Func< MmRelayNode, bool > customFilter = null, bool enableProfiling = false, float profilingThresholdMs = 1::0f)
Creates routing options with specified settings.
Definition at line 116 of file MmRoutingOptions.cs.
References AllowLateralRouting, CustomFilter, EnableHistoryTracking, EnableProfiling, HistoryCacheSizeMs, MaxRoutingHops, and ProfilingThresholdMs.
Member Function Documentation
AllFeaturesEnabled()
MmRoutingOptions MercuryMessaging.MmRoutingOptions.AllFeaturesEnabled () static
Creates routing options with all advanced features enabled (for testing/debugging).
Warning: Higher overhead - use only during development.
Definition at line 201 of file MmRoutingOptions.cs.
References MmRoutingOptions().
Clone()
MmRoutingOptions MercuryMessaging.MmRoutingOptions.Clone ()
Creates a copy of the routing options.
Note: CustomFilter is shallow-copied (same delegate reference).
Definition at line 138 of file MmRoutingOptions.cs.
References MmRoutingOptions(), AllowLateralRouting, CustomFilter, EnableHistoryTracking, EnableProfiling, HistoryCacheSizeMs, MaxRoutingHops, and ProfilingThresholdMs.
Referenced by MercuryMessaging.MmMetadataBlock.MmMetadataBlock().
ToString()
override string MercuryMessaging.MmRoutingOptions.ToString ()
Definition at line 249 of file MmRoutingOptions.cs.
Validate()
string MercuryMessaging.MmRoutingOptions.Validate ()
Validates routing options and returns error message if invalid.
Returns null if options are valid.
Definition at line 222 of file MmRoutingOptions.cs.
References AllowLateralRouting, EnableHistoryTracking, HistoryCacheSizeMs, MaxRoutingHops, and ProfilingThresholdMs.
WithCustomFilter()
MmRoutingOptions MercuryMessaging.MmRoutingOptions.WithCustomFilter (Func< MmRelayNode, bool > filter) static
Creates routing options with custom filter predicate.
Definition at line 179 of file MmRoutingOptions.cs.
References MmRoutingOptions().
WithHistoryTracking()
MmRoutingOptions MercuryMessaging.MmRoutingOptions.WithHistoryTracking (int cacheSizeMs = 100) static
Creates routing options with history tracking enabled (for cycle detection).
Definition at line 158 of file MmRoutingOptions.cs.
References MmRoutingOptions().
WithLateralRouting()
MmRoutingOptions MercuryMessaging.MmRoutingOptions.WithLateralRouting () static
Creates routing options with lateral routing enabled (siblings/cousins).
Definition at line 169 of file MmRoutingOptions.cs.
References MmRoutingOptions().
WithProfiling()
MmRoutingOptions MercuryMessaging.MmRoutingOptions.WithProfiling (float thresholdMs = 1::0f) static
Creates routing options with performance profiling enabled.
Definition at line 189 of file MmRoutingOptions.cs.
References MmRoutingOptions().
Member Data Documentation
AllowLateralRouting
bool MercuryMessaging.MmRoutingOptions.AllowLateralRouting = false
Enable routing to sibling and cousin nodes.
When disabled, only hierarchical (parent/child) routing is allowed. When enabled, LevelFilter.Siblings and LevelFilter.Cousins become available. Default: false (for backward compatibility)
Definition at line 64 of file MmRoutingOptions.cs.
Referenced by MmRoutingOptions(), Clone(), MercuryMessaging.MmRelayNode.HandleAdvancedRouting(), and Validate().
CustomFilter
Func<MmRelayNode, bool> MercuryMessaging.MmRoutingOptions.CustomFilter = null
Custom predicate function for filtering relay nodes during routing.
Called for each candidate relay node before message delivery. Return true to include node, false to skip.
Example: Options.CustomFilter = (node) => node.tag == "Player" && node.activeInHierarchy;
Note: Called frequently during routing - keep logic fast (< 10 microseconds). Default: null (no custom filtering)
Definition at line 80 of file MmRoutingOptions.cs.
Referenced by MmRoutingOptions(), Clone(), and MercuryMessaging.MmRelayNode.HandleAdvancedRouting().
EnableHistoryTracking
bool MercuryMessaging.MmRoutingOptions.EnableHistoryTracking = false
Enable message history tracking for improved cycle detection.
When enabled, messages track which nodes they've visited using a time-windowed cache. This provides better circular routing prevention than hop counting alone. Default: false (for backward compatibility)
Definition at line 32 of file MmRoutingOptions.cs.
Referenced by MmRoutingOptions(), Clone(), and Validate().
EnableProfiling
bool MercuryMessaging.MmRoutingOptions.EnableProfiling = false
Enable performance profiling hooks for this routing operation.
When enabled, timing data is collected and logged via MmLogger. Useful for identifying routing bottlenecks. Default: false (zero overhead when disabled)
Definition at line 92 of file MmRoutingOptions.cs.
Referenced by MmRoutingOptions(), and Clone().
HistoryCacheSizeMs
int MercuryMessaging.MmRoutingOptions.HistoryCacheSizeMs = 100
Time window in milliseconds for message history cache.
Messages older than this are evicted from the history cache. Larger values = better cycle detection, higher memory usage. Default: 100ms (supports ~1000 messages at typical throughput)
Definition at line 40 of file MmRoutingOptions.cs.
Referenced by MmRoutingOptions(), Clone(), and Validate().
MaxRoutingHops
int MercuryMessaging.MmRoutingOptions.MaxRoutingHops = 50
Maximum number of hops a message can traverse before being dropped.
Prevents infinite loops in circular hierarchies. Set to -1 for unlimited hops (use with caution). Default: 50 (MmMessage.MAX_HOPS_DEFAULT)
Definition at line 52 of file MmRoutingOptions.cs.
Referenced by MmRoutingOptions(), Clone(), and Validate().
ProfilingThresholdMs
float MercuryMessaging.MmRoutingOptions.ProfilingThresholdMs = 1.0f
Log profiling data only if routing time exceeds this threshold (milliseconds).
Helps filter out fast routes and focus on slow ones. Default: 1.0ms (logs routes taking > 1ms)
Definition at line 99 of file MmRoutingOptions.cs.
Referenced by MmRoutingOptions(), Clone(), and Validate().
The documentation for this class was generated from the following file:
Protocol/Routing/MmRoutingOptions.cs