MercuryMessaging: MercuryMessaging.Network.MmServerReconciliation Class Reference
MercuryMessaging.Network.MmServerReconciliation Class Reference
Server-side input processing and state broadcast.
Public Member Functions
void Initialize (Func< MmStateSnapshot, MmInputSnapshot, MmStateSnapshot > simulationStep)
Initialize with simulation step function.
void SetInitialState (MmStateSnapshot state)
Set initial state.
void OnClientInput (int clientId, MmInputSnapshot input)
Receive input from a client.
MmStateSnapshot ProcessTick ()
Process one server tick.
bool TryGetHistoricalState (uint tick, out MmStateSnapshot state)
Get historical state for lag compensation.
void RemoveClient (int clientId)
Remove a client.
void Reset ()
Reset all state.
Public Attributes
int TickRate = 60
Tick rate for server updates (Hz).
int StateHistorySize = 60
How many past states to keep for rewinding.
Properties
MmStateSnapshot AuthoritativeState [get]
Current authoritative state.
uint CurrentTick [get]
Current server tick.
Private Attributes
readonly Dictionary< int, Queue< MmInputSnapshot > > _clientInputs = new Dictionary<int, Queue<MmInputSnapshot>>()
readonly Queue< MmStateSnapshot > _stateHistory = new Queue<MmStateSnapshot>()
MmStateSnapshot _authoritativeState
uint _currentTick = 0
Func< MmStateSnapshot, MmInputSnapshot, MmStateSnapshot > _simulationStep
Detailed Description
Server-side input processing and state broadcast.
Definition at line 284 of file MmNetworkPrediction.cs.
Member Function Documentation
Initialize()
void MercuryMessaging.Network.MmServerReconciliation.Initialize (Func< MmStateSnapshot, MmInputSnapshot, MmStateSnapshot > simulationStep)
Initialize with simulation step function.
Definition at line 322 of file MmNetworkPrediction.cs.
References _simulationStep.
OnClientInput()
void MercuryMessaging.Network.MmServerReconciliation.OnClientInput (int clientId, MmInputSnapshot input)
Receive input from a client.
Definition at line 339 of file MmNetworkPrediction.cs.
References _clientInputs.
ProcessTick()
MmStateSnapshot MercuryMessaging.Network.MmServerReconciliation.ProcessTick ()
Process one server tick.
Returns the new authoritative state.
Definition at line 360 of file MmNetworkPrediction.cs.
References _authoritativeState, _clientInputs, _currentTick, _simulationStep, _stateHistory, and StateHistorySize.
RemoveClient()
void MercuryMessaging.Network.MmServerReconciliation.RemoveClient (int clientId)
Remove a client.
Definition at line 411 of file MmNetworkPrediction.cs.
References _clientInputs.
Reset()
void MercuryMessaging.Network.MmServerReconciliation.Reset ()
Reset all state.
Definition at line 419 of file MmNetworkPrediction.cs.
References _clientInputs, _currentTick, and _stateHistory.
SetInitialState()
void MercuryMessaging.Network.MmServerReconciliation.SetInitialState (MmStateSnapshot state)
Set initial state.
Definition at line 330 of file MmNetworkPrediction.cs.
References _authoritativeState, _currentTick, and MercuryMessaging.Network.MmStateSnapshot.SequenceNumber.
TryGetHistoricalState()
bool MercuryMessaging.Network.MmServerReconciliation.TryGetHistoricalState (uint tick, out MmStateSnapshot state)
Get historical state for lag compensation.
Definition at line 394 of file MmNetworkPrediction.cs.
References _stateHistory.
Member Data Documentation
_authoritativeState
MmStateSnapshot MercuryMessaging.Network.MmServerReconciliation._authoritativeState private
Definition at line 303 of file MmNetworkPrediction.cs.
Referenced by ProcessTick(), and SetInitialState().
_clientInputs
readonly Dictionary<int, Queue<MmInputSnapshot> > MercuryMessaging.Network.MmServerReconciliation._clientInputs = new Dictionary<int, Queue<MmInputSnapshot>>() private
Definition at line 297 of file MmNetworkPrediction.cs.
Referenced by OnClientInput(), ProcessTick(), RemoveClient(), and Reset().
_currentTick
uint MercuryMessaging.Network.MmServerReconciliation._currentTick = 0 private
Definition at line 304 of file MmNetworkPrediction.cs.
Referenced by ProcessTick(), Reset(), and SetInitialState().
_simulationStep
Func<MmStateSnapshot, MmInputSnapshot, MmStateSnapshot> MercuryMessaging.Network.MmServerReconciliation._simulationStep private
Definition at line 307 of file MmNetworkPrediction.cs.
Referenced by Initialize(), and ProcessTick().
_stateHistory
readonly Queue<MmStateSnapshot> MercuryMessaging.Network.MmServerReconciliation._stateHistory = new Queue<MmStateSnapshot>() private
Definition at line 300 of file MmNetworkPrediction.cs.
Referenced by ProcessTick(), Reset(), and TryGetHistoricalState().
StateHistorySize
int MercuryMessaging.Network.MmServerReconciliation.StateHistorySize = 60
How many past states to keep for rewinding.
Definition at line 294 of file MmNetworkPrediction.cs.
Referenced by ProcessTick().
TickRate
int MercuryMessaging.Network.MmServerReconciliation.TickRate = 60
Tick rate for server updates (Hz).
Definition at line 289 of file MmNetworkPrediction.cs.
Property Documentation
AuthoritativeState
MmStateSnapshot MercuryMessaging.Network.MmServerReconciliation.AuthoritativeState get
Current authoritative state.
Definition at line 312 of file MmNetworkPrediction.cs.
CurrentTick
uint MercuryMessaging.Network.MmServerReconciliation.CurrentTick get
Current server tick.
Definition at line 317 of file MmNetworkPrediction.cs.
The documentation for this class was generated from the following file:
Protocol/Network/MmNetworkPrediction.cs