MercuryMessaging: MercuryMessaging.MmQuickExtensions Class Reference
MercuryMessaging.MmQuickExtensions Class Reference
Ultra-minimal extension methods for MmRelayNode.
Static Public Member Functions
static void Init (this MmRelayNode relay)
Initialize all descendants.
static void Done (this MmRelayNode relay)
Notify parent(s) of completion.
static void Sync (this MmRelayNode relay)
Refresh all descendants.
static void Tell (this MmRelayNode relay, bool value)
Send a boolean value to all descendants.
static void Tell (this MmRelayNode relay, int value)
Send an integer value to all descendants.
static void Tell (this MmRelayNode relay, float value)
Send a float value to all descendants.
static void Tell (this MmRelayNode relay, string value)
Send a string value to all descendants.
static void Tell (this MmRelayNode relay, Vector3 value)
Send a Vector3 value to all descendants.
static void Report (this MmRelayNode relay, bool value)
Report a boolean value to parent(s).
static void Report (this MmRelayNode relay, int value)
Report an integer value to parent(s).
static void Report (this MmRelayNode relay, float value)
Report a float value to parent(s).
static void Report (this MmRelayNode relay, string value)
Report a string value to parent(s).
static void Activate (this MmRelayNode relay, bool active)
Send SetActive to all descendants.
static void State (this MmRelayNode relay, string stateName)
Send a state switch command to descendants.
Detailed Description
Ultra-minimal extension methods for MmRelayNode.
These methods auto-execute without requiring .Execute() for simple cases.
API Tiers:
Quick (this class): Init(), Tell(), Done() - shortest, auto-execute
Convenience: Broadcast(), Notify() - one-liners, auto-execute
Fluent: Send().ToX().Execute() - chainable, requires Execute()
Raw: MmInvoke() - full control, verbose
Definition at line 25 of file MmQuickExtensions.cs.
Member Function Documentation
Activate()
void MercuryMessaging.MmQuickExtensions.Activate (this MmRelayNode relay, bool active) static
Send SetActive to all descendants.
Common pattern for enabling/disabling subtrees.
relay.Activate(true); // 23 chars vs 31 for BroadcastSetActive
Definition at line 182 of file MmQuickExtensions.cs.
References MercuryMessaging.MmFluentMessage.Execute(), and MercuryMessaging.MmFluentMessage.ToDescendants().
Done()
void MercuryMessaging.MmQuickExtensions.Done (this MmRelayNode relay) static
Notify parent(s) of completion.
Shortest way to signal done. Equivalent to: relay.Notify(MmMethod.Complete)
relay.Done(); // 14 chars vs 22 for NotifyComplete
Definition at line 48 of file MmQuickExtensions.cs.
References MercuryMessaging.MmFluentMessage.Execute(), and MercuryMessaging.MmFluentMessage.ToParents().
Init()
void MercuryMessaging.MmQuickExtensions.Init (this MmRelayNode relay) static
Initialize all descendants.
Shortest way to broadcast Initialize. Equivalent to: relay.Broadcast(MmMethod.Initialize)
relay.Init(); // 14 chars vs 38 for Broadcast
Definition at line 36 of file MmQuickExtensions.cs.
References MercuryMessaging.MmFluentMessage.Execute(), and MercuryMessaging.MmFluentMessage.ToDescendants().
Report() [1/4]
void MercuryMessaging.MmQuickExtensions.Report (this MmRelayNode relay, bool value) static
Report a boolean value to parent(s).
Equivalent to: relay.Notify(MmMethod.MessageBool, value)
relay.Report(true); // 21 chars vs 35 for Notify
Definition at line 135 of file MmQuickExtensions.cs.
References MercuryMessaging.MmFluentMessage.Execute(), and MercuryMessaging.MmFluentMessage.ToParents().
Report() [2/4]
void MercuryMessaging.MmQuickExtensions.Report (this MmRelayNode relay, float value) static
Report a float value to parent(s).
Definition at line 156 of file MmQuickExtensions.cs.
References MercuryMessaging.MmFluentMessage.Execute(), and MercuryMessaging.MmFluentMessage.ToParents().
Report() [3/4]
void MercuryMessaging.MmQuickExtensions.Report (this MmRelayNode relay, int value) static
Report an integer value to parent(s).
relay.Report(100); // 19 chars
Definition at line 146 of file MmQuickExtensions.cs.
References MercuryMessaging.MmFluentMessage.Execute(), and MercuryMessaging.MmFluentMessage.ToParents().
Report() [4/4]
void MercuryMessaging.MmQuickExtensions.Report (this MmRelayNode relay, string value) static
Report a string value to parent(s).
relay.Report("done"); // 22 chars
Definition at line 167 of file MmQuickExtensions.cs.
References MercuryMessaging.MmFluentMessage.Execute(), and MercuryMessaging.MmFluentMessage.ToParents().
State()
void MercuryMessaging.MmQuickExtensions.State (this MmRelayNode relay, string stateName) static
Send a state switch command to descendants.
relay.State("Playing"); // 25 chars
Definition at line 193 of file MmQuickExtensions.cs.
References MercuryMessaging.MmFluentMessage.Execute(), and MercuryMessaging.MmFluentMessage.ToDescendants().
Sync()
void MercuryMessaging.MmQuickExtensions.Sync (this MmRelayNode relay) static
Refresh all descendants.
Shortest way to broadcast Refresh. Equivalent to: relay.Broadcast(MmMethod.Refresh)
relay.Sync(); // 14 chars
Definition at line 60 of file MmQuickExtensions.cs.
References MercuryMessaging.MmFluentMessage.Execute(), and MercuryMessaging.MmFluentMessage.ToDescendants().
Tell() [1/5]
void MercuryMessaging.MmQuickExtensions.Tell (this MmRelayNode relay, bool value) static
Send a boolean value to all descendants.
Equivalent to: relay.Broadcast(MmMethod.MessageBool, value)
relay.Tell(true); // 19 chars vs 40 for Broadcast
Definition at line 76 of file MmQuickExtensions.cs.
References MercuryMessaging.MmFluentMessage.Execute(), and MercuryMessaging.MmFluentMessage.ToDescendants().
Tell() [2/5]
void MercuryMessaging.MmQuickExtensions.Tell (this MmRelayNode relay, float value) static
Send a float value to all descendants.
relay.Tell(3.14f); // 21 chars
Definition at line 98 of file MmQuickExtensions.cs.
References MercuryMessaging.MmFluentMessage.Execute(), and MercuryMessaging.MmFluentMessage.ToDescendants().
Tell() [3/5]
void MercuryMessaging.MmQuickExtensions.Tell (this MmRelayNode relay, int value) static
Send an integer value to all descendants.
relay.Tell(42); // 17 chars
Definition at line 87 of file MmQuickExtensions.cs.
References MercuryMessaging.MmFluentMessage.Execute(), and MercuryMessaging.MmFluentMessage.ToDescendants().
Tell() [4/5]
void MercuryMessaging.MmQuickExtensions.Tell (this MmRelayNode relay, string value) static
Send a string value to all descendants.
relay.Tell("hello"); // 22 chars
Definition at line 109 of file MmQuickExtensions.cs.
References MercuryMessaging.MmFluentMessage.Execute(), and MercuryMessaging.MmFluentMessage.ToDescendants().
Tell() [5/5]
void MercuryMessaging.MmQuickExtensions.Tell (this MmRelayNode relay, Vector3 value) static
Send a Vector3 value to all descendants.
Definition at line 119 of file MmQuickExtensions.cs.
References MercuryMessaging.MmFluentMessage.Execute(), and MercuryMessaging.MmFluentMessage.ToDescendants().
The documentation for this class was generated from the following file:
Protocol/DSL/MmQuickExtensions.cs