MercuryMessaging: MercuryMessaging.MmListenerExtensions Class Reference
MercuryMessaging.MmListenerExtensions Class Reference
Extension methods for subscribing to messages on MmRelayNode.
Static Public Member Functions
static MmListenerBuilder< T > Listen< T > (this MmRelayNode relay)
Creates a listener builder for messages of type T.
static MmListenerBuilder< T > ListenOnce< T > (this MmRelayNode relay)
Creates a one-time listener builder that auto-disposes after receiving one message.
static MmListenerSubscription< MmMessageFloat > OnFloat (this MmRelayNode relay, Action< float > handler)
Quick subscription for float messages without builder pattern.
static MmListenerSubscription< MmMessageInt > OnInt (this MmRelayNode relay, Action< int > handler)
Quick subscription for int messages without builder pattern.
static MmListenerSubscription< MmMessageString > OnString (this MmRelayNode relay, Action< string > handler)
Quick subscription for string messages without builder pattern.
static MmListenerSubscription< MmMessageBool > OnBool (this MmRelayNode relay, Action< bool > handler)
Quick subscription for bool messages without builder pattern.
static MmListenerSubscription< MmMessageVector3 > OnVector3 (this MmRelayNode relay, Action< UnityEngine.Vector3 > handler)
Quick subscription for Vector3 messages without builder pattern.
static MmListenerBuilder< MmMessage > ListenFor (this MmRelayNode relay, MmMethod method)
Creates a listener for a specific MmMethod.
static MmListenerSubscription< MmMessage > OnInitialize (this MmRelayNode relay, Action handler)
Quick subscription for Initialize messages.
static MmListenerSubscription< MmMessageBool > OnSetActive (this MmRelayNode relay, Action< bool > handler)
Quick subscription for SetActive messages.
static MmListenerSubscription< MmMessage > OnRefresh (this MmRelayNode relay, Action handler)
Quick subscription for Refresh messages.
static MmListenerSubscription< MmMessage > OnComplete (this MmRelayNode relay, Action handler)
Quick subscription for Complete messages.
static MmListenerSubscription< MmMessageString > OnSwitch (this MmRelayNode relay, Action< string > handler)
Quick subscription for Switch messages.
static void ClearAllListeners (this MmRelayNode relay)
Removes all listeners from this relay node.
static int GetListenerCount (this MmRelayNode relay)
Gets the number of active listeners on this relay node.
static MmListenerBuilder< T > Listen< T > (this MmBaseResponder responder)
Creates a listener builder for messages of type T (from responder).
static MmListenerBuilder< T > ListenOnce< T > (this MmBaseResponder responder)
Creates a one-time listener builder (from responder).
static MmListenerSubscription< MmMessageFloat > OnFloat (this MmBaseResponder responder, Action< float > handler)
Quick subscription for float messages (from responder).
static MmListenerSubscription< MmMessageInt > OnInt (this MmBaseResponder responder, Action< int > handler)
Quick subscription for int messages (from responder).
static MmListenerSubscription< MmMessageString > OnString (this MmBaseResponder responder, Action< string > handler)
Quick subscription for string messages (from responder).
static MmListenerSubscription< MmMessageBool > OnBool (this MmBaseResponder responder, Action< bool > handler)
Quick subscription for bool messages (from responder).
static MmListenerSubscription< MmMessageVector3 > OnVector3 (this MmBaseResponder responder, Action< UnityEngine.Vector3 > handler)
Quick subscription for Vector3 messages (from responder).
static MmListenerBuilder< MmMessage > ListenFor (this MmBaseResponder responder, MmMethod method)
Creates a listener for a specific MmMethod (from responder).
static MmListenerSubscription< MmMessage > OnInitialize (this MmBaseResponder responder, Action handler)
Quick subscription for Initialize messages (from responder).
static MmListenerSubscription< MmMessageBool > OnSetActive (this MmBaseResponder responder, Action< bool > handler)
Quick subscription for SetActive messages (from responder).
static MmListenerSubscription< MmMessage > OnRefresh (this MmBaseResponder responder, Action handler)
Quick subscription for Refresh messages (from responder).
static MmListenerSubscription< MmMessage > OnComplete (this MmBaseResponder responder, Action handler)
Quick subscription for Complete messages (from responder).
static MmListenerSubscription< MmMessageString > OnSwitch (this MmBaseResponder responder, Action< string > handler)
Quick subscription for Switch messages (from responder).
static void ClearAllListeners (this MmBaseResponder responder)
Removes all listeners from this responder's relay node.
static int GetListenerCount (this MmBaseResponder responder)
Gets the number of active listeners on this responder's relay node.
Detailed Description
Extension methods for subscribing to messages on MmRelayNode.
Part of DSL Phase 2.1: Receiving Listener Pattern.
Definition at line 16 of file MmListenerExtensions.cs.
Member Function Documentation
ClearAllListeners() [1/2]
void MercuryMessaging.MmListenerExtensions.ClearAllListeners (this MmBaseResponder responder) static
Removes all listeners from this responder's relay node.
Definition at line 455 of file MmListenerExtensions.cs.
References MercuryMessaging.MmRelayNode.ClearListeners(), and MercuryMessaging.MmBaseResponder.GetRelayNode().
ClearAllListeners() [2/2]
void MercuryMessaging.MmListenerExtensions.ClearAllListeners (this MmRelayNode relay) static
Removes all listeners from this relay node.
Use with caution - this will stop all external subscribers.
Parameters
relay The relay node to clear listeners from.
Definition at line 274 of file MmListenerExtensions.cs.
References MercuryMessaging.MmRelayNode.ClearListeners().
GetListenerCount() [1/2]
int MercuryMessaging.MmListenerExtensions.GetListenerCount (this MmBaseResponder responder) static
Gets the number of active listeners on this responder's relay node.
Definition at line 461 of file MmListenerExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode(), and MercuryMessaging.MmRelayNode.ListenerCount.
GetListenerCount() [2/2]
int MercuryMessaging.MmListenerExtensions.GetListenerCount (this MmRelayNode relay) static
Gets the number of active listeners on this relay node.
Useful for debugging and testing.
Parameters
relay The relay node to query.
Returns
The number of active listeners.
Definition at line 285 of file MmListenerExtensions.cs.
References MercuryMessaging.MmRelayNode.ListenerCount.
Listen< T >() [1/2]
MmListenerBuilder< T > MercuryMessaging.MmListenerExtensions.Listen< T > (this MmBaseResponder responder) static
Creates a listener builder for messages of type T (from responder).
Null-safe: returns default builder if responder has no relay node.
Template Parameters
T The message type to listen for.
Parameters
responder The responder to listen from.
Returns
A builder for configuring the listener.
// From a responder - same API as relay node! var subscription = myResponder.Listen<MmMessageFloat>() .OnReceived(msg => brightness = msg.value) .Execute();
Type Constraints
T : MmMessage
Definition at line 314 of file MmListenerExtensions.cs.
Listen< T >() [2/2]
MmListenerBuilder< T > MercuryMessaging.MmListenerExtensions.Listen< T > (this MmRelayNode relay) static
Creates a listener builder for messages of type T.
Use this to subscribe to specific message types from external components.
Template Parameters
T The message type to listen for.
Parameters
relay The relay node to listen on.
Returns
A builder for configuring the listener.
// Basic typed listener var subscription = relay.Listen<MmMessageFloat>() .OnReceived(msg => brightness = msg.value) .Execute();
// Later, unsubscribe subscription.Dispose();
Type Constraints
T : MmMessage
Definition at line 37 of file MmListenerExtensions.cs.
ListenFor() [1/2]
MmListenerBuilder< MmMessage > MercuryMessaging.MmListenerExtensions.ListenFor (this MmBaseResponder responder, MmMethod method) static
Creates a listener for a specific MmMethod (from responder).
Definition at line 394 of file MmListenerExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
ListenFor() [2/2]
MmListenerBuilder< MmMessage > MercuryMessaging.MmListenerExtensions.ListenFor (this MmRelayNode relay, MmMethod method) static
Creates a listener for a specific MmMethod.
Listens for any message with the specified method type.
Parameters
relay The relay node to listen on.
method The MmMethod to listen for.
Returns
A builder for configuring the listener.
relay.ListenFor(MmMethod.Initialize) .OnReceived(msg => HandleInit()) .Execute();
Definition at line 177 of file MmListenerExtensions.cs.
ListenOnce< T >() [1/2]
MmListenerBuilder< T > MercuryMessaging.MmListenerExtensions.ListenOnce< T > (this MmBaseResponder responder) static
Creates a one-time listener builder (from responder).
Null-safe: returns default builder if responder has no relay node.
Template Parameters
T The message type to listen for.
Parameters
responder The responder to listen from.
Returns
A builder for configuring the listener.
Type Constraints
T : MmMessage
Definition at line 328 of file MmListenerExtensions.cs.
ListenOnce< T >() [2/2]
MmListenerBuilder< T > MercuryMessaging.MmListenerExtensions.ListenOnce< T > (this MmRelayNode relay) static
Creates a one-time listener builder that auto-disposes after receiving one message.
Useful for waiting for a specific response or event.
Template Parameters
T The message type to listen for.
Parameters
relay The relay node to listen on.
Returns
A builder for configuring the listener.
// Wait for a result message, then auto-unsubscribe relay.ListenOnce<MmMessageString>() .OnReceived(msg => ProcessResult(msg.value)) .Execute();
Type Constraints
T : MmMessage
Definition at line 56 of file MmListenerExtensions.cs.
OnBool() [1/2]
MmListenerSubscription< MmMessageBool > MercuryMessaging.MmListenerExtensions.OnBool (this MmBaseResponder responder, Action< bool > handler) static
Quick subscription for bool messages (from responder).
Definition at line 370 of file MmListenerExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
OnBool() [2/2]
MmListenerSubscription< MmMessageBool > MercuryMessaging.MmListenerExtensions.OnBool (this MmRelayNode relay, Action< bool > handler) static
Quick subscription for bool messages without builder pattern.
Parameters
relay The relay node to listen on.
handler The handler to call with the bool value.
Returns
A subscription handle.
var sub = relay.OnBool(value => gameObject.SetActive(value));
Definition at line 132 of file MmListenerExtensions.cs.
OnComplete() [1/2]
MmListenerSubscription< MmMessage > MercuryMessaging.MmListenerExtensions.OnComplete (this MmBaseResponder responder, Action handler) static
Quick subscription for Complete messages (from responder).
Definition at line 432 of file MmListenerExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
OnComplete() [2/2]
MmListenerSubscription< MmMessage > MercuryMessaging.MmListenerExtensions.OnComplete (this MmRelayNode relay, Action handler) static
Quick subscription for Complete messages.
Parameters
relay The relay node to listen on.
handler The handler to call when Complete is received.
Returns
A subscription handle.
Definition at line 239 of file MmListenerExtensions.cs.
OnFloat() [1/2]
MmListenerSubscription< MmMessageFloat > MercuryMessaging.MmListenerExtensions.OnFloat (this MmBaseResponder responder, Action< float > handler) static
Quick subscription for float messages (from responder).
Definition at line 340 of file MmListenerExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
OnFloat() [2/2]
MmListenerSubscription< MmMessageFloat > MercuryMessaging.MmListenerExtensions.OnFloat (this MmRelayNode relay, Action< float > handler) static
Quick subscription for float messages without builder pattern.
Parameters
relay The relay node to listen on.
handler The handler to call with the float value.
Returns
A subscription handle.
var sub = relay.OnFloat(value => slider.value = value);
Definition at line 75 of file MmListenerExtensions.cs.
OnInitialize() [1/2]
MmListenerSubscription< MmMessage > MercuryMessaging.MmListenerExtensions.OnInitialize (this MmBaseResponder responder, Action handler) static
Quick subscription for Initialize messages (from responder).
Definition at line 402 of file MmListenerExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
OnInitialize() [2/2]
MmListenerSubscription< MmMessage > MercuryMessaging.MmListenerExtensions.OnInitialize (this MmRelayNode relay, Action handler) static
Quick subscription for Initialize messages.
Parameters
relay The relay node to listen on.
handler The handler to call when Initialize is received.
Returns
A subscription handle.
Definition at line 190 of file MmListenerExtensions.cs.
OnInt() [1/2]
MmListenerSubscription< MmMessageInt > MercuryMessaging.MmListenerExtensions.OnInt (this MmBaseResponder responder, Action< int > handler) static
Quick subscription for int messages (from responder).
Definition at line 350 of file MmListenerExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
OnInt() [2/2]
MmListenerSubscription< MmMessageInt > MercuryMessaging.MmListenerExtensions.OnInt (this MmRelayNode relay, Action< int > handler) static
Quick subscription for int messages without builder pattern.
Parameters
relay The relay node to listen on.
handler The handler to call with the int value.
Returns
A subscription handle.
var sub = relay.OnInt(value => score = value);
Definition at line 94 of file MmListenerExtensions.cs.
OnRefresh() [1/2]
MmListenerSubscription< MmMessage > MercuryMessaging.MmListenerExtensions.OnRefresh (this MmBaseResponder responder, Action handler) static
Quick subscription for Refresh messages (from responder).
Definition at line 422 of file MmListenerExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
OnRefresh() [2/2]
MmListenerSubscription< MmMessage > MercuryMessaging.MmListenerExtensions.OnRefresh (this MmRelayNode relay, Action handler) static
Quick subscription for Refresh messages.
Parameters
relay The relay node to listen on.
handler The handler to call when Refresh is received.
Returns
A subscription handle.
Definition at line 223 of file MmListenerExtensions.cs.
OnSetActive() [1/2]
MmListenerSubscription< MmMessageBool > MercuryMessaging.MmListenerExtensions.OnSetActive (this MmBaseResponder responder, Action< bool > handler) static
Quick subscription for SetActive messages (from responder).
Definition at line 412 of file MmListenerExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
OnSetActive() [2/2]
MmListenerSubscription< MmMessageBool > MercuryMessaging.MmListenerExtensions.OnSetActive (this MmRelayNode relay, Action< bool > handler) static
Quick subscription for SetActive messages.
Parameters
relay The relay node to listen on.
handler The handler to call with the bool value.
Returns
A subscription handle.
Definition at line 206 of file MmListenerExtensions.cs.
OnString() [1/2]
MmListenerSubscription< MmMessageString > MercuryMessaging.MmListenerExtensions.OnString (this MmBaseResponder responder, Action< string > handler) static
Quick subscription for string messages (from responder).
Definition at line 360 of file MmListenerExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
OnString() [2/2]
MmListenerSubscription< MmMessageString > MercuryMessaging.MmListenerExtensions.OnString (this MmRelayNode relay, Action< string > handler) static
Quick subscription for string messages without builder pattern.
Parameters
relay The relay node to listen on.
handler The handler to call with the string value.
Returns
A subscription handle.
var sub = relay.OnString(value => label.text = value);
Definition at line 113 of file MmListenerExtensions.cs.
OnSwitch() [1/2]
MmListenerSubscription< MmMessageString > MercuryMessaging.MmListenerExtensions.OnSwitch (this MmBaseResponder responder, Action< string > handler) static
Quick subscription for Switch messages (from responder).
Definition at line 442 of file MmListenerExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
OnSwitch() [2/2]
MmListenerSubscription< MmMessageString > MercuryMessaging.MmListenerExtensions.OnSwitch (this MmRelayNode relay, Action< string > handler) static
Quick subscription for Switch messages.
Parameters
relay The relay node to listen on.
handler The handler to call with the state name.
Returns
A subscription handle.
Definition at line 255 of file MmListenerExtensions.cs.
OnVector3() [1/2]
MmListenerSubscription< MmMessageVector3 > MercuryMessaging.MmListenerExtensions.OnVector3 (this MmBaseResponder responder, Action< UnityEngine.Vector3 > handler) static
Quick subscription for Vector3 messages (from responder).
Definition at line 380 of file MmListenerExtensions.cs.
References MercuryMessaging.MmBaseResponder.GetRelayNode().
OnVector3() [2/2]
MmListenerSubscription< MmMessageVector3 > MercuryMessaging.MmListenerExtensions.OnVector3 (this MmRelayNode relay, Action< UnityEngine.Vector3 > handler) static
Quick subscription for Vector3 messages without builder pattern.
Parameters
relay The relay node to listen on.
handler The handler to call with the Vector3 value.
Returns
A subscription handle.
var sub = relay.OnVector3(value => transform.position = value);
Definition at line 151 of file MmListenerExtensions.cs.
The documentation for this class was generated from the following file:
Protocol/DSL/MmListenerExtensions.cs