MercuryMessaging: MercuryMessaging Namespace Reference
MercuryMessaging Namespace Reference
Namespaces
namespace Network
namespace StandardLibrary
namespace Data
namespace Task
Classes
class MmAppStateResponder
Application State data.
class MmAppStateSwitchResponder
MmSwitchResponder for controlling MmAppStates.
class MmRelayAppStateNode
MmRelayNode for handling MmAppStateResponder.
class MmGenerateDispatchAttribute
Marks a responder class for automatic dispatch code generation.
class MmHandlerAttribute
Marks a method as a handler for a specific custom MmMethod value.
class EnumFlagAttribute
Used by MercuryMessaging classes to setup Enum Flags.
class GameObjectExtensions
Collection of GameObject extensions useful if using MercuryMessaging to create applications using MercuryMessaging.
struct HSBColor
From: http://wiki.unity3d.com/index.php?title=HSBColor.
class IEnumerableExtensions
class MaterialExtensions
Simple utilities to provide some blend and fade support to Unity Materials.
class MatrixUtilities
Some helpful matrix functions if creating applications using MercuryMessaging.
class ReorderableListAttribute
class ReorderableList< T >
class TransformExtensions
Collection of GameObject extensions useful if creating applications using MercuryMessaging.
class MmCircularBuffer< T >
Fixed-size circular buffer that automatically overwrites oldest entries Used for message history tracking with bounded memory.
class MmHashSetPool
Pool for HashSet<int> used by VisitedNodes in message routing.
class MmLogger
Mercury's Logger is used throughout the framework to log: Framework, MmResponder, Application, and Error level messages.
class MmMessagePool
High-performance message pooling using Unity's ObjectPool.
class AppStateBuilder
Fluent builder for configuring application states.
class MmAppState
Static factory for app state configuration.
class HierarchyBuilder
Fluent builder for constructing MercuryMessaging hierarchies programmatically.
class MmHierarchy
Static factory for creating hierarchy builders.
class MmHierarchyExtensions
Extension methods for relay node hierarchy management.
struct MmDeferredRoutingBuilder
Deferred routing builder that requires explicit Execute() to send messages.
class MmFluentExtensions
Extension methods for MmRelayNode to enable fluent message sending.
class MmFluentFilters
Provides convenient static properties for common routing filters.
struct MmRouteBuilder
Provides a fluent route builder for combining multiple filters.
class MmLevelFilterExtensions
Extension methods for MmLevelFilter to enable property chaining.
struct MmFluentMessage
Fluent message builder for MercuryMessaging.
struct MmPredicate
Represents a single predicate for filtering responders.
class MmPredicateList
Container for multiple predicates.
class MmPredicateListPool
Object pool for MmPredicateList to avoid allocations.
class MmListenerSubscription< T >
Represents an active message listener subscription.
interface IMmListenerSubscription
Non-generic base interface for listener subscriptions.
class MmListenerSubscriptionImpl< T >
Generic listener subscription that implements the interface.
struct MmListenerBuilder< T >
Fluent builder for creating message listeners.
class MmListenerExtensions
Extension methods for subscribing to messages on MmRelayNode.
class MmMessageFactory
Factory class for creating MmMessage instances from various types.
class MmMessagingExtensions
Unified messaging extensions for both MmRelayNode and MmBaseResponder.
class MmNetworkExtensions
Extension methods for network-aware messaging.
struct MmQuery< T >
Fluent query builder for traversing and querying MercuryMessaging hierarchies.
struct MmQueryBuilder
Non-generic query builder that returns MmResponder by default.
class MmQueryExtensions
Extension methods for querying MercuryMessaging hierarchies.
class MmQuickExtensions
Ultra-minimal extension methods for MmRelayNode.
class MmRelayNodeExtensions
Convenience extension methods for MmRelayNode to simplify common messaging patterns.
class MmRelaySwitchNodeExtensions
Extension methods for MmRelaySwitchNode to enable fluent FSM configuration.
class MmResponderExtensions
Extension methods for MmExtendableResponder to enable fluent handler configuration.
struct MmRoutingBuilder
Property-based routing builder for shorter DSL syntax.
class MmRoutingExtensions
Extension methods for simplified runtime hierarchy registration.
class MmTagExtensions
Extension methods for fluent tag configuration.
struct MmTagConfigBuilder
Fluent builder for bulk tag configuration.
class MmTemporalExtensions
Temporal extension methods for MmRelayNode providing time-based messaging patterns.
class MmTemporalHandle
Handle for cancelling temporal operations.
struct MmTemporalBuilder
Fluent builder for temporal message operations.
class MmTemporalRunner
MonoBehaviour that runs temporal coroutines.
class ResponderHandlerBuilder
Fluent builder for configuring message handlers on MmExtendableResponder.
class ResponderHandlerWrapper
Wrapper that holds configured handlers for standard methods.
class MmLevelFilterHelper
Utility to quickly generate MmLevelFilterHelpers.
class MmMetadataBlock
MmMetadataBlock is a collection of settings allowing you to specify the precise invocation path of an MmMessage invoked on an MmRelayNode through its MercuryMessaging hierarchy.
class MmMetadataBlockHelper
Helper class to easily create common MercuryMessaging MetadataBlocks.
class MmTagHelper
class FiniteStateMachine< T >
Finite State Machine, supporting generic types states.
class FsmConfigBuilder< T >
Fluent builder for configuring FiniteStateMachine event handlers.
interface IFiniteStateMachine< T >
Defines required methods for a Finite State Machine.
class KeyedList< K, V >
class StateEvents
States used by FiniteStateMachine FiniteStateMachine<T>.
interface IMmNetworkResponder
Implement this interface to utilize your chosen Networking framework with Mercury XM.
interface IMmNode
Defines methods required by an MmResponder & utility methods making invocation MmMethods with built-in MmMessages easier.
interface IMmResponder
The core of MercuryMessaging.
class MmMessage
Base class for messages passed through MmInvoke.
class MmMessageBool
MmMessage with bool payload.
class MmMessageByteArray
MmMessage with byte array payload.
class MmMessageFloat
MmMessage with float payload.
class MmMessageGameObject
MmMessage with MmMessageGameObject payload.
class MmMessageInt
MmMessage with int payload.
class MmMessageQuaternion
MmMessage with Quaternion payload.
class MmMessageSerializable
MmMessage that sends a serialized object as payload You need to assign your implementation of the IMSerializable interface to the Serializable types somewhere in your program.
class MmMessageString
MmMessage with string payload.
class MmMessageTransform
MmMessage with MmTransform payload.
class MmMessageTransformList
MmMessage with Transform List payload.
class MmMessageVector3
MmMessage with Vector3 payload.
class MmMessageVector4
MmMessage with Vector4 payload.
struct MmTransform
A struct containing the translation, rotation and scale of a transformation.
class MmNetworkResponder
class MmQuickNode
Modification of the standard MmRelayNode that allows skipping of standard checks to allow for faster propagation.
class MmRelayNode
Base routing node of Mercury XM.
class MmRelaySwitchNode
an MmRelayNode with an FSM to allow for limited MmResponder selection in the MmRelayNode's MmRoutingTable.
class MmBaseResponder
MmResponder that implements a switch handling the framework-provided MmMethods.
class MmExtendableResponder
Base responder with extensible custom method handling via registration API.
class MmResponder
Base implmentation of IMmResponder.
class MmSwitchResponder
Controller for MmRelaySwitchNode.
class ParsedPath
Represents a parsed routing path with validated segments.
class MmInvalidPathException
Exception thrown when path specification is invalid.
class MmPathSpecification
Path specification parser for hierarchical message routing.
class MmRoutingOptions
Configuration options for advanced message routing behavior.
struct MmFilterCacheKey
Cache key for filter result caching (QW-3).
class MmRoutingTable
A form of Reorderable List ReorderableList<T> specifically for all derivations of MmResponder.
class MmRoutingTableItem
Wrapper objects for MmResponders for use in MmRoutingTables.
class MmTransformResponder
interface IMmGUI
Defines interface for basic GUI requirements in Mercury.
class MmGuiHandler
class MmGuiResponder
GUI Interaction Component - Adapter for IMmGUI objects.
class Utilities
General utility functions Some have been found online.
Enumerations
enum MmPredicateType {
Within , InDirection , InBounds , WithComponent ,
Custom
}
Predicate types for fluent message filtering.
enum MmActiveFilter { Active , All }
Filter that allows you to send messages only to objects active in MercuryMessaging hierarchy or to all objects.
enum MmLevelFilter {
Self = 1 << 0 , Child = 1 << 1 , Parent = 1 << 2 , Siblings = 1 << 3 ,
Cousins = 1 << 4 , Descendants = 1 << 5 , Ancestors = 1 << 6 , Custom = 1 << 7
}
Filter represents relationship types of MmResponders.
enum MmNetworkFilter { All , Local , Network }
Filter that allows you to specifiy whether a message should execute locally or over the network.
enum MmSelectedFilter { All , Selected }
Filter that allows you to send messages only to selected objects.
enum MmTag {
Tag0 = 1 << 0 , Tag1 = 1 << 1 , Tag2 = 1 << 2 , Tag3 = 1 << 3 ,
Tag4 = 1 << 4 , Tag5 = 1 << 5 , Tag6 = 1 << 6 , Tag7 = 1 << 7
}
enum MmMessageType : short {
MmVoid = 1001 , MmInt , MmBool , MmFloat ,
MmVector3 , MmVector4 , MmString , MmByteArray ,
MmTransform , MmTransformList , MmSerializable , MmGameObject ,
MmQuaternion
}
Supported base MercuryMessage Message types.
enum MmMethod {
NoOp = 0 , Initialize , SetActive , Refresh ,
Switch , Complete , TaskInfo , Message ,
MessageBool , MessageByteArray , MessageFloat , MessageInt ,
MessageSerializable , MessageString , MessageTransform , MessageTransformList ,
MessageVector3 , MessageVector4 , MessageGameObject , MessageQuaternion
}
The list of support MmRelayNode function calls.
enum MmRoutingChecks {
None = 0 , Level = 1 , Active = 2 , Selected = 4 ,
Tag = 8 , Network = 16 , All = Level | Active | Selected | Tag | Network
}
Flags controlling which routing checks to perform during message dispatch.
enum PathSegment {
Parent , Child , Sibling , Self ,
Ancestor , Descendant , Wildcard
}
Represents a segment in a routing path.
Functions
delegate void Transition ()
delegate void IMmCallback ()
IMm callback type used by implementations of IMmResponder.
Enumeration Type Documentation
MmActiveFilter
enum MercuryMessaging.MmActiveFilter
Filter that allows you to send messages only to objects active in MercuryMessaging hierarchy or to all objects.
Enumerator
Active
All
Definition at line 41 of file MmActiveFilter.cs.
MmLevelFilter
enum MercuryMessaging.MmLevelFilter
Filter represents relationship types of MmResponders.
This is a Flags enum - values can be combined using bitwise OR (|).
Phase 2.1 Extensions (Advanced Routing):
Siblings: Same-parent nodes (lateral routing)
Cousins: Parent's-sibling's-children (extended family)
Descendants: Recursive all children (deep traversal)
Ancestors: Recursive all parents (upward traversal)
Custom: User-defined predicate filtering
Enumerator
Self
Child
Parent
Siblings
Cousins
Descendants
Ancestors
Custom
Definition at line 51 of file MmLevelFilter.cs.
MmMessageType
enum MercuryMessaging.MmMessageType : short
Supported base MercuryMessage Message types.
You may want to add new values here if you want to support new message types across the framework.
Enumerator
MmVoid
MmInt
MmBool
MmFloat
MmVector3
MmVector4
MmString
MmByteArray
MmTransform
MmTransformList
MmSerializable
MmGameObject
MmQuaternion
Definition at line 42 of file MmMessageType.cs.
MmMethod
enum MercuryMessaging.MmMethod
The list of support MmRelayNode function calls.
MmMethod only defines values 0-18. In order to invoke new method types, you can use any number, without adding it to this list. We suggest you start above 1000 to safely avoid clashes with the core of the framework.
Enumerator
NoOp
Initialize
SetActive
Refresh
Switch
Complete
TaskInfo
Message
MessageBool
MessageByteArray
MessageFloat
MessageInt
MessageSerializable
MessageString
MessageTransform
MessageTransformList
MessageVector3
MessageVector4
MessageGameObject
MessageQuaternion
Definition at line 43 of file MmMethod.cs.
MmNetworkFilter
enum MercuryMessaging.MmNetworkFilter
Filter that allows you to specifiy whether a message should execute locally or over the network.
If Network is specified, the message should not execute locally. This is useful when you do not want a message to effect the local MercuryMessaging Hierarchy.
Enumerator
All
Local
Network
Definition at line 46 of file MmNetworkFilter.cs.
MmPredicateType
enum MercuryMessaging.MmPredicateType
Predicate types for fluent message filtering.
Used to filter target responders based on spatial, type, or custom criteria.
Enumerator
Within
Filter responders within a radius of the source.
InDirection
Filter responders in a specific direction from the source.
InBounds
Filter responders within a bounding box.
WithComponent
Filter responders with a specific component type.
Custom
Custom predicate function.
Definition at line 12 of file MmFluentPredicates.cs.
MmRoutingChecks
enum MercuryMessaging.MmRoutingChecks
Flags controlling which routing checks to perform during message dispatch.
Disable specific checks for performance at the cost of filtering capability.
Use EnabledChecks on MmRelayNode to control which filters are applied:
// Full filtering (default, backward compatible)
relay.EnabledChecks = MmRoutingChecks.All;
// Skip tag checks only (common optimization)
relay.EnabledChecks = MmRoutingChecks.All &amp; ~MmRoutingChecks.Tag;
// Skip ALL checks (equivalent to old MmQuickNode behavior)
relay.EnabledChecks = MmRoutingChecks.None;
Enumerator
None
No routing checks performed - messages go to all responders.
Level
Level filter check (Child/Parent/Self routing).
Active
Active filter check (active GameObjects only).
Selected
Selected filter check (FSM state selection).
Tag
Tag filter check (tag-based routing).
Network
Network filter check (local vs network messages).
All
All routing checks enabled (default).
Definition at line 75 of file MmRelayNode.cs.
MmSelectedFilter
enum MercuryMessaging.MmSelectedFilter
Filter that allows you to send messages only to selected objects.
The definition of selected is left open for anyone to redefine. In MmRelayNode, selected is not defined. In MmRelaySwitchNode, selected means active in the FSM.
Enumerator
All
Selected
Definition at line 44 of file MmSelectedFilter.cs.
MmTag
enum MercuryMessaging.MmTag
Enumerator
Tag0
Tag1
Tag2
Tag3
Tag4
Tag5
Tag6
Tag7
Definition at line 39 of file MmTag.cs.
PathSegment
enum MercuryMessaging.PathSegment
Represents a segment in a routing path.
Enumerator
Parent
Navigate to immediate parent node.
Child
Navigate to immediate child nodes.
Sibling
Navigate to sibling nodes (same parent).
Self
Navigate to self (current node).
Ancestor
Navigate to all ancestor nodes recursively.
Descendant
Navigate to all descendant nodes recursively.
Wildcard
Wildcard - expand to all nodes at this step.
Definition at line 16 of file MmPathSpecification.cs.
Function Documentation
IMmCallback()
delegate void MercuryMessaging.IMmCallback ()
IMm callback type used by implementations of IMmResponder.
Referenced by MercuryMessaging.IMmNetworkResponder.MmRegisterAwakeCompleteCallback(), MercuryMessaging.IMmResponder.MmRegisterAwakeCompleteCallback(), MercuryMessaging.MmNetworkResponder.MmRegisterAwakeCompleteCallback(), MercuryMessaging.MmResponder.MmRegisterAwakeCompleteCallback(), MercuryMessaging.IMmNetworkResponder.MmRegisterStartCompleteCallback(), MercuryMessaging.IMmResponder.MmRegisterStartCompleteCallback(), MercuryMessaging.MmNetworkResponder.MmRegisterStartCompleteCallback(), and MercuryMessaging.MmResponder.MmRegisterStartCompleteCallback().
Transition()
delegate void MercuryMessaging.Transition ()
Referenced by MercuryMessaging.FsmConfigBuilder< T >.OnEnter(), MercuryMessaging.FsmConfigBuilder< T >.OnEnter(), MercuryMessaging.FsmConfigBuilder< T >.OnExit(), MercuryMessaging.FsmConfigBuilder< T >.OnExit(), MercuryMessaging.MmRelaySwitchNodeExtensions.OnStateEnter(), and MercuryMessaging.MmRelaySwitchNodeExtensions.OnStateExit().