MercuryMessaging: MercuryMessaging.MmDeferredRoutingBuilder Struct Reference
MercuryMessaging.MmDeferredRoutingBuilder Struct Reference
Deferred routing builder that requires explicit Execute() to send messages.
Public Member Functions
MmDeferredRoutingBuilder (MmRelayNode relay)
Creates a new deferred routing builder for the specified relay node.
MmDeferredRoutingBuilder ToChildren ()
Target direct children only.
MmDeferredRoutingBuilder ToParents ()
Target direct parents only.
MmDeferredRoutingBuilder ToDescendants ()
Target self and all descendants (recursive children).
MmDeferredRoutingBuilder ToAncestors ()
Target self and all ancestors (recursive parents).
MmDeferredRoutingBuilder ToSiblings ()
Target siblings (same-parent nodes).
MmDeferredRoutingBuilder ToSelfAndChildren ()
Target self and children (default routing).
MmDeferredRoutingBuilder ToAll ()
Target all connected nodes (bidirectional).
MmDeferredRoutingBuilder Active ()
Only target active GameObjects.
MmDeferredRoutingBuilder IncludeInactive ()
Include inactive GameObjects.
MmDeferredRoutingBuilder Selected ()
Only target selected responders (FSM state).
MmDeferredRoutingBuilder OverNetwork ()
Send over network as well as locally.
MmDeferredRoutingBuilder LocalOnly ()
Send locally only (default).
MmDeferredRoutingBuilder WithTag (MmTag tag)
Filter by tag.
MmDeferredRoutingBuilder Send (string value)
Set string payload. Does NOT execute - call Execute() to send.
MmDeferredRoutingBuilder Send (int value)
Set int payload. Does NOT execute - call Execute() to send.
MmDeferredRoutingBuilder Send (float value)
Set float payload. Does NOT execute - call Execute() to send.
MmDeferredRoutingBuilder Send (bool value)
Set bool payload. Does NOT execute - call Execute() to send.
MmDeferredRoutingBuilder Send (Vector3 value)
Set Vector3 payload. Does NOT execute - call Execute() to send.
MmDeferredRoutingBuilder Send (Vector4 value)
Set Vector4 payload. Does NOT execute - call Execute() to send.
MmDeferredRoutingBuilder Send (Quaternion value)
Set Quaternion payload. Does NOT execute - call Execute() to send.
MmDeferredRoutingBuilder Send (Transform value)
Set Transform payload. Does NOT execute - call Execute() to send.
MmDeferredRoutingBuilder Send (GameObject value)
Set GameObject payload. Does NOT execute - call Execute() to send.
MmDeferredRoutingBuilder Initialize ()
Set Initialize command. Does NOT execute - call Execute() to send.
MmDeferredRoutingBuilder Refresh ()
Set Refresh command. Does NOT execute - call Execute() to send.
MmDeferredRoutingBuilder Complete ()
Set Complete command. Does NOT execute - call Execute() to send.
MmDeferredRoutingBuilder SetActive (bool active)
Set SetActive command. Does NOT execute - call Execute() to send.
MmDeferredRoutingBuilder Switch (int stateIndex)
Set Switch command. Does NOT execute - call Execute() to send.
MmDeferredRoutingBuilder Switch (string stateName)
Set Switch command. Does NOT execute - call Execute() to send.
void Execute ()
Execute the deferred message.
Private Attributes
readonly MmRelayNode _relay
MmLevelFilter _levelFilter
MmActiveFilter _activeFilter
MmSelectedFilter _selectedFilter
MmNetworkFilter _networkFilter
MmTag _tag
MmMethod _method
object _payload
bool _hasPayload
Detailed Description
Deferred routing builder that requires explicit Execute() to send messages.
Unlike MmRoutingBuilder which auto-executes, this builder stores the message configuration and only sends when Execute() is called.
Use cases:
Conditional execution: if (ready) builder.Execute();
Storing message config for later reuse
Building message in stages before sending
Example usage:
// Deferred execution (requires .Execute())
var builder = relay.Build().ToChildren().Send("Hello");
if (condition)
    builder.Execute();
// Compare with auto-execute (relay.To)
relay.To.Children.Send("Hello"); // Sends immediately
Definition at line 36 of file MmDeferredRoutingBuilder.cs.
Constructor & Destructor Documentation
MmDeferredRoutingBuilder()
MercuryMessaging.MmDeferredRoutingBuilder.MmDeferredRoutingBuilder (MmRelayNode relay)
Creates a new deferred routing builder for the specified relay node.
Definition at line 54 of file MmDeferredRoutingBuilder.cs.
References _activeFilter, _hasPayload, _levelFilter, _method, _networkFilter, _payload, _relay, _selectedFilter, _tag, MercuryMessaging.MmTagHelper.Everything, and MercuryMessaging.MmLevelFilterHelper.SelfAndChildren.
Referenced by Active(), Complete(), IncludeInactive(), Initialize(), LocalOnly(), OverNetwork(), Refresh(), Selected(), Send(), Send(), Send(), Send(), Send(), Send(), Send(), Send(), Send(), SetActive(), Switch(), Switch(), ToAll(), ToAncestors(), ToChildren(), ToDescendants(), ToParents(), ToSelfAndChildren(), ToSiblings(), and WithTag().
Member Function Documentation
Active()
MmDeferredRoutingBuilder MercuryMessaging.MmDeferredRoutingBuilder.Active ()
Only target active GameObjects.
Definition at line 138 of file MmDeferredRoutingBuilder.cs.
References MmDeferredRoutingBuilder().
Complete()
MmDeferredRoutingBuilder MercuryMessaging.MmDeferredRoutingBuilder.Complete ()
Set Complete command. Does NOT execute - call Execute() to send.
Definition at line 321 of file MmDeferredRoutingBuilder.cs.
References MmDeferredRoutingBuilder().
Execute()
void MercuryMessaging.MmDeferredRoutingBuilder.Execute ()
Execute the deferred message.
This is the terminal operation that sends the message.
Definition at line 371 of file MmDeferredRoutingBuilder.cs.
References _activeFilter, _hasPayload, _levelFilter, _method, _networkFilter, _payload, _relay, _selectedFilter, _tag, and MercuryMessaging.MmTagHelper.Everything.
IncludeInactive()
MmDeferredRoutingBuilder MercuryMessaging.MmDeferredRoutingBuilder.IncludeInactive ()
Include inactive GameObjects.
Definition at line 147 of file MmDeferredRoutingBuilder.cs.
References MmDeferredRoutingBuilder().
Initialize()
MmDeferredRoutingBuilder MercuryMessaging.MmDeferredRoutingBuilder.Initialize ()
Set Initialize command. Does NOT execute - call Execute() to send.
Definition at line 299 of file MmDeferredRoutingBuilder.cs.
References MmDeferredRoutingBuilder().
LocalOnly()
MmDeferredRoutingBuilder MercuryMessaging.MmDeferredRoutingBuilder.LocalOnly ()
Send locally only (default).
Definition at line 174 of file MmDeferredRoutingBuilder.cs.
References MmDeferredRoutingBuilder().
OverNetwork()
MmDeferredRoutingBuilder MercuryMessaging.MmDeferredRoutingBuilder.OverNetwork ()
Send over network as well as locally.
Definition at line 165 of file MmDeferredRoutingBuilder.cs.
References MmDeferredRoutingBuilder().
Refresh()
MmDeferredRoutingBuilder MercuryMessaging.MmDeferredRoutingBuilder.Refresh ()
Set Refresh command. Does NOT execute - call Execute() to send.
Definition at line 310 of file MmDeferredRoutingBuilder.cs.
References MmDeferredRoutingBuilder().
Selected()
MmDeferredRoutingBuilder MercuryMessaging.MmDeferredRoutingBuilder.Selected ()
Only target selected responders (FSM state).
Definition at line 156 of file MmDeferredRoutingBuilder.cs.
References MmDeferredRoutingBuilder().
Send() [1/9]
MmDeferredRoutingBuilder MercuryMessaging.MmDeferredRoutingBuilder.Send (bool value)
Set bool payload. Does NOT execute - call Execute() to send.
Definition at line 229 of file MmDeferredRoutingBuilder.cs.
References MmDeferredRoutingBuilder().
Send() [2/9]
MmDeferredRoutingBuilder MercuryMessaging.MmDeferredRoutingBuilder.Send (float value)
Set float payload. Does NOT execute - call Execute() to send.
Definition at line 218 of file MmDeferredRoutingBuilder.cs.
References MmDeferredRoutingBuilder().
Send() [3/9]
MmDeferredRoutingBuilder MercuryMessaging.MmDeferredRoutingBuilder.Send (GameObject value)
Set GameObject payload. Does NOT execute - call Execute() to send.
Definition at line 284 of file MmDeferredRoutingBuilder.cs.
References MmDeferredRoutingBuilder().
Send() [4/9]
MmDeferredRoutingBuilder MercuryMessaging.MmDeferredRoutingBuilder.Send (int value)
Set int payload. Does NOT execute - call Execute() to send.
Definition at line 207 of file MmDeferredRoutingBuilder.cs.
References MmDeferredRoutingBuilder().
Send() [5/9]
MmDeferredRoutingBuilder MercuryMessaging.MmDeferredRoutingBuilder.Send (Quaternion value)
Set Quaternion payload. Does NOT execute - call Execute() to send.
Definition at line 262 of file MmDeferredRoutingBuilder.cs.
References MmDeferredRoutingBuilder().
Send() [6/9]
MmDeferredRoutingBuilder MercuryMessaging.MmDeferredRoutingBuilder.Send (string value)
Set string payload. Does NOT execute - call Execute() to send.
Definition at line 196 of file MmDeferredRoutingBuilder.cs.
References MmDeferredRoutingBuilder().
Send() [7/9]
MmDeferredRoutingBuilder MercuryMessaging.MmDeferredRoutingBuilder.Send (Transform value)
Set Transform payload. Does NOT execute - call Execute() to send.
Definition at line 273 of file MmDeferredRoutingBuilder.cs.
References MmDeferredRoutingBuilder().
Send() [8/9]
MmDeferredRoutingBuilder MercuryMessaging.MmDeferredRoutingBuilder.Send (Vector3 value)
Set Vector3 payload. Does NOT execute - call Execute() to send.
Definition at line 240 of file MmDeferredRoutingBuilder.cs.
References MmDeferredRoutingBuilder().
Send() [9/9]
MmDeferredRoutingBuilder MercuryMessaging.MmDeferredRoutingBuilder.Send (Vector4 value)
Set Vector4 payload. Does NOT execute - call Execute() to send.
Definition at line 251 of file MmDeferredRoutingBuilder.cs.
References MmDeferredRoutingBuilder().
SetActive()
MmDeferredRoutingBuilder MercuryMessaging.MmDeferredRoutingBuilder.SetActive (bool active)
Set SetActive command. Does NOT execute - call Execute() to send.
Definition at line 332 of file MmDeferredRoutingBuilder.cs.
References MmDeferredRoutingBuilder().
Switch() [1/2]
MmDeferredRoutingBuilder MercuryMessaging.MmDeferredRoutingBuilder.Switch (int stateIndex)
Set Switch command. Does NOT execute - call Execute() to send.
Definition at line 343 of file MmDeferredRoutingBuilder.cs.
References MmDeferredRoutingBuilder().
Switch() [2/2]
MmDeferredRoutingBuilder MercuryMessaging.MmDeferredRoutingBuilder.Switch (string stateName)
Set Switch command. Does NOT execute - call Execute() to send.
Definition at line 354 of file MmDeferredRoutingBuilder.cs.
References MmDeferredRoutingBuilder().
ToAll()
MmDeferredRoutingBuilder MercuryMessaging.MmDeferredRoutingBuilder.ToAll ()
Target all connected nodes (bidirectional).
Definition at line 125 of file MmDeferredRoutingBuilder.cs.
References MmDeferredRoutingBuilder(), and MercuryMessaging.MmLevelFilterHelper.SelfAndBidirectional.
ToAncestors()
MmDeferredRoutingBuilder MercuryMessaging.MmDeferredRoutingBuilder.ToAncestors ()
Target self and all ancestors (recursive parents).
Definition at line 98 of file MmDeferredRoutingBuilder.cs.
References MmDeferredRoutingBuilder(), and MercuryMessaging.MmLevelFilterHelper.SelfAndAncestors.
ToChildren()
MmDeferredRoutingBuilder MercuryMessaging.MmDeferredRoutingBuilder.ToChildren ()
Target direct children only.
Definition at line 71 of file MmDeferredRoutingBuilder.cs.
References MmDeferredRoutingBuilder().
ToDescendants()
MmDeferredRoutingBuilder MercuryMessaging.MmDeferredRoutingBuilder.ToDescendants ()
Target self and all descendants (recursive children).
Definition at line 89 of file MmDeferredRoutingBuilder.cs.
References MmDeferredRoutingBuilder(), and MercuryMessaging.MmLevelFilterHelper.SelfAndDescendants.
ToParents()
MmDeferredRoutingBuilder MercuryMessaging.MmDeferredRoutingBuilder.ToParents ()
Target direct parents only.
Definition at line 80 of file MmDeferredRoutingBuilder.cs.
References MmDeferredRoutingBuilder().
ToSelfAndChildren()
MmDeferredRoutingBuilder MercuryMessaging.MmDeferredRoutingBuilder.ToSelfAndChildren ()
Target self and children (default routing).
Definition at line 116 of file MmDeferredRoutingBuilder.cs.
References MmDeferredRoutingBuilder(), and MercuryMessaging.MmLevelFilterHelper.SelfAndChildren.
ToSiblings()
MmDeferredRoutingBuilder MercuryMessaging.MmDeferredRoutingBuilder.ToSiblings ()
Target siblings (same-parent nodes).
Definition at line 107 of file MmDeferredRoutingBuilder.cs.
References MmDeferredRoutingBuilder(), and MercuryMessaging.MmLevelFilterHelper.SelfAndSiblings.
WithTag()
MmDeferredRoutingBuilder MercuryMessaging.MmDeferredRoutingBuilder.WithTag (MmTag tag)
Filter by tag.
Definition at line 183 of file MmDeferredRoutingBuilder.cs.
References MmDeferredRoutingBuilder().
Member Data Documentation
_activeFilter
MmActiveFilter MercuryMessaging.MmDeferredRoutingBuilder._activeFilter private
Definition at line 40 of file MmDeferredRoutingBuilder.cs.
Referenced by MmDeferredRoutingBuilder(), and Execute().
_hasPayload
bool MercuryMessaging.MmDeferredRoutingBuilder._hasPayload private
Definition at line 48 of file MmDeferredRoutingBuilder.cs.
Referenced by MmDeferredRoutingBuilder(), and Execute().
_levelFilter
MmLevelFilter MercuryMessaging.MmDeferredRoutingBuilder._levelFilter private
Definition at line 39 of file MmDeferredRoutingBuilder.cs.
Referenced by MmDeferredRoutingBuilder(), and Execute().
_method
MmMethod MercuryMessaging.MmDeferredRoutingBuilder._method private
Definition at line 46 of file MmDeferredRoutingBuilder.cs.
Referenced by MmDeferredRoutingBuilder(), and Execute().
_networkFilter
MmNetworkFilter MercuryMessaging.MmDeferredRoutingBuilder._networkFilter private
Definition at line 42 of file MmDeferredRoutingBuilder.cs.
Referenced by MmDeferredRoutingBuilder(), and Execute().
_payload
object MercuryMessaging.MmDeferredRoutingBuilder._payload private
Definition at line 47 of file MmDeferredRoutingBuilder.cs.
Referenced by MmDeferredRoutingBuilder(), and Execute().
_relay
readonly MmRelayNode MercuryMessaging.MmDeferredRoutingBuilder._relay private
Definition at line 38 of file MmDeferredRoutingBuilder.cs.
Referenced by MmDeferredRoutingBuilder(), and Execute().
_selectedFilter
MmSelectedFilter MercuryMessaging.MmDeferredRoutingBuilder._selectedFilter private
Definition at line 41 of file MmDeferredRoutingBuilder.cs.
Referenced by MmDeferredRoutingBuilder(), and Execute().
_tag
MmTag MercuryMessaging.MmDeferredRoutingBuilder._tag private
Definition at line 43 of file MmDeferredRoutingBuilder.cs.
Referenced by MmDeferredRoutingBuilder(), and Execute().
The documentation for this struct was generated from the following file:
Protocol/DSL/MmDeferredRoutingBuilder.cs