MercuryMessaging: MercuryMessaging.MmQuery< T > Struct Template Reference
MercuryMessaging.MmQuery< T > Struct Template Reference
Fluent query builder for traversing and querying MercuryMessaging hierarchies.
Public Member Functions
MmQuery (MmRelayNode relay)
Creates a new query builder for the specified relay node.
MmQuery< T > Children ()
Query direct children only.
MmQuery< T > Parents ()
Query direct parents only.
MmQuery< T > Descendants ()
Query all descendants recursively.
MmQuery< T > Ancestors ()
Query all ancestors recursively.
MmQuery< T > Siblings ()
Query siblings (same parent).
MmQuery< T > SelfAndChildren ()
Query self and all children.
MmQuery< T > All ()
Query all connected nodes (bidirectional).
MmQuery< TTarget > OfType< TTarget > ()
Filter by a specific responder type.
MmQuery< T > WithTag (MmTag tag)
Filter by tag.
MmQuery< T > Active ()
Filter to only active GameObjects.
MmQuery< T > IncludeInactive ()
Include inactive GameObjects in the query.
MmQuery< T > Where (Func< T, bool > predicate)
Filter by a custom predicate.
MmQuery< T > Named (string name)
Filter by name (exact match).
MmQuery< T > NamedLike (string pattern)
Filter by name pattern (wildcard: * matches any characters).
void Execute (Action< T > action)
Execute an action on each matching item.
List< T > ToList ()
Get all matching items as a list.
T FirstOrDefault ()
Get the first matching item, or default if none found.
T First ()
Get the first matching item, or throw if none found.
int Count ()
Get the count of matching items.
bool Any ()
Check if any items match.
bool Any (Func< T, bool > predicate)
Check if any items match the predicate.
Private Member Functions
IEnumerable< T > EnumerateMatches ()
Enumerates all matching items based on current query configuration.
IEnumerable< T > EnumerateDirect (MmRelayNode relay)
Enumerate direct children/parents from routing table.
IEnumerable< T > EnumerateRecursive (MmRelayNode relay, HashSet< MmRelayNode > visited)
Recursively enumerate descendants/ancestors.
bool MatchesLevelFilter (MmLevelFilter itemLevel)
Check if a routing table item's level matches our filter.
Private Attributes
readonly MmRelayNode _relay
MmLevelFilter _levelFilter
MmTag _tagFilter
bool _activeOnly
bool _includeInactive
Func< T, bool > _predicate
bool _recursive
Detailed Description
Fluent query builder for traversing and querying MercuryMessaging hierarchies.
Supports filtering by type, tag, level, and custom predicates. Uses lazy evaluation for performance.
Template Parameters
T The type of responder to query for (default: MmResponder)
Type Constraints
T : class
Definition at line 23 of file MmQuery.cs.
Member Function Documentation
Active()
MmQuery< T > MercuryMessaging.MmQuery< T >.Active ()
Filter to only active GameObjects.
Definition at line 163 of file MmQuery.cs.
References _activeOnly, _includeInactive, and MmQuery().
All()
MmQuery< T > MercuryMessaging.MmQuery< T >.All ()
Query all connected nodes (bidirectional).
Definition at line 120 of file MmQuery.cs.
References _levelFilter, _recursive, MmQuery(), and MercuryMessaging.MmLevelFilterHelper.SelfAndBidirectional.
Referenced by MercuryMessaging.MmQueryBuilder.All().
Ancestors()
MmQuery< T > MercuryMessaging.MmQuery< T >.Ancestors ()
Query all ancestors recursively.
Definition at line 87 of file MmQuery.cs.
References _levelFilter, _recursive, and MmQuery().
Referenced by MercuryMessaging.MmQueryBuilder.Ancestors().
Any() [1/2]
bool MercuryMessaging.MmQuery< T >.Any ()
Check if any items match.
Definition at line 311 of file MmQuery.cs.
References _relay, and EnumerateMatches().
Any() [2/2]
bool MercuryMessaging.MmQuery< T >.Any (Func< T, bool > predicate)
Check if any items match the predicate.
Definition at line 325 of file MmQuery.cs.
References _relay, and EnumerateMatches().
Children()
MmQuery< T > MercuryMessaging.MmQuery< T >.Children ()
Query direct children only.
Definition at line 54 of file MmQuery.cs.
References _levelFilter, _recursive, and MmQuery().
Referenced by MercuryMessaging.MmQueryBuilder.Children().
Count()
int MercuryMessaging.MmQuery< T >.Count ()
Get the count of matching items.
Definition at line 296 of file MmQuery.cs.
References _relay, and EnumerateMatches().
Descendants()
MmQuery< T > MercuryMessaging.MmQuery< T >.Descendants ()
Query all descendants recursively.
Definition at line 76 of file MmQuery.cs.
References _levelFilter, _recursive, and MmQuery().
Referenced by MercuryMessaging.MmQueryBuilder.Descendants().
EnumerateDirect()
IEnumerable< T > MercuryMessaging.MmQuery< T >.EnumerateDirect (MmRelayNode relay) private
Enumerate direct children/parents from routing table.
Definition at line 371 of file MmQuery.cs.
References _activeOnly, _includeInactive, _predicate, _tagFilter, MercuryMessaging.MmTagHelper.Everything, and MatchesLevelFilter().
Referenced by EnumerateMatches(), and EnumerateRecursive().
EnumerateMatches()
IEnumerable< T > MercuryMessaging.MmQuery< T >.EnumerateMatches () private
Enumerates all matching items based on current query configuration.
Definition at line 344 of file MmQuery.cs.
References _recursive, _relay, EnumerateDirect(), and EnumerateRecursive().
Referenced by Any(), Any(), Count(), Execute(), FirstOrDefault(), and ToList().
EnumerateRecursive()
IEnumerable< T > MercuryMessaging.MmQuery< T >.EnumerateRecursive (MmRelayNode relay, HashSet< MmRelayNode > visited) private
Recursively enumerate descendants/ancestors.
Definition at line 409 of file MmQuery.cs.
References EnumerateDirect(), EnumerateRecursive(), and MatchesLevelFilter().
Referenced by EnumerateMatches(), and EnumerateRecursive().
Execute()
void MercuryMessaging.MmQuery< T >.Execute (Action< T > action)
Execute an action on each matching item.
Definition at line 243 of file MmQuery.cs.
References _relay, and EnumerateMatches().
First()
T MercuryMessaging.MmQuery< T >.First ()
Get the first matching item, or throw if none found.
Definition at line 285 of file MmQuery.cs.
References FirstOrDefault().
FirstOrDefault()
T MercuryMessaging.MmQuery< T >.FirstOrDefault ()
Get the first matching item, or default if none found.
Definition at line 271 of file MmQuery.cs.
References _relay, and EnumerateMatches().
Referenced by First().
IncludeInactive()
MmQuery< T > MercuryMessaging.MmQuery< T >.IncludeInactive ()
Include inactive GameObjects in the query.
Definition at line 174 of file MmQuery.cs.
References _activeOnly, _includeInactive, and MmQuery().
MatchesLevelFilter()
bool MercuryMessaging.MmQuery< T >.MatchesLevelFilter (MmLevelFilter itemLevel) private
Check if a routing table item's level matches our filter.
Definition at line 442 of file MmQuery.cs.
References _levelFilter, MercuryMessaging.Self, MercuryMessaging.MmLevelFilterHelper.SelfAndBidirectional, and MercuryMessaging.MmLevelFilterHelper.SelfAndChildren.
Referenced by EnumerateDirect(), and EnumerateRecursive().
MmQuery()
MercuryMessaging.MmQuery< T >.MmQuery (MmRelayNode relay)
Creates a new query builder for the specified relay node.
Definition at line 37 of file MmQuery.cs.
References _activeOnly, _includeInactive, _levelFilter, _predicate, _recursive, _relay, _tagFilter, MercuryMessaging.MmTagHelper.Everything, and MercuryMessaging.MmLevelFilterHelper.SelfAndChildren.
Referenced by Active(), All(), Ancestors(), Children(), Descendants(), IncludeInactive(), Named(), NamedLike(), OfType< TTarget >(), Parents(), SelfAndChildren(), Siblings(), Where(), and WithTag().
Named()
MmQuery< T > MercuryMessaging.MmQuery< T >.Named (string name)
Filter by name (exact match).
Definition at line 203 of file MmQuery.cs.
References MmQuery(), and Where().
NamedLike()
MmQuery< T > MercuryMessaging.MmQuery< T >.NamedLike (string pattern)
Filter by name pattern (wildcard: * matches any characters).
Definition at line 219 of file MmQuery.cs.
References MmQuery(), and Where().
OfType< TTarget >()
MmQuery< TTarget > MercuryMessaging.MmQuery< T >.OfType< TTarget > ()
Filter by a specific responder type.
Template Parameters
TTarget The target responder type.
Type Constraints
TTarget : class
Definition at line 136 of file MmQuery.cs.
References _activeOnly, _includeInactive, _levelFilter, _recursive, _relay, _tagFilter, and MmQuery().
Parents()
MmQuery< T > MercuryMessaging.MmQuery< T >.Parents ()
Query direct parents only.
Definition at line 65 of file MmQuery.cs.
References _levelFilter, _recursive, and MmQuery().
Referenced by MercuryMessaging.MmQueryBuilder.Parents().
SelfAndChildren()
MmQuery< T > MercuryMessaging.MmQuery< T >.SelfAndChildren ()
Query self and all children.
Definition at line 109 of file MmQuery.cs.
References _levelFilter, _recursive, MmQuery(), and MercuryMessaging.MmLevelFilterHelper.SelfAndChildren.
Siblings()
MmQuery< T > MercuryMessaging.MmQuery< T >.Siblings ()
Query siblings (same parent).
Definition at line 98 of file MmQuery.cs.
References _levelFilter, _recursive, and MmQuery().
Referenced by MercuryMessaging.MmQueryBuilder.Siblings().
ToList()
List< T > MercuryMessaging.MmQuery< T >.ToList ()
Get all matching items as a list.
Definition at line 256 of file MmQuery.cs.
References _relay, and EnumerateMatches().
Where()
MmQuery< T > MercuryMessaging.MmQuery< T >.Where (Func< T, bool > predicate)
Filter by a custom predicate.
Definition at line 185 of file MmQuery.cs.
References _predicate, and MmQuery().
Referenced by Named(), and NamedLike().
WithTag()
MmQuery< T > MercuryMessaging.MmQuery< T >.WithTag (MmTag tag)
Filter by tag.
Definition at line 153 of file MmQuery.cs.
References _tagFilter, and MmQuery().
Member Data Documentation
_activeOnly
bool MercuryMessaging.MmQuery< T >._activeOnly private
Definition at line 28 of file MmQuery.cs.
Referenced by Active(), EnumerateDirect(), IncludeInactive(), MmQuery(), and OfType< TTarget >().
_includeInactive
bool MercuryMessaging.MmQuery< T >._includeInactive private
Definition at line 29 of file MmQuery.cs.
Referenced by Active(), EnumerateDirect(), IncludeInactive(), MmQuery(), and OfType< TTarget >().
_levelFilter
MmLevelFilter MercuryMessaging.MmQuery< T >._levelFilter private
Definition at line 26 of file MmQuery.cs.
Referenced by All(), Ancestors(), Children(), Descendants(), MatchesLevelFilter(), MmQuery(), OfType< TTarget >(), Parents(), SelfAndChildren(), and Siblings().
_predicate
Func<T, bool> MercuryMessaging.MmQuery< T >._predicate private
Definition at line 30 of file MmQuery.cs.
Referenced by EnumerateDirect(), MmQuery(), and Where().
_recursive
bool MercuryMessaging.MmQuery< T >._recursive private
Definition at line 31 of file MmQuery.cs.
Referenced by All(), Ancestors(), Children(), Descendants(), EnumerateMatches(), MmQuery(), OfType< TTarget >(), Parents(), SelfAndChildren(), and Siblings().
_relay
readonly MmRelayNode MercuryMessaging.MmQuery< T >._relay private
Definition at line 25 of file MmQuery.cs.
Referenced by Any(), Any(), Count(), EnumerateMatches(), Execute(), FirstOrDefault(), MmQuery(), OfType< TTarget >(), and ToList().
_tagFilter
MmTag MercuryMessaging.MmQuery< T >._tagFilter private
Definition at line 27 of file MmQuery.cs.
Referenced by EnumerateDirect(), MmQuery(), OfType< TTarget >(), and WithTag().
The documentation for this struct was generated from the following file:
Protocol/DSL/MmQuery.cs