MercuryMessaging: MercuryMessaging.MmFluentMessage Struct Reference
MercuryMessaging.MmFluentMessage Struct Reference
Fluent message builder for MercuryMessaging.
Public Member Functions
MmFluentMessage (MmRelayNode relay, MmMethod method, object payload=null)
Initializes a new fluent message builder.
MmFluentMessage To (MmLevelFilter filter)
Target child nodes in the hierarchy.
MmFluentMessage ToChildren ()
Target only child nodes.
MmFluentMessage ToParents ()
Target only parent nodes.
MmFluentMessage ToSiblings ()
Target sibling nodes (same parent).
MmFluentMessage ToDescendants ()
Target all descendants recursively.
MmFluentMessage ToAncestors ()
Target all ancestors recursively.
MmFluentMessage ToAll ()
Target all connected nodes (bidirectional).
MmFluentMessage Active ()
Target only active GameObjects.
MmFluentMessage IncludeInactive ()
Include inactive GameObjects.
MmFluentMessage Selected ()
Target only FSM-selected responders.
MmFluentMessage AllSelected ()
Target all responders regardless of selection.
MmFluentMessage LocalOnly ()
Send message locally only.
MmFluentMessage NetworkOnly ()
Send message over network only.
MmFluentMessage AllDestinations ()
Send message both locally and over network.
MmFluentMessage OverNetwork ()
Send message over network (alias for AllDestinations).
MmFluentMessage RemoteOnly ()
Shorthand for NetworkOnly() - send only over network, not locally.
MmFluentMessage WithTag (MmTag tag)
Filter by a specific tag.
MmFluentMessage WithTags (params MmTag[] tags)
Filter by multiple tags (bitwise OR).
MmFluentMessage AnyTag ()
Match any tag (no filtering).
MmFluentMessage NoTags ()
Match no tags.
MmFluentMessage Within (float radius)
Filter to responders within a specified radius from the source.
MmFluentMessage InDirection (Vector3 direction, float angle)
Filter to responders in a specific direction from the source.
MmFluentMessage InBounds (Bounds bounds)
Filter to responders within a bounding box.
MmFluentMessage InBounds (Vector3 center, Vector3 size)
Filter to responders within a bounding box defined by center and size.
MmFluentMessage InCone (Vector3 direction, float angle, float range)
Filter to responders in a cone from the source.
MmFluentMessage OfType< T > ()
Filter to responders whose GameObject has a component of type T.
MmFluentMessage WithComponent< T > ()
Filter to responders whose GameObject has a component of type T.
MmFluentMessage WithComponent (Type componentType)
Filter to responders whose GameObject has a component of the specified type.
MmFluentMessage Implementing< T > ()
Filter to responders whose GameObject implements a specific interface.
MmFluentMessage Where (Func< GameObject, bool > predicate)
Filter responders using a custom predicate on the GameObject.
MmFluentMessage WhereRelay (Func< MmRelayNode, bool > predicate)
Filter responders using a custom predicate on the MmRelayNode.
MmFluentMessage OnLayer (int layer)
Filter responders by Unity layer.
MmFluentMessage OnLayer (string layerName)
Filter responders by Unity layer name.
MmFluentMessage WithUnityTag (string unityTag)
Filter responders by Unity tag.
MmFluentMessage Named (string pattern)
Filter responders by name pattern (contains).
MmFluentMessage NamedExactly (string exactName)
Filter responders by exact name match.
void Execute ()
Execute the message send operation.
void Send ()
Alias for Execute() to provide alternative syntax.
Private Member Functions
void EnsurePredicates ()
Ensure predicates list is initialized (lazy allocation).
MmMetadataBlock CreateMetadata ()
Creates a metadata block from current filter settings.
void ExecuteWithTargetCollection ()
Execute by collecting targets and sending to each with MmLevelFilter.Self.
void ExecuteStandard (MmMetadataBlock metadata)
Standard execution without predicates.
void ExecuteWithPredicates (MmMetadataBlock metadata)
Execute with predicate filtering.
List< MmRelayNode > CollectTargets ()
Collect potential targets based on level filter.
void CollectChildRelays (MmRelayNode parent, List< MmRelayNode > targets, bool recursive)
Collect child relay nodes recursively if needed.
void CollectParentRelays (MmRelayNode child, List< MmRelayNode > targets, bool recursive)
Collect parent relay nodes recursively if needed.
void CollectSiblingRelays (MmRelayNode node, List< MmRelayNode > targets)
Collect sibling relay nodes (children of same parent).
void SendToTarget (MmRelayNode target, MmMetadataBlock metadata)
Send the message to a specific target relay node.
Static Private Member Functions
static bool ComputeNeedsTargetCollection (MmLevelFilter filter)
Helper to compute whether a level filter requires target collection.
Private Attributes
readonly MmRelayNode _relay
readonly MmMethod _method
readonly object _payload
MmLevelFilter _levelFilter
MmActiveFilter _activeFilter
MmSelectedFilter _selectedFilter
MmNetworkFilter _networkFilter
MmTag _tag
bool _hasCustomFilters
bool _needsTargetCollection
MmPredicateList _predicates
Static Private Attributes
static readonly MmMetadataBlock DefaultMetadata
Optimization 2.3: Pre-allocated default metadata block for simple messages.
Detailed Description
Fluent message builder for MercuryMessaging.
This struct provides a chainable API for constructing and sending messages through the Mercury framework. Uses struct to avoid heap allocations and maintain high performance.
Phase 2 additions: Supports spatial filtering (Within, InDirection, InBounds), type filtering (OfType, WithComponent), and custom predicates (Where).
Definition at line 21 of file MmFluentMessage.cs.
Constructor & Destructor Documentation
MmFluentMessage()
MercuryMessaging.MmFluentMessage.MmFluentMessage (MmRelayNode relay, MmMethod method, object payload = null)
Initializes a new fluent message builder.
Definition at line 44 of file MmFluentMessage.cs.
References _activeFilter, _hasCustomFilters, _levelFilter, _method, _needsTargetCollection, _networkFilter, _payload, _predicates, _relay, _selectedFilter, _tag, MercuryMessaging.MmTagHelper.Everything, and MercuryMessaging.MmLevelFilterHelper.SelfAndChildren.
Referenced by Active(), AllDestinations(), AllSelected(), AnyTag(), Implementing< T >(), InBounds(), InBounds(), IncludeInactive(), InCone(), InDirection(), LocalOnly(), Named(), NamedExactly(), NetworkOnly(), NoTags(), OfType< T >(), OnLayer(), OnLayer(), OverNetwork(), RemoteOnly(), Selected(), To(), ToAll(), ToAncestors(), ToChildren(), ToDescendants(), ToParents(), ToSiblings(), Where(), WhereRelay(), WithComponent(), WithComponent< T >(), Within(), WithTag(), WithTags(), and WithUnityTag().
Member Function Documentation
Active()
MmFluentMessage MercuryMessaging.MmFluentMessage.Active ()
Target only active GameObjects.
Definition at line 182 of file MmFluentMessage.cs.
References MmFluentMessage(), _activeFilter, and _hasCustomFilters.
AllDestinations()
MmFluentMessage MercuryMessaging.MmFluentMessage.AllDestinations ()
Send message both locally and over network.
Definition at line 256 of file MmFluentMessage.cs.
References MmFluentMessage(), _hasCustomFilters, and _networkFilter.
Referenced by OverNetwork().
AllSelected()
MmFluentMessage MercuryMessaging.MmFluentMessage.AllSelected ()
Target all responders regardless of selection.
Definition at line 219 of file MmFluentMessage.cs.
References MmFluentMessage(), _hasCustomFilters, and _selectedFilter.
AnyTag()
MmFluentMessage MercuryMessaging.MmFluentMessage.AnyTag ()
Match any tag (no filtering).
Definition at line 322 of file MmFluentMessage.cs.
References MmFluentMessage(), _hasCustomFilters, _tag, and MercuryMessaging.MmTagHelper.Everything.
CollectChildRelays()
void MercuryMessaging.MmFluentMessage.CollectChildRelays (MmRelayNode parent, List< MmRelayNode > targets, bool recursive) private
Collect child relay nodes recursively if needed.
Definition at line 922 of file MmFluentMessage.cs.
References CollectChildRelays(), and MercuryMessaging.MmRelayNode.RoutingTable.
Referenced by CollectChildRelays(), and CollectTargets().
CollectParentRelays()
void MercuryMessaging.MmFluentMessage.CollectParentRelays (MmRelayNode child, List< MmRelayNode > targets, bool recursive) private
Collect parent relay nodes recursively if needed.
Uses RoutingTable entries with Level == Parent.
Definition at line 949 of file MmFluentMessage.cs.
References CollectParentRelays(), and MercuryMessaging.MmRelayNode.RoutingTable.
Referenced by CollectParentRelays(), and CollectTargets().
CollectSiblingRelays()
void MercuryMessaging.MmFluentMessage.CollectSiblingRelays (MmRelayNode node, List< MmRelayNode > targets) private
Collect sibling relay nodes (children of same parent).
First finds parents via RoutingTable, then collects their children.
Definition at line 976 of file MmFluentMessage.cs.
References MercuryMessaging.MmRelayNode.RoutingTable.
Referenced by CollectTargets().
CollectTargets()
List< MmRelayNode > MercuryMessaging.MmFluentMessage.CollectTargets () private
Collect potential targets based on level filter.
Definition at line 880 of file MmFluentMessage.cs.
References _levelFilter, _relay, CollectChildRelays(), CollectParentRelays(), and CollectSiblingRelays().
Referenced by ExecuteWithPredicates(), and ExecuteWithTargetCollection().
ComputeNeedsTargetCollection()
bool MercuryMessaging.MmFluentMessage.ComputeNeedsTargetCollection (MmLevelFilter filter) static private
Helper to compute whether a level filter requires target collection.
Extracted to avoid duplicating this logic.
Definition at line 93 of file MmFluentMessage.cs.
Referenced by To().
CreateMetadata()
MmMetadataBlock MercuryMessaging.MmFluentMessage.CreateMetadata () private
Creates a metadata block from current filter settings.
Extracted to avoid code duplication.
Definition at line 687 of file MmFluentMessage.cs.
References _activeFilter, _levelFilter, _networkFilter, _selectedFilter, _tag, and MercuryMessaging.MmTagHelper.Everything.
Referenced by Execute().
EnsurePredicates()
void MercuryMessaging.MmFluentMessage.EnsurePredicates () private
Ensure predicates list is initialized (lazy allocation).
Definition at line 65 of file MmFluentMessage.cs.
References _predicates, and MercuryMessaging.MmPredicateListPool.Get().
Referenced by Implementing< T >(), InBounds(), InCone(), InDirection(), OfType< T >(), Where(), WhereRelay(), WithComponent(), and Within().
Execute()
void MercuryMessaging.MmFluentMessage.Execute ()
Execute the message send operation.
This is the terminal operation that actually sends the message. When predicates are present, uses predicate-based filtering. For Descendants/Ancestors/Parent/Siblings filters, collects targets and sends individually.
Definition at line 629 of file MmFluentMessage.cs.
References _hasCustomFilters, _needsTargetCollection, _predicates, _relay, CreateMetadata(), DefaultMetadata, ExecuteStandard(), ExecuteWithPredicates(), and ExecuteWithTargetCollection().
Referenced by MercuryMessaging.MmQuickExtensions.Activate(), MercuryMessaging.MmQuickExtensions.Done(), MercuryMessaging.MmQuickExtensions.Init(), MercuryMessaging.MmRelayNodeExtensions.Notify(), MercuryMessaging.MmRelayNodeExtensions.Notify(), MercuryMessaging.MmRelayNodeExtensions.Notify(), MercuryMessaging.MmRelayNodeExtensions.Notify(), MercuryMessaging.MmRelayNodeExtensions.Notify(), MercuryMessaging.MmRelayNodeExtensions.NotifyAncestors(), MercuryMessaging.MmRelayNodeExtensions.QueryDescendants(), MercuryMessaging.MmQuickExtensions.Report(), MercuryMessaging.MmQuickExtensions.Report(), MercuryMessaging.MmQuickExtensions.Report(), MercuryMessaging.MmQuickExtensions.Report(), Send(), MercuryMessaging.MmQuickExtensions.State(), MercuryMessaging.MmQuickExtensions.Sync(), MercuryMessaging.MmQuickExtensions.Tell(), MercuryMessaging.MmQuickExtensions.Tell(), MercuryMessaging.MmQuickExtensions.Tell(), MercuryMessaging.MmQuickExtensions.Tell(), and MercuryMessaging.MmQuickExtensions.Tell().
ExecuteStandard()
void MercuryMessaging.MmFluentMessage.ExecuteStandard (MmMetadataBlock metadata) private
Standard execution without predicates.
Definition at line 735 of file MmFluentMessage.cs.
References _method, _payload, and _relay.
Referenced by Execute().
ExecuteWithPredicates()
void MercuryMessaging.MmFluentMessage.ExecuteWithPredicates (MmMetadataBlock metadata) private
Execute with predicate filtering.
Collects matching relay nodes and sends messages individually. Uses Self filter to prevent double-delivery.
Definition at line 841 of file MmFluentMessage.cs.
References _activeFilter, _networkFilter, _predicates, _relay, _selectedFilter, _tag, CollectTargets(), MercuryMessaging.MmTagHelper.Everything, MercuryMessaging.MmPredicateListPool.Return(), and SendToTarget().
Referenced by Execute().
ExecuteWithTargetCollection()
void MercuryMessaging.MmFluentMessage.ExecuteWithTargetCollection () private
Execute by collecting targets and sending to each with MmLevelFilter.Self.
Used for Descendants, Ancestors, and Siblings level filters. Uses Self filter to prevent double-delivery when iterating through collected targets.
Definition at line 701 of file MmFluentMessage.cs.
References _activeFilter, _networkFilter, _selectedFilter, _tag, CollectTargets(), MercuryMessaging.MmTagHelper.Everything, and SendToTarget().
Referenced by Execute().
Implementing< T >()
MmFluentMessage MercuryMessaging.MmFluentMessage.Implementing< T > ()
Filter to responders whose GameObject implements a specific interface.
Template Parameters
T The interface type to filter by.
relay.Send("Save").ToDescendants().Implementing<ISaveable>().Execute();
Type Constraints
T : class
Definition at line 483 of file MmFluentMessage.cs.
References MmFluentMessage(), _predicates, MercuryMessaging.MmPredicate.CreateCustom(), and EnsurePredicates().
InBounds() [1/2]
MmFluentMessage MercuryMessaging.MmFluentMessage.InBounds (Bounds bounds)
Filter to responders within a bounding box.
Parameters
bounds The world-space bounds to check against.
var room = new Bounds(roomCenter, roomSize); relay.Send("Activate").ToDescendants().InBounds(room).Execute();
Definition at line 386 of file MmFluentMessage.cs.
References MmFluentMessage(), _hasCustomFilters, _predicates, MercuryMessaging.MmPredicate.CreateInBounds(), and EnsurePredicates().
Referenced by InBounds().
InBounds() [2/2]
MmFluentMessage MercuryMessaging.MmFluentMessage.InBounds (Vector3 center, Vector3 size)
Filter to responders within a bounding box defined by center and size.
Parameters
center The center of the bounding box in world space.
size The size of the bounding box.
Definition at line 400 of file MmFluentMessage.cs.
References MmFluentMessage(), and InBounds().
IncludeInactive()
MmFluentMessage MercuryMessaging.MmFluentMessage.IncludeInactive ()
Include inactive GameObjects.
Definition at line 193 of file MmFluentMessage.cs.
References MmFluentMessage(), _activeFilter, and _hasCustomFilters.
InCone()
MmFluentMessage MercuryMessaging.MmFluentMessage.InCone (Vector3 direction, float angle, float range)
Filter to responders in a cone from the source.
Combines direction and distance filtering.
Parameters
direction The direction of the cone (will be normalized).
angle The half-angle of the cone in degrees.
range The maximum distance of the cone.
relay.Send("Detect").ToDescendants().InCone(transform.forward, 30f, 20f).Execute();
Definition at line 416 of file MmFluentMessage.cs.
References MmFluentMessage(), _hasCustomFilters, _predicates, MercuryMessaging.MmPredicate.CreateInDirection(), MercuryMessaging.MmPredicate.CreateWithin(), and EnsurePredicates().
InDirection()
MmFluentMessage MercuryMessaging.MmFluentMessage.InDirection (Vector3 direction, float angle)
Filter to responders in a specific direction from the source.
Parameters
direction The direction vector from source (will be normalized).
angle Maximum angle (in degrees) from the direction to include responders.
relay.Send("Alert").ToChildren().InDirection(Vector3.forward, 45f).Execute();
Definition at line 369 of file MmFluentMessage.cs.
References MmFluentMessage(), _hasCustomFilters, _predicates, MercuryMessaging.MmPredicate.CreateInDirection(), and EnsurePredicates().
LocalOnly()
MmFluentMessage MercuryMessaging.MmFluentMessage.LocalOnly ()
Send message locally only.
Definition at line 234 of file MmFluentMessage.cs.
References MmFluentMessage(), _hasCustomFilters, and _networkFilter.
Named()
MmFluentMessage MercuryMessaging.MmFluentMessage.Named (string pattern)
Filter responders by name pattern (contains).
Parameters
pattern The pattern that the GameObject name must contain.
relay.Send("Update").ToDescendants().Named("Enemy").Execute();
Definition at line 603 of file MmFluentMessage.cs.
References MmFluentMessage(), and Where().
NamedExactly()
MmFluentMessage MercuryMessaging.MmFluentMessage.NamedExactly (string exactName)
Filter responders by exact name match.
Parameters
exactName The exact name the GameObject must have.
Definition at line 613 of file MmFluentMessage.cs.
References MmFluentMessage(), and Where().
NetworkOnly()
MmFluentMessage MercuryMessaging.MmFluentMessage.NetworkOnly ()
Send message over network only.
Definition at line 245 of file MmFluentMessage.cs.
References MmFluentMessage(), _hasCustomFilters, and _networkFilter.
Referenced by RemoteOnly().
NoTags()
MmFluentMessage MercuryMessaging.MmFluentMessage.NoTags ()
Match no tags.
Definition at line 333 of file MmFluentMessage.cs.
References MmFluentMessage(), _hasCustomFilters, _tag, and MercuryMessaging.MmTagHelper.Nothing.
OfType< T >()
MmFluentMessage MercuryMessaging.MmFluentMessage.OfType< T > ()
Filter to responders whose GameObject has a component of type T.
Template Parameters
T The component type to filter by.
relay.Send("Enable").ToDescendants().OfType<Enemy>().Execute();
Type Constraints
T : Component
Definition at line 437 of file MmFluentMessage.cs.
References MmFluentMessage(), _hasCustomFilters, _predicates, MercuryMessaging.MmPredicate.CreateWithComponent(), and EnsurePredicates().
Referenced by WithComponent< T >().
OnLayer() [1/2]
MmFluentMessage MercuryMessaging.MmFluentMessage.OnLayer (int layer)
Filter responders by Unity layer.
Parameters
layer The layer index to filter by.
relay.Send("Detect").ToDescendants().OnLayer(enemyLayer).Execute();
Definition at line 557 of file MmFluentMessage.cs.
References MmFluentMessage(), and Where().
Referenced by OnLayer().
OnLayer() [2/2]
MmFluentMessage MercuryMessaging.MmFluentMessage.OnLayer (string layerName)
Filter responders by Unity layer name.
Parameters
layerName The layer name to filter by.
relay.Send("Detect").ToDescendants().OnLayer("Enemies").Execute();
Definition at line 570 of file MmFluentMessage.cs.
References MmFluentMessage(), and OnLayer().
OverNetwork()
MmFluentMessage MercuryMessaging.MmFluentMessage.OverNetwork ()
Send message over network (alias for AllDestinations).
More intuitive naming for network-enabled messaging. Host double-receive is automatically handled by the framework.
relay.Send("PlayerMoved").ToDescendants().OverNetwork().Execute();
Definition at line 272 of file MmFluentMessage.cs.
References MmFluentMessage(), and AllDestinations().
Referenced by MercuryMessaging.MmNetworkExtensions.SendNetworked(), MercuryMessaging.MmNetworkExtensions.SendNetworked(), MercuryMessaging.MmNetworkExtensions.SendNetworked(), MercuryMessaging.MmNetworkExtensions.SendNetworked(), MercuryMessaging.MmNetworkExtensions.SendNetworked(), and MercuryMessaging.MmNetworkExtensions.SendNetworked().
RemoteOnly()
MmFluentMessage MercuryMessaging.MmFluentMessage.RemoteOnly ()
Shorthand for NetworkOnly() - send only over network, not locally.
Use when local handling is done separately.
Definition at line 282 of file MmFluentMessage.cs.
References MmFluentMessage(), and NetworkOnly().
Selected()
MmFluentMessage MercuryMessaging.MmFluentMessage.Selected ()
Target only FSM-selected responders.
Definition at line 208 of file MmFluentMessage.cs.
References MmFluentMessage(), _hasCustomFilters, and _selectedFilter.
Send()
void MercuryMessaging.MmFluentMessage.Send ()
Alias for Execute() to provide alternative syntax.
Definition at line 1091 of file MmFluentMessage.cs.
References Execute().
SendToTarget()
void MercuryMessaging.MmFluentMessage.SendToTarget (MmRelayNode target, MmMetadataBlock metadata) private
Send the message to a specific target relay node.
Definition at line 1009 of file MmFluentMessage.cs.
References _method, _payload, and MercuryMessaging.MmRelayNode.MmInvoke().
Referenced by ExecuteWithPredicates(), and ExecuteWithTargetCollection().
To()
MmFluentMessage MercuryMessaging.MmFluentMessage.To (MmLevelFilter filter)
Target child nodes in the hierarchy.
Definition at line 79 of file MmFluentMessage.cs.
References MmFluentMessage(), _hasCustomFilters, _levelFilter, _needsTargetCollection, and ComputeNeedsTargetCollection().
ToAll()
MmFluentMessage MercuryMessaging.MmFluentMessage.ToAll ()
Target all connected nodes (bidirectional).
Definition at line 166 of file MmFluentMessage.cs.
References MmFluentMessage(), _hasCustomFilters, _levelFilter, _needsTargetCollection, and MercuryMessaging.MmLevelFilterHelper.SelfAndBidirectional.
Referenced by MercuryMessaging.MmFluentExtensions.Broadcast(), and MercuryMessaging.MmFluentExtensions.Broadcast().
ToAncestors()
MmFluentMessage MercuryMessaging.MmFluentMessage.ToAncestors ()
Target all ancestors recursively.
Definition at line 154 of file MmFluentMessage.cs.
References MmFluentMessage(), _hasCustomFilters, _levelFilter, and _needsTargetCollection.
Referenced by MercuryMessaging.MmRelayNodeExtensions.NotifyAncestors().
ToChildren()
MmFluentMessage MercuryMessaging.MmFluentMessage.ToChildren ()
Target only child nodes.
Definition at line 105 of file MmFluentMessage.cs.
References MmFluentMessage(), _hasCustomFilters, _levelFilter, and _needsTargetCollection.
ToDescendants()
MmFluentMessage MercuryMessaging.MmFluentMessage.ToDescendants ()
Target all descendants recursively.
Definition at line 142 of file MmFluentMessage.cs.
References MmFluentMessage(), _hasCustomFilters, _levelFilter, and _needsTargetCollection.
Referenced by MercuryMessaging.MmQuickExtensions.Activate(), MercuryMessaging.MmQuickExtensions.Init(), MercuryMessaging.MmRelayNodeExtensions.QueryDescendants(), MercuryMessaging.MmQuickExtensions.State(), MercuryMessaging.MmQuickExtensions.Sync(), MercuryMessaging.MmQuickExtensions.Tell(), MercuryMessaging.MmQuickExtensions.Tell(), MercuryMessaging.MmQuickExtensions.Tell(), MercuryMessaging.MmQuickExtensions.Tell(), and MercuryMessaging.MmQuickExtensions.Tell().
ToParents()
MmFluentMessage MercuryMessaging.MmFluentMessage.ToParents ()
Target only parent nodes.
Uses direct MmInvoke routing (Parent filter) which the framework handles natively.
Definition at line 118 of file MmFluentMessage.cs.
References MmFluentMessage(), _hasCustomFilters, _levelFilter, and _needsTargetCollection.
Referenced by MercuryMessaging.MmQuickExtensions.Done(), MercuryMessaging.MmRelayNodeExtensions.Notify(), MercuryMessaging.MmRelayNodeExtensions.Notify(), MercuryMessaging.MmRelayNodeExtensions.Notify(), MercuryMessaging.MmRelayNodeExtensions.Notify(), MercuryMessaging.MmRelayNodeExtensions.Notify(), MercuryMessaging.MmQuickExtensions.Report(), MercuryMessaging.MmQuickExtensions.Report(), MercuryMessaging.MmQuickExtensions.Report(), and MercuryMessaging.MmQuickExtensions.Report().
ToSiblings()
MmFluentMessage MercuryMessaging.MmFluentMessage.ToSiblings ()
Target sibling nodes (same parent).
Definition at line 130 of file MmFluentMessage.cs.
References MmFluentMessage(), _hasCustomFilters, _levelFilter, and _needsTargetCollection.
Where()
MmFluentMessage MercuryMessaging.MmFluentMessage.Where (Func< GameObject, bool > predicate)
Filter responders using a custom predicate on the GameObject.
Parameters
predicate Function that returns true for GameObjects that should receive the message.
relay.Send("Alert") .ToDescendants() .Where(go => go.layer == LayerMask.NameToLayer("Enemies")) .Execute();
Definition at line 516 of file MmFluentMessage.cs.
References MmFluentMessage(), _hasCustomFilters, _predicates, MercuryMessaging.MmPredicate.CreateCustom(), and EnsurePredicates().
Referenced by Named(), NamedExactly(), OnLayer(), and WithUnityTag().
WhereRelay()
MmFluentMessage MercuryMessaging.MmFluentMessage.WhereRelay (Func< MmRelayNode, bool > predicate)
Filter responders using a custom predicate on the MmRelayNode.
Parameters
predicate Function that returns true for relay nodes that should receive the message.
relay.Send("NetworkSync") .ToDescendants() .WhereRelay(node => node.layer == 5) .Execute();
Definition at line 538 of file MmFluentMessage.cs.
References MmFluentMessage(), _hasCustomFilters, _predicates, MercuryMessaging.MmPredicate.CreateCustomRelay(), and EnsurePredicates().
WithComponent()
MmFluentMessage MercuryMessaging.MmFluentMessage.WithComponent (Type componentType)
Filter to responders whose GameObject has a component of the specified type.
Parameters
componentType The component type to filter by.
Definition at line 464 of file MmFluentMessage.cs.
References MmFluentMessage(), _hasCustomFilters, _predicates, MercuryMessaging.MmPredicate.CreateWithComponent(), and EnsurePredicates().
WithComponent< T >()
MmFluentMessage MercuryMessaging.MmFluentMessage.WithComponent< T > ()
Filter to responders whose GameObject has a component of type T.
Alias for OfType<T>().
Template Parameters
T The component type to require.
relay.Send("Damage").ToChildren().WithComponent<Health>().Execute();
Type Constraints
T : Component
Definition at line 454 of file MmFluentMessage.cs.
References MmFluentMessage(), and OfType< T >().
Within()
MmFluentMessage MercuryMessaging.MmFluentMessage.Within (float radius)
Filter to responders within a specified radius from the source.
Parameters
radius Maximum distance from source to include responders.
relay.Send("Explosion").ToDescendants().Within(10f).Execute();
Definition at line 352 of file MmFluentMessage.cs.
References MmFluentMessage(), _hasCustomFilters, _predicates, MercuryMessaging.MmPredicate.CreateWithin(), and EnsurePredicates().
WithTag()
MmFluentMessage MercuryMessaging.MmFluentMessage.WithTag (MmTag tag)
Filter by a specific tag.
Definition at line 295 of file MmFluentMessage.cs.
References MmFluentMessage(), _hasCustomFilters, and _tag.
WithTags()
MmFluentMessage MercuryMessaging.MmFluentMessage.WithTags (params MmTag[] tags)
Filter by multiple tags (bitwise OR).
Definition at line 306 of file MmFluentMessage.cs.
References MmFluentMessage(), _hasCustomFilters, _tag, and MercuryMessaging.MmTagHelper.Nothing.
WithUnityTag()
MmFluentMessage MercuryMessaging.MmFluentMessage.WithUnityTag (string unityTag)
Filter responders by Unity tag.
Note: This is different from MmTag - this uses Unity's GameObject.tag system.
Parameters
unityTag The Unity tag to filter by.
relay.Send("Player").ToDescendants().WithUnityTag("Player").Execute();
Definition at line 590 of file MmFluentMessage.cs.
References MmFluentMessage(), and Where().
Member Data Documentation
_activeFilter
MmActiveFilter MercuryMessaging.MmFluentMessage._activeFilter private
Definition at line 27 of file MmFluentMessage.cs.
Referenced by MmFluentMessage(), Active(), CreateMetadata(), ExecuteWithPredicates(), ExecuteWithTargetCollection(), and IncludeInactive().
_hasCustomFilters
bool MercuryMessaging.MmFluentMessage._hasCustomFilters private
Definition at line 31 of file MmFluentMessage.cs.
Referenced by MmFluentMessage(), Active(), AllDestinations(), AllSelected(), AnyTag(), Execute(), InBounds(), IncludeInactive(), InCone(), InDirection(), LocalOnly(), NetworkOnly(), NoTags(), OfType< T >(), Selected(), To(), ToAll(), ToAncestors(), ToChildren(), ToDescendants(), ToParents(), ToSiblings(), Where(), WhereRelay(), WithComponent(), Within(), WithTag(), and WithTags().
_levelFilter
MmLevelFilter MercuryMessaging.MmFluentMessage._levelFilter private
Definition at line 26 of file MmFluentMessage.cs.
Referenced by MmFluentMessage(), CollectTargets(), CreateMetadata(), To(), ToAll(), ToAncestors(), ToChildren(), ToDescendants(), ToParents(), and ToSiblings().
_method
readonly MmMethod MercuryMessaging.MmFluentMessage._method private
Definition at line 24 of file MmFluentMessage.cs.
Referenced by MmFluentMessage(), ExecuteStandard(), and SendToTarget().
_needsTargetCollection
bool MercuryMessaging.MmFluentMessage._needsTargetCollection private
Definition at line 35 of file MmFluentMessage.cs.
Referenced by MmFluentMessage(), Execute(), To(), ToAll(), ToAncestors(), ToChildren(), ToDescendants(), ToParents(), and ToSiblings().
_networkFilter
MmNetworkFilter MercuryMessaging.MmFluentMessage._networkFilter private
Definition at line 29 of file MmFluentMessage.cs.
Referenced by MmFluentMessage(), AllDestinations(), CreateMetadata(), ExecuteWithPredicates(), ExecuteWithTargetCollection(), LocalOnly(), and NetworkOnly().
_payload
readonly object MercuryMessaging.MmFluentMessage._payload private
Definition at line 25 of file MmFluentMessage.cs.
Referenced by MmFluentMessage(), ExecuteStandard(), and SendToTarget().
_predicates
MmPredicateList MercuryMessaging.MmFluentMessage._predicates private
Definition at line 38 of file MmFluentMessage.cs.
Referenced by MmFluentMessage(), EnsurePredicates(), Execute(), ExecuteWithPredicates(), Implementing< T >(), InBounds(), InCone(), InDirection(), OfType< T >(), Where(), WhereRelay(), WithComponent(), and Within().
_relay
readonly MmRelayNode MercuryMessaging.MmFluentMessage._relay private
Definition at line 23 of file MmFluentMessage.cs.
Referenced by MmFluentMessage(), CollectTargets(), Execute(), ExecuteStandard(), and ExecuteWithPredicates().
_selectedFilter
MmSelectedFilter MercuryMessaging.MmFluentMessage._selectedFilter private
Definition at line 28 of file MmFluentMessage.cs.
Referenced by MmFluentMessage(), AllSelected(), CreateMetadata(), ExecuteWithPredicates(), ExecuteWithTargetCollection(), and Selected().
_tag
MmTag MercuryMessaging.MmFluentMessage._tag private
Definition at line 30 of file MmFluentMessage.cs.
Referenced by MmFluentMessage(), AnyTag(), CreateMetadata(), ExecuteWithPredicates(), ExecuteWithTargetCollection(), NoTags(), WithTag(), and WithTags().
DefaultMetadata
readonly MmMetadataBlock MercuryMessaging.MmFluentMessage.DefaultMetadata static private
Initial value:
= new MmMetadataBlock(
            MmLevelFilterHelper.SelfAndChildren,
            MmActiveFilter.All,
            MmSelectedFilter.All,
            MmNetworkFilter.Local
        )
Optimization 2.3: Pre-allocated default metadata block for simple messages.
Avoids allocating a new struct every time.
Definition at line 675 of file MmFluentMessage.cs.
Referenced by Execute().
The documentation for this struct was generated from the following file:
Protocol/DSL/MmFluentMessage.cs