MercuryMessaging: MercuryMessaging.MmListenerBuilder< T > Struct Template Reference
MercuryMessaging.MmListenerBuilder< T > Struct Template Reference
Fluent builder for creating message listeners.
Public Member Functions
MmListenerBuilder< T > OnReceived (Action< T > handler)
Sets the handler to be called when a matching message is received.
MmListenerBuilder< T > When (Func< T, bool > predicate)
Adds a filter predicate.
MmListenerBuilder< T > WithTag (MmTag tag)
Filters messages by MercuryMessaging tag.
MmListenerBuilder< T > Once ()
Marks this as a one-time listener that auto-disposes after receiving one message.
MmListenerSubscription< T > Execute ()
Finalizes the builder and registers the listener with the relay node.
Package Functions
MmListenerBuilder (MmRelayNode relay, bool oneTime=false)
Creates a new listener builder for the specified relay node.
Private Attributes
readonly MmRelayNode _relay
Action< T > _handler
Func< T, bool > _filter
MmTag _tagFilter
bool _oneTime
Detailed Description
Fluent builder for creating message listeners.
Supports filtering by message type, tags, and custom predicates.
Template Parameters
T The message type to listen for
Type Constraints
T : MmMessage
Definition at line 169 of file MmListener.cs.
Member Function Documentation
Execute()
MmListenerSubscription< T > MercuryMessaging.MmListenerBuilder< T >.Execute ()
Finalizes the builder and registers the listener with the relay node.
Returns a subscription that can be disposed to unsubscribe.
Returns
A subscription handle that can be disposed to unsubscribe.
Definition at line 271 of file MmListener.cs.
References _filter, _handler, _oneTime, _relay, and _tagFilter.
MmListenerBuilder()
MercuryMessaging.MmListenerBuilder< T >.MmListenerBuilder (MmRelayNode relay, bool oneTime = false) package
Creates a new listener builder for the specified relay node.
Definition at line 181 of file MmListener.cs.
References _filter, _handler, _oneTime, _relay, _tagFilter, and MercuryMessaging.MmTagHelper.Everything.
Referenced by Once(), OnReceived(), When(), and WithTag().
Once()
MmListenerBuilder< T > MercuryMessaging.MmListenerBuilder< T >.Once ()
Marks this as a one-time listener that auto-disposes after receiving one message.
relay.Listen<MmMessageString>() .Once() .OnReceived(msg => ProcessResult(msg)) .Execute();
Definition at line 260 of file MmListener.cs.
References _oneTime, and MmListenerBuilder().
OnReceived()
MmListenerBuilder< T > MercuryMessaging.MmListenerBuilder< T >.OnReceived (Action< T > handler)
Sets the handler to be called when a matching message is received.
Parameters
handler The action to invoke with the received message.
relay.Listen<MmMessageFloat>() .OnReceived(msg => brightness = msg.value) .Execute();
Definition at line 200 of file MmListener.cs.
References _handler, and MmListenerBuilder().
When()
MmListenerBuilder< T > MercuryMessaging.MmListenerBuilder< T >.When (Func< T, bool > predicate)
Adds a filter predicate.
Only messages passing the filter will trigger the handler.
Parameters
predicate The filter predicate.
relay.Listen<MmMessageInt>() .When(msg => msg.value > 50) .OnReceived(msg => StartAlert(msg.value)) .Execute();
Definition at line 217 of file MmListener.cs.
References _filter, and MmListenerBuilder().
WithTag()
MmListenerBuilder< T > MercuryMessaging.MmListenerBuilder< T >.WithTag (MmTag tag)
Filters messages by MercuryMessaging tag.
Only messages with matching tag bits will trigger the handler.
Parameters
tag The tag to filter by.
relay.Listen<MmMessageString>() .WithTag(MmTag.Tag0) .OnReceived(msg => HandleTaggedMessage(msg)) .Execute();
Definition at line 244 of file MmListener.cs.
References _tagFilter, and MmListenerBuilder().
Member Data Documentation
_filter
Func<T, bool> MercuryMessaging.MmListenerBuilder< T >._filter private
Definition at line 173 of file MmListener.cs.
Referenced by Execute(), MmListenerBuilder(), and When().
_handler
Action<T> MercuryMessaging.MmListenerBuilder< T >._handler private
Definition at line 172 of file MmListener.cs.
Referenced by Execute(), MmListenerBuilder(), and OnReceived().
_oneTime
bool MercuryMessaging.MmListenerBuilder< T >._oneTime private
Definition at line 175 of file MmListener.cs.
Referenced by Execute(), MmListenerBuilder(), and Once().
_relay
readonly MmRelayNode MercuryMessaging.MmListenerBuilder< T >._relay private
Definition at line 171 of file MmListener.cs.
Referenced by Execute(), and MmListenerBuilder().
_tagFilter
MmTag MercuryMessaging.MmListenerBuilder< T >._tagFilter private
Definition at line 174 of file MmListener.cs.
Referenced by Execute(), MmListenerBuilder(), and WithTag().
The documentation for this struct was generated from the following file:
Protocol/DSL/MmListener.cs