MercuryMessaging: MercuryMessaging.MmTagConfigBuilder Struct Reference
MercuryMessaging.MmTagConfigBuilder Struct Reference
Fluent builder for bulk tag configuration.
Public Member Functions
MmTagConfigBuilder ApplyToSelf (MmTag tag, bool enableChecking=false)
Applies a tag to the relay node itself (if it has responders).
MmTagConfigBuilder ApplyToChildren (MmTag tag, bool enableChecking=false)
Applies a tag to all direct children.
MmTagConfigBuilder ApplyToDescendants (MmTag tag, bool enableChecking=false)
Applies a tag to all descendants recursively.
MmTagConfigBuilder SetTagChecking (bool enable)
Applies tag checking to all responders in the hierarchy.
MmRelayNode Build ()
Finalizes the tag configuration.
Package Functions
MmTagConfigBuilder (MmRelayNode relay)
Private Member Functions
void ApplyToDescendantsRecursive (MmRelayNode node, MmTag tag, bool enableChecking)
void SetTagCheckingRecursive (MmRelayNode node, bool enable)
Private Attributes
readonly MmRelayNode _relay
Detailed Description
Fluent builder for bulk tag configuration.
Definition at line 240 of file MmTagExtensions.cs.
Constructor & Destructor Documentation
MmTagConfigBuilder()
MercuryMessaging.MmTagConfigBuilder.MmTagConfigBuilder (MmRelayNode relay) package
Definition at line 244 of file MmTagExtensions.cs.
References _relay.
Referenced by ApplyToChildren(), ApplyToDescendants(), ApplyToSelf(), and SetTagChecking().
Member Function Documentation
ApplyToChildren()
MmTagConfigBuilder MercuryMessaging.MmTagConfigBuilder.ApplyToChildren (MmTag tag, bool enableChecking = false)
Applies a tag to all direct children.
Parameters
tag The tag to apply.
enableChecking Whether to enable tag checking.
Returns
The builder (for chaining).
Definition at line 279 of file MmTagExtensions.cs.
References MmTagConfigBuilder(), and _relay.
ApplyToDescendants()
MmTagConfigBuilder MercuryMessaging.MmTagConfigBuilder.ApplyToDescendants (MmTag tag, bool enableChecking = false)
Applies a tag to all descendants recursively.
Parameters
tag The tag to apply.
enableChecking Whether to enable tag checking.
Returns
The builder (for chaining).
Definition at line 301 of file MmTagExtensions.cs.
References MmTagConfigBuilder(), _relay, and ApplyToDescendantsRecursive().
ApplyToDescendantsRecursive()
void MercuryMessaging.MmTagConfigBuilder.ApplyToDescendantsRecursive (MmRelayNode node, MmTag tag, bool enableChecking) private
Definition at line 309 of file MmTagExtensions.cs.
References ApplyToDescendantsRecursive().
Referenced by ApplyToDescendants(), and ApplyToDescendantsRecursive().
ApplyToSelf()
MmTagConfigBuilder MercuryMessaging.MmTagConfigBuilder.ApplyToSelf (MmTag tag, bool enableChecking = false)
Applies a tag to the relay node itself (if it has responders).
Parameters
tag The tag to apply.
enableChecking Whether to enable tag checking.
Returns
The builder (for chaining).
Definition at line 255 of file MmTagExtensions.cs.
References MmTagConfigBuilder(), and _relay.
Build()
MmRelayNode MercuryMessaging.MmTagConfigBuilder.Build ()
Finalizes the tag configuration.
Returns
The relay node.
Definition at line 378 of file MmTagExtensions.cs.
References _relay.
SetTagChecking()
MmTagConfigBuilder MercuryMessaging.MmTagConfigBuilder.SetTagChecking (bool enable)
Applies tag checking to all responders in the hierarchy.
Parameters
enable Whether to enable or disable tag checking.
Returns
The builder (for chaining).
Definition at line 336 of file MmTagExtensions.cs.
References MmTagConfigBuilder(), _relay, and SetTagCheckingRecursive().
SetTagCheckingRecursive()
void MercuryMessaging.MmTagConfigBuilder.SetTagCheckingRecursive (MmRelayNode node, bool enable) private
Definition at line 353 of file MmTagExtensions.cs.
References SetTagCheckingRecursive().
Referenced by SetTagChecking(), and SetTagCheckingRecursive().
Member Data Documentation
_relay
readonly MmRelayNode MercuryMessaging.MmTagConfigBuilder._relay private
Definition at line 242 of file MmTagExtensions.cs.
Referenced by MmTagConfigBuilder(), ApplyToChildren(), ApplyToDescendants(), ApplyToSelf(), Build(), and SetTagChecking().
The documentation for this struct was generated from the following file:
Protocol/DSL/MmTagExtensions.cs