MercuryMessaging: MercuryMessaging.MmQueryBuilder Struct Reference
MercuryMessaging.MmQueryBuilder Struct Reference
Non-generic query builder that returns MmResponder by default.
Public Member Functions
MmQuery< T > OfType< T > ()
Start a typed query.
MmQuery< MmResponder > Children ()
Query direct children.
MmQuery< MmResponder > Parents ()
Query direct parents.
MmQuery< MmResponder > Descendants ()
Query all descendants recursively.
MmQuery< MmResponder > Ancestors ()
Query all ancestors recursively.
MmQuery< MmResponder > Siblings ()
Query siblings.
MmQuery< MmResponder > All ()
Query all connected nodes.
Package Functions
MmQueryBuilder (MmRelayNode relay)
Private Attributes
readonly MmRelayNode _relay
Detailed Description
Non-generic query builder that returns MmResponder by default.
Definition at line 461 of file MmQuery.cs.
Constructor & Destructor Documentation
MmQueryBuilder()
MercuryMessaging.MmQueryBuilder.MmQueryBuilder (MmRelayNode relay) package
Definition at line 466 of file MmQuery.cs.
References _relay.
Member Function Documentation
All()
MmQuery< MmResponder > MercuryMessaging.MmQueryBuilder.All ()
Query all connected nodes.
Definition at line 529 of file MmQuery.cs.
References _relay, and MercuryMessaging.MmQuery< T >.All().
Ancestors()
MmQuery< MmResponder > MercuryMessaging.MmQueryBuilder.Ancestors ()
Query all ancestors recursively.
Definition at line 511 of file MmQuery.cs.
References _relay, and MercuryMessaging.MmQuery< T >.Ancestors().
Children()
MmQuery< MmResponder > MercuryMessaging.MmQueryBuilder.Children ()
Query direct children.
Definition at line 484 of file MmQuery.cs.
References _relay, and MercuryMessaging.MmQuery< T >.Children().
Descendants()
MmQuery< MmResponder > MercuryMessaging.MmQueryBuilder.Descendants ()
Query all descendants recursively.
Definition at line 502 of file MmQuery.cs.
References _relay, and MercuryMessaging.MmQuery< T >.Descendants().
OfType< T >()
MmQuery< T > MercuryMessaging.MmQueryBuilder.OfType< T > ()
Start a typed query.
Type Constraints
T : class
Definition at line 475 of file MmQuery.cs.
References _relay.
Parents()
MmQuery< MmResponder > MercuryMessaging.MmQueryBuilder.Parents ()
Query direct parents.
Definition at line 493 of file MmQuery.cs.
References _relay, and MercuryMessaging.MmQuery< T >.Parents().
Siblings()
MmQuery< MmResponder > MercuryMessaging.MmQueryBuilder.Siblings ()
Query siblings.
Definition at line 520 of file MmQuery.cs.
References _relay, and MercuryMessaging.MmQuery< T >.Siblings().
Member Data Documentation
_relay
readonly MmRelayNode MercuryMessaging.MmQueryBuilder._relay private
Definition at line 463 of file MmQuery.cs.
Referenced by MmQueryBuilder(), All(), Ancestors(), Children(), Descendants(), OfType< T >(), Parents(), and Siblings().
The documentation for this struct was generated from the following file:
Protocol/DSL/MmQuery.cs