MercuryMessaging: MercuryMessaging.MmTemporalBuilder Struct Reference
MercuryMessaging.MmTemporalBuilder Struct Reference
Fluent builder for temporal message operations.
Public Member Functions
MmTemporalBuilder (MmRelayNode relay, MmMethod method, object payload)
MmTemporalBuilder ToChildren ()
Target children with the message.
MmTemporalBuilder ToDescendants ()
Target descendants with the message.
MmTemporalBuilder ToParents ()
Target parents with the message.
MmTemporalBuilder After (float seconds)
Set a delay before sending.
MmTemporalBuilder Every (float seconds, int maxRepeats=0)
Make the message repeat at an interval.
MmTemporalHandle Execute ()
Execute the temporal operation.
Private Attributes
readonly MmRelayNode _relay
readonly MmMethod _method
readonly object _payload
MmMetadataBlock _metadata
float _delay
float _interval
int _repeatCount
Detailed Description
Fluent builder for temporal message operations.
Definition at line 456 of file MmTemporalExtensions.cs.
Constructor & Destructor Documentation
MmTemporalBuilder()
MercuryMessaging.MmTemporalBuilder.MmTemporalBuilder (MmRelayNode relay, MmMethod method, object payload)
Definition at line 466 of file MmTemporalExtensions.cs.
References _delay, _interval, _metadata, _method, _payload, _relay, _repeatCount, and MercuryMessaging.MmMetadataBlockHelper.Default.
Referenced by After(), Every(), ToChildren(), ToDescendants(), and ToParents().
Member Function Documentation
After()
MmTemporalBuilder MercuryMessaging.MmTemporalBuilder.After (float seconds)
Set a delay before sending.
Definition at line 507 of file MmTemporalExtensions.cs.
References MmTemporalBuilder(), and _delay.
Every()
MmTemporalBuilder MercuryMessaging.MmTemporalBuilder.Every (float seconds, int maxRepeats = 0)
Make the message repeat at an interval.
Definition at line 516 of file MmTemporalExtensions.cs.
References MmTemporalBuilder(), _interval, and _repeatCount.
Execute()
MmTemporalHandle MercuryMessaging.MmTemporalBuilder.Execute ()
Execute the temporal operation.
Returns
A handle to cancel the operation.
Definition at line 527 of file MmTemporalExtensions.cs.
References _delay, _interval, _metadata, _method, _relay, and _repeatCount.
ToChildren()
MmTemporalBuilder MercuryMessaging.MmTemporalBuilder.ToChildren ()
Target children with the message.
Definition at line 480 of file MmTemporalExtensions.cs.
References MmTemporalBuilder(), and _metadata.
ToDescendants()
MmTemporalBuilder MercuryMessaging.MmTemporalBuilder.ToDescendants ()
Target descendants with the message.
Definition at line 489 of file MmTemporalExtensions.cs.
References MmTemporalBuilder(), and _metadata.
ToParents()
MmTemporalBuilder MercuryMessaging.MmTemporalBuilder.ToParents ()
Target parents with the message.
Definition at line 498 of file MmTemporalExtensions.cs.
References MmTemporalBuilder(), and _metadata.
Member Data Documentation
_delay
float MercuryMessaging.MmTemporalBuilder._delay private
Definition at line 462 of file MmTemporalExtensions.cs.
Referenced by MmTemporalBuilder(), After(), and Execute().
_interval
float MercuryMessaging.MmTemporalBuilder._interval private
Definition at line 463 of file MmTemporalExtensions.cs.
Referenced by MmTemporalBuilder(), Every(), and Execute().
_metadata
MmMetadataBlock MercuryMessaging.MmTemporalBuilder._metadata private
Definition at line 461 of file MmTemporalExtensions.cs.
Referenced by MmTemporalBuilder(), Execute(), ToChildren(), ToDescendants(), and ToParents().
_method
readonly MmMethod MercuryMessaging.MmTemporalBuilder._method private
Definition at line 459 of file MmTemporalExtensions.cs.
Referenced by MmTemporalBuilder(), and Execute().
_payload
readonly object MercuryMessaging.MmTemporalBuilder._payload private
Definition at line 460 of file MmTemporalExtensions.cs.
Referenced by MmTemporalBuilder().
_relay
readonly MmRelayNode MercuryMessaging.MmTemporalBuilder._relay private
Definition at line 458 of file MmTemporalExtensions.cs.
Referenced by MmTemporalBuilder(), and Execute().
_repeatCount
int MercuryMessaging.MmTemporalBuilder._repeatCount private
Definition at line 464 of file MmTemporalExtensions.cs.
Referenced by MmTemporalBuilder(), Every(), and Execute().
The documentation for this struct was generated from the following file:
Protocol/DSL/MmTemporalExtensions.cs