MercuryMessaging: MercuryMessaging.MmFilterCacheKey Struct Reference
MercuryMessaging.MmFilterCacheKey Struct Reference
Cache key for filter result caching (QW-3).
Public Member Functions
MmFilterCacheKey (MmRoutingTable.ListFilter listFilter, MmLevelFilter levelFilter)
override int GetHashCode ()
override bool Equals (object obj)
bool Equals (MmFilterCacheKey other)
Public Attributes
readonly MmRoutingTable.ListFilter ListFilter
readonly MmLevelFilter LevelFilter
Detailed Description
Cache key for filter result caching (QW-3).
Combines ListFilter and MmLevelFilter for efficient lookup. Phase 7 Optimization: Sequential layout for predictable memory access.
Definition at line 46 of file MmRoutingTable.cs.
Constructor & Destructor Documentation
MmFilterCacheKey()
MercuryMessaging.MmFilterCacheKey.MmFilterCacheKey (MmRoutingTable.ListFilter listFilter, MmLevelFilter levelFilter)
Definition at line 51 of file MmRoutingTable.cs.
References LevelFilter, and ListFilter.
Referenced by Equals(), and Equals().
Member Function Documentation
Equals() [1/2]
bool MercuryMessaging.MmFilterCacheKey.Equals (MmFilterCacheKey other)
Definition at line 74 of file MmRoutingTable.cs.
References MmFilterCacheKey(), LevelFilter, and ListFilter.
Equals() [2/2]
override bool MercuryMessaging.MmFilterCacheKey.Equals (object obj)
Definition at line 69 of file MmRoutingTable.cs.
References MmFilterCacheKey(), and Equals().
Referenced by Equals().
GetHashCode()
override int MercuryMessaging.MmFilterCacheKey.GetHashCode ()
Definition at line 57 of file MmRoutingTable.cs.
References LevelFilter, and ListFilter.
Member Data Documentation
LevelFilter
readonly MmLevelFilter MercuryMessaging.MmFilterCacheKey.LevelFilter
Definition at line 49 of file MmRoutingTable.cs.
Referenced by MmFilterCacheKey(), Equals(), and GetHashCode().
ListFilter
readonly MmRoutingTable.ListFilter MercuryMessaging.MmFilterCacheKey.ListFilter
Definition at line 48 of file MmRoutingTable.cs.
Referenced by MmFilterCacheKey(), Equals(), and GetHashCode().
The documentation for this struct was generated from the following file:
Protocol/Routing/MmRoutingTable.cs