MercuryMessaging: MercuryMessaging.HSBColor Struct Reference
MercuryMessaging.HSBColor Struct Reference
From: http://wiki.unity3d.com/index.php?title=HSBColor.
Public Member Functions
HSBColor (float h, float s, float b, float a)
HSBColor (float h, float s, float b)
HSBColor (Color col)
Color ToColor ()
override string ToString ()
Static Public Member Functions
static HSBColor FromColor (Color color)
static Color ToColor (HSBColor hsbColor)
static Color Lerp (Color a, Color b, float t)
static HSBColor Lerp (HSBColor a, HSBColor b, float t)
Public Attributes
float h
float s
float b
float a
Detailed Description
From: http://wiki.unity3d.com/index.php?title=HSBColor.
Definition at line 42 of file HSBColor.cs.
Constructor & Destructor Documentation
HSBColor() [1/3]
MercuryMessaging.HSBColor.HSBColor (float h, float s, float b, float a)
Definition at line 49 of file HSBColor.cs.
References a, b, h, and s.
Referenced by HSBColor(), FromColor(), Lerp(), Lerp(), and ToColor().
HSBColor() [2/3]
MercuryMessaging.HSBColor.HSBColor (float h, float s, float b)
Definition at line 57 of file HSBColor.cs.
References b, h, and s.
HSBColor() [3/3]
MercuryMessaging.HSBColor.HSBColor (Color col)
Definition at line 65 of file HSBColor.cs.
References HSBColor(), a, b, FromColor(), h, and s.
Member Function Documentation
FromColor()
HSBColor MercuryMessaging.HSBColor.FromColor (Color color) static
Definition at line 74 of file HSBColor.cs.
References HSBColor(), b, and h.
Referenced by HSBColor().
Lerp() [1/2]
Color MercuryMessaging.HSBColor.Lerp (Color a, Color b, float t) static
Definition at line 197 of file HSBColor.cs.
References HSBColor(), a, and b.
Referenced by MercuryMessaging.StandardLibrary.Animation.InterpolatorColor.Apply().
Lerp() [2/2]
HSBColor MercuryMessaging.HSBColor.Lerp (HSBColor a, HSBColor b, float t) static
Definition at line 202 of file HSBColor.cs.
References HSBColor(), a, b, h, and s.
ToColor() [1/2]
Color MercuryMessaging.HSBColor.ToColor ()
Definition at line 187 of file HSBColor.cs.
References ToColor().
Referenced by ToColor().
ToColor() [2/2]
Color MercuryMessaging.HSBColor.ToColor (HSBColor hsbColor) static
Definition at line 127 of file HSBColor.cs.
References HSBColor(), a, b, h, and s.
ToString()
override string MercuryMessaging.HSBColor.ToString ()
Definition at line 192 of file HSBColor.cs.
References b, h, and s.
Member Data Documentation
a
float MercuryMessaging.HSBColor.a
Definition at line 47 of file HSBColor.cs.
Referenced by HSBColor(), HSBColor(), Lerp(), Lerp(), and ToColor().
b
float MercuryMessaging.HSBColor.b
Definition at line 46 of file HSBColor.cs.
Referenced by HSBColor(), HSBColor(), HSBColor(), FromColor(), Lerp(), Lerp(), ToColor(), and ToString().
h
float MercuryMessaging.HSBColor.h
Definition at line 44 of file HSBColor.cs.
Referenced by HSBColor(), HSBColor(), HSBColor(), FromColor(), Lerp(), ToColor(), and ToString().
s
float MercuryMessaging.HSBColor.s
Definition at line 45 of file HSBColor.cs.
Referenced by HSBColor(), HSBColor(), HSBColor(), Lerp(), ToColor(), and ToString().
The documentation for this struct was generated from the following file:
Protocol/Core/Extensions/HSBColor.cs